### ISSUE TITLE
[Pathway] Don’t Feed the Trolls

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#1]
Imagined to be a pathway for youth, parents, and mentors, Don’t Feed the Trolls will focus on online bullying. Sessions in this pathway will not only share how to stay safe online, but also encourage participants to create media content and learning opportunities for others. This pathway will invite organizations like I Keep Safe to share their content, test approaches they’re currently using, and collaborate with participants to create more resources for youth and parents.

**Comment by EPIKhub** [comment]
This would also be good in the youthZone or creating a pathway to that session
