### ISSUE TITLE
Anonymity Online

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#10]
- Facilitators name
- How can we offer people — adults and teens alike — anonymity without encouraging bad behavior?  
- How to build moderating systems and empower users to report bad behavior.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for Dont feed the trolls

**Comment by Melechuga** [comment]
Placeholder
