### ISSUE TITLE
Get yourself online now!!!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#100]
**[ Google Spreadsheet Row Number ]** 66
**[ Facilitator ]** Muhammad Radwan
### Description

The session will be a practical workshop where participants learn how to use a Spark/Particle to connect their Internet of Things (IoT).  We will demonstrate uses of this technology focusing on topics related to sustainability in an attempt to promote innovation in open source sustainable solutions using the hacker/maker culture.  The idea is to disrupt the regular track of prototyping, scaling, and production as per the status quo and to innovate the solutions that have impact using the open technologies of today.  It is the first time the power of the crowd can achieve the high levels of impact with the connectivity of the web and its open source designs and its associated low cost ubiquitous hardware.
### Agenda

The workshop is broken up into two segments with the first being an interactive format to explain of the hardware and software aspects of the technology.  Following a short break, an circle intro will take place so that people can begin to form their groups, but this will depend on the size.  There will be subgroups of three people on each unit.  Following the group formation, the practical session will begin.  Finally a demonstration of each group's prototype will take place.  The session should be two to three hours depending on the size.
### Participants

There will be a constraint on the number of people depending on how many units area available.  Assuming unlimited units, with the growing number of participants, volunteers will be called upon to support with the facilitation.  With a small number (5), then I will form just one group.  As it grows larger, a maximum of three to four per unit will form subgroups.  At 50, the challenge will be to find volunteers to help with the practical and the preferred number would be 15 for this workshop.
### Outcome

The activities learned in this workshop could lead to replication in participants' respective home cities which would further promote the concepts of open web, remote connectivity, and environmental awareness as tech is now available to intersect both worlds in a a time of impending climate issues.  With the leaders and larger companies interested in more short term goals, its upon netizens and greens to combine efforts and crowdsource the solutions of tomorrow using the tools emerging today, namely the web and the appropriate tech that can be connected to it.  Only when the shrewd solutions arise through these events will those at the top tiers of decision-making finally make the necessary and difficult choices required for a future where our children can live a normal life.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
