### ISSUE TITLE
Web Development

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#101]
**[ Google Spreadsheet Row Number ]** 47
**[ Facilitator ]** April Mrs.
### Description

My session will allow new developers to learn what web devlopment is, to learn how to set up their development environment, to learn about databases and servers, and to code websites to put up through the web development process, as well as to learn python for serverside use. Plus JavaScript will be taught for them to learn about client side and server side use.
### Agenda

I see a lot of attendees turning up for this event eager to learn this, as well assee a fun experience for all who do attend this event.
### Participants

With any sise of participants, I will treat them all equally.and teach them as equally/with the same methods of teaching as is possible. I will listen to as many of their questions as is possible and then try my best to answer tham as well as I can. 
### Outcome

I hope to please and inspire as many participants as possible to want to contribute for Mozilla via back-end programming and even front-end programming for Mozilla. That is my goal.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
