### ISSUE TITLE
JavaScript in the real world with Espruino

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#102]
**[ Google Spreadsheet Row Number ]** 51
**[ Facilitator ]** Gordon Williams
### Description

People will learn how to create devices that do things in the real world (lights, motors, sensors) using the Espruino JavaScript interpreter. The session should give people who had no previous knowledge of electronics a lot of confidence and enthusiasm, although a member of each group with some basic programming knowledge would be needed. At the end of the session people will hopefully have made something automated that runs without the need for a host computer. This session won't be about connecting things to the net - while that's possible, this will be about using JavaScript to have fun controlling things with hardware.
### Agenda

It'll be a very quick talk about the Espruino board - what it is, why it's cool, how it works and how to get set up with it. I'll give a quick demo too, and will put up a few ideas for projects. It'll be bring your own laptop, but there'll then be some kits of parts that people can use (breadboard, robots, and small gameboy-like devices) - and for the second half I'll wander around and help out anyone that has problems.
### Participants

I have a selection of parts. 5 people would have full choice of whatever parts they wanted, 15 would have one board each (robot or breadboard kit), and for more they could divide into groups of 2 or more.
### Outcome

For me, I'd like to get more people to see how much fun it is to hack around with hardware, and to show that JavaScript on hardware - and Espruino in particular - really is good! I've already done a nodebots day for JSOxford - it ended up being really popular but I've got a load of ideas on how to make it more fun and inclusive now. Afterwards, participants could continue using Espruino on a variety of devices (it's Open Source, and available for >10 different types of board at the moment). Either that or the confidence they gain might let them move to Arduino, but it won't be as fun ;)

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
