### ISSUE TITLE
Living Light with WebGL - A Collaborative Art Experience

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#103]
**[ Google Spreadsheet Row Number ]** 50
**[ Facilitator ]** Greg Tatum
### Description

Participants will collaborate on a shared WebGL experience taking "living light" from a central server and creating individualized experiences. This project will illustrate the importance of opening up low-level APIs to the web, and how such technologies can empower transformative experiences.
### Agenda

A central screen will hold a repository of "living light". Participants will be able to capture these on their mobile devices and then feed them into their own custom built visualizations.

WebGL is a complicated specification, but there will be a simple starter kit to allow the participants to manipulate their living light and share the experience with others. Some intermediate JavaScript programming experience will be required, but the starter kit will provide an easy interface to begin playing with the technology.

The end result will be a set of finished individualized experiences that participants can go through and "feed" with their living light.
### Participants

5 participants will be an intimate experience of writing code together and exploring ideas closely.

15 participants will be a more typical workshop experience with a small amount of lecture explaining a few core concepts, and then breaking down into small groups to create unique projects.

With 50, people would break into groups with hopefully at least one person more familiar with programming or visualization concepts to help lead and mentor the groups, while I can provide some lecture time, and aid in the collaboration.
### Outcome

WebGL is a relatively young specification, and the adoption rate is growing. It has limitations compared to systems such as full OpenGL, DirectX, and the latest generation of gaming consoles. I hope people will be inspired to see how the web makes WebGL a different experience.

I've been working on WebGL MDN content kits through my MDN Fellowship, and editing MDN WebGL articles. Documentation is only part of what is needed to fully utilize the power of this new technology. The other even more important aspect is inspiring people to think of the new applications that WebGL enables through the power of the open web.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by Saallen** [comment]
cc @cubicgarden - this session is coming to the event so wondered if you had space within your spaces for this one?

**Comment by cubicgarden** [comment]
Sounds good to me @Saallen, sure we can find room for this...

**Comment by Saallen** [comment]
:hamburger:
