### ISSUE TITLE
Geo-location Stars

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#104]
**[ Google Spreadsheet Row Number ]** 49
**[ Facilitator ]** Sandeep kapalawai
### Description

My Session Deals with the people who joined in the session , wil be learning about what Geolocation , how Geolocation will helps ,also we discuss about the project Briefly, by the end of the event people who involved in this session will get to know about MLS and we will be showing live Demonstration and Conduct a mini game.
### Agenda

Glance on MLS 
Demonstration on MLS
Activity to the participants
Kick of Session
Winner Declaration
### Participants

If the participants number Goes with 10-50  we will make them in to even groups consisting 5 in a team , 

If the count goes with 50-150 ,we will make 3 team each consists 30 people in a group.
### Outcome

By the end of this participants will ge t to know about MLS and they will took a step forward to Contribute MLS.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
