### ISSUE TITLE
BRCK+PI Showcase

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#107]
**[ Google Spreadsheet Row Number ]** 57
**[ Facilitator ]** Frankie Onuonga
### Description

This session will demonstrate running various applications on our mobile microserver which we call BRCK+PI.
This will include emergency comms applications, WebMaker and possibly a mobile medical application.

How to build and deploy a mobile microserver. 
How to build web applications that can be deployed remotely or in emergency situations without connectivity to the internet.
How to take advantage of communication between browser and the PI for remote regions. 
### Agenda

First we will discuss the hardware features of the BRCK and the BRCK+PI.
Then we will demonstrate some of the open source applications we have developed so far. 
We will also explain how we have structured the GitHub repository for our emergency applications.  Then we want to discuss releasing the project to the community.  
This should generate enough interest or spark some new ideas that we can discuss further or possibly even start to implement on a the PI platform (which is cheap and open source )
### Participants

With a few participants we will have the most flexibility to either keep as a discussion only or get more hands on and develop some applications.
With 20 or more participants we will split into interest groups such as Webmaker, Emergency Comms and Others.
Some of the groups can be more discussion oriented while the other groups can be doing testing or possibly development.
We hope to have at least 5 demonstration boards some with screens, some that are headless.
### Outcome

Our emergency communications ecosystem is Open Source.  We hope to tap into the community knowledge on how to release and build excitement around this software.

We also want participants to go away thinking of new applications for a mobile microserver.  We are constantly getting ideas for new applications and MozFest will be a great opportunity to listen to even more application ideas for BRCK+PI.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
