### ISSUE TITLE
Lerevaging wiki technology to rally teachers in developing countries to create content aligned to national curricular.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#108]
**[ Google Spreadsheet Row Number ]** 73
**[ Facilitator ]** Vincent Kizza
### Description

Participants will be able to:-
(i) Learn wiki editing skills.
(ii) Learn the different modes of communication and collaboration within the wiki platform.
(iii) Create curriculum specific content on the wiki platform.
(IV) People will be able to brainstorm and acquire insights on "open education" advocacy.
### Agenda
- Participants are introduced to wiki technology and creating accounts on the platform,setting up personal wikieducator (WE personal pages-www.wikieducator.org),features and customization (30min)
- Introduction to Mediawiki editing,text editing,formatting and media handling and case studies(Uganda OER school Portal that I am championing at http://wikieducator.org/OERUG  (2 hrs)
- Lab work: participants create their own content(3 Hours)
- Showcasing(1 hr)
- Brainstorming session on open education advocacy for our countries- case study Uganda,continued on blogs and other media(1 hr)
### Participants

Participants will work in groups of 5 in each preferred learning area.
### Outcome
- Widened collaboration networks for all participants.
- Participants will have obtained wikimedia editing skills  for content creation in a cost effective way suitable for resource restricted countries.
- Improved advocacy skills for open education

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
