### ISSUE TITLE
African perspectives on music for the open web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#109]
**[ Google Spreadsheet Row Number ]** 65
**[ Facilitator ]** Kevin Ovita Teddy
### Description

The panel that I’m going to lead will allow young people to have insights into African music, how to do research and write about it online, how to represent it as a brand and other resource guides e.g. Vlogging.If you approve this proposal we can also include a performance from an African artist.
### Agenda

I will lead and also moderate a panel and a performance that will include myself, two other panelists and 1 artist each doing a 15 minutes presentation.I will do a presentation on how to do research and write about African music.The second presenter will do a part on how to represent African music as a successful brand online and opportunities in the Pan Afrikan market.The 3rd presenter will do a topic dubbed ‘oh my African Vlogs’ that’s meant to be a vlogging resource guide specifically for African music genres including Afrobeats, Chimurenga, Ghana Highlife and many more which will be concluded by a performance.
### Participants

For a small audience of 5 to 15 we will use discussion as the main method of presentation in which each presenter will do a 10 minutes talk followed by a question and answer session for 5 minutes.For a crowd of 50 people we might change presentation formats to include an interview and visual aids comprising of a laptop preloaded with some music that will be played and analyzed in between sessions.
### Outcome

We will collect a list of the young participants and music enthusiasts and will give them an activity of coming up with their own music resources and sharing them online. We will also follow up inorder to work together back in Africa on some Pan African music establishments.

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by simonaramkisson** [comment]
@jvallera

**Comment by Zebetus** [comment]
@EPIKhub once again a way to include music in the zone and has some wide reach into thinking about global comunities

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
