### ISSUE TITLE
Bar Code Hacking

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#110]
**[ Google Spreadsheet Row Number ]** 79
**[ Facilitator ]** Saisharan Amaravadhi
### Description

many like to hack something over internet, however it will not happens. But my session make them to learn about barcode and their encryption by manually calculating by human brain. Moreover, it is not easy as it seems to be done. so, come and join with me we can do wonders by barcodes. 
### Agenda

Use barcode technique in real time.
Agenda

> Introduction of barcode.
> What is barcode?
> Types of barcode systems,
> How to encrypt/decrypt?
> Applications in real world,
> Advantages and Disadvantages.
### Participants

Many like to hack on internet, so this is the main key to attract participants.  I can manage either 5 or else 50, However I expect more than 50 to my session as it is more interesting topic and cool hacking process. 
As attendees increases we get enthusiast to tell more detaily and perfectionaly.
### Outcome

I expect pupils to learn something by the end of the event.
they should not get boring and nerves by sitting at one place and going on learning things, there should some entertaining to rejoice themselves. however many come different places and we can meet at one place. This make people energetic and explore to rapid changes in innovative technology.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
