### ISSUE TITLE
Putting the world in its place: Geocoders, their promise and pitfalls.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#112]
**[ Google Spreadsheet Row Number ]** 67
**[ Facilitator ]** Stuart Lynn
### Description

Our world is a environment where a lot of things happen. Every day we refer to locations to meet, memories of places, that wonderful restaurant that you should totally go to or 101 other things. To a computer though, our vague designations of "That bakery off Chicago avenue near the book store" or even just "State and Lake" can be confusing and hard to pin down. The programs that link our human understanding of the world to definite points of latitude and longitude on a map are called geocoders. In this session attendees will learn how to use various geocoders to make their data geospatial and understand where they might go wrong and the pitfalls involved.
### Agenda

We will give a brief presentation on how geocoders go about taking a string of text and turning it in to a location on a map and then talk about how to use some of the open geocoders that exist online to add location data to peoples data. As part of this section we will invite people to bring data that they have to be geocoded and we will help them through that process.

We will talk through some of the common pitfalls of geocoding by showing 3D visualizations of NY city with the locations of the buildings moved to where the geocodes think they are. We will invite the attendees to the session to try and come up with a location name that geocodes to the furthest place than it was intended to be.
### Participants

A few of us will hopefully be at Mozfest, so we'd like to give a quick presentation and introduction followed by small group clinic sessions with our facilitators (Dave Riordan from Mapzen, Stuart Lynn from CartoDB/Zooniverse, Andy Eschbacher + Aurelia Moser from CartoDB). I've found the small group split to be really productive, time economical, and intimate. It accommodates all attendance counts and can be easily done based on general proficiency or attending topic-level interest. We'll aim for a relaxed but thoughtful vibe best facilitated by close interaction with, but not reliance on, attending participants.
### Outcome

We would like people to leave with a new tool for enriching data under their belts and to understand the limitations of that data. We will aim to produce one large map of all the data that people bring to us that we have managed to geocode during the session.

**Comment by Saallen** [comment]
cc @kaythaney cc @erikao
