### ISSUE TITLE
https://arabicmozilla.etherpad.mozilla.org

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#113]
**[ Google Spreadsheet Row Number ]** 69
**[ Facilitator ]** Mahmood Qudah
### Description

They will be well known about the latest hacks at social media and how to avoid them , people these days hacks themselves without knowing that, being aware about the way that hackers is using helps you to avoid getting there self's hacked.

also what add-on's hackers is using to hack anyone or to hack websites, and what add-on's should they use to protect them self's from getting hacked.

How Mozilla Firefox helps people to stay safe, in every detail.
### Agenda

They will be well known about the latest hacks at social media and how to avoid them , people these days hacks themselves without knowing that, being aware about the way that hackers is using helps you to avoid getting there self's hacked.

also what add-on's hackers is using to hack anyone or to hack websites, and what add-on's should they use to protect them self's from getting hacked.

How Mozilla Firefox helps people to stay safe, in every detail.
### Participants

I will give them everything i have, everyone must work on there own Laptops i believe when they work with us step by step the more they understand what we are talking about.

I dealt with more audience with the help of my local community we work as a Team am lecturing students since 3 years.
### Outcome

People will be aware of what happens around them while they are working on the web,they will know who is compromising there Privacy and who is protecting it, how to stay safe , they are going to know that we care about there privacy as we say at Mozilla "We believe that your personal data belongs to you and only you" it's our duty to make this real because we are part of this family Mozilla family.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
