### ISSUE TITLE
Serious Science with Silly Sensors

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#114]
**[ Google Spreadsheet Row Number ]** 70
**[ Facilitator ]** Margaret Low
### Description

We will develop and calibrate some simple scientific instruments for experimentation.  These are based around the scratch picoboard. Young people are encouraged to carry out experiments in order to develop a better understanding of science. In this workshop we will focus on home made sensors and interfaces to sense events taking place around us.

Young people are surrounded by sophisticated high-tech devices that are designed to be used without an understanding of how they work. The Technology Volunteers at the University of Warwick aim to provide opportunities for young people to build “cheap and cheerful” sensors + interfaces and reflect on how such devices work.  
Technology Volunteers:  www.warwick.ac.uk/techvolunteers
Sensing Resources: www.warwick.ac.uk/scratchresources
### Agenda

It will be a workshop.  There will be a brief introduction to the resources, then we'll connect boards and show people how to use them with Scratch.  We'll bring along 20 Scratch picoboards, and resources. Participants will need a laptop.  
Worksheets: http://go.warwick.ac.uk/scratchresources
### Participants

For 5 to 15 participants, people can choose whether they want to work with a partner or as an individual, we'd encourage working as a pair based on previous experience of running these sessions.  
For > 15 we'd recommend working in pairs.

> 50 participants, we'd form groups of 2 or 3.
### Outcome

Participants exploring and sharing ideas for homemade sensors and applications,and sharing these ideas with young people.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Zebetus** [comment]
@EPIKhub fun way to get young people involved in science

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
