### ISSUE TITLE
Girls Hack the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#116]
**[ Google Spreadsheet Row Number ]** 104
**[ Facilitator ]** Jacquelyn Guderley
### Description

We will teach girls to code their own website and vary the activity depending on the level of skill and experience of the session attendees. 

We use a range of online software tools including the Mozilla range like Thimble. Girls will hack to to a brief (to be decided between Mozilla and Stemettes) for anything up to two hours and present their products at the end. 

Open to all age groups and abilities. 
### Agenda

9am Welcome & intro from Head Stemette
9.05am Ice breaker
9.15am Intro to Web tools and different activities
9.20am Tutorial on how to use the tools 
9.45am introduce the brief
9.50am Girls brainstorm
10am Girls hack and Code
10.45am Girls present their websites/mobile apps/games
11am Close
### Participants

The session will not change other than:

Only volunteers will present
Girls will have to share laptops depending on the number we have available
We will bring more session leads and facilitators
### Outcome
- Girls come to future Stemettes events
- Girls continue to use the online software including Mozilla Web maker apps
- Girls sign up to use the OtotheB online platform developed by the Stemettes through which they can access learning material and stay in touch with fellow Stemettes
- Girls continue to code and have have a passion for coding
- Girls consider CompSci as a degree or career
- Girls will be keen to attend next year's MozFest

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by chadsansing** [comment]
@EPIKhub - would this work in the Youth Zone?

**Comment by EPIKhub** [comment]
@chadsansing I'm a strong advocate that we should learn stuff together, irrespective of gender or age. Its whats in your head that matters, your aptitude, obsession and passion that we should focus on rather than silo by sex.

**Comment by EPIKhub** [comment]
@Saallen this session has no lables
