### ISSUE TITLE
Ethical Hacking

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#117]
**[ Google Spreadsheet Row Number ]** 94
**[ Facilitator ]** Shreyans Bora
### Description

Ethical hacking 
how to hack and how to secure our computer from hacking
live demonstration on hacking
teaching how to be anonymous on the internet
### Agenda

Introduction Hacking
Introducing concepts related my session
Actual demonstration of hacking
How to be secure on internet
How to be anonymous on internet
### Participants

giving more knowledge
### Outcome

All the participants become a web literated

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
