### ISSUE TITLE
User Interface for multiple windows on a touch-screen

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#118]
**[ Google Spreadsheet Row Number ]** 103
**[ Facilitator ]** Norman Stone
### Description

There is a new multi-touch human computer interface called Pawtals, which allows a user to create multiple windows on a single touch-screen, quickly and easily, and then select an app for that window, with a single touch.
This session will ask whether there is an opportunity to incorporate the new UI in within Mozilla applications and, if so, how.
Pawtals technology is IP protected, but will be offered for open source use if applications are identified, such as educational use. The technology is aimed at larger touch-screens (7" to 700").
### Agenda

The session will begin with a demonstration on a large touch-screen, and a link provided to a free demonstrator Android app. This will allow people to understand the concept.
Then there will be a discussion and brainstorming of area of application of interest to the Mozilla community. At the same time, if there are coders present who want to hack some code to recreate the interface, this will be initiated in parallel.
### Participants

A small number will be easy to handle, with a few people surrounding a 27" screen. For about 15, the screen will still be big enough for hosting still, and even at a push for 50. However, with this higher number it is hoped that there will be hackers who can develop code to implement the interface in one corner.
### Outcome

I have only been to one MozFest before (2014), and am not active in the community. However I hope for participation from, and championing of, some UX/UI experts in the sessions and afterwards, to take forward the ideas from the session, if there is strong support from participants.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
