### ISSUE TITLE
CoderDojo

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#119]
**[ Google Spreadsheet Row Number ]** 83
**[ Facilitator ]** Johnny Claffey
### Description

CoderDojo will provide environment for kids to learn to code using a range of Mozilla and Open Source Languages, The sessions will be open learning delivered by youth mentors in peer to peer sessions. Adults will be present to supervise and support youth mentors, if required
### Agenda

CoderDojo will provide sushi cards to support the event. The sushi cards will provide the attendees with coding activities including Mozilla webmaker and Open Source Languages such as scratch, html, javascript, python
### Participants

The CoderDojo are scalable sessions, CoderDojo propose a mixture of a rolling Dojo session and fixed time tutorial sessions. CoderDojo will investigate provision of laptops to support the event and outreach to kids from underserved areas of community
### Outcome

Giving the young participants the skills, confidence and experience to be young leaders in their communities and become ambassadors for CoderDojo and Mozilla

**Comment by soapdog** [comment]
cc @soapdog

**Comment by soapdog** [comment]
cc @marcwalsh this one might interest your youth pathway

**Comment by amirad** [comment]
@EPIKhub I want to cross tag this with the Clubs pathway but this is going in the youthzone milestones right? (if not, we will put it in ours!)

**Comment by EPIKhub** [comment]
@amirad the Pi foundation community are setting shop in the youthZone with 30 Pi's plus the Sonic and Astro Pi. It would be beneficial to coder dojo to be in the same space with them from a learning and networking perspective and would give me an opportunity to build a relationship with them was my thinking, but I'm open to alternatives :)

**Comment by amirad** [comment]
@EPIKhub I agree! I agree! They should be in your space. I just wanted to make sure they were marked somewhere (though I only just realized you already milestoned them...duh).

**Comment by EPIKhub** [comment]
@amirad Ok cool, I'll mark them as accepted

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
