### ISSUE TITLE
 What are trolls and how do we avoid feeding them?

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#12]
- Faciliators name
-  The most common tactics for trolls/bullies/stalkers.  Bullying myths.  Tips for parents and youths.  Social networking sites have made cruelty and meanness public. Previously these acts were invisible, now they are at display to all. 
- Discuss different views on what to do with this visibility.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for Dont feed the trolls

**Comment by Melechuga** [comment]
Placeholder
