### ISSUE TITLE
The Machinist : How to walk the walk , your'e in control ! 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#120]
**[ Google Spreadsheet Row Number ]** 82
**[ Facilitator ]** wissam  alazzam
### Description

we all play games , and surly wondered how the player move ? what moves it , how it behaves!
in this "workshop" we will check the mechanics of gaming , how does a sprite moves , jump  , how to put your character under a spot light , all in JavaScript .
also they will get out with a simple game of their making and will be compatible with Firefox OS , uploaded to the marketplace .
 people will learn how to code these mechanics in the easiest way possible also the fastest .
this session to satisfy your need for exploration and discovery .
there will be documented  examples of each mechanic , the audience shall experience practically in the session .
### Agenda

*Hello,mechanics! (intro)
*Tools in the shed ( what tools we will be using like JavaScript , editors , browsers )
*getting under the hood ( explain how he mechanics works from code )
*working it out ( the audience will choose the mechanics the want to implement  in their simple game )
- Foxing the game ( how to add the  FFOS manifest folder , try on the simulator , the the game and try it on the FFOS phone )
- spread the magic ( upload the game to FFOS market place ) 
### Participants

this session can take up to 25 participants , then we will form groups  of 5 ,  each group will work on their simple game using the mechanics of their own .
the best game will receive a prise :D :D 
### Outcome

people will get out with a good knowledge of how gaming is done , most of the people play games without knowing how it's made at it's most basic levels .
doing this will allow people to keep pushing the economics of the web as gaming industry takes a big part of the wheel .
now using web technologies they will surely see the how easy it is to start coding games with web .
after the festival the participants are free to get in touch with as i will also provide many resource for them to keep them forward running with the web .

**Comment by Zebetus** [comment]
@EPIKhub a lot of young people involved in computing through this way so it would be great to talk about this in the youth zone

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
