### ISSUE TITLE
Coding Evening - supporting teachers with teaching code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#121]
**[ Google Spreadsheet Row Number ]** 88
**[ Facilitator ]** Cat Lamin
### Description

Coding Evening is run by teachers for teachers. The goal of Coding Evenings are to invite teachers and community volunteers to share their good ideas and best practise for teaching coding to children.

When the new curriculum for computing was introduced in September 2014, a lot of teachers in both primary and lower secondary school felt underprepared and unqualified to teach some of the more complicated aspects of coding; many panic-bought software and hardware with no understanding of how to use it. Coding Evening was introduced as a way of helping teachers to learn more about what works and what doesn't in a relaxed and informal environment. 

I'd like to share a talk about how other people can set up and run their own Coding Evenings to support teachers with coding.
### Agenda

Using this prezi as a start point, I will talk for 15-20 minutes on where the idea for Coding Evening came from, how I would like to see it move forward and how other people can set up their own evenings:

http://prezi.com/9ypkjwng-agc/?utm_campaign=share&utm_medium=copy

I would also really like to include a Q&A session at the end
### Participants

The number of participants doesn't concern me as I will be talking to however many people turn up.
### Outcome

My key goal is to share and support as many teachers with the teaching of the new computing curriculum. I'd love to see people leaving my session with ideas for setting up their Coding Evening or even their own community involvement event to support the teaching of coding.

**Comment by chadsansing** [comment]
cc @chadsansing
