### ISSUE TITLE
Scaling an app infrastructure

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#122]
**[ Google Spreadsheet Row Number ]** 109
**[ Facilitator ]** Yash Shah
### Description

My session will add knowledge to people about scaling a web application infrastructure. How to handle humongous of connection requests, database queries, how to serve to million requests in milliseconds.
### Agenda

I will explain in general terms about web architecture behind scaling the growing application to handle the traffic it keeps gaining. 
### Participants

This session can handle variable amount of participants. lessor the participants, more interactive it'll be and more useful it'd be to them.
### Outcome

Participants will learn new techniques and concepts behind scaling a large scale application.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
