### ISSUE TITLE
Fox Wave

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#124]
**[ Google Spreadsheet Row Number ]** 90
**[ Facilitator ]** Mrinal Jain
### Description

At our booth people will be taught about the privacy and advocacy .  Activites setup at the booth will allow people to try various ways to keep there privacy without affecting its 
openness.
people will learn the importance of privacy on internet as well as day to day life .
we will have a series of activities which will increase
This session will be for all age groups.
and the goal  is to make people aware actual meaning of privacy and Opensource.
### Agenda

The concept of the session is flexible so it can be a talk or a live booth.
the agenda consists of the 5-6 activities (teaching kits are in process) for different age groups. 
which will have tasks to complete (for teenagers)
 privacy  & advocacy  game (for grown ups )
one on one talk with peoples for doubt solving.

and a  2min movie showing the importance of privacy 
### Participants

more the participants, the fun grows exponentially.
for 5-10 participants it will be an one on one session  with the help of the teaching kits and the will be provided the   privacy tasks to complete which will make them aware of how to work without affecting others privacy.

for a crowd of 50 or more the things get more interesting as they will get the real feeling of how the privacy matters in such a big crowd.
the will be assigned a token and we will make them  play a game Privacy Matters(this teaching kit is almost ready )
### Outcome

The world is moving rapidly forward. and the misconceptions regarding the privacy and opensource are misleading.

the possible outcomes of this workshop will be to make people care about there thinking of privacy and opensource. 

the participants will be taught with live examples so that it takes a place in their mind.

after all doing good is part of our code

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy
Good candidate for "Privacy Lab"

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
