### ISSUE TITLE
Cargografias to the world

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#125]
**[ Google Spreadsheet Row Number ]** 112
**[ Facilitator ]** Andres Snitcofsky
### Description

Cargografias is a project I started 4 years ago to plotline the careers of the politicians in Argentina. Now the tool is opensource and can do a timeline of politicians, soccer players, movie stars, or whatever.
The idea is to spread the word about the tool, teach how to refine, scrap and make lists of people, and actually make a Cargografias instance for the countries of the people attending.
If there is more time, we could even try to hack it and use it to visualize other kind of Influence Mappings. 
### Agenda

It will be a hands on workshop, mostly encouraging others like me to pursue their ideas and _try_ to make them work. Cargografias started as a rough sketch and now has instances in more than 5 latin american countries. We even got 3 rows of funding from different ONG's.
I'll share what I've learn about trying to lead non-profit project, and also, how to Scrap data, join it with open data, refine it with OpenRefine and use visualization tools (D3.js, Cargografias, or others) to draw conclusions. 
### Participants

I've done this sort of workshops in DataBootcamps in Montevideo (uruguay), La Paz (Bolivia), and Buenos Aires (Argentina) in different Hacks/Hackers events. On most of them , all the people attending were from the same country, but this time we could even divide in subgroups and try to make more than one new Cargografias Instance.
If we have even more people, we can work on other kind of List of People over Time to be visualized on the tool.
### Outcome

I want everyone attending to be coming out of this small workshop with some knowledge about the importance of getting good data, and getting it in proper form and refinement. Also, I hope they get along with the concept of iterative development of projects. Trial and error at it's best. 
But most of all, I want to encourage anyone to set firm on the idea and push it forward to see if it has some outcome.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
