### ISSUE TITLE
the genome in the machine – the ethics of open data meeting very personal data 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#126]
**[ Google Spreadsheet Row Number ]** 124
**[ Facilitator ]** Bastian Greshake
### Description

Crowdsourcing, open data/science/research, all that can sound very appealing to those of us who were born and raised on the web with all its collaboration. But all of these ideals can become a problem when working on what ethicists call “human subject research”. Psychology, sociology, life sciences, medicine and many other disciplines face this struggle between wanting to be open about science and data and the need to protect participants. 

This session serves as a discussion platform, bringing together people of a diverse background to figure out how we can square open science with ethical research conduct.
### Agenda

It should be largely an open discussion. After a short introduction it would be great to collect experiences of participants on whether they encountered the problem in their work and how they dealt with it, creating a list of problems and the solutions if the participants have found any. The discussion should be documented collaboratively in an etherpad.
### Participants

Depending on the number of participants it might be useful to split the sprint into smaller sub-groups, discussing particular issues. The ethics of open science for human subject research are a pretty broad field and groups can form around e.g. consent to research, is all data equal, responsibility in crowdsourcing, privacy/anonymity etc.
### Outcome

Ideally the outcome would be some document detailing the struggles experienced when trying to do ethical open science and workarounds figured out so far. Ideally we could also formulate a vision of how ethical open science should be done. Because so far in many instances only the two extremes (no ethical concerns vs. not doing open science at all) are heard.

**Comment by abbycabs** [comment]
Bastian will also be participating in the open research accelerator with the opensnp project
