### ISSUE TITLE
World of privacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#127]
**[ Google Spreadsheet Row Number ]** 107
**[ Facilitator ]** Zaid Ibhais
### Description

We all need to have privacy seeking the internet, so my session will describe the full system to have the full privacy browsing and seeking the internet.
### Agenda

This session will be as a workshop, it will start by describing what we will do and why we are doing this, then start doing the practical section of installing the tools... etc.

In the practical way all the participants will get the full idea, all the tools installed perfectly and that will be the good way working.
### Participants

With 5 participants : i can keep in touch with the participants directly so i can describe everything to them directly.

With 15 participants : it will be like a small lecture with data show projector to give them all the full idea then if there is any problem with one or more participant i will fix it directly.

With 50 participants : this will be like a big lecture full of students with data show projector but it will be slower than the others with small number of participants to give the full idea.
### Outcome

All of the participants will get the full privacy system and will keep moving forward to update and add new values to it, then we will all keep in touch to get the last update, get the details of the new values.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
