### ISSUE TITLE
Living and working in a Web without Plug-ins

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#128]
**[ Google Spreadsheet Row Number ]** 99
**[ Facilitator ]** Jet Villegas
### Description

A lot of the capabilities that the Web used plugins for are now available in HTML/CSS/JS across most browsers. I'll cover what's there and how you can create awesome interactive content that will remain after the plugins disappear. 
### Agenda

The session will include a brief overview, and dive into practical examples that you can use today as you build pages and applications with rich interactive features--all without plugins or add-ons. 
### Participants

A smaller session (10 or less) may get into hands-on making/building. A larger session will be more demos/examples with lots of useful info for future exploration.
### Outcome

Positive outcomes include increased awareness of the state of the Web platform and its capabilities. I will use feedback from this session to inform Web platform teams at Mozilla and others (I meet with all the vendors 4x a year) of the pain points that webmakers still face.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
