### ISSUE TITLE
Become a Human Rights CSI

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#129]
**[ Google Spreadsheet Row Number ]** 86
**[ Facilitator ]** Milena Marin
### Description

This session is a mini investigation of human rights abuses, drawing upon real life scenarios, that will enable participants to experience first hand what it takes to be a human rights CSI. It involves searching for content, thinking of chains of custody, documenting and verifying open source intelligence like satellite imagery, videos, images, text based reports, etc. and building an evidence wall. 
### Agenda

We are suggesting a 1.5 hours workshop. After a brief introduction, we will break down participants in small groups of max 5 persons each. Each group will have a specific mission like verifying a video, mapping military presence on a satellite image, sorting social media reports, etc. All missions will be around one single investigation and at the end of the workshop we aim to create an evidence wall pasting together all contributions from the workshop. We will have a team of up to 5 facilitators who will be "resources" for the groups. Besides building the evidence wall, at the end of the workshop we will ask each group to share their main take away or aha moment. 
### Participants

We will work in small groups and will have a team of facilitators to help all groups. Facilitators will be recruited directly at the Festival, drawing upon the amazing energy and talent at MozFest!
### Outcome

Amnesty International is seeking to develop new tools and resources to involve more human rights activists in the process of documenting human rights abuses using open source intelligence.  We are building a community of "Human Rights CSIs" and we hope to learn a lot from the Mozfest participants. We will also follow up with resources like http://citizenevidence.org/ providing more resources to those interested

 We will learn a lot by piloting some of these approaches during the workshop. We also hope that participants will learn not only about human rights but also about verifying and documenting user generated content and how to deal with open source intelligence. T

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy
