### ISSUE TITLE
[Pathway] Space Hacking

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#13]
Pathway two is for someone curious about open source and science (but not a researcher). They really like space, so they join a sprint session on NASA data and storytelling, run by a former OpenNews fellow. They learn how to find open data to play with, dig into it using web based tools, and share that work with their group, consisting of other peers, teens, journalists and educators.

Sessions include:
- [ ] tbd
- [ ] tbd
- [ ] tbd

**Comment by secretrobotron** [comment]
omg please include me.

Also, for the record, I thought "space" referred to a Mozfest space.

**Comment by stefanfreeston** [comment]
this sound's awesome will continue to watch this ;)

**Comment by Zebetus** [comment]
@EPIKhub Sounds awesome but not really sure with the lack of sessions mentioned
