### ISSUE TITLE
Karolina

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#130]
**[ Google Spreadsheet Row Number ]** 87
**[ Facilitator ]** Karolina Nedelkovska
### Description

Assessment in my country and inclusion,
Target group: Teachers, Officials
How to adopt our lesson plans and include all the students into the learning process.
I would like to share my experience about evaluating and assessing students. Presenting many different activities and best practices from different countries. Pros and Cons ; What do our students get by giving or reciving marks and points? 
### Agenda

Workshop
1. Introduction : Participants introduce themselves ( making a list )
2. Short presentation about the topic 
3. Interested teachers  explain about assessment in their country and give ideas about inclusion and best activities.
### Participants

O don't understand what do you mean by 'accommodate' participant
### Outcome

After the festival I can organize a short presentation in my school, invite local TV and other media from my town and explain about the festival.

**Comment by amirad** [comment]
cc: @amirad

**Comment by amirad** [comment]
@simonaramkisson @jvallera maybe some interest in your track?

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
