### ISSUE TITLE
Rethinking education

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#131]
**[ Google Spreadsheet Row Number ]** 96
**[ Facilitator ]** Dan Sofer
### Description

I am not entirely sure that this fits in with your format, but I wanted an opportunity to discuss FAC and our model of free education. Happy to make this into an open discussion about viable models of peer-led and free education, based on what we are doing at FAC. On the other hand, we could just to a mass coding workshop, if that fits in better with your requirements. We do plenty of those and that would be pretty easy to organise.

http://www.foundersandcoders.com/
### Agenda

Can I leave this until I have had a chance to discuss what you actually want us to do.
### Participants

Can I leave this until I have had a chance to discuss what you actually want us to do.
### Outcome

Can I leave this until I have had a chance to discuss what you actually want us to do.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by EPIKhub** [comment]
@Saallen Ive removed them as a Milestone but I have asked for a Skpe meeting to explore things with them as they are in London to come volunteer as there is no clear theme to their session, yet they have the skills for sure to contribute.

**Comment by Saallen** [comment]
:+1:

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
