### ISSUE TITLE
PROGRAMMING LANGUAGES

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#132]
**[ Google Spreadsheet Row Number ]** 93
**[ Facilitator ]** PRATIKKUMAR MOHITE
### Description

1.INTRODUCTION TO PROGRAMMING LANGUAGES
2.HOW THE LANGUAGES ARE DEVELOPED?
3.DIFFERENT TYPES OF LANGUAGES
4.THE PROPER IMPLEMENTATION OF LANGUAGES 
### Agenda

AGENDA
1.TRICKS AND IMPLEMENTING OF PROGRAMMING LANGUAGES
2.CREATING A PROJECT IN VB.NET
### Participants

THE NEW TOPICS TO MAKE THE SESSION INTERESTING,THE PROJECT TOPIC WHICH IS DEVELOPED IN VB.NET
### Outcome

MEMBERS CAN LEARN NEW THINGS WITH THIS SESSION

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
