### ISSUE TITLE
Policy engagments and Advocacy: Building a Global south agenda

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#133]
**[ Google Spreadsheet Row Number ]** 95
**[ Facilitator ]** Anivar A Aravind
### Description

Mozilla India's Policy and Advocacy taskforce has setup in May 2015 , as a followup of netneutrality campaign initiatives. Within last 3 months , apart from Netneutrality campaign, the task force engaged with various national policies such as National Opensource policy of Govt of India , Open API policy etc. The session plans to collectively build a Global South Advocacy agenda with Mozillians from various global south countries. We can share how to address governance systems and bring change , along with the hurdles usually faced by the community. Mozilla position on Netneutrality and Zero rating  and its importance on a global south senario will be also discussed with Learning toolkit we built on Zero rating and net neutrality. 
### Agenda

We plan a workshop. 
Agenda: 
1. Experinence sharing on working with Govt Policies in India  and common issues faces
2. Experinecs sharing on Mass Mobilization for Net neutrality in India
3. Discussion session on Building Global south agenda
4. Collective evaluation and  analysing of Zero rating projects in Global south with Learning toolkit on Zero rating and Net neutrality 
### Participants

we prefer discussions and learning  from participants, along with the presentations. So the comfortable size is max 40-60 people
### Outcome

We are interested in more advocacy and polcy volunteers for Mozilla from Global South Countries . Also we like to see emergence of a group working on netneutrality issues like zero rating  with Mozilla position.  The session proposer Anivar Aravind is a Public Policy expert , FOSS & Internet Rights activist, and owner of Mozilla India Policy and advocacy task force  . Akshay S Dinesh is the author of Zero rating toolkit https://asdofindia.makes.org/thimble/MTEyODkyMzY0OA==/zero-rating-in-india

Related URLS : http://blog.mozillaindia.org/1397
http://blog.mozillaindia.org/1406

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

India Advocacy Task Force participant -- could be included in "Participation"

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin prefer fire side chat format, to longer lecture share-out though.

**Comment by Melechuga** [comment]
Combined with https://github.com/mozilla/mozfest-program/issues/249
