### ISSUE TITLE
Snappy app craetor

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#134]
**[ Google Spreadsheet Row Number ]** 108
**[ Facilitator ]** Manaf AL-ghraybeh
### Description

Snappy ,
What is ? snappy is an hybrid app creator based on java script html 5 , css3 it generate in all platforms such as Android Firefox OS and ios.
is it hard to learn? Snappy is very simple tool to create application by drag and drop and filing the forms that you add.
how complex the app could be ? snappy is made for static  simple applications can't make very complex application.

What is the use of the snappy then ? that will know in the next episode, kidding you will know that in the next question :).
### Agenda

know days the mobile applications have a big share for promoting events and developing Communities and in journalism and sharing the words across the world.
Agenda:
1-  learn what is hybrid application "5 slides" (10 minutes)
2- learn how to create on with snappy "workshop" (20 minutes) .
3- how to devolve an app to promote an event in Mozilla community"5 slides"(10 minutes).
4-how to create an application to introduce people to your Mozilla community"walk through"(10 minutes ).  
### Participants

from my past  experience about such session, it can held up to 50 people if cover the slide section only and if i need to cover the developing side it will take up to 15. 
### Outcome

in this session we well gain two things are very mandatory :
 1- we will learn to create application in very simple way that anybody can learn.
2-we learn how to devolve our Community and events in very efficient way so it well reach very scale of people.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
