### ISSUE TITLE
Raspberry Pi audio streambox workshop

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#135]
**[ Google Spreadsheet Row Number ]** 100
**[ Facilitator ]** Grant Smith
### Description

This hands-on workshop introduces the Raspberry Pi mini computer as a tool for streaming live audio to the internet. Participants can work with the command line, the Pi's Linux operating system,  the open source application Darkice, and various microphones and soundcards to stream sounds to an Icecast server at Locus Sonus in Aix en Provence.  We will listen to some of the sounds on the Locus Sonus soundmap and consider the potential of a live open microphone network as a resource for artists, ecologists, activists and others..
### Agenda

We will bring a number of Raspberry Pi's and peripherals. Working in small groups, participants can go through the process of flashing an SD Card, setting up the Pi, connecting to it directly, over SSH or via a web interface, and adjusting settings so local sounds can be heard live on the server. We can help people get started if they are new to the Pi. More advanced users can explore the streambox's functions in greater detail. We will look into the decibel data streaming function developed by Christian Nold at UCL, and mention the streaming app Locuscast for mobiles.
### Participants

With 5 participants, we can support each person to run through the setup from scratch in detail, working alone or in pairs. The result will be a working streambox. With 15 participants, people can work in 5 or so small groups and run through the same setup process, focusing on the web based or the command line interface, or the audio, depending on their interests and experience and how much time is available. In our experience, groups can help each other out when they run into issues. With 50 people, we can work directly with around 15, and the wider group can get a sense of the project through observing, and through listening to the remote sounds, which we will play out into the space.
We have done Pi workshops along these lines with groups of young people, the general public, academics and mixed audiences in the past.
### Outcome

At soundCamp we've been working closely with live audio streaming since 2013. We're committed to increasing the range and diversity of participation in the field, and opening and developing it as a way of linking local ecological and acoustic projects. We invite participants to go home and build a streambox, and set it up somewhere with interesting sounds; or to set up a transient stream on International Dawn Chorus Day over the first weekend of May 2016, when we will be producing REVEIL: a radio broadcast that travels around the globe at daybreak, relaying live sounds supplied by a network of streamers in a unique 24 hour live transmission. Subject to funding, we hope to be able to give away a limited number of streamboxes from the workshop to people who want to take part.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
@emmairwin @geroter a could be a challange for participation tech

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
