### ISSUE TITLE
Free Software and Your Freedom week festival 3rd oct,2015

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#136]
**[ Google Spreadsheet Row Number ]** 106
**[ Facilitator ]** G.T RAO
### Description

" foss"
awareness campaign in RAJASTHAN  , INDIA which will develop new skills in the IT user/students within a short of span of months to enhance their employability and earning power a million times.

We believe that encouragement of FOSS will result in:
- Development of the domestic IT industry
- Creation of jobs\* Encouragement of skills development and up gradation
- Enable localization of software to Indian languages
- Reduction of India's dependence on monopolistic proprietary software
  vendors
- Encourage the usage of open standards
- Bridging the digital divide
- Rapid modernization and computerization of India's education system
- Technology up gradation of India's Small and Medium Enterprises
- Efficient usage of budget outlays for e-government
- Faster technology development through Collaborative Innovation.
### Agenda

The following are the topics that will be dealt in the festival :

Introduction to FOSS
How to install a GNU/Linux based operating system
How to navigate the GNU/Linux desktop,
Using applications and installing software.
How to get help and support.

More specific sessions:

General office and internet applications

GNU/Linux installation (hands-on)
Audio/Video editing tools (hands-on)
Desktop publishing tools (hands-on)
New-age licensing concepts (Creative Commons etc)
Migration to FOSS with minimal hassles
Compatibility of FOSS software with proprietary ones.
About Mozilla Firefox
### Participants

More then 200 Participants.
### Outcome

More then 200 Participants.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
