### ISSUE TITLE
How to learn/teach coding for beginners (no exp. required!)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#138]
**[ Google Spreadsheet Row Number ]** 89
**[ Facilitator ]** Eli Kariv
### Description

They'll learn how to code using tools like scratch and rails and, through learning, also understand what resources are available to learn to code online as well as what resources are available to teach kids to code. 
### Agenda

Our sessions are as hands-on as possible. If participants have computers, we take them straight to learning how to build things themselves (for example, showing them weebly, then using X-Ray or Firebug or inspect element to analyze code live on websites they love, then show them other tools they can use to start building their own sites from scratch, or we could do a very similar approach with teaching them to make games). The format is very collaborative, everyone sitting in a circle or a 'U' style and asking them to go on their own computers and explore coding topics they're passionate about with our guidance. It can also work without computers. 
### Participants

Since our presentation is extremely project based (participants working on their own projects) it's pretty good at scaling to different sizes and being the exact same. After 30, we might split into 2 groups (Steve teaching one, me teaching another) or have 5-10 minutes intro explaining some of the core basics, and then having people work on their own. 
### Outcome

This is the best part! Participants will feel empowered to not only learn code on their own, but to teach others. There's also a huge lack of females in computer science so hopefully participants feel empowered to help more girls learn to code. Participants will have a list of resources that they can use to explore more on their own, and help others.

**Comment by jvallera** [comment]
@simonaramkisson @jvallera
