### ISSUE TITLE
Hands on on Firefox OS add-ons

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#139]
**[ Google Spreadsheet Row Number ]** 118
**[ Facilitator ]** Francisco Jordano
### Description

Ever dreamt of hacking your mobile device to really suits your needs? This session will get you started on creating add-ons for Firefox OS to customise your device and get a truly tailored experience.
Bring your laptop and your Firefox OS device if you have one.
### Agenda

After a short introduction, we'll take the attendees to write their first add-ons. The goal is to showcase the possibilities that the add-on can offer.
### Participants

It's going to be practical so the fewer participants, the better. If there are a lot of people attending, we'll create groups so that they can work together.
### Outcome

We hope that this session will start building an ecosystem for add-ons for Firefox OS.

**Comment by Saallen** [comment]
cc @geroter

**Comment by soapdog** [comment]
cc @soapdog

**Comment by thornet** [comment]
cc @geroter @emmairwin if this fits in participation space.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by Saallen** [comment]
The facilitator has changes to Francisco, another awesome london mozillian who can lead this session

**Comment by emmairwin** [comment]
Thanks @Saallen If you are able to send an email I can get in touch.
