### ISSUE TITLE
Campaigning 101

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#14]
- Faciliators name
-  a group of digital campaigners explain the digital tools that can help create change and some basic best practices around how to use them. 
  - Agenda

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for building a crowd

**Comment by Melechuga** [comment]
Placeholder
