### ISSUE TITLE
E.A.K. Walk-In - Save Kittens, Learn HTML!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#140]
**[ Google Spreadsheet Row Number ]** 117
**[ Facilitator ]** Joe Dytrych
### Description

Learn a little bit of HTML and CSS, whilst saving kittens in the process. In Erase All Kittens (https://eraseallkittens.com/), players must explore a fantasy Internet universe, using code to change the world around them, in order to defeat the evil Operation E.A.K. - Erase All Kittens.

E.A.K. is aimed at anyone aged 7+, but kids much younger than that have enjoyed learning with E.A.K. too.
### Agenda

E.A.K. is pretty short - most kids can complete the game in 20-30 minutes. We'd like to have a walk-in style session - a two or three hour period where anyone - especially kids, parents, and teachers - can drop in and play the game, try on E.A.K. capes, get stickers (!!!), and chat to us about the game.
### Participants

We have 5 laptops available for demos, but going by MozFests-past, most attendants will also have laptops with them capable of running E.A.K.

As there's no set schedule, we should be able to just say hi to people and get them set up, then give them a little help as and when they need it.
### Outcome

E.A.K. is gives players an introduction to making on the web, in the most entertaining way possible. Hopefully, after playing, they'll make more things on the we. Yay, webmaking!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Zebetus** [comment]
@EPIKhub

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
