### ISSUE TITLE
Session on User Privacy and web literacy 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#141]
**[ Google Spreadsheet Row Number ]** 114
**[ Facilitator ]** Sayantan Saha
### Description

My session will be on privacy issue .. People will learn how to make their privacy secure on open web. I will give them tips on that  there will be hands on session on privacy and all. They will learn how to keep their secret with them. How Mozilla help one individual to keep their privacy secure .  How open source and open source technology respect user privacy and works on them. 
### Agenda

I believe in the agenda of Mozilla . My agenda on that session will be give the audience a opportunity to interact with different technologies by Mozilla. To make their private life secure. As i said I will give them a hands on session on that. 
after that i will collect feedbacks from them to make the privacy tools more secure . I will arrange a IRC channel for them those who want to be a part of the session. I will give them answers of their queries. If they want i can help them through the team viewer to configure their system.
### Participants

I will accommodate participants in to a small group. Because after listening the session they need their space to discuss on that and finishing the hands on session . I believe that after the group discussion they will come to a impact full point that how to make this things more better than ever .
### Outcome

I see the outcomes will be very fruitful for both the audience and the Foundation. There is a scope of huge discussion on several topics a great talented diverse community will be there from around the world. They have their own agenda and ideas to make the world more open and secure the user privacy and others . How to make the Open source more fruitful for users around the world .

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
