### ISSUE TITLE
Build, Teach and Protect the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#142]
**[ Google Spreadsheet Row Number ]** 121
**[ Facilitator ]** Tanzeel Khan
### Description

The session "Build, Teach and Protect the web" would be an interactive session for youth to learn how to program the webpage and how to learn effectively using different tools. In the session, people would build a webpage and would be introduced to some projects that teach web literacy. Besides, they would learn the different ways to increase Web Literacy in their region, contribute to projects and share the same with others.
The goal of this session would be to make people understand the need of learning, building, teaching and protecting the web in order to keep it open and accessible for all.
### Agenda

After introducing the participants about the session, its agenda and benefits. I will ask some questions, say some jokes (to awake them) and start teaching them like a friend.
In this session, I would introduce people to 
1. the tools that are needed to program a webpage.
2. the various resources available online that teach web literacy and that can be used to learn and make the web.
3. the problems/hurdles that we are facing in keeping the web open/accessible and the ways to help eliminate these hindrances.
4. the ways to increase Web Literacy in the region like by hosting workshops online/offline.

During the event, I will ask random questions and give swags to those who will answer correctly in order to make the session interactive and keep it alive!
### Participants

First of all, I will give an introductory talk about the session and its agenda and then according to the skill set and age, I will divide the groups so that they could easily discuss, learn and make together.
In case of 5 participants, I will ask them some 'Ice Breaking' Questions and then make them to ask me about the session, its benefit and agenda.
Then I will start with teaching them about the tools needed to make the webpage, then the resources to learn and then I would tell them the ways to teach and protect the web.
In case of 15 or 50 participants, I will divide them in groups and ask some questions and then start teaching them interactively so that all the groups would remain co-ordinated and learn and make together.
### Outcome

The goal of this session is to teach some basics of programming and building a webpage and aware them about the resources available online to learn and the ways to increase web literacy and protect the web. After the festival, they will use different resources available online to learn more about what I would teach them and they will join different programs, projects of mozilla to contribute, protect the web and learn new skills. Besides, they will organise workshops, hacktahons in their community to increase web literacy. They would share to the people, the need to learn to build the web and teach the same to others.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by amirad** [comment]
cc: @amirad

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
