### ISSUE TITLE
Growing Your Project with Academic Programs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#143]
**[ Google Spreadsheet Row Number ]** 97
**[ Facilitator ]** Dietrich Ayala
### Description

Engaging volunteers for participation in your project is often an opportunistic gambit with partially matching interests, unbalanced benefits on either side, and a wide variety of possible outcomes both positive and negative. Academic programs can be designed to mitigate many of the negative aspects to walk-up volunteer relationships, as the program designers have more control over the project, and the participants have a clear benefit in the form of class credit. This session will enable people to connect with academic organizations, identify healthy opportunities for students to learn while building software projects, and execute them such that all parties benefit equally.
### Agenda

The format will be led discussion, with some individual and group activity. We will introduce the challenges in a typical volunteer interaction, describe and explore the different types of academic interactions possible, discuss how to structure a program for optimal results, how to manage it through to completion, and the side benefits of these programs. We'll then have everyone think of some part of their own project that they could "outsource" to students, and then break up into groups to kick-start their program design with a worksheet (or Web page template on Thimble).  We'll finish by going around the room and having everyone summarize their program idea.
### Participants

The depth and length of discussion will likely vary with the participant size. The agenda describes how we'll break the session up into groups based on how many people are participating.
### Outcome

The participants will have the knowledge and inspiration to bring their ideas into reality using student programs. The session will result in academic program proposals by each participant. We'll have everyone add their proposal to the same Web page, so that we can track their progress through the year.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
