### ISSUE TITLE
Tree line

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#144]
**[ Google Spreadsheet Row Number ]** 102
**[ Facilitator ]** Jaime  Jackson
### Description

Tree line - act now on climate change, an Arts Council England funded project. 

A co-production of digital artwork leading to a national exhibition. 

Tree line brings art, technology and science together using people’s mindset shift, behavior change and participant's inspirational actions to create an incremental cultural resilience to climate change through digital art, learning through making.

Artists will work with participants, exploring their actions on climate change. Drawing together moments of mindset shift / behaviour change and people’s inspirational actions to create high quality digital artwork for a national tour.

Activity will be:
• Relational artists running participatory workshops with Mozfest participants
• Creation of the best contemporary artworks created for digital platforms

Tree line will tour the resulting digital artwork installations using latest motion capture and touch screen technology. 
Created by leading national digital artists in partnership with some of the UK's best scientists and academics.
### Agenda

Tree line will be Innovative, exciting and engaging, contributing to a greater level of understanding about mindset shift, and creating ongoing dialogue about action on climate change. Run by relational artists the workshops will enable participants to create text and visual collage artworks based on personal reflections of individual  behavior change triggers, to communicate climate change and climate change risk and cultural adaptation. 

Artists will engage with people to invite narratives and personal reflections, inspired by people’s actions and the need for environmental sustainability, we want to add to the creation of incremental cultural resilience to climate change.

These artworks will be incorporated into a digital wishing tree, an interactive and growing digital branch, trunk and root system populated by the participants own ideas and imaginative scientific, technological and artistic creations.

The project highlights the need for environmental sustainability to reduce our carbon footprint, to bring about incremental cultural change. 
### Participants

We will engage with people to invite narratives and personal reflections, inspired by people’s actions and the need for environmental sustainability. We hold teaching workshop qualifications and are practiced in delivering session goals peer to peer and small groups learning to enable participants to work effectively. 

We will hold workshops that can accommodate varying numbers of participants, not relying on a limited amount of  1-2-1 interface hardware, participants will contribute to the activity through advanced software engineering for large scale triple-A game development which could accommodate any number of participants. Our software programer artist ran his own digital download games studio specialising in 100+ player collaborative games for iOs devices. We will also working on collage, pen and paper, working with a text based artist.

Developing arts opportunities for people during the participatory workshop program, to add to the work created nationally during the exhibition tour.
### Outcome

"There is no overall Government plan or objective to improve public understanding of climate change risks." 'Progress in preparing for climate change' (Report to Committee on Climate Change June 2015).  

Tree line is commissioning experienced visual artists to create artwork inspired by the participatory outputs on the biggest threat to the world's future, participants can follow and add to the installations on-line and in exhibitions.

The work they make will be part of a national touring exhibition of high quality digital artworks with partner festivals and art venues across the country. Tree line can cop me back to Mozfest in the future to exhibit as the project will continue to tour to 2017.

We have formed a partnership with the Mass Observation Archive, arts and non-arts organisations to engage, disseminate, exhibit and archive Tree line and have commissioned a national marketing and communications company to support the project's development.

**Comment by Zebetus** [comment]
@EPIKhub

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by msaunby** [comment]
cc @msaunby @kaythaney I'm in discussion with scientists on BIFoR project to open up their data from baseline study for sharing ahead of MozFest http://www.birmingham.ac.uk/research/activity/bifor/index.aspx

**Comment by marcwalsh** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by cubicgarden** [comment]
@Saallen we need to talk about this one soon...

**Comment by cubicgarden** [comment]
@Saallen and @marcwalsh one for you guys...
