### ISSUE TITLE
Web Privacy and Web Building

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#145]
**[ Google Spreadsheet Row Number ]** 91
**[ Facilitator ]** Rahul Parakh
### Description
1. Session on tracking and preventions from it.
   2.Security steps to follow while using internet.
   3.Maintaining Privacy
   4.Prevention from getting hacked.
   5.Developing web pages using tool like webbuilder and many more.
### Agenda

Agenda
1.To show realtime tracking using lightbeam, ,ghostery. and tools to prevent from tracking.
2.To provide tips for deriving a safer and secure password.
3.To create webpage using webbuilder,thimble,etc
### Participants

It will be great with more than  20 participants.
It will have chat with participants about security steps they follow to maintain privacy.
I will take hands on activity like phishing.
It will have chat with them for deriving a strong password.
I will take live activity on web building.
### Outcome

Outcomes of  this will be
1.Learner will know about prevention from being tracked.
2.Learner will be become more strong in maintaining their privacy.
3.Building web pages will be as simple as drag and drop.

**Comment by mixedpuppy** [comment]
duplicate of issue #137
