### ISSUE TITLE
Using tablets to effectively teach programming

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#146]
**[ Google Spreadsheet Row Number ]** 101
**[ Facilitator ]** Neil Rickus
### Description

Schools are increasingly removing traditional computer suites, with only tablets available to undertake activities. This session's output will be an extended "grid of apps", outlining coverage related to programming concepts required within the English computing National Curriculum. Age appropriateness will be determined, along with progression from age five to eighteen. Apps will be given a rating for their suitability in the classroom, the available tablet platforms identified and also whether they are freely available. It will be build on my initial work here - http://computingchampions.co.uk/scratch-ams-2015/
### Agenda

Participants will be grouped depending on their area of expertise and asked to examine apps related to a specific concept or age group. Prior to using the apps, participants will be asked to decide on criteria to determine whether apps are suitable for use in the classroom and how they should be ranked. They will also record information relevant to teachers, such as price, platform, whether an Internet connection is required, etc.
### Participants

With more participants, a wider range of apps can be examined in more detail. With fewer participants, a more basic list of apps will be produced, with less guidance about suitability in the classroom.
### Outcome

The "grid of apps" can be shared with teachers worldwide and feedback sought on its usefulness. I intend to place the resource on the Computing at School website - http://computingatschool.org.uk/ and present the outcome at BETT 2016, as a follow up to my "using tablets to teach programming in primary schools" talk last year. Teachers will be free to alter the grid as they see fit and it can be updated as new apps become available, or apps are updated with additional functionality.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
