### ISSUE TITLE
EveryPolitician: easy re-usable political data & tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#147]
**[ Google Spreadsheet Row Number ]** 127
**[ Facilitator ]** Dave Whiteland
### Description

We've built EveryPolitician.org — a simple but ambitious project to collect and share data about every politican in the world, in a consistent, open format that anyone can use. We're adding a new country every day (yes, really!).
Because the data is in a clear, consistent format, if someone creates a tool or app that consumes it for their country, it'll probably work for your country too.
And to prove it, we have some examples.
You'll see the way the data works, the sort of things people have already done with it, and learn how to make their tool work for your country. And of course we'll show you how to build your own tool (and make it available for others).
This is part of the Poplus project: re-usable civic tech FTW!
### Agenda

We'll show you the site (if you haven't looked already) and show you a couple of examples of sites using that data. We'll say a couple of non-boring things about the data format. Then —boom!— we'll create new sites using those tools. Then we'll lift your jaws off the floor and help you do the same.
So after the demo, it's a workshop: we've got mySociety devs on hand to break up into groups to help people make new things, or repurpose the tools you've just seen (really: build a twitter-aggregating site for your country's politicians just by choosing your country and clicking).
At the end we'll look at the new websites you've built during the session. Whole. New. Websites. No, really. We want people to use this data, so we've set this up to be as doable as possible.
### Participants

We'll have at least three mySociety devs on hand, probably more. So when we break into groups, we'll double up if there are just a handful, or make bigger groups. The way EveryPolitician data is consumed, and the example applications created, means if just one person in a group does it, everyone else can see how that applies to their use-case too. We'll encourage discussion about how this approach works (how and why we are strict about the data we offer, and what we don't include) and answer questions.
It's possible (ideal, in fact) that some people will be more excited about collecting data rather than using it. Great! We'll bunch those people together to talk about adding new data.
If we break into lots of groups, we'll come together at the end to make sure everyone sees the cool things that happened in the other minigroups.
### Outcome

People will know we're collecting this data — and current politicians is the easy bit. We also want historic data (politicians from previous governments). They'll go away from this thinking about EveryPolitician data and spread the word that we're hungry for more.
Some people will write new scrapers and get more data.
Others will play the Gender Balance game to improve the data.
Others will take existing tools and apply them to their own country's data.
And some will write new tools using this data, which we'll help share.

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by cubicgarden** [comment]
@Saallen and @marcwalsh decided this doesn't quite fit the global village theme. Sorry
