### ISSUE TITLE
Listening with the Heart

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#148]
**[ Google Spreadsheet Row Number ]** 111
**[ Facilitator ]** Louise Ma
### Description

I'd like to teach people how to listen from the heart, as I believe the majority of us are now entrained to listen with our minds. Information can go further. And when it goes to our hearts and our guts, we can think with our entire body, which is in and of itself an entire sophisticated thinking/feeling machine that we can better understand and more wholly utilize.
### Agenda

I'd like to run an experiment where participants in my session listen to snippets of news/media/music in a "natural" state, and then in the context of listening with their heart--literally the core space in their chest where they send the input to. The exercises will be followed by dialogue and discussion about how/if they feel differently, what they observed, and what they learned. Students will learn from themselves and each other.
### Participants

I just need a room with walls so that we are isolated from sounds coming from other parts of the building. Ideally the space will be cleared so that we can sit in a circle on the floor.
### Outcome

The highest, most beautiful outcome is that people can carry on their professional and personal lives with greater clarity, greater acceptance and understanding, and less judgment, less confusion, less getting-stuck. If not, then at the very least they have a new, very different input from their daily lives--specifically thinking of thoughts and feelings being localized in their bodies. Perhaps with a Facebook group for listening with the heart, we can further discussions among us.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by cubicgarden** [comment]
Wondering if we could combine with #303 and #450 ?
