### ISSUE TITLE
BE 'RYL'  (Be A Revolutionary Youth Leader)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#149]
**[ Google Spreadsheet Row Number ]** 105
**[ Facilitator ]** GopiKrishan Bali
### Description

The participants will understand the process of 'Real Leadership' and How the true leaders communicates their vision/mission to the community.

They will be able to align their Head, Heart and Hands in a Self driven way and able to practice some powerful and very effective Communication Skills to lead their lives and projects.

The congruent person will be able to inspire team, achieve targets effortlessly while supporting others to grow.

The participants will go through an experiential process of making a plan, describing (communicating) it to all and also share their Reflection about the shift.
### Agenda

The whole process will have participant's centered activities, sharing session, To do things in an experiential way of knowing, learning and understanding the things.
During and after every stage they will Think-Pair and Share their responses and Reflect on their understanding. This ensure peer learning and group support process to get initiated
### Participants

Every individual counts. (recall the start fish story, every fish saved is making a difference )
We have a flexible adaptive approach and a participant driven methodology to accommodate any numbers (between 5-100+) :)
The whole session is based on pair-work, group work, individual introspection and whole batch work and will be in modular form. 
Hands on activities , fun driven process will not nly give participants a new way to live life but will add positivity to increase their HAPPINESS levels
(Happy people enjoy the process, perform efficiently and give generously always)
### Outcome
- Better Project participation
- Effortless giving / working
- Stronger team working
- Inspired individuals (Self driven) to drive projects
- Open sharing of ideas, best practices
  Universal family of Mozillians co-creating Happy future projects / Life

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
