### ISSUE TITLE
Teaching the Web with the New Thimble

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#150]
**[ Google Spreadsheet Row Number ]** 113
**[ Facilitator ]** Kieran Sedgwick
### Description

Participants will have an opportunity to make content for the web in a guided manner using professional tools like Thimble, Mozilla's online code editor, made accessible by the Webmaker team. Participants will use HTML, CSS, and JavaScript to remix one of three sample projects, learning the basics of the most important web technologies in a fun way! Educators will also have an opportunity to experience the power of the new tutorial system as a convenient way to share lessons.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by chadsansing** [comment]
@hannahkane, where would you like this to be? I think this is a great connector session between Clubs and Learning & Leading -

**Comment by hannahkane** [comment]
Can it be in both? If not, I'd choose Learning & Leading.

**Comment by soapdog** [comment]
cc @soapdog

**Comment by amirad** [comment]
@hannahkane is this proposal different than https://github.com/mozilla/mozfest-program/issues/455 ??

**Comment by chadsansing** [comment]
@amirad, @hannahkane: We can bring this one into our Milestones instead of the other, or we can run this in clubs and the other in L&L or visa versa - thoughts?

**Comment by hannahkane** [comment]
They are different. This one is specifically about Thimble, and #455 is about all three tools. If there's only room for one of these, I'd vote for keeping this Thimble-specific one. I gather there are other Webmaker-related sessions in other tracks, and I don't think we need to focus on Goggles.

**Comment by amirad** [comment]
Seems like there is a lot of overlap @hannahkane - maybe we join them and it lives in L&L track?

**Comment by hannahkane** [comment]
WFM, or we could just nix #455.
