### ISSUE TITLE
Crowdsourcing the Next Gigabit Cities: An Engagement Platform for Municipal Broadband

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#151]
**[ Google Spreadsheet Row Number ]** 76
**[ Facilitator ]** Josh Tabish
### Description

We are building a world-class engagement platform offering tools to push forward municipal broadband in communities across Canada. And at MozFest, we want to share this platform, and the importance of municipal broadband, with the world. Pioneering cities and towns have taken it upon themselves to close the digital divide by ensuring affordable, city-wide Internet access through municipal broadband networks. Our platform will build on the successes of these often disparate and isolated communities, and kickstart a new mass movement for municipal broadband initiatives that can be replicated anywhere. In the U.S. alone, over 100 communities have pledged to develop their own fibre, highlighting the role municipal networks can play in galvanizing the digital divide. Participants will receive a preview of our engagement platform to empower not just individuals, but entire communities, to organize in distributed, local groups, and address the digital deficits their cities and towns face.
### Agenda

This session will begin with the case for municipal broadband, through a brief presentation from OpenMedia project leads, Josh Tabish and Vojtěch Sedlák. First, we will review examples of successful, cutting-edge municipal broadband initiatives and the tangible benefits to local communities. We will then present the capabilities of our engagement platform, it’s goals, theory of change, supporter and community segmentation strategies, and the ladder of engagement for both individuals and communities as they progress through the platform. After demonstrating the platform to participants, we will then begin a series of breakout sessions, where participants will be asked to brainstorm; (i) public messaging strategies, (ii) how to activate advocates and local leaders, (iii) establishing legitimacy with key stakeholders (e.g, city councillors), (iv) engagement tactics for diverse communities, and (v) assess their own community’s digital needs. The majority of the session will be dedicated to exploring participant ideas.
### Participants

This project easily adapts to any size group, as the focus is on participants interacting with each other. The short introductory presentation will function similarly regardless of group size. And the small breakout sessions will adapt into different groups depending on the numbers, to ensure that groups do not have more than 10 people per discussion. If we have nearly 50 participants, each breakout group will be assigned a different level of engagement to discuss, such as public messaging, outreach strategies, and other items identified in the agenda above. At the end, we will feed back to the larger group with an open mic Q&A. The goal is to have participants leave with new ideas for engaging open web advocates in the future of municipal broadband initiatives and addressing the digital divide in their community.
### Outcome

As communities everywhere transition to the digital economies of the 21st century, it’s crucial that Internet advocates understand the promise of municipal broadband initiatives. Not only will we receive crucial feedback on how to improve our cutting-edge engagement platform, but we also plan to expand the network of makers, educators, innovators and advocates who can help overcome obstacles to affordable, world-class access, and ensure that no community is forced to face a future of digital “haves” and “have-nots.” We will ensure that every participant has a tangible step-by-step project outline for how to advance municipal broadband in any given community. Affordable access is a global issue, and we’re trying to create a scalable solution. Finally, we will continue building and facilitating these networks, coalitions, and partnerships long after the conference's completion.

**Comment by thornet** [comment]
cc @LindseyFrost in case it's of interest re: Gigabit cities.

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by cubicgarden** [comment]
Unfortunately this won't be happening anymore, due to travel costs
