### ISSUE TITLE
OpenBlogging

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#152]
**[ Google Spreadsheet Row Number ]** 77
**[ Facilitator ]** George Oriaifo
### Description

OpenBlogging session will allow people to learn how to use Blogulr! (an openblogging community plus social network) to express their passion for their profession through articles and advertise effectively for free on Blogulr.com and across other social networks. 
### Agenda

The agenda of the session is to show people how to maximize the effect of their internet activities on their professions and businesses by using their articles to complement and promote their adverts instead of promoting sponsored adverts only.

At the workshop, participants will signup as users, complete their profiles, setup their adverts, create articles of their interest, post them on Blogulr.com using recommended practices, share their articles on social networks, other online communities across the internet and monitor traffic to their pages.

There will be a chat session where we will all talk about:  the necessary features for an openblogging community, comparisons between Blogulr and other online platforms, what's-working and what's-not on Blogulr, why Blogulr is or is not necessary.
### Participants

5 participants: All 5 participants will participate individually at the workshop and collaborate as a group to make the best of their individual activities. We will all sit as a group during interactive sessions.

15 participants: Participants will be shared into 3 groups of 5. They will all participate individually at the workshop and collaborate with their group members (and members of other groups when necessary) to make the best of their individual activities, while I supervise. We will all sit as a group during interactive sessions.

150 participants: Participants will be shared into groups of 10. They will all participate individually at the workshop and collaborate with their group members (and members of other groups when necessary) to make the best of their individual activities, while I supervise. We will all sit as a group during interactive sessions.
### Outcome

By the end of the festival, all participants will be collaborative members of an OpenBlog community, helping each other make the best use of Blogulr and the internet while helping to make Blogulr better by sending suggestions and ideas as emails, messages, tweets and/or comments on an appropriate post on Blogulr.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
