### ISSUE TITLE
Women's Rights and Gender Equality on websites

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#153]
**[ Google Spreadsheet Row Number ]** 68
**[ Facilitator ]** Ghewa Srour
### Description

In my session, people will get to know how to use internet to ask for their rights, especially women (abused women, young age married women, uneducated women/girls, etc..) I have been already working on a mobile application that helps women get help when needed and knowledge to know their rights. I believe that women especially in the Arab area, need more education to know how to ask for their rights and speak aloud! Nowadays and with the help of the internet and technologies, I believe we will be able to make a difference. The session will mainly shed lights on topics participant (interested in the topic) should look for on the internet to satisfy their needs and get the information they seek.
### Agenda

Well the agenda will definitely depend on the duration of each session, and weather I will be giving the sessions during the 3 days or only for one day.
But in general, the agenda should be approximately in the following format:

Introduction about internet usage and benefits. Introduction about women's rights, gender equality and young age marriage.

workshops will definitely ask for the usage of a laptop to show how to search for the topics we need and how to look for the information we seek.

discussions will always be held between the participants weather through the introductions part or the workshops.
### Participants

5 participants, we will all get engaged together, share ideas and topics. 
15 participants or more, I will divide them into groups and ask each group to discuss the topic among its members and then we get all together and have a discussion between the groups and I. This way they all will be able to participate and share idea.
I may also ask each member to write his/her ideas on a paper and then we get into the group discussion without dividing them into groups.
I can use the two points as a way of breaking the routine during the sessions. 
### Outcome

As for me, I will try to get benefit of all the technical information I will be able to learn from people at Mozzilla Foundation so that I can set my next steps on my mobile application at my country. As for the participants, I believe they will end this event with more information and more internet abilities especially on how to use internet in a way that helps women and young girls know more about their rights and make men able to know how to use the internet to advice other men and teach them more about gender equality in their countries.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Melechuga** [comment]
Potential for panel session w/Smart Girls' Guide (x2)

**Comment by Melechuga** [comment]
cc @marcwalsh @Saallen unlabeling. Thanks!
