### ISSUE TITLE
Firefox OS app-building workshop

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#154]
**[ Google Spreadsheet Row Number ]** 72
**[ Facilitator ]** Errietta Kostala
### Description

Participants will learn to build their own Firefox OS app or game, ready to publish in the market! The session will allow them to build an app of their choice while getting help from other participants.
### Agenda

This will be a workshop session. I will show the basics of making a Firefox OS app and running it in the emulator, and I will then provide some examples the participants will use. The participants will be able to work alone or in a team to make their own app, using the examples and getting help from myself and other participants if needed. I will make sure the examples are suitable for varying degrees of knowledge, so both experts and completely new participants will be able to partake and enjoy the session.
### Participants

A smaller number of participants will allow for me to show more things and help the participants more. However, a bigger number of participants should allow participants with more knowledge to help others with less knowledge, as well as provide more app-building ideas by different people!
### Outcome

By the end of the session, the participants will be able to build their own app, and teach others how to do so. This will hopefully also increase interest in populating the Firefox OS market with useful apps.
I also hope for the session participants to run similar workshops in the future, especially in schools, and show people how they can make fun apps for Firefox OS using only web programming knowledge.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin we have about 3 of with these focus.  Errietta's session is participatory
