### ISSUE TITLE
Click Clean, Build Green

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#155]
**[ Google Spreadsheet Row Number ]** 80
**[ Facilitator ]** Andrew Hatton
### Description

This session will explore Greenpeace's campaign for a Cleaner Cloud - a cloud we can be proud of it, a cloud which is part of the solution to todays environmental challenges rather than part of the problem.
During this session people will learn about the journey Greenpeace has been on with the tech industry.
How we have gone from being viewed as an unwelcome outsider, to a welcome partner (by most) in moving to a cleaner cloud.
### Agenda

Fireside chat, telling the story of a very untypical campaign, from inception, through to execution and also where we are now/today.
We will explore our latest development, which is our clean Cloud plugin (currently for Chrome but other browsers coming soon).
Depending on the numbers, we may also co-opt the audience to take part in a bit of a twitter storm - helping our campaign along it's journey even more...
I'd also like to gather new ideas from the participants for how to take the campaign forward.
### Participants

In many ways it will be the same conversation.
But I guess the ideas gathering with a smaller group will be different, i.e. it will be easier to engage a smaller group  and get more involvement from them than it will with 50 people. If it's 50 people, we can still get them involved but it will have to be a more structured event. One idea here would be to have audience mass participation, which might sound cringey but could work. For example a big selfie and shout-out and then I tweet the photo to our campaign group for spreading on twitter.
### Outcome

The outcome for us would be spreading our message and also educating the audience about where the tech sector is in terms of renewables and clean cloud - all done in a fun and light hearted way of course.
We would hope people would come away converted to the importance of building a future Internet which has renewables at it's centre.

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by thornet** [comment]
cc @Melechuga as well

**Comment by cubicgarden** [comment]
@Saallen and @marcwalsh notice
