### ISSUE TITLE
Life around Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#156]
**[ Google Spreadsheet Row Number ]** 74
**[ Facilitator ]** Akshay Rajput
### Description

Every smartphone and PC user access the internet.
They know what is internet. But when it comes to "Web" , Nobody knows that what's the difference between web.
also what is open source , why this is important for us.
Like the current scenario people are shouting net neutrality in india. What is that. People will find the answer in my session. 
### Agenda

Keynote
Introduction to web
Web in daily life
Open source
fun with HTML5
### Participants

5 is a good number. it's good ,if i'll get this much. i'll discuss the question that everyone have in their minds but never had courage to ask. I'll tell them how open web is important for them and how can they support.
### Outcome

Ok,.. If i talk about myself , I inspired by a event on HTML5 , 3 years ago and started supporting open web. 

May be there are others like me out there waiting for someone who can show them a way to start.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
