### ISSUE TITLE
Innovation 101

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#157]
**[ Google Spreadsheet Row Number ]** 78
**[ Facilitator ]** Costa Michailidis
### Description

Mozillians make and maintain some of the coolest tech on Earth. Firefox is one of the most disruptive pieces of software out there. All this is done, with no formal education in Creativity & Innovation.

This session would give people the opportunity to learn and practice innovation techniques backed by research in the psychology of human creativity : )

My hope is that Mozillians will leave the session with more confidence in their own creative ability and some new habits that will drive innovation in their everyday lives.
### Agenda

We'll start out with a giant line on the ground (Made of masking tape : ) 

We'll ask people to imagine that this is a spectrum. On one end, "incremental innovation - small improvements" on the other "radical innovation - big change".

People will walk over the place on the spectrum they feel represents them best. A discussion will ensue about how both of these sides of innovation are super important, and how everyone has a tendency to be creative in their own way.

Afterwards participants will brainstorm ideas for incremental or radical innovations, form groups around their favorite ideas and develop them; getting feedback from their peers along the way. 

I'll provide some tool cards with specific thinking tools meant to assist in various stages of the innovation process. (If time allows we can present content instead)

Ideally, following the workshop, people run with their ideas!
### Participants

It should work regardless of the number of people since the workshop runs mostly with people in small groups. It can run with one group of five people right on up to 10 groups of five people.
### Outcome

Being a great engineer or developer is paramount, but it's not the only skill needed for Mozilla to stay relevant in the market. Mozillians need to have strong innovation skills in order to maintain Mozilla as a disruptive force, not a disrupted one.

The workshop is meant to inspire participants to pursue greater knowledge of creativity and innovation skills, and to lay some foundational habits for innovation.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
