### ISSUE TITLE
Securing the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#158]
**[ Google Spreadsheet Row Number ]** 60
**[ Facilitator ]** Sumanth  Damarla
### Description

This session focuses on building Web Security Awareness for the attendees. Its helps  the attendees to build  their applications more securely using Web Security Tools[1].
With the help of security tools, People can attack their own designed Web applications and check for the vulnerabilities in their applications and code it more securely. 

For an instance, Assume a coder created Login page, He can use ZAP (Web Security Tool) to attack his Login page in different ways and sort out the ways to trace out the flaws. In this way ZAP gives the coder chance to build their Web Application more securely. (Though its only one of the many features of ZAP). 
### Agenda

With the right skills, tools and software, you can protect yourself and remain secure. This course will take attendees from no knowledge of ZAP to a deep understanding of how to use it and its growing set of capabilities. This is a rare opportunity to learn how to use advanced ZAP features.
Session Plan:
-> Introduction to WebSecurity.
-> Importance of Security Testing Phase in SDLC.
-> Discussing the OWASP Top Ten Vulnerabilities.
-> Introducing ZAP as a testing environment.
-> A live demo on testing web application. 
### Participants

After discussing about top ten OWASP vulnerabilities, depending on the participants count we will decide on having a Hands-on session which focuses on attacking the sample authorised websites  to learn pentesting with ZAP. With 50 members in the session, we plan to set testing environment in the respective machines of the participants and help them getting started. With participants less than 20, a live demo on getting started with testing web application is organized which does not require participant’s laptop. It is shown on the screen. At the end of session, few simple challenges are given to participants to work on them. (Bodgeit Store challenges.)
### Outcome

We would be able to show path for the attendees how he/she can contribute to Mozilla in Security Aspects. The participant  can be able to contribute in following areas:
-> Help in solving vulnerabilities of Mozilla websites. 
-> Contributing to Mozilla security tool.
-> Working on bugs related to vulnerabilities issues.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
