### ISSUE TITLE
Reporting with Structured Data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#159]
**[ Google Spreadsheet Row Number ]** 81
**[ Facilitator ]** Jacqui Maher
### Description

Reporting the news involves gathering, assessing, creating and presenting information... often in an unstructured manner, whether for print, digital or broadcast. The relationships between the people, events and themes in the coverage get lost in a sea of text or video, as does the opportunity to leverage this knowledge and data in future reporting.  

This session will explore methods of retaining the structured data that lives in your notes (or thoughts) as you develop a story.
### Agenda

Expect to walk through the creation of a story, finding the points where digital tools can help journalists and the audience alike. We'll brainstorm and prototype a variety of approaches in a variety of media, including paper and the browser. 

Bring your ideas, a notebook and your laptop. We'll have sample stories to start from, but leads will be welcome if you have a particular story you think lends itself well to this topic.
### Participants

We'll break into smaller groups depending on the number of participants: each group can focus on a particular approach, then relate their experience and findings.
### Outcome

Participants will end up with prototypes for structured reporting tools and a hopefully new way of thinking about what we lose - and can ideally retain or gain - in the process of presenting our reporting.

**Comment by ryanpitts** [comment]
Jacqui is based in London, so travel would not be an issue.

**Comment by jacqui** [comment]
Hello, @jacqui here. Did you have any questions about this session proposal that I could answer? Just wondering about the status. I am indeed in London at BBC News Labs and would not require any kind of travel or accommodations :)

**Comment by EPIKhub** [comment]
@jacqui I could invite you to the youthZone if you was interested in working on your session from a youth perspective?

**Comment by thornet** [comment]
cc @ryanpitts to confirm the status of this session in Github and the schedule spreadsheet.
