### ISSUE TITLE
Kickstarter hacks

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#16]
- Facilitators name
-  A case study of people who have used Kickstarter successfully and the lessons they learned about how to successfully raise money through crowdfunding.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for building a crowd

**Comment by Melechuga** [comment]
Placeholder
