### ISSUE TITLE
Youth Empowerment 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#161]
**[ Google Spreadsheet Row Number ]** 115
**[ Facilitator ]** MOHAMMAD SALEH
### Description

I'll present youth empowerment skills also i will do with knowledge sharing in communities and how we can do it with NGOs and make youth fully power and having energy to start learning and sharing  with others , once I start with Leaders Of Tomorrow initiative in Amman , Jordan  we have one mission to train and study the youth environment from A to Z and we develop social platform to target people and trainers and share all opportunities and culture exchange for youth  , I hope to share youth skills 
### Agenda
- Youth Definition : 30 minutes
- Youth Power : 20  minutes
- Training & Sharing :  30 minutes
- Coffee Break : 20 minutes 
- Social Platforms : 20 minutes
- Youth and Knowledge : 20 minutes
- Closing : 20 minutes
### Participants

I will divide every five persons in one group and make all groups work with Youth development skills ideas
### Outcome

I hope to share this knowledge and skills with other communities and make youth power always motivated and possible and we will make big youth community with mozilla

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Zebetus** [comment]
@EPIKhub once again a way to look into seeing what young people would respond to when we are trying to empower them

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
