### ISSUE TITLE
Node.js and Express for Frontend Engineers

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#162]
**[ Google Spreadsheet Row Number ]** 128
**[ Facilitator ]** Cameron Hendrix
### Description

This session is designed to help frontend engineers learn the fundamentals of creating and navigating a Node.js app, ranging from webserver fundamentals to view fundamentals to arcane npm knowledge. Frontend developers will leave knowing how to get their bearings in a Node project and what to learn next in Node.
### Agenda

This session will be an interactive presentation / workshop format going through http://thinkful.slides.com/thinkful-admin/node-express-for-front-end-engineers-5?token=aBW9oDRj

During the presentation, we'll cover:
1. Web Server Basics
2. What are Node and Express?
3. Working with Modules
4. URL Routing
5. Middleware
6. Templating with Jade
### Participants

With 5 participants, we'll be able to go further in-depth with Node (and tailor it to the individual experience of folks in the session). With 50 participants, I would ask the advanced folks in the room to help out people who are having trouble. This approach worked pretty well with a workshop of ~25 people at Frontend Camp in NYC.
### Outcome

Participants leaving the session should feel less intimidated by the backend and by Node. They should be able to move forward more confidently with single-page app-type frameworks like React or Angular (since they'll understand what's happening under the hood on the API request parts of those apps), or move further into backend programming with Node.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
