### ISSUE TITLE
Privacy best practices for website and app developers

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#163]
**[ Google Spreadsheet Row Number ]** 119
**[ Facilitator ]** Guillaume Marty
### Description

Privacy is an important topic and every one involved in making of content on the web should be concerned about. 
The goal of this session is to think about the problem in the perspective of creators. How to build websites and apps that are safe for their users' privacy? Let's gather and make a list of best practices in that field!
### Agenda

I'm expecting this session to be like a discussion around the best practices for making privacy aware content on the web. This will lead to the creation of a document.
### Participants

I expect the document to be a wiki that people can edit live if there are a lot of participants. Otherwise, we can talk and discuss each items.
### Outcome

I'd love to build and maintain a set of best practices about web development and privacy that people can consult and amend. This list will be publicly available, released under a creative commons license and open to editing.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
