### ISSUE TITLE
Encouraging Contributions from Young Developers

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#164]
**[ Google Spreadsheet Row Number ]** 126
**[ Facilitator ]** Ryan Warsaw
### Description

Attendees will brainstorm ways of encouraging young developers to be code contributors. We will discuss some of the strategies I found most helpful, such as having thorough, well-written documentation and better communication strategies for encouraging participation.
### Agenda

At the beginning of the session, I’ll start off by sharing my own experience as well as sharing some of the strategies I found most helpful, which should spark discussion in the group and lead to further brainstorming of ideas. This would fit under the fireside chat / round table discussion format.
### Participants

With 5 participants we would have time to go over some ideas and discuss in more depth, with more participants we would simply just be limited to how in depth we can go on each topic while still giving everyone a chance to discuss. I would like to cap this event at 20 people max.
### Outcome

Participants will hopefully take their newfound knowledge and apply it to their own projects, improving the young developer participation rate for these projects. It would also be awesome to have participants report back what discussions were sparked by this session within their own groups / projects.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin @EPIKhub  could help intersect  youth zone and participation but depends what we mean by 'young developers'.

**Comment by EPIKhub** [comment]
@emmairwin @geroter it's certainly an area I am really interested in to explore as a whole; what would be cool is the ask the youth themselves rather than we the adults working it out for them type thing :) it should be done together as a collaboration.

**Comment by EPIKhub** [comment]
@emmairwin @geroter Ryan just pinged me on FB, he is a new to our group youth contributor, so Ive tagged him into the youthZone, I'm sure we can do more than 1 session here :) so maybe one in participation too?

**Comment by emmairwin** [comment]
+1 for sure in participation.
