### ISSUE TITLE
Research Reproducibility: Hands-on Experience with Replication

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#165]
**[ Google Spreadsheet Row Number ]** 130
**[ Facilitator ]** Garret Christensen
### Description

We will provide an opportunity to reproduce the results of a prominent academic publication. The goal of our workshop would be for attendees to be able to find a suitable publication, locate and download the original data from the Internet, reproduce the original results, and extend the analysis to probe the robustness of the published findings.
This would require that the participants have some statistical knowledge, as well as programming ability (R preferably, since it is available free, but also possibly Stata, SPSS, SAS, etc. if students have that software themselves).  However, by using a relatively simple randomized trial (such as “Are Emily and Greg More Employable than Lakisha and Jamal?” by Marianne Bertrand and Sendhil Mullainathan, 2004  just to name one possible example) on an important and easily understood topic (racial discrimination in employment), and by having attendees work in small groups, even beginners should be able to benefit.
### Agenda

Our workshop would begin with a 10-minute introduction to the reproducibility crisis in social science research, including such topics as publication bias, study registration, p-hacking, pre-analysis plans, and concluding with a discussion of data sharing and replication, and how these can be used to make research more reliable.

The majority of the time in the workshop would split the attendees into groups of approximately five, and instruct them to download the original dataset from the journal’s repository. Using the authors’ original code, attendees will attempt to first run the original code, and then extend the original analysis by constructing a new regression specification. We will offer up to three studies to replicate for participants to choose from.

To conclude, groups will present their findings to the entire workshop, and we will collectively discuss the sensitivity of the results to different specifications.
### Participants

Since we plan to divide attendees into small groups of approximately five people each, the workshop is quite easily scalable. The two main instructors plan to circulate among the teams answering questions and offering assistance, so attendance of only five would enable more direct assistance (but perhaps less interesting cross-group comparison) while attendance of 50 would be easily handled and would allow for interesting comparison of the different results of different groups. We will ensure that each group has at least one participant with advanced coding experience.
### Outcome

This workshop would stress the importance of data sharing and replication. By learning that some journals share data in a public location, we feel that workshop attendees would leave expecting that all researchers should share data, which could help change research norms. We also hope attendees learn the benefits of replication to their own knowledge (e.g. learning regression techniques by seeing how others do it) and to science (helping build a more reliable body of scientific evidence). Lastly, attendees should leave understanding how the web and its sharing tools and data repositories play an important part in reproducible science.

We will ask the participants to publish the results on Dataverse and the Open Science Framework, we will blog about the experience, and we will take this forward by embedding the most important take-home points from a pedagogical perspective into our own teaching, e.g. in the Replication Workshop at Cambridge.

**Comment by laramz** [comment]
Hi, is it still possible to somehow receive the do file to the paper (“Are Emily and Greg More Employable than Lakisha and Jamal?” by Marianne Bertrand and Sendhil Mullainathan, 2004) you mentioned? I am trying to replicate it at the moment.
