### ISSUE TITLE
IT Kids Clubs Kenya Safe Web session

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#166]
**[ Google Spreadsheet Row Number ]** 116
**[ Facilitator ]** Cleopa Otieno
### Description

Enable kids learn how to use the web responsibly, what and what not to share on social media sites, how to use social media to boost their networking and learning and enable kids learn basic web search skills to aid their research and learning.
### Agenda

This will be done at one of the telecentres in western Kenya where kids have been undertaking computer classes. The agenda will be drawn from the goals and it will take a workshop format.
### Participants

We will have one group of 30 people ages 5-18. We will have a joint session but also work in groups of 5 to discuss and report back to the main session. 
### Outcome

Since they are students they will be expected to use these skills in their studies, they will also be expected to be more responsible while using the web. They will also make good use of social media sites, those who do not have email and social media accounts will create and start using them.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by chadsansing** [comment]
cc @amirad

**Comment by soapdog** [comment]
cc @soapdog
