### ISSUE TITLE
Enhancing Open Web Experience

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#167]
**[ Google Spreadsheet Row Number ]** 120
**[ Facilitator ]** John Baptist Ochieng
### Description

Our session will allow the attendees come up with webmaker makes using the webmaker app, they will learn how to teach the Internet to others with both the availability and unavailability of Internet connectivity, and they will also leave with a proper understanding of the web, and learn how to use the web reliably and efficiently, which will enable them become citizens of the web 

Goal: Teach the open web offline and translate this knowledge to the web by illustrating the enhanced usage of the web.
Participants will learn how to train the open web without Internet connectivity and acquire skills of interacting with the web reliably and efficiently. 
Participants will learn, create makes, play games and compete in challenges 
### Agenda

Format: Interactive learning coupled with tutorials

Introduce basics of the web
Ask participants what they would want the web to do for them, or what they would want to do with the web.
Utilize crafted paper prototypes, card puzzles and games that would visually illustrate how to achieve the tasks from 2 above.
Hold a competition oriented challenge where participants will be tasked to map up a pattern of how to access, learn, connect, share and contribute on the web. 
Envisage the open web as any other daily life activity (i.e. sports, entertainment, education etc), match the concepts of the chosen activity to concepts that are consistent to values of the open web.
Webmaker app illustrations on paper.
### Participants

For small groups of participants, e.g 5 or 15, We shall have one circle, and for larger numbers, we shall work in small groups depending on the number of attendees we have, because the group resolves issues with each participant, the attendees get new insights by hearing different viewpoints and having their ideas critiqued, and learn and commit to new knowledge from the group discussion and decisions.
### Outcome

We hope to ignite off line teaching of the web and emphasize the ingredients of enhanced open web usage. Ultimately, our participants should have the ability to understand the web, and know how to use the web to fulfill exactly what they needed.
We hope to transform novice web user to intermediary web users and intermediary web user to expert web users, i.e. the degree of openness of the web will be boasted for the varying type of participants.
We hope to establish an outstanding format of teaching the web to all, and we hope to implement all this by teaching the web in schools here in Africa through web maker clubs.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
