### ISSUE TITLE
Start an open science study group

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#168]
**[ Google Spreadsheet Row Number ]** 123
**[ Facilitator ]** Anita Raichand
### Description

The session will inspire participants to create their own study groups in their communities.
### Agenda

Explain how study groups work, how to start one, content ideas and tips for running a successful group. I think it could be a fireside chat in a one hour format.

Another idea is actually running a small study group session similar to what we do in our local community.
### Participants

With 5 or 15 participants, we could do a hands-on session with the repo. With 25-50 participants, it could be more like a question and answer session.
### Outcome

The goal is to inspire others to start study groups that teach skills and collaboration in open science. We will take it forward by being available to answer questions and provide resources!

**Comment by painterly** [comment]
Very excited that my open science session proposal is a go even though I won't be there in person. Thanks to all the amazing participants for filling in and looking forward to learning about their perspectives. Here are some of my notes for 'Starting an Open Science Study Group' session (http://slides.com/practicaldatascience/blendedlearning). Feel free to share @Mozilla. The blended learning notes may be of interest to Mozilla Participation @emmairwin. Cheers and have fun:)
