### ISSUE TITLE
Your Privacy on the Web (Using Firefox Browser and more)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#169]
**[ Google Spreadsheet Row Number ]** 122
**[ Facilitator ]** Ankit Gadgil
### Description
- Security and Privacy being an important part of our online lives. This session will help attendees understand privacy and security on the internet better.
- I am taking a Firefox centric angle to showcase how Firefox puts the user first by guarding user data with privacy and  “do not tack” focussed approach.
- Participants will learn:
  *\* How to take care of their privacy online
  *\* Best practices to follow
  *\* How firefox can help them do it - using Firefox Like a BOSS
  *\* Various Privacy addons that can help user guard against unwanted tracking, ads and third-party cookies.
  *\* Understanding cache, cookies and permissions on website.
  *\* What is secure browsing (https)
  *\* Cookies and trackers
-  This session is contemporary, essential and practical discussing Privacy & Security with peers, students, teachers and netizens.
### Agenda
- I will be building up on my last year’s session at mozfest14 where we discussed the privacy features and learnings. Taking it a step further I will be discussing a practical and solution focussed approach by demoing addons, features, tips and tricks using Firefox Browser.
- The format of this session can be a hack booth, a session or a maker party table with handson for visitors.
- Session will have discussions, training and participatory learning on the following topics  
  *\* Privacy and security aspects on the web.
  *\* Private browsing
  *\* about:cache in firefox
  *\* about: memory in firefox
  *\* addons like ublock, adblock, ghostery
  *\* http vs https, certificates and why we need them.
  *\* Understanding Cookies are tracking.
  *\* User’s digital footprint  - handson
- Activities from the Privacy teaching kit: https://stacy.makes.org/thimble/OTI5Njk0MjA4/privacy-teaching-kit
- Format example: http://blog.mozillaindia.org/823
- Slides: 
  *\* http://www.slideshare.net/ankitgadgil/firefox-boss
  *\* http://www.slideshare.net/ankitgadgil/privacy-and-security-mozilla-firefox-30239914
### Participants
- This session is more about participatory learning and participants will learn as they practically work on Firefox. 
- A small intro talk and how to will help them spend some time at the session/booth and handson on Firefox Browser trying out advanced features and privacy addons, tips & tricks will help them understand aspects related to Privacy and Security on the Web.
- Having various aspects of understand Privacy and security on a display on computers, screens or monitors at the session/booth will help participants hack, make, learn and share with other participants.
- I will be comfortable facilitating for a varying number of participants at a time, I will be displaying slides, images, memes to explain things easily.
### Outcome
- The attendees/participants will take home an understanding of Privacy on the web,  How they can protect themselves while being a part of the open web. 
- The participant may want to help others (friends, family, classmates and colleagues) by teaching about Firefox and the privacy focussed aspects of it.
- This will facilitate growth in Firefox user base and also help the normal user to be an advanced user of Firefox. 
- They might want to be a mozillian contributing to Mozilla and/or joining the Privacy Task force: 
  https://wiki.mozilla.org/Privacy/Privacy_Task_Force
- The use of search engines that do not track their activity- duck duck go.
- Understanding and getting to know about this is the 1st step towards securing the HEALTH of the web.
- Participants might get interested in helping us teaching privacy on web, advocate open web.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy
This could be the FF session #SharePrivacy (#457)
