### ISSUE TITLE
World of Privacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#170]
**[ Google Spreadsheet Row Number ]** 129
**[ Facilitator ]** Abdelrahman Manna
### Description

Nowadays, in the big technology revolution we live, the need of securing the internet has been increased so that the techniques of the security also have to be increased and developed to walk in parallel with the technological development so we can live safely and avoid the security gaps as much as possible.
### Agenda

At the beginning of the session, we will show the main security challenges and all its aspects, discuss the reason behind making our session, then begin discussing the goals and work on the idea we are talking about by sharing the technology and the suggested results after applying that idea. At the end, we will show how our idea is going to take place in the world of privacy.
### Participants

In case of small number of people such as 5, we can discuss the idea in its specific details so that we can work on applying it in the real security field. For larger number such as 15, we can talk more general by discussing the goals and guide them how to apply this technology in step-by-step process. For much larger number such as 50, we will talk  generally about the technology and put the main points of how they can work on it and how it will affect the security aspects using a projector and data show to help us spreading our information.
### Outcome

The technology can be easily applied in the security field around the world and takes place in the world of privacy as it is newly developed and hasn't been widely used, so we can become ones of the first people who apply this technology especially in the security field because it has many sides beside that field, and the participants will be helped staying safe by protecting their presence and internet surfing.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
