### ISSUE TITLE
Tate Digital Learning - 'Albums, Sketches, Etc..!'

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#172]
**[ Google Spreadsheet Row Number ]** 125
**[ Facilitator ]** Luca Margherita Damiani
### Description

What is an album on the web? Is this a place for research? Is this a place for memories? Is this a place for creative and visual making? Using the 'Albums' digital web platform from the Tate (www.tate.org.uk/art/albums), participants will be able to create their own artistic digital platforms. The Tate Albums feature is a way to pull together data, curate Tate artworks, research items and archive all user created content. The session will have an engaging learning curve around digital making and web literacy, allowing creative thinking and reflection. With both an individual and participatory group approach, the activity calls participants to start their own digital albums and share their personal interests, identities, art and more!
### Agenda

During MozFest 2014 we run a Tate Digital Learning session with the Art track. The workshop 'Culture Remix Jam' allowed participants to remix the Tate site and learn about curatorial creativity and coding. This was run with a drop-in workshop approach. With 'Albums, Sketches, Etc..!', this year we would like to work in a similar way, allowing participants to come to the session and engage with the 'Albums' platform in a hands-on making way. We will bring four to six laptops, two USB printers and one scanner: this tech-installation should be enough. If, for whatever reason, the internet connection does not work (!), we will shape the session focusing on the making of albums (even in an analogue way if needed), discussing the overall concept and then show-casing how to use the web-platform. The 'Albums, Sketches, Etc..!' aims to think of web literacy as a shared experience of creativity.
### Participants

Due to the fact that the session will have a drop-in identity, we will need to be flexible and dynamic when working with the participants. Creating an album is a process, so there are lots of stages that will keep people busy: mind-mapping, using our laptops, creating a paper-album, or simply browsing all the art magazines we will bring for inspiration! People can work independently on the web-platform but we will encourage small group work for creation and exploration – participation is key.
### Outcome

During last year session at MozFest, we observed and evaluated the workshop in relation to its relevance to the arts and coding. This was done balancing different ethnographic techniques and also collecting participants' feedback; it was part of a wider research angle within our Digital Learning programme. We would like to evaluate the 'Albums, Sketches, Etc..!' session in a similar way but focusing on its art and web-literacy aspect. This review can happen during the festival but will continue also after the event. Participants will be able to create their own albums on the Tate platform; these web-albums will have a life after the event itself (as you can also see from here: www.tate.org.uk/art/albums/) and so participants can keep creating and updating their web presence with images, videos, text, etc. We aim to engage all kinds of participants to become active digital makers!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @cubicgarden  cc @ileddigital

**Comment by marcwalsh** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by Saallen** [comment]
cc @cubicgarden - this is from the Tate. would you be interested in this session?

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
