### ISSUE TITLE
The Invention Shop (with Know Cards)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#173]
**[ Google Spreadsheet Row Number ]** 135
**[ Facilitator ]** Alexandra Deschamps-Sonsino
### Description

We will give participants free packs of Know Cards (worth $140) to learn how to invent the next generation products they want to see in their local John Lewis.  A lot of smart product ideas can emerge from knowing what the building blocks are and Know Cards does that in a visual and accessible way. From inputs, outputs, power and connectors participants will get a chance to learn how to use the cards and brainstorm product ideas that could be built. 
### Agenda

We will introduce the cards to participants and explain how they work and 2 different ways to get good ideas. Then participants will get to populate a paper-made shop with product ideas they have drawn or built (based on cards they have selected) out of paper. The ideas will be well documented and each participant filmed to explain their idea in 6 seconds so we can post it on social media. 

The model is based on a workshop we ran at the Victoria and Albert Museum last year around wearables. (https://vimeo.com/101944079).
### Participants

I think we're looking for less than 20 people to do this as we'll be bringing packs of cards and physical making materials (scissors, paper, glue, etc). 
### Outcome

We would love to see people understand how to make things more quickly and easily using the cards and suggest to us different ways of interacting with them. We offer free cards to schools already and would love to see if they work well as an education tool during the workshop and if they convince people to 'make things'. Electronics components are still very intimidating for people, so using cards should give them a better idea of where to start ideally.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @cubicgarden
