### ISSUE TITLE
Data says no. All the things you can’t do with your dataset and why. 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#174]
**[ Google Spreadsheet Row Number ]** 132
**[ Facilitator ]** Mevan Babakar
### Description

We’re working with ONS Digital to create a machine readable format for caveats to statistical data. This will tell you what you can’t do with the data - a part of the open data ecosystem that is often overlooked, with unfortunate effects. 

Our session will teach people about the limitations of data sets and how to spot commonly overlooked details. From the simples ones: definitions, units, rounding errors, to the more complex: a change in government policy, new survey sample design or an anomalous data point.

Our session will also give people a tour of the sources we use as factcheckers on a day to day basis, and showcase examples of data sets that are skewed by certain events such as a Royal wedding.
### Agenda
- An introduction to the problem, using case studies of how bad data has had damaging effects in the past.
- An introduction to the types of caveats that are often overlooked
- An opportunity to play with the API (for those who can) as a small workshop. There will be a few exploratory questions that people will answer in teams. Experience of APIs isn't necessary.
- A discussion around the session, the caveat system we’ve devised and how to improve it.
### Participants

5 Participants: One group working together or pairs depending on laptop distribution.

15 Participants: Three groups working independently of one another then coming together for the group discussion.

50 Participants: Instead of being in pairs and doing the workshop, we would run it as a demo, answering the questions in turn, then offer a 10 minute free-play where people couple explore the system on their own. Interesting discoveries would be fed back into the discussion. 
### Outcome

The system will be in beta at this point with a taxonomy of about 40 caveats. We want to ask participants how it could be improved upon: how best to communicate the concept, what else it could be applied to apart from statistics and how we can optimise it for journalists.

This is as much about teaching us the value of a good product as it is about participants learning about the value of a good dataset!

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
