### ISSUE TITLE
Visual and material techniques to enable teaching and learning about complex technical concepts: methods for trainers an

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#175]
**[ Google Spreadsheet Row Number ]** 134
**[ Facilitator ]** Maya Indira Ganesh
### Description

Tactical Tech's newly concluded research project, Security in Context, has looked at how human rights defenders and activists adopt digital security and privacy practices. Evidence from three countries shows that one of the  challenges faced in adopting digital security practices is the personal, culturally specific mental models of how we think the internet and digital technologies work. These mental models can either enable or limit how we adopt technologies and apply technical knowledge of them in different situations. We have been working with visual and material techniques to externalise, or show, these mental models. Knowing about the cultural and personal models of technology people have can be valuable information for  educators and trainers to develop culturally relevant and customised learning and teaching processes. These practices can also be used as process evaluation methods to understand how people's learning is increasing -or not. 
### Agenda

This session will take the format of a workshop. It will participatory and, quite literally, hands-on. There will be some framing and introduction of the session and its goals, and presentation of the context in which we developed these techniques (I.e research on learning about digital security and privacy amongst human rights defenders). Then, participants will work in groups to externalise their own mental models about technology, and then present these. The session will end with a reflection and feedback on the process, as well as recommendations for how these techniques can be integrated into training and learning curricula. Tactical Tech's new videos about encryption will also be shown to spark a discussion about how visuals and metaphors are used in teaching and learning about complex technical concepts.
### Participants

15-25 participants is an ideal size for this workshop. There will be framing and introduction followed by some interactive group work using different visual and material techniques, followed by feedback, reflections and a discussion about how these techniques can be integrated into teaching/learning processes.
If we get 50 people, we will change the format a little bit and rely more heavily on our new videos about encryption and use them to spark a discussion about visual metaphors to talk about complex technical issues. There will be some presentation, framing and discussion both before and after the videos. 
If we get 5 people, we will follow the same process described above for the 15+ people group but with more time for discussion, sharing and individual work with the visual and material techniques. 
### Outcome

This session would be one of many with different audiences to get feedback on new techniques and curricula. It is part of a longer process of applied research, testing, sharing and evaluation of our own methods for teaching and learning about how to change the information practices of activists and HRDs. The session experience and feedback from it, will, cumulatively, shape how we develop and present  it further with other trainers and technical communities. For participants, we hope this will leave them with new techniques to use and apply in their own teaching and education about digital security and privacy.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by MozStacy** [comment]
suggest changing title.  also, would the same person also run the other Tactical Tech proposal?

**Comment by Melechuga** [comment]
Declined
