### ISSUE TITLE
Linking digital badges to a person's biometric identity with Yoti

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#176]
**[ Google Spreadsheet Row Number ]** 133
**[ Facilitator ]** Quirino Zagarese
### Description

We will help participants explore how they could offer digital badge issuers to link a person's digital badge to their biometric identity - so linked to passport and or driving license.
### Agenda

The session will be a technical one for interested parties, showing examples.
### Participants

We could work with any number of participants from 5-50.
### Outcome

Digital badge issuers will have a new way to allow people to prove biometrically that they have earned a badge.

Digital badge owners will be able to prove to employers and interested parties that they have earned a badge linked to their biometrics.

**Comment by mattdigitalme** [comment]
Would it be possible to provide some further information around how the session with run, and whether the focus is on a specific app or a more wider context. :)

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
