### ISSUE TITLE
Learn 3D modeling and print a robot.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#177]
**[ Google Spreadsheet Row Number ]** 150
**[ Facilitator ]** Bram Geenen
### Description

People will learn how to use free 3D modeling software to create 3D printed objects. In the workshop you’ll create the right models that are suitable for 3D printing, and start with printing a small humanoid robot.
### Agenda

During the workshop the participants will learn to use 3D modeling software, and what it takes to make designs that can actually be 3D printed. The idea is to connect this session with the session in which smart robots are being programmed; the participants will design and print new, enhanced and customized parts for the robots (who can turn the robot into Foxy?!!)
After a group introduction the facilitators give each participant individual coaching and feedback.
We will have a number of 3D printers available so that after the workshop we can print parts and start enhancing the robots.
### Participants

At least two facilitators with much experience in workshops are hosting the session. After a group introduction they can give each participant individual coaching and feedback. The software is available online and requires little setup.
### Outcome

After the workshop people will be confident in their ability to use 3D modeling software and 3D printers, opening a new world of possibilities to create tangible objects. They will also have learned about various online platforms such as Thingiverse and Cubehero to share or download models.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by cubicgarden** [comment]
I think this could work in the garage area @ileddigital?

**Comment by ileddigital** [comment]
@cubicgarden this is perfect - on this now and talking to Bram about requirements.

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone, likely most appropriate for Bronze participants

**Comment by bramgeenen** [comment]
My friend who is leading the 3D modeling workshop works at Autodesk. He asks how he can mention Autodesk and Mozilla when talking about the workshop for example on social media. And how can he mention Autodesk during the workshop? Are there any guidelines for this?
