### ISSUE TITLE
We are the Rangers Minecraft hack

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#178]
**[ Google Spreadsheet Row Number ]** 148
**[ Facilitator ]** Peter Jacobs
### Description

Using the ZSL Instant wild app camera trap image feeds, we want people to create inventive ways that we could incorporate the images into We are the rangers – both technical ways and as part of a game storyline
### Agenda

We’ll have access to the Instant wild app data set and the We are the Rangers map code. It would take the format of a brief introduction then perhaps dividing into teams focussing on different elements. A working session
### Participants

With 5 we’d focus on the area best suited to their skills (storylining, concepting or technical) and with more, we’d do a show of hands and divvy the teams/tasks accordingly. 
### Outcome

As we did with the FOC, we’d love to keep the community engaged in the map development, and to get them involved as a future development panel we could bounce ideas off in the future

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
