### ISSUE TITLE
Sustaining an Innovation Hub: Lessons from the iHub

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#179]
**[ Google Spreadsheet Row Number ]** 146
**[ Facilitator ]** Evans Campbell
### Description
1. To provide a comprehensive view of the iHub ecosystem and how balance is maintained
2. To showcase how iHub has evolved towards sustainability
3. To highlight ever-present sustainability challenges iHub faces
4. To openly brainstorm with the audience on how to overcome challenges
### Agenda

Part 1 [Talk]: 30-min on the iHub ecosystem, sustainability approach and challenges to achieving sustainability
Part 2 [Workshop]: A breakout, brainstorming session with attendees sharing their experiences with each other and generating potential solutions
### Participants

5 people: Describe the iHub experience in parts, inviting input at the end of each: 1) ecosystem 2) sustainability 3) challenges. End with joint brainstorm session.
15 people: Talk then breakout (5 people/team), brainstorming session
50 people+: Talk then breakout (10 people/team), brainstorming session.
### Outcome
1. Armed with images of their workshop sticky notes, a sense of belonging knowing "I am not alone in this" and insights gleaned from each other, they will have the information and inspiration needed to return to their hubs and craft new/revamp old sustainability models. 
2. Both early-stage and advanced hubs can learn what to look out for and mitigate against in their current sustainability approaches based on the good/bad experiences shared in the workshop and talk.

**Comment by amirad** [comment]
cc: @amirad

**Comment by soapdog** [comment]
cc @soapdog

**Comment by amirad** [comment]
@thornet @Saallen @Geralbine is this session in a space? Would love to have them at Mozfest but our pathway is super full!

**Comment by Saallen** [comment]
@amirad hey, will I remove your label so from this issue?

**Comment by amirad** [comment]
I guess so. But will give @benrito a headsup

**Comment by Saallen** [comment]
Ok- if you wish to keep it as part of your pathway that is fine- Just trying to get clarity on your postiion for the session :dancer:

**Comment by benrito** [comment]
@amirad @thornet have we heard from Tayo about whether she will absorb this session?

**Comment by thornet** [comment]
@Geralbine https://github.com/Geralbine is coordinating this pathway and
has a plan to link Tayo's session to this one, but as I understand it, they
will be discrete sessions but linke.

On Wed, Oct 14, 2015 at 5:30 PM, Ben Moskowitz notifications@github.com
wrote:

> @amirad https://github.com/amirad @thornet https://github.com/thornet
> have we heard from Tayo about whether she will absorb this session?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/179#issuecomment-148086741
> .

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by Geralbine** [comment]
I don't think Tayo can replace someone from iHub to take over the session but we have space for it in our pathway and would like to include it
