### ISSUE TITLE
 Jane Jacobs on the 'Net: How to Create Economic Opportunity through Online Communities

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#181]
**[ Google Spreadsheet Row Number ]** 151
**[ Facilitator ]** Sarah Judd Welch
### Description

Participants will learn about Jane Jacobs thinking in context of urban planning and then apply this to online community models. Everyone will walk away with a literal map (that they make themselves!) of the infrastructure of an online community that maximizes economic and relationship opportunities. This is an opportune session for community builders, information designers, product managers and strategists.
### Agenda

This session will be a discussion and activities-based workshop. We'll begin by exploring conversationally and visually Jane Jacob's principles of urban planning, and then we'll look at this together in context of today's most prominent community products online. We'll spend the last half of the session mapping out various case studies into architectures of online communities. 
### Participants

Whether 5 or 500 participants, we'll start the session all together in a facilitated group discussion (I'm pro at this kind of group facilitation), and then we'll break into groups of 4-5 people. We'll them come back together as we wrap up to share our learnings. 
### Outcome

I hope that participants will take the lessons learned from this session and apply it internally within their own company's community products and strategies. Further, I hope that this will give them a new appreciation for the value of community in a digital world. I'll likely share a recap of the session via Loyal's newsletter (http://community.is) and any participant is welcome to contribute and/or share their community designs and/or learnings.

**Comment by cubicgarden** [comment]
I'd like to explore this further with a look at not just online communities but also the real world when connected spaces are the norm. The Jane Jacobs analogy is perfect - @cubicgarden

**Comment by cubicgarden** [comment]
Unfortunately this can no longer be run
