### ISSUE TITLE
The Maker Cart: a hands on introduction to Maker Education

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#182]
**[ Google Spreadsheet Row Number ]** 145
**[ Facilitator ]** Carlos  Izsak
### Description

This session will introduce participants to the Maker Cart and the Maker   Movement. The Maker Cart is a mobile cost and space saving mobile unit that   contains the main ingredients to start a Makerspace and Maker Programme. It   consists of a 3d printer, digital cutter, electronics, micro-controllers and   robotics. The Maker Cart has been designed for schools, libraries and youth   centres but can also be use at home!  People will learn about the Maker movement, the tools and machinery   associated and the kind of projects that can be developed with the Maker   Cart.  People will have a chance to make something using some of the tools and   machines in the Maker Cart.
### Agenda

The session is designed as combination of chat & workshop.  The session will start with a brief chat where people will be introduced to the   Maker Movement, Makerspaces and the Maker Cart (5 mins)  The introduction will be followed by allowing people to choose to make   something from 3 different activities:  - 3d Making – from marshmallows and pasta to 3D Printing.  - Animated pop up cards.  - Robotics – Build and program robots.  The length of this session will vary depending on participants, it can be as   short as 30-45mins to as long as it takes to finish a project.  The session will end with an open show & tell, Q&A, feedback and discussion   (10mins)
### Participants

The chat part of the session can accommodate a large number of participants   and could be done independently and separately.  The hands on activities can accommodate up to 18 people, preferably family   groups of 2 to 5, where parents and children can work together to make   something using electronics, 3d printed parts, hacked paper pop ups and   robotics.  The whole talk/workshop can run 2-3 times a day.
### Outcome

People will leave with a better understanding of the Maker Movement and the   tools and machines associated. Participants can encourage the schools,   libraries and youth centres in their respective communities to start a Maker   Education programme with the Maker Cart or similar. Participants will be   given links and references to find further information about kitchen table   making or existing Makerspaces in London that they can join.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
@chadsansing this is a super fun piece and will be a roaming eperience that needs very little support. Great example of an experience as part of a larger learning objective that has low barrier entry for new festival participants

**Comment by chadsansing** [comment]
I agree; we are chock full of sessions, though. Mulling.

**Comment by EPIKhub** [comment]
@Saallen @chadsansing Ill look at it too, was thinking today of having room 205 just of the Crafting area as a "Lab" with tools in it to hack stuff, someplace we could for instance have a soldering irons or 3.

**Comment by chadsansing** [comment]
That would be swell!
