### ISSUE TITLE
Web to help for reviving after Disaster: NepalEarthquake Case Workshop

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#183]
**[ Google Spreadsheet Row Number ]** 147
**[ Facilitator ]** Prakash Neupane
### Description

Experience of rebuilding the trust of world after disaster  as before.
Learn how we have to fight, to spread right information using INTERNET (web) when any disaster occur.
Show how we have to won over media who were creating chaos all over the world.
Create some open idea/platform which is going to useful to the world if any such incident occurred.
Develop the perspective on developing tourism and other possibilities on that place on long run.
### Agenda

I will do one workshop.
The workshop will be designed for the participant to act as the responsible citizen to bring nation out of dark side.
The workshop will use the case of Nepal Earthquake and try to bring out different possible action plan on how web can be useful to rescue, recover and rebuilding.
For the rebuilding process, we will explore how web can use to rebuild TOURISM INDUSTRY. In most of the case, After any disaster on such place, there is high chance to create opportunity of developing tourism possibilities. We will use the case study of www.nepalnow.org
### Participants

This is brainstorming workshop targeting 4-5 people in each group. It will better if we can have at least 5 different group. Where each group have to present at the end, which it self will be the good learning for participant there. 
I am expecting each group have tech guy, marketing genius and good writer to deliver the message.
### Outcome

As the outcome we will have few best ideas/ways to build the platform which is going to useful to the country who might have to go through disaster in future.

**Comment by Saallen** [comment]
cc @ryanpitts cc @Melechuga

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by Geralbine** [comment]
This fits really well to a session we have planned in the GIG pathway on exactly the same topic and speaker from Nepal!

**Comment by thornet** [comment]
cc @Geralbine

**Comment by thornet** [comment]
@Geralbine shall we apply your pathway label here?

**Comment by marcwalsh** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by Saallen** [comment]
cc @marcwalsh-mozfest
