### ISSUE TITLE
Algorithms are ancient and not so scary. Let's write one with crayons. 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#184]
**[ Google Spreadsheet Row Number ]** 140
**[ Facilitator ]** Ryan  Graff
### Description

People often hear the word "algorithm" and think that it entails complicated math or heavy computer programming. At it's core, though, an algorithm is a simple set of rules that are relatively easy to understand. You can write an algorithm for almost anything — making a sandwich, deciding what to make for dinner, doing long division, naming children, and more. This session seeks above all to take away the mystery of a concept that influences our lives each day. It will help people understand how algorithms work and will allow participants to explore the concept of algorithms using simple English and no code.  
### Agenda

We'll start with a quick overview of a one or two sequence algorithm for a common everyday task. Should I eat lunch? for example. Then we'll look at some of the algorithms people likely encounter each day (search results, product recommendations, etc.) and unpack the logic behind them. Then we'll break in to small groups and ask each group to write an algorithm for a specific non-technical scenario. Groups will use paper, markers, stickers, etc. to help facilitate interaction.  
### Participants

With five participants we'll work as a single group. 15: we'll break in to three groups of five. 50: We'll break in to 10 groups of five. 150: I'll panic and then we'll work in 15 groups of 10.
### Outcome

I'd like the participants to walk away more comfortable with technology. It shouldn't be seen as "magic." They should understand how algorithms and computers in general work.

**Comment by ryanpitts** [comment]
Ryan is part of Knight Lab, and already has travel support to attend MozFest.
