### ISSUE TITLE
The Freeformers Experience! 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#185]
**[ Google Spreadsheet Row Number ]** 144
**[ Facilitator ]** Kai Barnes 
### Description

Participants will create their own  app idea inspired by specially designed  API card representatives and  turn it into a working prototype using pen, paper & various free resources on the web. Then using video tools they will learn how to market their idea and then create a webpage to market their app idea.
### Agenda

3 main stations/tables; - 
1. ‘The Prototyping Station’ - intro what APIs are and how they can be used as lego bricks of the internet. Participants then brainstorm various app ideas.Using pen & paper to visualise and draw the app idea, discovering free online tools to turn it into a MVP (minimal viable product). 
2. ‘Video Station’ - demonstration into how you can utilise video tools to best sell your idea or yourself etc. 
3. ‘Coding Station’ 15 laptops available to use if participants don’t have their own. Coding a whole webpage can be difficult for those not familiar so we will have a template already made for participants on “snippet” site where they can easily build & customise their own page. 
### Participants

We have experience in delivery to varying amounts of people in all sorts of different environments. We can confidently deliver the same content with 5-50 participants - all parts of our sessions are hands-on and not reliant on participant numbers, if we do manage to get 50 people at our stations we will divide people into groups to ease facilitation. 
### Outcome

Outcomes: 
Understand the “Lego Bricks”(APIs) of the internet & how they can use free online tools to create a MVP from scratch
Gain an insight into how to use video (youtube) to market your product / yourself.  
Understand the digital landscape and how it's built with 10% of code
Gain confidence in creating and talking about the web.
Pioneer the possibilities and keep innovating

All the tools we’ll use can be found for free online so participants  can continue their learning beyond the festival experience. . 
We will also create a  snippet page with a list of resources and tips for participants  so they can  continue customising their webpage beyond the festival experience.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
