### ISSUE TITLE
 Privacy and Security booths at Makerparties

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#186]
**[ Google Spreadsheet Row Number ]** 139
**[ Facilitator ]** Mayur  Patil
### Description

Understanding privacy is very important. Many adults think that they have lost control over their personal information , which is used by the online companies. This session will help them put their data in control. Mozilla has implemented a number of privacy features in their products and this session will promote those features.

Privacy Security booths can have series of booths:

1) Password Booth (How to make your password strong)
2) Tracking Booth (See how websites track you)
3) Firefox Features Booth (How Firefox can help you)
Eg: Lightbeam,Private Browsing,Forget Button,etc
4) Firefox + DuckDuckGo Booth
(demonstrate why Firefox with DuckDuckGo is a better choice)
5) Firefox for Phones Booth
6) Firefox OS (The only Mobile OS to have DO NOT TRACK feature)
7) Installation Booth (help attendees install privacy products on their personal laptops and phones )
8) Net Neutrality Booth (Spread awareness about)
*Differential pricing
*Surveillance
*Zero platforms
### Agenda

Attendees will gain knowledge about number of Firefox features and privacy related addons

This session will answer the following questions:
1)Importance of data Privacy and Security
2)Why should we care about it?
3)What we should do to protect our data online?
4)How Firefox browser can help protect your data?
5)Why net neutrality is so important and how you can support it

This session will make people aware about the best secure alternative products:
1)Google / Bing / Yahoo       ---->   DuckDuckGo (secure search engine)
2)Whatsapp / WeChat / Line  ---->   Telegram (secure messaging app)
3)Gmail / Yahoo / Rediff        ----->   Proton mail (secure email)
4)Skype / Google hangout     ----->   Firefox hello (secure video call feature)
### Participants

large number of crowd can be easily managed by these booth system. As the crowd will be distributed between multiple booths.

All these topics can also be covered in a single seminar session (3 hour session).
Demo + hands on. All the topics and tools can be demonstrated and we can have handson as well .
### Outcome

1)People may want to be involved with Mozilla and become contributors.
2)People will be more web literate, they will be more aware about the corporate tracking and will take their online privacy seriously.
3)Some people will start using Firefox and other products as a result the download count of these products might increase. 
4)Many future #Makerparties might host such Privacy & Security booths and spread awareness to more people.
5)People will be more knowledge about Internet issues like #Netneutrality and they will have a clear idea why is it important and how they can support it.
6)People might start preferring the alternative softwares like Firefox hello for video call or telegram for messaging.

**Comment by Melechuga** [comment]
Could be incorporated in Privacy Bar.

**Comment by EPIKhub** [comment]
@Melechuga @Saallen could merge this with the boys session on introduction to security in the youthZone; we've also accepted his other session

**Comment by Melechuga** [comment]
@EPIKhub We were thinking of asking him to modify this, but if you're already accepted his other session, we probably won't include this one. Thanks for the update.

**Comment by thornet** [comment]
cc @Melechuga is this session taking place?

**Comment by Melechuga** [comment]
@thornet Not as an independent session. Mayur will be running a stand within Privacy Lab.

**Comment by thornet** [comment]
Thanks! Closing this here so that the info will be carried over to the Privacy Lab sessions.
