### ISSUE TITLE
ReThink – An effective way to stop Cyber bullying

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#187]
**[ Google Spreadsheet Row Number ]** 141
**[ Facilitator ]** Trisha  Prabhu
### Description

My goals for this session would be the following:
1)  Raise awareness about the deadly consequences and harmful effects caused by the silent pandemic of cyberbullying and internet negativity.
2)  Educate participants on the alarming statistics on teen-age suicides, depression, anxiety and low self-esteem, all caused by cyberbullying.
3)  Discuss why most of the parental control or cyberbullying reporting solutions are not effective?
4)  Why does cyberbullying occur more in adolescents than adults?
5)  How does the ReThink software and movement tackle’s cyberbullying proactively?
6)  Why “ReThinking” before posting is the best strategy and how can it be integrated as part of our education systems and technology world.
7)  I strongly believe that, no one has to pay to be safe on the internet. I hope to have the participants carry this message
### Agenda

When I have conducted similar presentations / workshop sessions in the recent past – I like to take the first 15-20 minutes covering the items listed in the goals above. This gives the audience an opportunity to bring all their experiences and ideas to the session.  Once the audience is engaged, I would like to present 5 specific questions/ideas related to the cyberbullying and technology track and have the participants form groups of 3 or 5 to work on those questions/ideas.  Then the participants would have about 10 minutes to present their ideas and feedbacks. The questions were primarily around how they would implement such a system in their schools.  In addition to the software app that I have created, I also run a ReThink Ambassador Program, where teachers may nominate students from their schools to become ReThink Ambassadors.  
### Participants

With an audience size of 15 and above, I would ask the audience to form small groups with individuals from across the rooms, so that individuals from various organizations, teams and areas of interest are able to come together and engage in a lively discussion. This would allow for an innovative, engaging and exciting discussion around the topics and ideas covered in the session. Each group would then have an opportunity to present their ideas and feedback. With a smaller group of participants 5 - 15, it is easier to engage and encourage all the participants in an open forum to provide their innovative ideas and feedback.
### Outcome

The key outcome that I am looking for, would be the engagement of parents, teens, youth and educators to consider “ReThink” mind-set as one of the key lesson plans at their schools to combat Cyberbullying and to promote Internet positivity.  With “ReThink” App available on both Android and iOS, students may be encouraged to download this app on their phones and desktop computers. ReThink promotes responsible digital citizenship on and off of social media.  Just that opportunity for a second chance to reconsider their decision to post a hurtful message could mean someone’s life OR someone’s job.  That is the message I would like for the participants to take-away.

**Comment by Melechuga** [comment]
@MozStacy

**Comment by Zebetus** [comment]
@EPIKhub This could be a good way to link youth to the DC Zone as cyber bulling affect so many of our youths
