### ISSUE TITLE
First steps into coding Smart Objects

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#188]
**[ Google Spreadsheet Row Number ]** 149
**[ Facilitator ]** Bram Geenen
### Description

People of all ages, from laymen to skilled coders will get started with programming Smart Objects using 3D printed robots. Beginners can learn by programming the robots through a visual interface. More advanced coders can directly write code to control the robot and let it interact with the world.
As the internet is moving into our physical objects, getting literate and confident with (re)programming our tangible environment becomes an essential skill, and these little open source robots will help you make the first steps.
### Agenda

In this workshop we provide robots that can be programmed. There will be a facilitator teaching beginners to use the GUI, and a facilitator to help more advanced coders program the robots directly. The participants will need to collaborate, because the goal of the workshop is that at the end of Mozfest2015 we’ll make the robots perform live on stage and record video message about Internet Of Things literacy.
### Participants

We have 10 programmable robots available, which can be shared between people to upload and test their code, enabling us to facilitate a large number of people.
### Outcome

The outcome during the festival is a collaboratively created funny video message to spread knowledge about Internet Of Things Literacy. 
After the festival participants can continue working on the robots and even build a robot themselves because it is an open source hardware project. All knowledge and files to 3D print and make a robot are available online, as is the code. People can write code locally as well and share it with others who have a robot to see how it performs.

**Comment by Zebetus** [comment]
@EPIKhub Maybe look at incoorporating this with the sumo bot making???

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
