### ISSUE TITLE
Community Co-Creation Pathways

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#189]
**Google Spreadsheet Row Number**

162

**Facilitator**

Robert Friedman

**Description**

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by samueledyson** [comment]
Hi @mattdigitalme! 
I'm co-wrangling the MLN Space with @LindseyFrost.  I work with Robert, the Mozilla staff members who submitted this proposal (robert@mozillafoundation.org). He will be at MozFest. It looks like you want to include this in your independent pathway which is great.  If it would be helpful to also have it listed in the MLN Space, let me and @LindseyFrost know.  
Matt, I suggest you contact Robert to confirm whether he needs other people to travel with him to co-facilitate this session, so we know if we would need to provide travel support.
@chadsansing, if this does get cross-listed with us in the MLN space, is this something you would want listed in your pathway?  No pressure if it doesn't fit.

**Comment by mattdigitalme** [comment]
@samueledyson I'll drop Robert an email and find out about extra facilitators, happy for it to be in the MLN space and we signpost people off to it from our pathway as it is an opportunity to explore badges (which is at the heart of our pathway)

**Comment by omnignorant** [comment]
Just tagging myself (@omnignorant) because @samueledyson pointed me here and I want to make sure I can follow.

**Comment by mattdigitalme** [comment]
Hey @samueledyson spoke to @Saallen on a 1:1 yesterday regarding this - we unfortunately don't have any travel stipends left to offer, so if there is additional travel needs, we wouldn't be help to help here :( Sorry! Might be worth dropping @Saallen a line to see if this can be picked up :)

Thanks

Matt
