### ISSUE TITLE
Lessons we've learned

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#19]
- faciliators name
- A presentation of the research we've done in India and Bangladesh as well as MozReps and Community members presenting the lessons they've learned while being on various task forces.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

Is this a real session @Saallen?

**Comment by Saallen** [comment]
@Melechuga this was submitted as part of Access in the Global South pathway outline with sessions by @MozStacy

**Comment by Melechuga** [comment]
Placeholder
