### ISSUE TITLE
Adopt a School !

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#190]
**[ Google Spreadsheet Row Number ]** 155
**[ Facilitator ]** Bala Subramaniyan P
### Description

I believes that the problem is grave,But solutions exist. A good education is a key element of future success not only for the individual but also the larger community and the country, the World..Etc. Adopt a School, Focuses on empowering children to achieve their right to education.Even many countries are developed, But education is a beset for many serious problems( Country development,Literacy rate,etc..).Adopt a School hopes to improve its innovative teaching methods, directly reach a greater number of children, and continue campaigning for institutional change across the global.
### Agenda

Children those, Who don't go to schools in worldwide mostly don’t have access to hands-on knowledge to solve practical problems. They often lack entrepreneurial guidance or meta skills that’ll prepare them for the real world.Our strategy is to demonstrate that setting these goals and designing teaching and delivery methods to achieve these goals can directly enhance the learning outcomes of children. 
### Participants

Having different sort of activities in my session. Applicable to each and every participants. Making them, To take part is my aim. Will move with sessions followed by school teaching skill activities, At last "Adopting a school video trailer". 
### Outcome

With different outcomes, Adopt-a-School includes a well-designed pedagogy, measures to lower dropout rates, digital literacy, originating from specific needs in education and vocational skilling.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
