### ISSUE TITLE
Building games for Firefox OS

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#191]
**[ Google Spreadsheet Row Number ]** 156
**[ Facilitator ]** Andrzej Mazur
### Description

People will learn how to build HTML5 games for the Firefox OS platform and how to submit them to the Firefox Marketplace.
### Agenda

It would be a workshop focusing on hands-on experience testing the game using the simulator, pushing the game to the device, remote debugging, and then submitting it to the Marketplace.
### Participants

Workshop approach can scale for more participants by gathering them in a few smaller groups, so they can help each other.
### Outcome

People will know how the HTML5 games work, why Firefox OS is the perfect platform for web gaming and how to prepare and submit your own game for the Firefox Marketplace, so they can grow the number of games available for that platform.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
