### ISSUE TITLE
To space: Leading the next generation of coders and scientists into space through machine learning.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#192]
**[ Google Spreadsheet Row Number ]** 158
**[ Facilitator ]** Sharon Middleton
### Description

Allow people to learn how Machine Learning in space travel can inspire children to develop a passion for technology, science and coding.

This year a groundbreaking STEAM (Science, Technology, Engineering, Arts & Maths) project for children follows the launch of real life British Astronaut, Tim Peake, to the International Space Station.

BUT the project needs MozFest – 

It already has 
-   a fictional story world
-   a 3D printed character
-   a real life astronaut
-   The universe!
-   Open Badges
-   The Met Office, the European Space Agency, The Science Museum, Young Rewired State, Royal Observatory Greenwich

BUT we want to do more next year. We want to see if we can include Machine Learning and get EVEN MORE children and young people inspired by science, coding and technology.
### Agenda

Jon Spooner is the Director of Human Space Flight at Unlimited Space Agency. ‘Mini Jon’ is a 3D printed scale model of Jon that will (hopefully) be hacking his way in to space to join Tim Peake as part of his mission from Earth to the ISS.

Jon Spooner and Tim Peake will be in the session through an introductory film about space and the project.

Mini Jon will be there in person (3D printed mini person).

Following the film, the workshop will crowd source images of MozFest. Some images will have Mini Jon on location at MozFest.

We will then feed use machine learning to determine which images contain Mini Jon, and explore alternative ways Machine Learning can be used to determine information.

The workshop will finish with a sharing of ideas around how machine learning can be integrated in to education projects to inspire coding, hacking, tech exploration.
### Participants

5 participants – as one group - watch, capture, feed, explore, share.
15 participants – two groups, each take a turn with mini Jon and rotate around and then come together at the end to share.
50 participants – four groups, each with a different mini figure and image creation brief – a small game will determine which group has mini Jon.
### Outcome

We and participants will leave with a greater, shared understanding and awareness of Machine Learning and how this can provide a playful and interesting element of social learning projects with children and young people. 

The chance to follow this year’s project, the launch of Tim Peake and the potential space mission of Mini Jon.

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by EPIKhub** [comment]
@mattdigitalme @acabunoc I'm in conversation with the Pi foundation on this topic of Tim Peake, Astro Pi's and a teaching kit to wrap it all into one. We have the Pi foundation community coming setting up shop in the youthZone about 40 Pi's in all plus now the Astro Pi. I'm wondering if I should bring this session into the youthZone as we are essentially covering this already, they just don't have the kit that is heading out to space in novemeber, the Pi?

**Comment by EPIKhub** [comment]
@mattdigitalme we have the Astro Pi session running at the youthZone also with a Tim Peake theme of space as that version of the Pi is going into space in November

**Comment by mattdigitalme** [comment]
cc @marcwalsh @Saallen
