### ISSUE TITLE
Ethical drone hacking

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#193]
**[ Google Spreadsheet Row Number ]** 161
**[ Facilitator ]** Danny Bluestone
### Description

The Cyber-Duck IoT team will teach participants when and how to use drones. Aiming to boost users' experience, we'll brainstorm a variety of potential use cases: from the news desk, to flying your latest purchases right to your doorstep. Going beyond the native, out of the box software, we'll show you how to use open source APIs and JavaScript to develop automated, tailored functionality, which suits each possibility.  We'll also share how users must control drones responsibly, highlighting the legal and media risks and limitations. 
### Agenda

The session will be a workshop and will split into two parts:

SESSION 01 - One hour (creative brainstorming)
- Introduction to different type of drones: what type of affordable drones are there? What are the advantages of each one? What's been 'done' already?
- Bringing the future closer: what's the motivation (and possible use cases) for drones? We'll brainstorm and creatively sketch ideas together. 
- Hitting the limits: building awareness of the limitations and risks for using drones, including legal, journalistic and media risks.
- Ensuring accessibility: brainstorming about different technologies, and ensuring access. 

SESSION 02  - Two hours (development and engineering)
- Introducing the different types of drones that can be controlled, using open source libraries.
- Controlling drones using libraries.
- Examples of how smartwatches can control drones. 
- How IoT can boost interaction with drones, including notifications and controls.
### Participants

As the workshop is based on creative ideation, brainstorming and outlining potential development together, the session can flex according to the size of the group. We will provide enough technology and mentors for up to 50 people. 
### Outcome

The workshop will tackle this upcoming, controversial yet exciting technology, revealing the opportunities for participants. We will teach participants the best theoretical concepts and use cases for drones, and how to ensure a good user experience by delving into human centred design models. This will be followed by technical tuition. We will demonstrate how to go beyond the native software, and use open source APIs to automate and tailor technological choices to the specific use case, brainstormed in the previous session. Overall, both sessions will give participants a great overview of the potential of drones: from ideation and theory, to build and release 'into the wild'!

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
