### ISSUE TITLE
Stakeholder Mapping and Power Analysis

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#194]
**[ Google Spreadsheet Row Number ]** 166
**[ Facilitator ]** Dirk Slater
### Description

In this session you will get an opportunity to focus on the people who are impacted or involved with your advocacy or activism campaign. Through several hands-on exercises, you will get an opportunity to map your stakeholders and learn how get them more deeply involved and engaged. You will also work with a power analysis technique that will allow you to create tactics and strategies that can change the minds of those in charge. This session will also give you insights on messaging and building power for those that don't have it.
### Agenda
1. We will start with the spectrogram exercise, getting participants to react to controversial statements by moving along a straightline towards agree or disagree. 2. We will have a quick discussion about what a campaign for change actually looks like and discuss realistic campaign goals. 3. We will then identify stakeholders in participant's campaigns. 4. We will use the spectrogram to see if stakeholders are allies, neutral parties or opponents. 5. We will discuss tactics appropriate for allies, neutral parties or opponents. 6. We will then identify who has power to make the change the campaign is seeking and analyse who has influence on them. 7. We will end with identifying which stakeholders don't have power but should and how to employ campaign tactics to address that.
### Participants

The activities can scale easy from 3 participants to 50.
### Outcome

We will continue to build kick-ass campaigns and change the world.

**Comment by shaghdoosti** [comment]
I love this concept - I think the title could be changed to be more inclusive, I don't think everyone knows what power mapping is.

**Comment by Melechuga** [comment]
Decided to go with the other session.
