### ISSUE TITLE
Ethical Brand Communities: How do we keep them good?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#195]
**[ Google Spreadsheet Row Number ]** 152
**[ Facilitator ]** Sarah Judd Welch
### Description

This session will be a collective, action-oriented brainstorm on how to keep online communities owned by the people rather than the brands that sponsor them. Community is an increasingly hot topic and must-have digital strategy for today's most competitive brands. Though, this is sometimes without meaning, and sometimes, with less than good intentions. How can we educate brands on their obligations to the communities that they enable and hold them accountable?
### Agenda

I'll start out by framing the challenge through case studies and statistics, and then we'll all share our observations on the problem. As a group, we'll break down each element of the situation. Then, we'll break into groups of 4-5 people, each taking on an element of the challenge. Each group will create an action plan to tackle their element of the challenge. We'll then come back together as a group to share our action plans and create a holistic action plan collectively. We'll then decide as a group how to best implement the action - whether as individuals or an industry.
### Participants

Regardless of numbers, this session with operate with strong facilitation and small groups. The larger the group, the more formal the facilitation to ensure that we stay focused and on track. 
### Outcome

The ideal outcome would be actually implementing the plans that we create. I'll take lead on organizing whatever way we collectively decide in the session to make that happen.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
