### ISSUE TITLE
Equal Rating Panel Discussion + Q&A

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#196]
**[ Google Spreadsheet Row Number ]** 160
**[ Facilitator ]** Jochai Ben-Avie
### Description

Participants will hear from external and internal policy experts about their thinking and vision around equal rating, and they'll have the opportunity to pose questions.
### Agenda

This session will be in panel format, with about 5 speakers and a moderator curating the discussion. In a scheduled 60min, perhaps each panelist will have 5 minutes to introduce and discuss his/her view on equal rating in a given context, followed by q&a from the audience -- including questions pre-organized by the moderator.
### Participants

Since it's a panel, with fewer participants the more intimate the discussion, and with a larger audience it will be more of a back-and-forth. But with a salient topic and speakers like Mitchell, Jochai, and higher-ups of our coalition partner organizations, we anticipate a high level of interest.
### Outcome

Participants will walk away with a deeper understanding of Mozilla's stance on equal rating, with coalition partners' views on the topic, and with ideas of actions they can take in their local contexts.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Melechuga** [comment]
During lunch hour.

**Comment by Melechuga** [comment]
Not enough panellists.
