### ISSUE TITLE
Practical tools and information about reuse and ICT for development

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#197]
**[ Google Spreadsheet Row Number ]** 154
**[ Facilitator ]** Rajeh Shaikh
### Description

The type and subject of session would be both on an informational and practical level. We would suggest the following title: “Practical tools and information about reuse and ICT for development”. We would like to learn people more about ICT for development and how practical ICT solutions can tackle poverty.
### Agenda

This would be an interactive session with both an interactive and a theoretical level. We could divide the session in four sections:
1.      Theoretical section about impact of reuse on the environment – interactive
   1.       Practical section about reusing and refurbishing computers – showing examples (laptop etc.)
   2.       Theoretical section about impact of reuse on a social level – interactive
   3.       Interactive role play with 4 groups: agriculture, education, post-crisis and health
      Example of question asked in the role play:
      You are a doctor in Northern Kenya, you manage a clinic miles away from the nearest main town.  You have a scanner, a computer and internet connection. 
      a)  One of your patients has a sprain that you cannot identify; how can you overcome this, get other expert advice and learn how to diagnose and treat this patient:
      …with ICT?
      …without ICT?
### Participants

For the theoretical section of the session, it would not be a problem to accommodate big numbers of participants. And for the practical and interactive section, we can easily be creative and divide groups into subgroups for the role play, i.e. subgroups of farmers in the group of agriculture, subgroups of teachers and students in the group of education group, nurses, patients and doctors for the health group and development workers, government and refugees for the post-crisis group.
### Outcome

Participants will be more conscious about e-waste and recycling, they will have more knowledge about tools of reuse and know how to be part of the circular economy.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
