### ISSUE TITLE
Building Grassroots Communications Campaigns

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#198]
**[ Google Spreadsheet Row Number ]** 165
**[ Facilitator ]** Paul Johnson
### Description

Participants will help build a "playbook" for promoting products, programs, campaigns across media, social, blogs and via events. Create a megaphone for your projects without formal training in marketing and communications and with little to no budget. 
### Agenda

Format is a collaborative, interactive workshop. 

As a group we'll pick a "thing" we want to amplify/promote (ex. Clubs). Bonus points, if that "thing" was something new being created at Mozfest itself. 

We'll run that through a framework to co-design a plan. 

And then, we'll build and actual plan and, ideally, deploy some of the initial comms tactics in real-time.

At the end of Mozfest we'll report back on how the mini-campaign worked. 
### Participants

If participation would was limited we would work as a single group. With a larger group we would break off into smaller teams, each of whom would create their own mini-playbook and have a demo at the end to share ideas. 
### Outcome

Community members and organizations will walk away with  a basic toolkit that they can use to amplify and promote future projects. Ideally, the ultimate outcome is more reach, more impact and more participation in future grassroots campaigns.

**Comment by secretrobotron** [comment]
cc @secretrobotron re #51

**Comment by Melechuga** [comment]
Combining with "Campaign Hack -- Codesigning a Framework for Activism" (https://github.com/mozilla/mozfest-program/issues/271). Paul will help Sue Smith facilitate.
