### ISSUE TITLE
Questions to ask frequently when collecting data in marginalised and 'at risk' communities

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#199]
**[ Google Spreadsheet Row Number ]** 168
**[ Facilitator ]** Dirk Slater
### Description

In this session we will look at the ethics, dilemmas and responsibilities of collecting data in marginalised communities and with individuals 'at risk' of human rights abuses.  Participants will get an understanding of how data collection can undermine other advocacy efforts to build power for those who are marginalised and potentially put vulnerable populations at greater risk of human rights violations. We will formulate questions to ask frequently QAFS, as opposed to FAQs, when developing and implementing your data project plan. 
### Agenda

This will be a workshop that will build on the experiences of the participants to create a list of questions.  We will start with small group discussions that will get participants to reflect on their own experiences and then come together in a large group to create a list of questions
### Participants

If there are 5 or less we will only have one small group discussion as opposed to several.
### Outcome

It would be great to have a communications mechanism that would allow us to continue to share lessons learned.

**Comment by cubicgarden** [comment]
Sorry @Saallen and @marcwalsh  were removing this one from the global village
