### ISSUE TITLE
Library Freedom Project: Practical privacy tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#200]
**[ Google Spreadsheet Row Number ]** 167
**[ Facilitator ]** Kevin Sanders
### Description

The session introduces participants to some of the tools that they can use to protect their privacy online. In turn, this exposure to and training in the deployment of these tools will give citizens the skills they need, as the United Nations rapporteur for free expressions has stated, to “exercise the right that you have under human rights law.”

This session is offered by The Library Freedom Project, an organisation that is training librarians about digital security for their library communities. We present sessions to meet local needs, along with offering technical support for librarians who have decided to test out some of our suggested technologies.
### Agenda

This workshop will provide training on the use of privacy-protective tools, including:

-Creating strong passphrases with the Diceware word list;
-Encrypted passphrases with KeePassX;
-Tor browser and HTTPS: what they each do and how they work together;
-Encrypted text messaging with TextSecure/Signal;
-Encrypted instant messaging with Pidgin or Adium
### Participants

Kevin's experience in delivering information skills sessions to a diverse range of university students has developed his ability to respond to dynamic circumstances.

The session is malleable, and so can accommodate smaller or larger numbers, becoming more detailed in smaller groups and broader in larger sessions.
### Outcome

After the session, participants will feel confident in the use of some online privacy tools. They will also understand the reasons why the use of these tools is important for them, and that changes to online behaviour are important for their online safety in the future.

Anyone at MozFest 2015 is encouraged to attend, particularly those that facilitate access to and use of the internet, librarians, and other such information workers.

**Comment by Melechuga** [comment]
Could be incorporated into Privacy Bar.
