### ISSUE TITLE
Data Literacy and Social Change

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#201]
**[ Google Spreadsheet Row Number ]** 171
**[ Facilitator ]** Dirk  Slater
### Description

This session will give participants an opportunity to share learnings about 'Data Literacy,' how is it important, appropriate and relevant in social change work. This will build upon a recent research project undertaken by School of Data and FabRiders to better understand how to effectively use data in social change/justice campaigns. We will examine different methodologies for collecting and using data in advocacy and activism campaigns, with an emphasis on engaging and mobilising stakeholders. We will also review resources that participants have found helpful in their data literacy work.
### Agenda

This will be a workshop where participants will break into small groups to discuss their own experiences and then convene into a large group to create best practices.  We will also have a 'farmers market' of resources - where participants will populate stalls organised by topics with resources they have found useful.
### Participants

The amount of small groups will be determined by the number of participants
### Outcome

There will be a 'data literacy' and social change blog that we will ask participants to contribute their experiences to.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
