### ISSUE TITLE
Capturing a visual thought

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#202]
**[ Google Spreadsheet Row Number ]** 153
**[ Facilitator ]** Bryan Mathers
### Description

A picture says a thousand words - and it’s never been easier to create images that can have real impact.

If you’d asked me a couple of years ago - “Can you draw?” I’d have said “Not really - I’m a programmer”. However, creating visual thoughts is now central to everything I do.

This session will aim to illustrate how a visual thought can be captured, created and shared and if this wasn’t just a lowly text form, I’d put a few examples in to show what I mean.

Unfortunately, visual thoughts are limited by your ability to think…
### Agenda

I’ll give some context to our work at wapisasa and the impact that visual thoughts have had.

I’ll unpack the process I go through: Listen - Capture - Visualise - Create - Edit - Share and the devices and apps that I use.

I’ll set a visual thought “challenge” to those wanting to give it a shot. We'll focus on some of the visual metaphors used by the keynote speakers. Ideally, participants will have an iPad with the “paper by 53” app on it, and a stylus, although pencil and paper is also a great starting point.
### Participants

For the challenge session, I’ll be asking participants to get into groups of two’s or three’s, and some of the wapisasa crew will also be on hand to help out.
### Outcome

Participants visual thoughts are used in their everyday work, to engage and inspire others.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
cc @cubicgarden
