### ISSUE TITLE
Super Fun Creative Ninja Training

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#203]
**[ Google Spreadsheet Row Number ]** 164
**[ Facilitator ]** Cassie McDaniel
### Description

Harnessing creativity is a skill. Learn how to do this! Experience some lightweight activities that will lighten the mood and get a team having fun together. You’ll learn about the way you (and others in this session) operate in stressful environments – an insight you will be able to take back to your everyday work. This is a great session for teams to take together, for leaders who want to learn some creative activities to do with their teams, for designers and artists who need to reclaim their juju, and for that button-up type who wants to figure out how to loosen up. If you don’t know anyone at Mozfest: come here – you’ll leave with friends!
### Agenda

This is a workshop session that will be organized in six micro-activities.

• Posturing – learn how your physical posture can influence your success. – 10 min
• What’s in a name – find out how other participants got their names – 5 min
• Group rock paper scissors – a room-wide game to discover the champ – 5 min
• 30 second portraits – low pressure way to get started drawing – 5 min
• 30 circles – Put 30 ideas on paper. How do you self-edit yourself? – 5 min
• Ball sounds – a challenging room-wide improv game – 5 min
• Group discussion – What surprised you? What did you learn about yourself? What did you learn about others? How do you think you can apply what you learned in your everyday work? – 20 min
### Participants

These activities will work in any-sized groups. The discussion can be broken into small groups if necessary.

The activities are set up for participants to work independently, but they encourage sharing and participation, e.g., the 30 Second Portrait requires a participant to draw a picture of their neighbor, that they will likely share the result and laugh. The Group Rock Paper Scissors requires participants to play Rock Paper Scissors with their neighbor until we whittle the room down into one final competition. The 30 Circles Activity asks people to draw as many ideas as they can inside 30 circles – people will likely share their results with others.

The challenge with a large group will be in getting the room to switch activities – so we can employ the clap and listen approach, or find a bull-horn! If we overrun time-wise on the activities the final discussion can be truncated.
### Outcome

This session is mostly about loosening up, having fun and getting people (perhaps unexpected people from unexpected places) to forge connections and embrace creative exercise as a means of facilitation and self-exploration. I imagine people from all walks of life could benefit from more of this in their lives!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
