### ISSUE TITLE
Fundraising on the open Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#204]
**[ Google Spreadsheet Row Number ]** 170
**[ Facilitator ]** Erika Drushka
### Description

Fundraising 'open' is hard. Organizations' donor lists are guarded like gold, and proprietary database technologies make it difficult to share tools. Increasing fundraising capacity by giving volunteer developers backend access to through open source platforms like Github can be a frightening prospect for small and large organizations alike. How can social impact non-profits learn to work more open to increase their revenue and reach? 

This session will be an opportunity to share experiences and brainstorm solutions to the challenges of applying the "work open" ethos to fundraising.
### Agenda

[Placeholder] Case studies followed by discussion. Facilitators can discuss their experiences (Mozilla, MSF) and the nuances of working open, while respecting people's private information.
### Participants

5 participants would allow everyone to share and ask questions. If 15-50 participants attend, we could present case studies, then break into discussion groups according to topics of most interest.
### Outcome

[Placeholder] Specific tips and recommendations for working open in philanthropy, co-created with the group and shared in a blog on fundraising.mozilla.org Perhaps this could be the start of a white paper?

**Comment by edrushka** [comment]
===> I think this session will probably be cancelled <=====

**Comment by Melechuga** [comment]
@edrushka Why?

**Comment by edrushka** [comment]
@Melechuga Rebecca was going to co-lead with me and AFAIK she will no longer be attending. I don't have capacity to lead 2 sessions on my own.

**Comment by Melechuga** [comment]
@edrushka Thanks for the update; taking off our list and closing now.
