### ISSUE TITLE
No Good Number Goes Unpunished

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#205]
**[ Google Spreadsheet Row Number ]** 159
**[ Facilitator ]** Anne Li
### Description

Data simultaneously reveals and conceals. And no matter how diligent journalists are, we can never be certain that our numbers are truly bullet proof - and some stories are by nature unethical if conveyed solely through data. We will discuss the various ways a journalist can unintentionally misrepresent a story through data, and brainstorm questions to ask ourselves before determining whether a story can be ethically represented through data. With these questions we will create a Hippocratic Oath for data journalists to adhere by when working with data. This session is inspired by the book "How to Lie with Statistics."  
### Agenda

The goal of our session is to create a Hippocratic Oath for data journalists to help them create as ethical of a story as possible. I will collect various examples of "bad" data stories from this past year, and ask participants to identify what makes these stories unintentionally (or intentionally) unethical. We will show what was wrong with the data or the visualization through theoretical discussions or technical drawings. At the end of the discussion, we'll brainstorm questions to ask ourselves before beginning or publishing a data story in order to ensure that the end result is up to our ethical standards.
### Participants

A small group (5-15) will function as a fireside chat, while a larger group will require splitting up into discussion groups  that will each discuss a different "bad" data story. We will then come together as a large group to create the Hippocratic Oath. 
### Outcome

I want participants to leave with a better understanding of the various ways a data story can unintentionally be unethical or a misrepresentation of reality. While the takeaway should be that there is no way to fully bulletproof a data story, participants and non-participants should feel empowered with the Hippocratic Oath that can help them stay vigilant against unintentional pitfalls in data storytelling.

**Comment by ryanpitts** [comment]
Anne is part of Knight Lab, and already has travel support to attend MozFest.

**Comment by ryanpitts** [comment]
Journalism is accepting this session.
