### ISSUE TITLE
What the heck are 'Jobs in tech'?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#206]
### Google Spreadsheet Row Number

169
### Facilitator

name: Erika Drushka
twitter: @ErikaDrush
organization: Mozilla Foundation
### Description

There's a lot of talk about 'jobs in tech' but what does that actually _mean_ -- especially for those of us that don't code (yet!) In this interactive, non-intimidating session you'll create a "dream job" based on what you're good at and what you like to do. You'll also hear a diverse panel share how they parlayed their skills and passions into a dynamic -- and often self-defined -- role in the tech industry. A great session for MozFest newbies, youth, and anyone considering transitioning their careers into this exciting field. Everyone is welcome!

**Comment by thornet** [comment]
cc @msaunby who said he'll bring cake. ^-^

**Comment by EPIKhub** [comment]
Helping people understand tech roles is a really good idea, I recently was told the person creating code for a bank was not an artist by any stretch of the imagination but a front end web dev was. There is a huge misunderstanding as what tech people actually do. To me the software engineer at the bank is an artist, that stuff is complex, deep and the finished product is unique to the person who worked on that project, in contrast front end devs, their stuff might not be that unique... but we need both and all kinds at all levels of skill :)

**Comment by cubicgarden** [comment]
Interested in this one for our space @cubicgarden

**Comment by EPIKhub** [comment]
@jvallera @simonaramkisson who is accepting this session? I milestoned it 14 days ago for the youthZone

**Comment by jvallera** [comment]
@EPIKhub @simonaramkisson we are not accepting this submission for the Diverse Leaders pathway.

**Comment by edrushka** [comment]
For scheduling, if I'd love to request this take place as early as possible (i.e. Saturday), or even Friday evening (?!) as a quieter alternative to the Science Fair. I'm hoping this session facilitates some informal mentorships for first-time youth attendees, so the earlier the better.

**Comment by edrushka** [comment]
My list of  :cherries: :two_hearts: INCREDIBLE :two_hearts: :cherries: panelists (so far):
- @simonaramkisson 
- @LauraReynal 
- @sabrinang 
- @shaghdoosti 
- Leah
- An-Me
- plus I plan to invite some non-moz folk

**Comment by simonaramkisson** [comment]
@edrushka Definitely excited participate! Let me know if you need any support

**Comment by EPIKhub** [comment]
I was planning to put it on on Saturday 11am, Sarah and I have been talking
about it and it would be great as a lead into the wider festival so once
they hear about the jobs they can go meet people in one that interest them,
I'm also linking it to SUMO with tech support as one of  the follow on
session from yours, amongst others

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by cubicgarden** [comment]
Will make sure the dyslexia session doesn't clash then... Sounds good let me

sent from my phone. sorry in advance for the auto correct madness and
general typos

**Comment by edrushka** [comment]
Draft agenda ==> comments welcome!
- Welcome (ErikaD)   3 mins 
- How I got my job in tech (Panelists, moderated by ErikaD)  15 mins 
- Break into small groups with panelists   3 mins 
- Intros in small groups ('what do you like to do?' 'what are you good at?')  10 mins 
- Attendees design dream jobs  10 mins 
- Attendees share job within their small groups  7 mins 
- Report back to larger group (Panelists to lead this for efficiency. All panelists encouraged to recommend other MozFest sessions according to attendees' skills & interests). 12 mins 

Total time: 60 mins

**Comment by EPIKhub** [comment]
Looks good to me, how are you planning to recruit your panelists?

On Thursday, October 22, 2015, Erika Drushka notifications@github.com
wrote:

> Draft agenda ==> comments welcome!
> - Welcome (ErikaD) 3 mins
> - How I got my job in tech (Panelists, moderated by ErikaD) 15 mins
> - Break into small groups with panelists 3 mins
> - Intros in small groups ('what do you like to do?' 'what are you good
>   at?') 10 mins
> - Attendees design dream jobs 10 mins
> - Attendees share job within their small groups 7 mins
> - Report back to larger group (Panelists to lead this for efficiency.
>   All panelists encouraged to recommend other MozFest sessions according to
>   attendees' skills & interests). 12 mins
> 
> Total time: 60 mins
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/206#issuecomment-150378284
> .

## 

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by EPIKhub** [comment]
Tom Farrow could be one of your panelist? He is 15, 16 on the 8 Nov and has
just taken the job of UK Community manager for Mozilla, he has been volunteering 
with Mozilla since he was 9 years old, his specialty is Cyber security

On Thursday, October 22, 2015, Erika Drushka notifications@github.com
wrote:

> Draft agenda ==> comments welcome!
> - Welcome (ErikaD) 3 mins
> - How I got my job in tech (Panelists, moderated by ErikaD) 15 mins
> - Break into small groups with panelists 3 mins
> - Intros in small groups ('what do you like to do?' 'what are you good
>   at?') 10 mins
> - Attendees design dream jobs 10 mins
> - Attendees share job within their small groups 7 mins
> - Report back to larger group (Panelists to lead this for efficiency.
>   All panelists encouraged to recommend other MozFest sessions according to
>   attendees' skills & interests). 12 mins
> 
> Total time: 60 mins
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/206#issuecomment-150378284
> .

## 

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by edrushka** [comment]
Great suggestion @EPIKhub. You can see some of the other panelists I've approached in the comments above.

**Comment by EPIKhub** [comment]
@edrushka how about @SpikeUK, An awesome engineer who is also our MozFest volunteer, volunteer co-ordinator & grandpa to us all, not to mention a fantastic person. A range of roles and backgrounds as panalist might be useful for balance :)? and volunteering is a good way to dip your foot in the water to see if you like it plus you do so in a social supportive sand box....

**Comment by SpikeUK** [comment]
@EPIKhub shssssssh (blush)

**Comment by edrushka** [comment]
Now that is a fantastic idea! @SpikeUK what do you think? I'd be thrilled if you could join. Hoping this will be in the first session slot on Saturday.

**Comment by SpikeUK** [comment]
I would be delighted and honoured @edrushka - thank you

**Comment by EPIKhub** [comment]
@edrushka how about @MozStacy expert on cyber security, mum and lover of games :)

**Comment by msaunby** [comment]
I'm going to give a shout out to this session in my keynote on Saturday morning - 'cos it will be the first session I'll be joining.   Yes, I'll try to remember cake @thornet

**Comment by edrushka** [comment]
Whaaaat? We get a mainstage shoutout?!  That's fantastic! :dancer:

This would be a great session to call out for newbies and/or people that have no idea where they fit into the festival madness for the first session. No special skills or knowledge required to attend (i.e this won't be the "wrong" place for anyone).
