### ISSUE TITLE
BadgeLAB Leeds: Testing open badges for arts engagement

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#207]
**Google Spreadsheet Row Number**

157

**Facilitator**

Alison Smith

**Description**

DigitalME are pioneers in Open Badge design, implementation and consultation. Our recent research project BadgeLAB Leeds explored the use of Open Badges for arts engagement, at artist led sessions in schools, programmes for NEET young people and young people with learning difficulties, and at large scale public events. 

We will discuss findings from the report by Sheffield Hallam University, the key themes and how they are shaping our approach to Open Badge design for arts and city wide learning. The session will be open and informal - we aim to unearth experiences, compare approaches and share tools and resources with participants.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by mattdigitalme** [comment]
cc @mattdigitalme
