### ISSUE TITLE
Internet and Web Privacy- Web Literacy 101 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#208]
**[ Google Spreadsheet Row Number ]** 163
**[ Facilitator ]** Asma  Islam
### Description

The session is precisely about connecting to the web, keeping self-privacy and get to know how people are using it in daily life. The understanding of inter-relation among HTTP, Browser and web documents will make the attendee to capture what the content in the INTERNET is and why it is for. From this attendee will be able to categorize the private and safety information that needs to hide from public access. The session will include a hands-on network topology build-up for mail-server(using network-simulator) and help them learn about the data packet passing more visually.  A little understanding with visual talk on data filtering will be added to let them understand about behavioral data. There will also be a little talk on net neutrality and user's right to get the web information on an equal platform. From Internet activity to Net Neutrality will be the flow of awareness talk. 
### Agenda

The Session will be like a fireside chat or a group interaction where attendee will talk about what they know and what they think about the topics or anything related to their experience of learning, teaching web and exchanging information over the INTERNET. The agendas will be-
-Have a crosstalk networking among the attendee for better interaction during the session and feel comfortable with each other.
-Asking the attendee and also the organizer one by one what they think about INTERNET and why it is for. This will help to find the starting point to making them understand session aims and achieve maximum output through the facts they will learn. 
-Response with each and every interference in the topic and while switching to the next topic specially from how the staff works to the hands-on network simulation
-Conclude everything with sticky notes about reviews, small idea to reshape our network.  
### Participants

As there can be varying session attendee the formate will be tow based on the number. This might ease the way for better output.
-Attendee < 5: ni this case we'll have the session in more like an informal chat and pull down the overall session agenda. This will be like peer-to-peer session for a go through talk over INTERNET connectivity to the data communication and activity and the user's right more like privacy staffs.
-Attendee<15 and >5- Will make a round-table open conversation. Here will be talk, fun and mutual interaction, perfect for the proposed session. Talk and their experience sharing will be additive to hold a fruitful interaction. For almost 15 people there will be two groups for the hands-on simulation show-up.
- Attendee<50 & >15 if in case the session will more like a formal teach-learn session. Organizers will split into several teams here to achieve goal.  
### Outcome

The session aims at making the attendee aware about the Internet Data flow, privacy, communication and the need of Web literacy for all. This session is proposed specially for the school-kids and college students eager to learn about these staffs. Hence, the probable outcome of at-least mediocre-successful session will include-
-Attendee will know about THE INTERNET and the contents in it. 
-They will be acknowledged about their rights over the web for rightful information.
-They will be aware about using the web more efficiently after they get Literate about the  Internet.
-There will be an awareness among the attendee to learn on collaborative manner about Information and web literacy.  
-If 10% of them get any information they didn't know earlier there is a probability that they will share this with their peer and rise awareness about web, privacy and need of it with better knowledge about how that works.

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
