### ISSUE TITLE
Can Advocacy be Fun? 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#209]
**[ Google Spreadsheet Row Number ]** 177
**[ Facilitator ]** Eric Swanson
### Description

Online campaigning is often serious and grave, with little continuing incentive for users to visit campaign sites without being prompted. You make your donation, you sign a petition, you share and then you leave until someone asks you to come back. The goal of this session is to collaboratively play with gamification principals to make a sample advocacy campaign MORE FUN, so that people WANT to take the next bite-sized action without being prompted. 
### Agenda
-   Get clear on the problem (as described above). 
-   Introduce a sample online advocacy campaign, with a clear strategy that we need people to participate in. 
-   Introduce a basic collection of gamification principals (like rewards, quests, level ups, characters, etc.). These could be represented and summarized on little cards and handed out to people. If there are gamers/game designers in the room who can add to the mix now’s the time! 
-   Have BREAKOUT SESSIONS on individual gamification elements. E.g. what could a “quest” look like in the campaign? Have participants write ideas on cards. 
-   Put the cards in the middle of the room for all to see and review. 
-   Put up a giant piece of paper representing a narrative arc, and invite teams of people to collaborate and mix and match gamification ideas (cards) along the arc, mapping out a complete game experience. 
### Participants

More participants = More people in each group (up to a max of 8), more ideas generated. Additional narrative arcs available on walls for the final exercise. 

Fewer participants = Fewer people in each group (minimum of 3), fewer ideas generated e.g. could aim for one idea per gamification principal.  

5 people: everyone hacks together; trying to come up with at least one idea for each of the basic gamification principals during the initial brainstorm. Then everyone works together on a single sample narrative arc, mixing things together and placing them. 

15: split into five groups of 3, each tackling 2-3 game elements during the initial brainstorm. Then reconvene as two groups of 7-8 to complete two sample narrative arcs. 

50: 7 groups of 7-8, each tackling 1-2 game elements in initial brainstorm, then reconvene as groups of 8-10 and complete 5 sample narrative arcs. 
### Outcome

I’ll be attempting to apply the lessons and ideas to an advocacy campaign I’m currently running, and it’d be awesome if others tried as well. 

I will Blog my progress and compile a case study so attendees can see the outcome of their participation in a real-world application. 

I need all the help I can get on the design and technical side, so there’s plenty of opportunity for further collaboration on implementation.

**Comment by edrushka** [comment]
cc @Melechuga

**Comment by edrushka** [comment]
@shaghdoosti just want to make sure you see this one. Eric is brilliant, as has done a lot of work in campaign-related movement-building in Canada's environmental movement.

**Comment by edrushka** [comment]
@marcwalsh and @Saallen  - looks like all the labels have been removed :(

**Comment by EPIKhub** [comment]
@edrushka I might be interested in this, one of our young lads aged 9 ran a campaign and I know Arts award has a civic engagement tool so we might be able to localize it to a UK youth audience?

**Comment by edrushka** [comment]
What's the status of this one? It doesn't have a 'session accepted' label.

**Comment by EPIKhub** [comment]
Im trying to talk to the session leader but she is in Canada with time zone
issues, will try again tomorrow

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by EPIKhub** [comment]
I got an email just now saying she is in the middle of a federal election
and time is getting to close now to make arrangements for her to come

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies
