### ISSUE TITLE
[Pathway] Inclusive Communities

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#21]
Community: We want to build healthy communities on the web and in real life, with a focus on inclusion, safety, privacy. This pathway would draw in work at the Coral Project as well as structure and support for face-to-face events. (It would be possible to split into "online community" and "in-person community.") We have someone specific in mind to lead this pathway.

Sessions include: 
- [ ] tbh
- [ ] tbh
- [ ] tbh

**Comment by cubicgarden** [comment]
This sounds like its better fitting for the library? @cubicgarden

**Comment by cubicgarden** [comment]
@thornet lets talk?....?

**Comment by thornet** [comment]
cc @erikao who's helping with this pathway. @cubicgarden it might be something to coordinate how this pathway flows with your beautiful plans in the global village.

**Comment by cubicgarden** [comment]
Could do... lets talk soon

**Comment by Saallen** [comment]
This session has been closed by erikao
