### ISSUE TITLE
Communities at Scale

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#210]
**[ Google Spreadsheet Row Number ]** 174
**[ Facilitator ]** Sara Haghdoosti
### Description

This session will focus on best-practices at growing grassroots communities around the world. Participants will have a chance to hear from and speak to leaders at organizations like Wikimedia, Mozilla, Global Voices, Creative Commons, and Open Knowledge Foundation (TBC). Participants will be encouraged to share their knowledge about what works at a grassroots level in their local contexts.
### Agenda

A hybrid panel-discussion type of session. Each member from the visiting organization will give a short talk on how they've created communities at scale, what worked and what didn't, and how they chose which communities to engage. Then everyone will break into groups with one organization member in each group, and they'll chat. The participants will have the opportunity to rotate around and talk to each organizational representative.
### Participants

With 5 participants, this will probably just be one discussion group. From 15-50, this will be a larger group format at first, followed by break-out groups (as described above).
### Outcome

The goal is for the participants to learn about strategies that the represented organizations have employed, and find ways to integrate them in their community outreach. We also envision the participants sharing local knowledge with the members of the represented organizations.

**Comment by Melechuga** [comment]
@shaghdoosti 
Jochai is helping organize this as well.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin could inspire community outreach goals of community leaders

**Comment by Melechuga** [comment]
Invited participants have a conflict with IFG.
