### ISSUE TITLE
Edges of Open Governance 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#212]
**[ Google Spreadsheet Row Number ]** 181
**[ Facilitator ]** Bala Subramaniyan P
### Description

The open data movement—the idea that certain data should be freely available to everyone—can drive innovation, make government and corporate activities more transparent and improve decision-making about natural resources. Helps in monitoring platform, has helped make data accessible and visible to the public.
### Agenda

“OPENNESS” of data by enabling users to derive more meaning and benefit from the information.Finding open data for global can be difficult. Those who own the data may be reluctant to share information for fear it will be misused or improperly cited, or because of intellectual property or confidentiality restrictions. A lack of international data sharing requirements and standards also limits access.
### Participants

Making them to think on different edges of open source system and making them to aware on open source digital platform. Educating them with different open source activities. Motivating them to move  with openness.
### Outcome

Open data can help solve complex challenges : (1) It Can Drive Science and Research, (2) It Can Hold Companies Accountable and (3) It Can Improve development changes with future plan strategies. Driving open innovation from each and every participants.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
