### ISSUE TITLE
Hack the Backpack! 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#213]
**[ Google Spreadsheet Row Number ]** 183
**[ Facilitator ]** Matt Rogers, DigitalMe & Makewaves, @digitalme_ @MakewavesTweets @mattdigitalme
### Description

Help develop and ‘fix’ the Mozilla Backpack using Mozfest as the ideal place to find like-minded community members with whom to join forces. We have identified a numbers of developments in house that we are working on in Partnership with the Badge Alliance and the Mozilla Foundation. Alongside these developments there are also a number of issues identified on GitHub we would like to work on over the course of the festival with the aim of getting them staged and signed off within the weeks after MozFest. We are really keen to utilise the skills and expertise of the community to help make this happen by holding a hack workshop over the course of the festival. We will enable people to work on fixes at MozFest itself, but also remotely from around the world as we intend to contact developers within the community in the build up to the festival. By supporting ‘remote’ hacking we can ensure maximum accessibility for people unable to attend in person and recognise the international importance of the Backpack.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by mattdigitalme** [comment]
cc @chadsansing Hey Chad, just wanted to let you know that we can only get our developers there on the Saturday so won't be able to run this session explicitly on the Sunday -  although I will be at the Festival so can do a q&a or help support work that continuing from the Saturday

**Comment by chadsansing** [comment]
Thanks for the heads-up, @mattdigitalme; you're tentatively schedule for Saturday AM.
