### ISSUE TITLE
webmaker session

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#214]
**[ Google Spreadsheet Row Number ]** 175
**[ Facilitator ]** Alvin Aliu
### Description

It will teach people how to use webmaker tools. 
People will also learn how to use webmaker app and also gain some experience in using web content.
People that don't know code will find it easier to create web content
### Agenda

First I will introduce myself and team.
I'll pose an open minded question   ( Why should people choose open source data)
Then I will introduce the session to the participants
I will then start involving participants to do some practice work with webmaker tools and webmaker app.
We will share our published creations by sharing links to different social portals for other people to view
Get feedback from the participants bout the session
End the session
### Participants

If they are five participants, i'll then work with them to ensure maximum participation of each individual..that is each individual making stuff with webmaker app and Tools
If they are more than 5 participants i.e 15 or 50, I will group them into smaller units in order to have effective performance of the groups and also efficient creation of webmaker products.
### Outcome

One of the major outcomes will be creation of a bigger community for the people. And also , creation of new communities.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
