### ISSUE TITLE
Collaborative Community Spaces

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#215]
**[ Google Spreadsheet Row Number ]** 173
**[ Facilitator ]** Vineel Reddy  Pindi
### Description

The goal of the session is to teach participants how to educate, engage and empower individuals, local communities & organizations to make impact through a collaborative platform.

Help create/ identify various ways to support hackers, makers, startups and creative people. Promote experiential learning, co-creation and collaboration through the interests of people.

The aim is to bring in various communities together to work on the things they like, connect, share, teach and build.

The activity will focus on benefits of embracing the Open Practices. Understanding a few case studies and hands-on workshop to build the structure for various scenarios.

The participants will learn how research, knowledge exchange, learning and mentoring with each other can be driven. 

A part of the session will be focused around discussing what a open and inclusive space is to them.

Learn how to make these spaces sustainable so they can continue make impact in long run. 
### Agenda

Many local communities, big and small, several initiatives that touch technology, learning by making, Web, building things, each have a shortcoming of resources either it be physical, or knowledge sharing. 

The session agenda will be a hands-on activity where participants will understand and design a Collaborative space for their city/ region:
- Introduction to Collaborative Community Spaces
- Impact stories
- Why start Collaborative Spaces?
- Who can start these spaces
- Where/ which city can have these
- What kind of resources get into building one
- Identifying the roots. Community is the backbone.
- Support Structure. 
- Educating, Engaging & Empowering
- Partnerships & value addition
- Creating a learning, making & sharing environment
- Sustainability
- Measuring Impact
- Role is local ecosystem
### Participants

We are designing the activity such that the core outcome, learning's are the same but would differ in how we engage and methods used will be tailored  to set of participants. 
- For a group of 5 members:
  -- The activity will be more 1-1, a in-depth discussion, understanding and execution.
  For a group of 5 or more, the format would be pretty much similar where participants are divided into a group of small numbers, where each team will work on specifics of the activity.  
  For a group of ~50 participants, the participants will be divided to small groups based on their interest in specific area in the agenda. Each team will be working on a specific area and build a plan. One person from each team will summarize to the rest of the groups.
### Outcome

The major outcomes after the festival that I see are:
- Participants exploring to build collaborative spaces in their region
- Participants actively supporting/ engaging with the existing collaborative spaces.
- Participants launching collaborative space in their city in 3 months from Mozilla Festival.
- Participants keep in touch sharing their stories/ journey in building the spaces. 
- We'll be publishing all the notes, learning from the session and document it for anyone's reference.  
- We'll keep in touch with the participants who show interest in building spaces, provide them support wherever needed.

**Comment by cubicgarden** [comment]
Could fit the library space @cubicgarden

**Comment by amirad** [comment]
cc: @amirad

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin bridging communities a component of  participation leadership framework.
