### ISSUE TITLE
Learn Python Programming and write your own game (Programming Simple text-based games in Python)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#216]
**[ Google Spreadsheet Row Number ]** 201
**[ Facilitator ]** Tina Götschi
### Description

This session will introduce the Python programming language to participants. It will teach them how to get it, install it and use it. Python is a great first programming language to learn because of its simple and clear syntax. Its also easy to get going and write a simple games so we hope the session will inspire participants to learn to code by teaching them to code some fun games that they will enjoy playing.  We’ll help participants will install IDLE (the Python integrated development environment) on their laptops and help them code a game: the Magic 8-ball (easy), a number guessing game (moderate) and/or Rock/Paper/Scissors (advanced)
### Agenda

The session will be a workshop where participants will get hands on with Python and learn to write their own code. They will download or install IDLE and then be guided through how to code and debug the game(s) they choose to code.  The facilitators will be students from St Philomena’s School who have learned to program in Python as part of their Computing/Computer Science course at school. They are all 14 – 17 year old girls. We will also provide online help (on a website or github) in the form of tutorials and sample code. The session will allow each participant to work at their own pace on the game they choose or to work in groups with the help of the student facilitators.
### Participants

We will be able to accommodate a large number of participants. We will have Python available on memory sticks to prevent long download times. Help sheets and templates will be available online for participants to get started themselves. We will have 10+ facilitators available to help and participant can work together in teams. 
### Outcome

We hope that this session will encourage more young people to program in Python and also help students and teachers become more comfortable with this great programming language. We also hope to show participants that coding is accessible to all and not some “dark art” only for the few nerds and geeks out there.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
