### ISSUE TITLE
Digital Literacy in the World of Accelerating Returns

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#217]
**[ Google Spreadsheet Row Number ]** 188
**[ Facilitator ]** Soumya Deb
### Description

Design a participation model, how to address the challenge of educating & enabling the collective humanity about the future of rapid and exponential growth of technology (and its projected pros and cons - relating to privacy, AI, mortality etc.), which so far, is only a concern for very selective few futurists.
### Agenda

Interactive Fireside Chat.
- Discuss the magnitude of exponential growth of tech
- Draw the demographics of people actively in/out of it
- Plan how to expand digital literacy programs to cover it
- Plan how/whom/where to address/educate and why
### Participants

For a handful of people, this is a brainstorming session, with a single flow of topics, and with some general outcomes.

For 15+ participants, there will be a series of _split-up and figure out_ and then _gather-around and share_ on the agenda.

Based on the participants, this can be made further flexible.
### Outcome

Add curricula/chapter in Mozilla's digital literacy program & connected learning, to address the need of educating people not only the web-of-past, but also the web-of-future, as it shapes - and prepare the entire humanity (not only a selective few) for the same (or better, share hands in shaping it).

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin
