### ISSUE TITLE
Ending Online Tracking - Do Not Track And Beyond

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#218]
**[ Google Spreadsheet Row Number ]** 172
**[ Facilitator ]** Noah Swartz
### Description

Attendees will learn about the current state of online tracking and user opt-out. They'll become familiar with Do Not Track history and EFF's new DNT policy as well as modern ad blocking tools. Attendees will have a sense of the online tracking ecosystem, and will have an opportunity to voice their concerns and suggestions for how to reform it. The session will also cover the technical details of how browsers are able to be tracked, what prevention tools do to circumvent this, and what browsers can do by default to aid users and tools. The hope is that attendees leave with a better understanding of what is going on and feel empowered to use the tools available to help reform the state of web tracking. 
### Agenda

The session will begin with a brief overview of exiting tools, policies, and the projects I've worked on, along with the technical details of how web tracking works. Then attendees will discuss their experiences with web tracking and technical countermeasures. The discussion will focus on how we can use these tools influence better behavior from ad tech companies as well as what is needed to better aid users who want to opt-out. It will be a general discussion, moderated (if need be) by me to allow participants to share equally.
### Participants

With a small group it will be just a simple round table discussion. For a larger group it will be a moderated discussion where I will manage a stack. If it gets larger than that we will break up into small groups, do round table or moderated discussions, then all reconvene and present on what our groups discussed.

One of the best sessions I went to last year was on a very similar topic (the birth of the W3C DNT header and it's current state in adoption) and run as a roundtable. It was by far the session I learned the most from, and I'm hoping to repeat it's success with new DNT progress. Additionally I will try to rope in other knowledgeable attendees to help lead/foster discussion.
### Outcome

Attendees will leave the session with a collective better understanding of how web tracking operates and what we can do to influence better behavior. Additionally attendees should have knowledge of the current status of efforts to reform advertisers, some of which are either very new or not common knowledge. Attendees should be able to take what they learn and apply it to their own project, their own advocacy, or even just their day to day lives (in their personal web browsing). If attendees work on tools or browsers they will leave with a better sense of what is needed to stymie trackers. Attendees should also be able to share what they learn with authority, and hopefully spread excitement about the current anti-tracking movement.

**Comment by Melechuga** [comment]
cc @mixedpuppy @MozStacy @shaghdoosti
