### ISSUE TITLE
MODELLING THE WEB FOR AFRICA.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#219]
**[ Google Spreadsheet Row Number ]** 184
**[ Facilitator ]** MICHEAL ABAHO
### Description

Learn - Participants will learn about the current state of the web in Africa i.e Africa's presence on the web, perception about the web, Challenges, hindrances, opportunities and the digital literacy in Africa.
Identify - Participants will work together to create a SWOT analysis around web literacy in Africa, focused on identifying the barriers holding Africa back from taking advantage of the web.
Solve - Participants will  brainstorm ideas and solutions that they think, when implemented, they would enhance the web presence and experience in the African region.
### Agenda

A. A brief presentation entailing statistics about Africa's presence on the web, the current effort input to steer web literacy, Web trends, Web accessibility and internet affordability. Plus, IT will map these facts to Mozilla's mission and what Mozilla is already doing.
B. Show a case a video clip capturing different people’s responses to simple questions concerning the web.
C. Dive into small groups, Task these groups to identify different problem statements, gather information (both background and current info) and generate solutions to the different barriers identified above.

Sessions' format:
Mini-workshop with a solution oriented approach. Each of the participants will at least identify a problem or come up with an idea/solution
### Participants

Intend to utilize small groups probably groups of 3-5 for a large audience (group of participants). However, with a small group of people, Definitely enclose in a circle and model the web for Africa.
### Outcome

1.Being a solution oriented session, we shall encourage participants to make commitments both individually and in small groups to set the pace to implement the ideas and solutions collected during the session.
2. We shall also draw a generic road map for implementation, that will guide the participants in planning and executing the different ideas and solutions.
3. We shall as well appoint team leaders for following up on the different projects that erupt from the session.]

**Comment by Melechuga** [comment]
cc @mixedpuppy  @shaghdoosti  @MozStacy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
