### ISSUE TITLE
[Pathway] Data & Impact

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#22]
Impact is the prism we're using to look at working with data. How do you acquire it (scraping, FOIA-style requests)? How do you analyze it? How do you publish work that changes people's lives in the real world? This pathway would provide significant opportunities to coordinate with Science.

Subthemes: Mapping, FOIA/access, Tools for analysis

Sessions include: 
- [ ] tbd
- [ ] tbd
- [ ] tbd

**Comment by ryanpitts** [comment]
Closing in favor of https://github.com/mozilla/mozfest-program/issues/50
