### ISSUE TITLE
 Hack on Webmaker App

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#220]
**[ Google Spreadsheet Row Number ]** 199
**[ Facilitator ]** Santosh Viswanatham
### Description

We will provide few basic templates of webmaker app. The participants will hack on the webmaker app and build their own web projects which can be remixed by others.we make different templates for different age group.For example a cartoon character template for a kid ,a movie template for a movie lover and a TV series template for a youngster.This enables the participants to create their own web content using our building blocks and publish it to Internet without any coding experience leading to web literacy. 
### Agenda

The format of the session will include both fireside chats as well as workshop.If we get like 5-15 then we will go on with informal discussions with the participants and if we get a large crowd of 50 then we will have a talk with a demo of how awesome things can be made using webmaker app thus leading to web literacy.As they start working on examples they will learn about the basic elements(text,image and link) of web and how effectively then can build web content using this application.
### Participants

Since we got few templates we can actively involve any number of participants. Everyone will love to make web if they will be able to share it with others. If there are only few number of people like for about 10 then we will show the app on our mobiles and ask them to their hands on it so that they will have a hacking experience on spot.If we have 50 number of participants then we will divide them into teams and show them a demo of how awesome things can be made using the app and give them the link to the templates we made along with the installation file of webmaker app so that they can hack on templates by the end of this event and publish them.
### Outcome

We get a sustained group of contributors where people will love to share what they made and how he made. I can see the sustainability in this because when a kid makes a webpage published on the internet definitely he will love to share it with his group of kids and parents.When another kid gets to know about this webpage he will obviously love to make the same for his favourite cartoon character.The next take away is the clear perspective about what extent the webmaker app can unleash the web learning experience using this app.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
