### ISSUE TITLE
The Internet of Things: Hands-on Development Workshop

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#222]
**[ Google Spreadsheet Row Number ]** 191
**[ Facilitator ]** Varun Kaushik
### Description

Internet of Things is the art of connecting ‘Things’, using a bunch of modern day technologies, to the internet and eventually to each other. This allows us to improve efficiency, save costs and achieve control like never before, by accessing and analyzing the large chuck of data coming from these objects. 

This workshop will provide knowledge of building Internet of Things (IoT) products. A smart home automation system using the Raspberry Pi, Arduino and other smart mini-computers as a platform during this workshop. 

The attendees will be able to witness amazing on-the-spot demos and learn (Hands-On) how to build a smart home automation systems. 

Futuristic learning, using the web in an efficient and effective way and experiencing and building the new technology and tools.

Come be a part of the next major leap forward in mankind’s technical evolution - The Internet of Things!
### Agenda

The best collaborative build-a-thon.

We will make this the best Fun-learning workshop of the Mozilla Festival!

Agenda:
- A small informative 5 min. description talk of IoT.

*DIVE!
People love to watch things being built and they want to build cool things on their own. After the informative small 5 min. talk, we will dive directly to the Build and Make part. 

*Build while teaching; We will build an easy and smart Home Automation product from the scratch while teaching each and everything to the participants. *Participants will be given their tools, so that they can try, while learning. 

A super interesting live demo will be given, where we will show the live and Real working of the system and control AC's, TV's lights and PC's and other devices using that.

A BUILD-YOUR-OWN IoT device Hands-On session after that will help users to make and learn it perfectly! 
### Participants

We will be establishing small 'Connectivity Groups', where each group will first learn, how to build their very own IoT Product and see the amazing live-showcase/demo. 

We will then allow people to set up their mini work-stations and build their very own IoT products and go for demos. 

We tend to keep it a very fun-learning session and a very collaborative one. 

Each group will be mentored and they will learn; To build a IoT Product (Home Automation), Use the web effectively and efficiently, Be a Web-Superhero and fun-learning; The most important part.

Each group will be provided the Tools and the mini-computers to build the products. 

Come to this workshop equipped with your own IoT ideas and make them a reality, or build your very own IoT device as part of a collaborative build-a-thon.
### Outcome

Insanely Great! We are so sure about that.

We will be forming a huge collaborative team of participants, who will later work remotely and build an IoT Organisation, who will work together to teach people about IoT and build great new IoT products, innovate and share the things with the world. 

Learn, Teach and Share is what we aim for and we are so sure, that we will achieve it. 

Come with an Idea, join us, leave with a Community, Organization, Family and a futuristic goal and spread the things is what we aim for.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
