### ISSUE TITLE
Techniques to facilitate a club

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#223]
**[ Google Spreadsheet Row Number ]** 187
**[ Facilitator ]** Sayak Sarkar
### Description

What do we mean when we say teach in a way that is open, collaborative and inclusive? Learn how to take those words and practice them in a club setting to become a better facilitator. 
### Agenda

This would be similar to a fireside chat with a lot of open discussions and interaction with the session participants about open practices and collaboration in real life and also about team building in a mutually inclusive environment. 
### Participants

Since its going to be a fireside chat with open interactions with the participants, the format is mostly going to be the same for 5 or 15 people. However, if there is a turnout of 50 or more participants, I am prepared to transform into a talk session with slides and other discussion materials. 
### Outcome

I envision the session to help people understand what an open, collaborative and inclusive team look like and help them take forward the same spirit to their own clubs and share the spirit of teaching, learning and making together in a collaborative environment.

**Comment by cubicgarden** [comment]
Interested @cubicgarden

**Comment by soapdog** [comment]
want to help!

cc @soapdog

**Comment by amirad** [comment]
Closing this @soapdog as we have sayak focusing on session #226
