### ISSUE TITLE
Flattening the ivory tower: harnessing the knowledge of readers for Open Journalism

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#225]
**[ Google Spreadsheet Row Number ]** 200
**[ Facilitator ]** Gideon Goldberg
### Description

Participants will learn and share best practices for engaging with online communities in a structured and meaningful way. Including how the Guardian uses tools like Guardian Witness to achieve this. As well as coming up with ideas for how this could be done better in the future!
### Agenda

We all know that a small number of journalists can't have the monopoly of expertise on any topic. But in a deluge of user comments (one recent Guardian Live Blog had over 25,000,) it can be difficult to pick out useful information from readers.

We will use a workshop format and work in groups to break down elements of this problem such as: how can we separate out readers’ experience from opinion? How could readers be rewarded for their contributions? How could we verify and utilise readers’ expertise?  
We will then come together to report back on our findings
### Participants

With a greater number of participants we would be able to split into a larger number of small groups to discuss different elements of the topic. 
### Outcome

We hope that this workshop will seed best practices and new ideas that journalists can take back and try in their newsrooms and that readers will discover ways to engage with journalists in a meaningful way.

**Comment by ryanpitts** [comment]
Gideon and colleagues are based in London.

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Building Online Communities" pathway.
