### ISSUE TITLE
Tips, tools and resources to help fund your local club, program or group

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#226]
### Google Spreadsheet Row Number

186
### Facilitator

Name: Sayak Sarkar
Twitter: @Sayak_Sarkar 
Org: Red Hat
### Description

Hosting and running a club isn't easy, neither is dealing with the costs. Need help reaching out to local partners to help fund parts of the event or supply resources? Want to build a microfundraising site where people can donate to your club? Find out how you can fundraise to help support your clubs. This session aims at empowering individuals and groups with the know-how and essential understanding of basic tips and methods of fundraising for their clubs or programs.

**Comment by soapdog** [comment]
cc @soapdog
