### ISSUE TITLE
Bring your web development skills to mobile

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#227]
**[ Google Spreadsheet Row Number ]** 197
**[ Facilitator ]** Alastair Coote
### Description

We'll take your existing desktop HTML/CSS/JS skills and learn the extras you need to make the most of mobile. Bring your phone and laptop with you, and we'll walk through device debugging, meta tags, viewport-based CSS units and some mobile JavaScript APIs.

We'll go through a guided coding session, then you'll be free to play with the code and make whatever you want.
### Agenda

It'll be a workshop format, with everyone pulling down the same GitHub repo, then walking through different features in mobile browsers, editing various values/functions to illustrate how they work. Then I'll leave it open for people to edit the code however they wish, or start something new, with me available to answer any questions they have.
### Participants

Everyone will be following the same guided path, so more people shouldn't be a problem - within reason!
### Outcome

Hopefully it'll give them the groundwork so that the next time they start a project they'll consider how to add touch/swipe interactions or a mobile UI from the beginning.

**Comment by ryanpitts** [comment]
Alastair is our pathway coordinator for Mobile & Accessibilty, and will have travel support to attend MozFest.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Mobile & Accessibility" pathway.
