### ISSUE TITLE
MakeWebYourWay

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#228]
**[ Google Spreadsheet Row Number ]** 195
**[ Facilitator ]** M. Shafique Patni
### Description

The session includes an activity in which people would be asked to make group of 4-5 members which must include minimum 1 female participant and  then these groups would be asked to present a product idea that could be anything for web literacy that could be made available to users on the open web teaching.

Team have to give idea on webmaker to build better for web literacy & decide product's name for apps, games or tools , prepare its logo by using graphics or by doodling it on paper, and team have to prepare an advertisement of that product including all the features of that product and convincing people to use it. Then the team will be given 2 minutes to present their apps, tools, or games in front of everyone. The product can be imaginary. They do not have think about implementation of that product.
### Agenda

This session will involve more participants and encourage everyone to think beyond their imagination to discover new innovative products like apps, games, tools by which the webmaker could be made a better place for the users. As they just have to represent the idea , the participants will need not to worry about its implementation or anything.
The team will be given 30 minutes for develop apps maker, apps development, other ideas on workshop, prepare its logo and prepare its advertisement. 
The advertisement should include live performance by the participants. This will include peer to peer session and learning through making logo. The team may use webmaker app in presenting their idea.
### Participants

The number of teams will vary according to the number of participants.
also, if participation are more interested on project then i will work for making apps, games, or tools for webmaker project.
### Outcome

This will improve web learning, leadership quality and team working of all the participants. If any product idea seems feasible and seems to help the web make a better place for the users, then this can be funded and promoted by the community. Mainly the outcome of this session would be better and innovative ideas for improving the open web. 
Also, Women's contribution in the web would increase as the team would be incomplete without female's participants. The participants will have no limit on their innovations and imaginations.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
cc @LindseyFrost @samueledyson

**Comment by simonaramkisson** [comment]
@jvallera @simonaramkisson

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
