### ISSUE TITLE
Webmaker for Android Hans-on!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#229]
**[ Google Spreadsheet Row Number ]** 190
**[ Facilitator ]** Umesh Agarwal
### Description

It will allow users to create custom Web content easily and quickly, no coding required. Its practical, fun, and a key building block for teaching and improving Web literacy. It’s also a tool for empowering individuals and strengthening the open Web.
Goals:-

> Make active users of web!
> Allow users to create using their imagination.
> Increase interest in users for making the web!  
### Agenda

It will be a hands on interactive session!
First will show a small demo to the group of participants.
Then will provide them android device(if they don't have one) to make something using the Webmaker app.

We will provide them theme to put their imagination and make something cool!

This will be a repetitive work. As any new participant comes we will allow the old participant to teach the new ones. This way they will learn as well as teach!

Some goodies for  awesome work as well!
### Participants

For 5 participant we will ask them to work individual.
For 15 we can make groups of 3.
For 50 we can make groups of 5.
### Outcome

1) It will help individuals move beyond a read-only version of the Web.
2) It will help them to learn as well as teach!
3) It will create an awareness among individual that how fun is making the web.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
