### ISSUE TITLE
Modular frequencies - HearUsHere soundlab

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#230]
**[ Google Spreadsheet Row Number ]** 189
**[ Facilitator ]** Klasien van de Zandschulp
### Description

In the ‘Modular frequencies’ workshop we’ll create a spacial audio installation! The HearUsHere app (location based audio) combined with iBeacons allows us to create a new sonic experience. Every iBeacon is a frequency that carriers a sound, when you get closer to one of these frequencies the audio will automatically fade in and cross fade with others. Using the speakers of our phones, we’ll create a collective audio experience. This results in unique and constantly changing soundscape created by the visitors and their navigation in the space.  
Within the workshop you won’t only experience these modular frequencies. You’ll learn about frequencies, location based audio and you’ll hack the beacons to create your own ‘pirate radio’! (No coding skills required).
### Agenda

This is a hands-on workshop. We’ll start with a session exploring location based audio and the possibilities of iBeacons before we experience the audio installation. Afterwards we’ll create sounds ourselves and start hacking the beacons. We end with presenting our hacks by listening to and experiencing the audio installation.

During MozFest the installation will stay active and for everyone to enjoy and experience.
### Participants

This workshop can easily be done by a small or bigger amount of participants by dividing everyone in groups to work together on a frequency. 
### Outcome

This workshop is a preview of our project that will be executed in spring 2016 in Chicago, together with Radius (experimental and online radio). The results of the MozFest workshop will be presented in Chicago and used as input for this project.

The participants of the workshop will be able to use and build upon the technology as HearUsHere is an open source platform.

**Comment by Zebetus** [comment]
@EPIKhub Once again maybe a way to incorporate tech and music

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by cubicgarden** [comment]
Ideally it could work off the back of #559

**Comment by EPIKhub** [comment]
@Saallen @cubicgarden a version of this session will also be running in the youthZone as a second session that is youth Centric within the Music pathway

**Comment by cubicgarden** [comment]
Ok thats fine... maybe we could have two running or it running in the youthZone and a talk in the living room?
