### ISSUE TITLE
Decentralizing the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#231]
**[ Google Spreadsheet Row Number ]** 198
**[ Facilitator ]** Nicola Greco
### Description

This session is about understanding why we should and how we can decentralized the web. By this, I mean making apps that do not need a man-in-the-middle and where users can control their data - the idea is to bring peer-to-peer on the web.

The session will cover the different layers to achieve a decentralized web: standardization, online identity and peer-to-peer technologies.

Attendants will learn about the technology and code together their first decentralized app built on Linked Data, WebID and the Solid protocol, fresh from the MIT CSAIL Lab!

Goal: Make them experience some extreme-decentralized-web mad science!
### Agenda

It is a participation based session divided in two parts: conversation and coding.

Conversation part:
- I will introduce the different level of decentralization and the state of the art of decentralized technologies
- We will discuss the importance of making decentralized apps (and their incredible power!)

Coding:
- We will do some live coding to show how to set up an decentralized system - I will go through the MIT Solid, but also, Matrix, WebTorrent and IPFS
- We will go through a demo app (full demos will be on github)
- We can start to use the decentralized app we have built straightaway amongst them!
### Participants

Less participants will turn the session into a "Get the decentralization pill and let's explore this world together"

More participants will need to be divided in smaller teams during the coding session. However, it is very important to have interaction in the Conversation part of the session and to_play_ with decentralized demo apps.

Depending on the skills of the participants there will be more or less coding
### Outcome

Participants will learn a new way of doing web apps, for which they don't need a central server and where the user has more control its own data. After the festival they will write apps, release open source code and inspire a new set of developers to push forward the decentralized web

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
