### ISSUE TITLE
Building an Encyclopedia of File Formats

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#232]
**[ Google Spreadsheet Row Number ]** 196
**[ Facilitator ]** Benedikt Kroll
### Description

File formats are an essential part of everybody's routine, where the internet or computing is involved. Every chat application, every social network and all other services on the web have their own formats: These define the types and amounts of content being saved, the information carried in attached metadata as well as the possible mobility and convertability of data, for example the ability to access data with other applications or on other operating systems.

At the Mozilla Festival, I'd like to bring together ideas and requirements for an encyclopedia of file formats. The aim of it would be to be a source of information, for example to access before deciding on a software choice for a task. I think that to teach information literacy, it is very important to have low-level resources available on the basics of how computers save their data and what this can mean for human users. 
### Agenda

This project idea touches many areas: First of all, building a low-level resource means to form an easy-to-use and intuitive interface to contents. What alternatives are there to plain texts, i.e. thinking database, linked data, comparison charts and automatic assistants for people seeking a file format for certain tasks.

Obviously, the second important point is to think about  contributors. What would contributing be like, how can it be made both easy and safe? How to conduct quality assurance and how to get feedback from users?

I'd like to present ideas for that project, put up some open questions for discussion. It would be about technological and community aspects that are necessary to start such an independent and empowering resource for general internet users on file formats and their practical implications.
### Participants

With around five participants, the workshop would address questions and issues one by one. If more people would participate, that would be great because groups could be formed that focus on certain aspects and maybe even organize themselves.

Besides that, it could make sense to have sort of a "silent discussion" on a large whiteboard or poster for people who would just like to write down their comments when passing by.
### Outcome

I'd prepare to have some raw structures up and running before the festival, so that it would be great to bring the file formats encyclopedia on the way. This would allow participants to see their results online after the festival and spread the word to others who might be interested to view the site and maybe even contribute.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
