### ISSUE TITLE
Connecting everything but the kitchen sink to Scratch

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#233]
**[ Google Spreadsheet Row Number ]** 193
**[ Facilitator ]** Thomas Preece
### Description

In the session I aim to get participants using Scratch (a fun interactive block based programming language) with Scratch extensions both created by myself and others. These extensions allow you to do many different things with Scratch but in the session we will focus on connecting Scratch to the outside world using hardware such as as Arduinos or mobile phones and the open source extensions I have developed. If there is time we will also look at several other different Scratch extensions that others have produced that I've found interesting and also briefly detail how participants can make their own extensions.
### Agenda

Ideally I would like to run the session as a workshop with myself doing a brief introduction on the extensions and Scratch and then letting the participants try everything for themselves with me walking around and available to help out anyone that needs it. Hopefully I'll also have created tutorials by November so I can give people website links to the content and guides so they can come back to it in their own time too. Failing being able to do a workshop a space to put up a poster with links to content and tutorials would also be very good.
### Participants

I'll be bringing a set of Arduinos that can be distributed between the participants during the session but as long as participants bring a laptop they can install Scratch and all the extensions for free and use most of them without any extra equipment. As not all the extensions require an Arduino if there is too many participants to share the Arduinos then some can play with the other extensions whilst the Arduinos are being used. If there is a very large amount of people then I'll point participants in the direction of online tutorials and resources so my time can be more focused on those that need it.
### Outcome

The session will really help me to get useful feedback on my extensions especially how easy they are to use, which is very important information to gather as they are designed to be used by non technical people (school students and teachers) and so any information that will allow me to make them more user friendly is amazing. However I'm also hoping that the extensions I show that have been made by myself and others will inspire the participants to go out and create their own extensions to add weird and/or wonderful features to Scratch that students around the world will enjoy.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
cc @cubicgarden @kaythaney

**Comment by EPIKhub** [comment]
cc @msaunby for the garden, I think this would be an interesting addition to the garden
