### ISSUE TITLE
On Your Mark !

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#234]
**[ Google Spreadsheet Row Number ]** 179
**[ Facilitator ]** Bala Subramaniyan P
### Description

"Office Run - Open Trip Planner"  The daily commute in world is often no joy-ride, an open trip planner based on open data (Open-Source System) standard can help office-goers plan (or imagine!) their trip on public transport, and planners analyze patterns.
### Agenda

While a trip planner is no novelty, an “open” tool can also provide a platform for analysis of accessibility of various areas for resilience and urban planning. It also provides easy tools for hackers, developers, and entrepreneurs to build future apps from "Office Run - Open Trip Planner"
### Participants

A simple open trip planner session that lets office goers use GTFS data for BMTC and Metro services to help plan (or imagine!) their day  commute on public transport.
Based on a collection of popular ‘tech park’ locations in the city, it can also indicate and rate how ‘accessible’ a particular office location actually is with public transport. 
### Outcome

Everyone is reaching gods destiny land (Beauty of Nature). Will move session through each and every corner of the world with loads of entertainment and ice breaking session, Mind blowing imagination...

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
