### ISSUE TITLE
Tackling the 'nothing to hide' argument

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#235]
**[ Google Spreadsheet Row Number ]** 211
**[ Facilitator ]** Tactical  Tech
### Description

Encryption isn't always the answer though we may want it to be. In light of the Snowden revelations and exposure of how pervasive surveillance is, and given the limits on human rights defence and progressive, non-violent activism, the use of encryption and anonymity as privacy enhancing technologies is vital. There is also a crackdown on the use of privacy enhancing behaviours and technologies around the world. Law and policy against encryption in particular, and privacy in general, increasingly deploy the 'nothing to hide' argument, especially in relation to national security. This reduces privacy to something that only people who are engaged in something suspicious would do. This session  would be an opportunity to generate a public discussion about dealing with the 'nothing to hide' argument, developing arguments to counter it, and building a global narrative on 'something to hide'. 
### Agenda

This participatory discussion will be in a workshop format. It will present legal and policy perspectives on the limits to privacy, and the nothing to hide argument, as well as qualitative information on the experiences of human rights defenders and activists affected by this. Then, it will engage participants in unpacking and responding to the 'nothing to hide' argument. It isn't as easy as we think to actually challenge the nothing to hide argument. In past workshops we've found that having people stand up and articulate arguments in favour of privacy makes them think through it more carefully and confront its challenges. So, session participants will be encouraged to do the same through a combination of reflective discussions, and small-group work to develop role play sketches that argue the right to privacy from different perspectives. 
### Participants

With 5 people, we could have a cosy, free-form discussion and role-plays.
With 15, we would do interactive and participatory session with role plays and discussions 
With 50 people, we would have a moderated discussion in a 'TV talk show' style.
### Outcome

It is important, we feel, to bring a  primarily technical community into discussions about law, policy and human rights defence about this topic. This session would be one of the first in a new project around addressing the challenges to human rights defence and activism through the criminalisation of privacy. The session is an opportunity to mainstream the discussion, and raise awareness about how the right to privacy and the use of tools like encryption does not guarantee protection in many parts of the world. The session should help us, and participants, be more informed and reflective about how to address the nothing to hide argument.

**Comment by Melechuga** [comment]
This could be incorporated into the Online Harassment panel discussion.

**Comment by Melechuga** [comment]
Declined
