### ISSUE TITLE
Serving Social Change: Leveraging the internet for the empowerment of social movements.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#236]
**[ Google Spreadsheet Row Number ]** 203
**[ Facilitator ]** Bomani McClendon
### Description

The internet has provided the opportunity for people all over the world to unify and spread a message. This session will be focused on brainstorming how to maximize the power of this connectedness for driving social and political change. We will review a few cases of the how communities on the internet have organized towards making a positive change, and then begin to bring together thoughts and knowledge on the most valuable techniques and online resources for empowering movements.
### Agenda

In order to start piercing the topic, I would like to guide a full group discussion on two case studies dealing with situations in which the web has been used to strengthen the voice of a community seeking change, such as the Spanish Anti-Austerity Movement. These case studies will be international enough to have relevance to people coming from different backgrounds and relationships with the internet. Afterwards, I would like to break the session attendees into smaller groups for discussions and brainstorming on a diverse set of real social/political issues and how movements addressing these problems could utilize the internet. These small groups will then give a brief summary of their discussion turnouts to the rest of the attendees, and give me the written or typed notes from the discussions so that I may amalgamate these into a resource after the session has ended.
### Participants

Initially, I would like to do a full group discussion of two case studies. Another portion of the session would be devoted towards breaking the attendees into groups. With 15 attendees, the small groups would be made of three people. At 50 to 150 attendees, the groups would contain 10 people. These groups can discuss and track the outcomes of their conversations independently, and then share with the larger group after the small group discussion time has finished. This amount of time that each group will have to explain their specific findings will be shortened depending on the amount of groups. 
### Outcome

I would like participants in this sessions to feel more aware of practices that they can utilize to help empower movements that they are passionate about using the web. After the session, the ideas and resources that we discussed can be combined into an open and editable list of resources (technology, examples, concepts, etc).

**Comment by ryanpitts** [comment]
Bomani is part of Knight Lab, and already has travel support to attend MozFest.

**Comment by shaghdoosti** [comment]
Love this! My key feedback is that the case studies should be clear at the top. I'd love to hear about the Spanish Austerity movement. Can we reframe/rename this session as case studies of movements and learnings?
