### ISSUE TITLE
Using Wikidata and Histropedia to visualise UNESCO (and other organisation’s) data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#237]
**[ Google Spreadsheet Row Number ]** 207
**[ Facilitator ]** Navino Evans
### Description

A workshop to learn how data from organisations can be added to Wikidata, queried and visualised with examples using data from UNESCO including World Heritage Sites.
After the workshop, people will:

Know what Wikidata is, its purpose and how it can be used
Understand how to add data to Wikidata 
Understand how to access the data through making queries 
Understand how to use these queries to produce visualisations on Histropedia
### Agenda

The session will primarily be a workshop, with brief presentations to introduce the concepts and tools needed to contribute to Wikidata and create visualisations.

Demonstration of how to add information to Wikidata, and practical session. 
Demonstration of tools used to query the data, and practical session on creating queries from UNESCO data.
Practical session showing people how to make timelines using Histropedia.
Participants make timelines with help from facilitators followed by a show and tell.
The best timelines will feature on a Histropedia blog post about the workshop and be published to the timeline directory.
### Participants

If a large number of people attend, we will:
- Ask other Wikidata experts who are attending Mozfest to support the session
- Possibly leave out one of our activities if more time is needed for each activity

If a small number of people attend, we will:
- Go into more detail during the activities
- Give more direct support to each attendee, enhancing their learning experience.
- incorporate ‘fireside chat’ discussions after activities.
### Outcome

People will be know how add data to Wikidata, query the data, and reuse it in visualisations.

They will hopefully be inspired to try and import other data sets into Wikidata.

**Comment by Saallen** [comment]
cc @Melechuga @ryanpitts

**Comment by Melechuga** [comment]
I think this fits better in the Data & Impact pathway than anything in digital citizenship. Thanks!

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
