### ISSUE TITLE
From Garoa Hacker Clube to Olabi: 5 years of hackerspaces, makerspaces, hardware startups and creative hubs in Brazil

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#238]
**[ Google Spreadsheet Row Number ]** 205
**[ Facilitator ]** Rodrigo Rodrigues da Silva
### Description

The idea of this panel is to share experiences on the creation and sustainability of innovation and community-run spaces like hackerspaces, makerspaces and fablabs, with a special focus on the 3rd world and its specific challenges.

In other words, that means that every participant will be able to learn from others and share their own experiences about innovation/hacking/making community-run spaces from their own perspectives.

A consequence of this is building stronger connections betwwen communities and spaces in the underdeveloped and developing world.
### Agenda

To brake the ice, I will start sharing my own personal and professional experiences lived and observed in the last 5 years in the Brazilian hacker/maker/creative scene. Starting with Garoa Hacker Clube and the House of Digital Culture, many initiatives, both community-lead and entrepreneurial, have anarchically spread all over the country in a really short period of time. Now we are more than 10 active hackerspaces and at the least the same number sums up makerspaces, collective working spaces and fablabs. We will also present several entrepreneurial initiatives, specially on open hardware and free software development, that connect to this network.

The overall format will depend basically on the size of the space and number of people attending (as described below), but in fact I think this session will work better with a small group (not more than 20), as the idea is more "share and hear back" then "tell".
### Participants

With 5 participants, we will grab some coffee or mate, sit around a table, open our laptops and start sharing our experiences and take collaborative notes on a pad.

With 15 participants we will organize in a big circle and then we will go around the circle with each of the participants sharing their own views and/or questions about the subject.

With 50 participants I might speak a bit longer and open up for questions in the end. One alternative would be inviting other people from the GIG network (or whoever feels comfortable to join in) and do a round table, with time for questions in the end.
### Outcome

From previous Mozilla Camps that I have participated in the past I know that the audience is very diversified in geographical terms. That would enable us to straighten the bonds between people and spaces from a south-south perspective, as most of the present connections are either north-north or north-south.

The outcome of a similar session at the Chaos Communication Camp 2015 was extremely positive, and we want to go even further, having more people aboard. And, in the context of the Mozilla Festival, we want to be immersed in discussions about the open web and make sure it is part of the spaces agenda.

**Comment by thornet** [comment]
cc @soapdog

**Comment by soapdog** [comment]
Garoa Hacker Clube work in São Paulo is inspirational. They are awesome! They are what I think when I think of hackerspaces :-) :+1:

**Comment by amirad** [comment]
cc: @amirad

**Comment by thornet** [comment]
cc @Geralbine

**Comment by thornet** [comment]
@Geralbine shall we apply your pathway label here?

**Comment by Saallen** [comment]
To take place within the garbage disposal room within the Garage
