### ISSUE TITLE
Data from Head to Toe

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#239]
**[ Google Spreadsheet Row Number ]** 221
**[ Facilitator ]** Ashley Wu
### Description

This session will allow people to open their minds to how much data is actually around them. In order to work effectively with data (analysis, visualization, scraping, etc), we need to know where to find it and how to get at it first. A fun way to do that is to have people start looking for data about the things or people they see every day or within normal activities. This session will get people in the mindset of looking at the world in terms of interesting data that can be used for learning and storytelling.
### Agenda

After an introduction, I'd show a few examples of data from everyday activities and translate it to 1 or 2 cool ways of telling a story based on the numbers. Then, people would split up into groups of 3 or 4 and come up with a list of 10-15 sets of data, big or small, they could get just from the room (ex. small = demographics of the people, heights, nails painted or not, how many people are chewing gum / bigger = social media likes by type of post, number languages that people speak maybe based on where they come from, etc). We'd share ideas, write them on a large board at the front and bounce ideas/pitches off each other. After that, we'd delve deeper and pull out 3-4 that would make cool data stories that could be presented in the form of a written story or graphic, interactive.
### Participants

This would work really well with any number of people. A smaller crowd of 5-10 would have more opportunity to participate in a second part - discussion of how these small or bigger sets of data would work as legitimate stories. Larger crowds of 25 or more could talk more amongst themselves while I, and/or other facilitators, walk around and gather a cool list to display and we'd have a longer list of ideas with more variety for people to mull over and talk about.
### Outcome

People will hopefully be more aware of the rich (or sometimes silly but interesting) data that can be found around them, start asking questions about their environments, ask why things are and maybe have the mindset and resources to answer those questions. This workshop-style session also allows people to begin getting over their fear of data sets (if they have a fear like I did) and lets people come away with tangible, real story ideas centered around data, which is helpful especially for journalists.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts @erikao

**Comment by ryanpitts** [comment]
Ashley is part of Knight Lab, and already has travel support to attend MozFest.
