### ISSUE TITLE
[Pathway] Games and Understanding 

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#24]
Alternate, entertaining ways of imparting information are invigorating not just for the audience, but also for the journalists who create them. From games that explore topics in the news to folk dances that illustrate computer algorithms, this is a space that's interactive and fun.

Pathway coordinator: Sisi Wei, ProPublica
Twitter handle: @sisiwei

**Comment by Zebetus** [comment]
@EPIKhub I have commented on most of the sessions in this pathway but i think this one could be a really cool one to lead youths into journalism if maybe we had one of the sessions in the youth zone
