### ISSUE TITLE
Do you have what it takes to be an Entrepreneur?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#241]
**[ Google Spreadsheet Row Number ]** 214
**[ Facilitator ]** Aastha Vijay
### Description

*Take up the challenge of starting one's own firm.
*Session on Organisational Behavior, Work Ethics, etc.
- Developing marketing skills, leadership qualities, personality development, confidence boosting.
  *Main role of an Entrepreneur in the Society , why do we need to increase the number of entrepreneurs and what does it take to become one!
  *Advice and suggestions to young entrepreneurs and aspiring entrepreneurs.
### Agenda

*Informative and Interactive session.
*Interactive workshop on: how to solve problems, because that's what entrepreneurs do.
*FAQ's and Q and A session.
### Participants

*A seminar hall would be an appropriate venue for my session as I plan to be the orator for at least  75% of my session.
- Conducting a session with 5 members would be real fun and more interactive as we will share our views and ideas on a personal level.
  *Conducting with 15 and 50 would be more on a professional level.
  I'll make sure it's worth their participation.
### Outcome
- I see that I'd definitely be able to drive more and more of my listeners to take up the challenge of stepping into the world of business.
  *I plan on creating a mailing list and a a group on social media where one can suggest and share inspiring, informative videos, current scenarios of the upcoming market, etc.

**Comment by marcwalsh-zz** [comment]
cc @Melechuga

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by Aastha14** [comment]
Thanks. I have submitted 2 proposals this year. Hoping for a better response.
