### ISSUE TITLE
Hacking on Public Engagement Resources for Fellows

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#243]
**[ Google Spreadsheet Row Number ]** 209
**[ Facilitator ]** Karen Smith
### Description

It can be a little overwhelming to receive an email asking you to give a talk, run a training session, or co-organize a hackathon if you’ve never done it before.  Fellows who collaborate with Mozilla across science, journalism, learning and advocacy need resources to assist them to effectively engage the public in a variety of situations.  This open hack sessions aims to create a space at MozFest to compile and co-create resources to assist Mozilla fellows, as well as other leaders, to engage the public. 
### Agenda

This open hack session will begin with a round of introductions so that participants can learn about the interests of all those who are attending.  The participants will break into small teams to begin to hack together to create resources to assist fellows, and other leaders, to engage with the public.  Prototypes of toolkits will be developed on topics such as “collaborative learning strategies” to use in training sessions or at conferences when fellows are working with various communities and groups.  
### Participants

Varying numbers of participants can be accommodated in this session. With a small group (5-20 people), introductions and work teams can form after everyone introduces themselves.  With a large group of participants (20-50+), introductions and team formation will be handled in sub-groups.  
### Outcome

Resources created during this session will be compiled on etherpads or on the Mozilla Wiki.  The faciliatator can report back to the relevant Mozilla Learning Networks working group or the program managers responsible for various fellowship programs at Mozilla.

**Comment by marcwalsh-zz** [comment]
cc @samueledyson @LindseyFrost @Melechuga @ryanpitts

**Comment by abbycabs** [comment]
cc @acabunoc @kaythaney

**Comment by Melechuga** [comment]
@kaythaney @acabunoc Just wanted to flag that this isn't going to fit within Digital Citizenship.

**Comment by thornet** [comment]
cc @acabunoc @kaythaney @Melechuga @ryanpitts could you confirm the status of this session here and in the schedule spreadsheet? Thank you!

**Comment by Melechuga** [comment]
FYI Karen will be at MozFest. Comment about session not fitting in Digital Citizenship still stands.

**Comment by thornet** [comment]
Unfortunately this session is not taking place, but Karen will be at Mozfest and involved in other things. Woot!
