### ISSUE TITLE
Connecting the BioWeb: Mapping Earth's biggest challenges with an open online ecosystem.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#244]
**[ Google Spreadsheet Row Number ]** 215
**[ Facilitator ]** Jacob Caggiano
### Description

There's been a lot of new innovation in open source mapping tools lately. We'll show you how to roll your own crowdmap with free software and strategize your tech stack. We'll also share knowledge to organize, engage, and sustain web literacy for communities most impacted by toxic pollution.

---

Questions we'll be addressing:

1) What are the advantages and disadvantages to various technologies for mapping environmental issues?

2) How does one collect, organize, and manage various data types (geospatial, government, community driven)

3) How do we grow the coalition of community groups and open technologists working for sustainability and environmental health on a global scale.

Through these questions and experiences we will walk away with a working knowledge of collective storytelling for bioregions under ecological crisis bridged with the ecosystem of the open web.
### Agenda

This is a workshop grounded in our personal experience creating community maps to address socio-environmental conflicts. We will do a brief introduction about our stories and emerging success in the most polluted areas of Buenos Aires & Seattle. We will then share our code and curriculum and help others who want to fork, adapt, and localize for communities affected by poor environmental health. 

We hope to bridge together community organizers and open technologists and will have activities designed to accommodate various skill levels.

We would like to continue the process of building "standards" for socio-environmental conflicts across the open web ecosystem. These standards will enable the production of web based resources to shape agendas for future collaborations and emerging networks.
### Participants

With 5 people we can hack prototypes together and if there's interest, have a more focused discussion on geojournalism and bridging environmental standards with open web standards.

With 15-50 we will first do a rapid fire survey to organize folks based on geographic region of interest and specific technology they're experienced with or want to learn. We can then break into working groups based on those interests and hack prototypes.
### Outcome

Our goal is to develop a methodology and to prototype projects for communities who want to map their polluted environments. We already have a growing library of open source software and community groups doing this work in several hotspots around the world. We are determined to actively grow and sustain this network after the festival to bring more troubled bioregions into the mix and develop core standards for achieving success.

We also have a goal of building a strong foundation of environmental education through web literacy. We believe that organizing toward a healthy and sustainable ecosystem on planet Earth is analogous to building a free and open information ecology online.

**Comment by arlissc** [comment]
@cubicgarden - this session will not be able to make it to MozFest this year (financial constraints) - not sure where this impacts your pathway but wanted to give a heads up

**Comment by thornet** [comment]
Closing this since the facilitator is not coming.
