### ISSUE TITLE
Mozilla Awareness

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#245]
**[ Google Spreadsheet Row Number ]** 220
**[ Facilitator ]** Mijanur Rahman Rayhan Mijanur
### Description

Mozilla Awareness and Privacy and Security using Firefox
### Agenda

1)What is online privacy and security?
2) What is data privacy and why data privacy is important?
3)HTTPS and SSL description and how it work?
4)What is DuckDuckGo and why it is best secure search engine?
5)A brief description about DuckDuckGo.
6)Why firefox browser is best secure web browser?
7)What is firefox private browsing?
8)Uses of firefox Permissions Manager.
9)Session On Lightbeam addon for Firefox and how it works.
10)What is Thunderbird and why its best secure email application ?
11)Tracking Protection on Firefox.
### Participants

I ll introduce Firefox privacy with them. Will show them why privacy matters and why we want to need secure cyber life. 
### Outcome

Participants will aware about privacy and they'll start using Lightbeam and DuckDuckGo.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
