### ISSUE TITLE
Hacking for Journalists 101/Journalism for Hackers 101

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#246]
**[ Google Spreadsheet Row Number ]** 202
**[ Facilitator ]** Samantha Sunne, Judith Morales
### Description

Participants will leave this session with a story pitch in hand, using data we will locate, scrape and analyze during the session. MozFest 2015 is focused on helping everyone – especially younger users – learn to use the Web for journalism. As a recent journalism grad myself, I’ve seen many younger journalists embrace Internet tools like multimedia and social media, but avoid developer tools and source code. Discovering the Web that exists behind their screens would help journalists, both young and old, realize that websites and data can and should be vetted and investigated, just like human sources. Non-journalists would also benefit from this session, because it would help them acquire and distribute data for a civic hacking purpose. The goal is to not just learn how to get off the Web, but do it with a journalistic mindset: what information is important, and how will it benefit my community?
### Agenda

In this workshop, each attendee will actively participate on a desktop computer or personal laptop. While part of the session will be my own demonstrations of web browsers, source code and APIs, participants will do their own scraping and analysis. The actual tools and techniques we cover will be similar to a tutorial I have done multiple times at IRE and NICAR conferences on investigating data and metadata online. We will all scrape a national dataset so that each participant can then localize it to their school or hometown. The end goal is for each participant to walk out with an actionable story pitch tailored for their news outlet or civic hacking community.
### Participants

While a lower number of attendees would allow me to offer more substantial individual help, dozens of attendees could follow along as we scrape a dataset together. As a backup, we would use a national data set that has already been cleaned and published. I plan on using ICIJ’s offshore leaks data if we have a lot of international attendees, or a data set from the Bureau for Investigative Journalism if most attendees are from the UK. Because news outlets opened this data and published it themselves, using it will demonstrate to participants that they have both the ability to discover the open Web and the responsibility to help create it.
### Outcome

Participants will learn techniques for manipulating code and web browsers, but more importantly, understand some of the theories and structures behind the Web. It’s important that journalists, and young web users in general, understand that they can investigate and interrogate websites and data, just as they could with human sources, and that you don’t need to be a hacker or genius to do it. Because each participant will walk out of the session having at least a basic story pitch, I will ask each to share the story they end up publishing. I also believe continuing support is vital for new learners to keep their momentum, so I plan to connect each participant with a local support group such as PyJournos or Hacks/Hackers as well as offer my own continuing support.

**Comment by evaconstantaras** [comment]
Better for Tools, Analysis, & Storytelling track.

**Comment by ryanpitts** [comment]
Samantha is based in London, so travel would not be an issue.

**Comment by ryanpitts** [comment]
Journalism is accepting this session.
