### ISSUE TITLE
Fostering inclusivity and diversity in the Technology space

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#247]
Google Spreadsheet Row Number: 208

Facilitator:

name: Alifiyah  Ganijee
twitter: @alifyaganijee
organization: Mozilla Mombasa

Description:

The Sessions’ goal is to learn the strategy and approach of how women are represented in the developed countries and how the blueprint can be used to make a ground plan for the change process in developing countries.This will be an interactive activity that will divide participants in groups of 3-4 people, each team will be expected to brainstorm and note down the challenges, achievements, impacts, opportunities and the potential of women in technology and the workforce scenario

**Comment by jvallera** [comment]
@simonaramkisson @jvallera

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin interesting angle

**Comment by emmairwin** [comment]
Hope to connect with Larissa who is also doing a diversity session as part of coaching sessions

**Comment by simonaramkisson** [comment]
**[ Google Spreadsheet Row Number ]** 208
**[ Facilitator ]** Alifiyah  Ganijee

### Description

This will be an interactive activity that will divide participants in groups of 3-4 people, each team will be expected to brainstorm and note down the challenges, achievements, impacts, opportunities and the potential of women in technology and the workforce scenario. Each team will be discussing different factors, all which are key in fostering inclusivity and diversity: (Culture, Geographical location (Developed Vs Developing countries), Age, Education amongst other)

The Sessions’ goal is to learn the strategy and approach of how women are represented in the developed countries and how the blueprint can be used to make a ground plan for the change process in developing countries.

### Agenda

Agenda:
Introductions
Overview of session
Teams break-out
Presentation
Chart out the strategy model based on collective discussions

### Participants

5 Participants
In a case of 5 participants, we shall form teams of 2 people and the same format will be followed (as stated in the agenda)

15 Participants
In case of 15 participants, we shall form teams of 3 people per team and the same format will be followed (as stated in the agenda)

50 participants
In case of 50 participants, we shall form teams of 5 people per team and the same format will be followed (as stated in the agenda)

### Outcome

The learning and activities of the session will be used to enhance and improve participation of females within respective communities and to apply the best practices of community management and leadership. Moving forward, participants may communicate and share their feedback of what worked and what did not work and how to improve on further. This will result in increased female participation and motivate more girls in technology thus ensuring sustainable communities.
