### ISSUE TITLE
Open Web Apps for Android

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#248]
**[ Google Spreadsheet Row Number ]** 210
**[ Facilitator ]** Ashish Mishra
### Description

This session will allow people to make android apps, they will learn how to make android apps in easy steps using android studio or eclipse. They will also learn about Open Web Apps for Android. You don't need any knowledge of Android development, or to take any extra development steps, to use Open Web Apps for Android: you simply select the option for distribution to Firefox Mobile or Firefox Tablet when submitting your apps to the Firefox Marketplace.
### Agenda
1. Introduction to Android and Firefox Marketplace.
2. Environment setup for development.
3. Hello world in android & firefox OS.
4. Getting started with Intents, Content Providers, Services, Broadcast Receivers etc.
5. Android Advance Concepts.
6. One Final Project.
### Participants
1. If  we had 5 participants then everyone will work together & We'll teach them individually.
2. If we had 15 participants then we'll divided them in 3 groups.
3. If we had 50 participants then we'll the entire session will be conducted through a projector and after the completion of the course they have to create one project within a day.
### Outcome

After the session participants will able to make android and firefox apps. They will learn something amazing and productive. In future they can carry on the learning and activities forward by going though our courses and via online courses and will able to contribute to mozilla as well as in android.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin re: creating teaching materials like this for others to use in their communities
