### ISSUE TITLE
Engaging Stakeholders on Net Neutrality & Impact on Youth Start-Ups /Innovation in Developing Countries 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#249]
**[ Google Spreadsheet Row Number ]** 213
**[ Facilitator ]** Kudzai M Mubaiwa
### Description

Discuss and learn the definitions of net neutrality, the most popular public outcries and perspectives, understand the experiences of different countries and especially draw parallels and/or distinctions between the developing country experience and the developed country experience. 

Discover its’ impact on start-ups and web innovation. 

Share methodology for identifying and engaging critical stakeholders for a nation with a view to finding balance and mapping a way forward that does not infringe on internet governance guidelines and rights. 

Raise awareness on available resources and support groups in the internet access space. 
### Agenda

We will format it as a fireside chat where the facilitator/s will give key insights and experiences from the public domain and encourage dialogue, whilst noting submissions on a screen. These will be collated and shared online as a blogpost or a wiki before the festival ends and conversation can continue via social media particularly twitter. 
### Participants

With 5 we can explore detailed experiences from their geographical locations – and it can work whether they have no idea what net neutrality is or if they do. We will have prompts that can assist us to extract the position in their country of origin and map out how each represented region is placed. 

With 15 we can divide in 5 groups of 3 and ask attendees to start with just finding perspectives from Africa, Americas, Europe, Asia and the Pacific in a desktop search exercise – inside 10 minutes. We would then carry on the dialogue from the findings and triangulate them. 

With 50 we can proceed with the first indicated full fireside chat with facilitator prompting conversation points and recording on a screen then sharing the collated material afterwards. 
### Outcome

Outcomes are: 
-   Good understanding of net neutrality from a global perspective by participants and appreciation of the impact on start-ups and innovations 
-   Knowledge of tools, methodologies and hacks for stimulating engagement at national level and links to existing support systems / platforms
  Way forward: 
-   Continue to build on the wiki/blogposts
-   Commitment to sharing a brief report / situation analysis 6 months / 12 months from the festival
-   Creation of a social media platform to share resources / events / material

**Comment by Melechuga** [comment]
@Geralbine Can we combine this with https://github.com/mozilla/mozfest-program/issues/133? They can work together to focus on the global south, using India as a case study if relevant.

**Comment by Geralbine** [comment]
@Melechuga  I tihnk that would be an interesting approach - let's talk it through tomorrow?
