### ISSUE TITLE
How, when and why to use encryption

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#25]
- faciliators names

*using tools and projects such as Let's Encrypt (https://letsencrypt.org/), HTTPS campaign for libraries, HTTPS Everywhere, https://www.eff.org/encrypt-the-web.  

Learn from examples, such as data collection forms on the web that don't use encryption and what can happen to your data if you fill them out without encryption.  What are the benefits of using encrypted communications such as encrypted email and text (such as Silent Circle or Wickr).

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

Is this a real session @Saallen?

**Comment by Saallen** [comment]
@Melechuga this is a session outline as submitted on a pathway by @mixedpuppy

**Comment by Melechuga** [comment]
Placeholder.
