### ISSUE TITLE
Get your hand dirty with webmaker app.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#250]
**[ Google Spreadsheet Row Number ]** 216
**[ Facilitator ]** Gautam  Sharma
### Description

In this session people will make those things in which they are best. The session will focus on bring out the talent of the particular person and that person will maker something using the webmaker app. This will help in fulfilling our motive of collaborative learning and web-literacy. This will help other people to learn a particular talent and sharing the knowledge. 
### Agenda

The session will start with a basic understanding of Mozilla and open source project. Then the details overview of the webmaker will be given to participants. Now to make the session interactive we will be asking people about their interest and special talent of a particular person after listening all the participants we will be telling them to make something related to their talent so that it will help others learn that thing or help other to know about it. As the participants will be doing things of their interest this will make the whole session interesting and joyful. During the session we will be having some interesting activities which will help participants in understanding about open source projects.
### Participants

The session is fully interactive so if we have varying number of participants it will not affect the session. As we will divide participants with similar interest in a single group, Which will help them in collaborative learning and making something awesome. We will be hosting some interesting activities so the people can understand about the Open source project in a interesting and joyful way.  
### Outcome

The outcome of the session will be that the people with special talent will be able to show case their talent to others on web platform with the help of our awesome webmaker app. During the session we will make sure that all the participants who need help will be get help in a right manner. After the session we will host regular meet ups with participants and ask them about the experiences of the session and how others are responding to their makes. We will also try to connect to other people who missed our session and help them in showcasing their talent with the help of webmaker app and web-literacy.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
