### ISSUE TITLE
Why open source? 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#251]
**[ Google Spreadsheet Row Number ]** 218
**[ Facilitator ]** Aastha Vijay
### Description

*what is open sourcing? 
*Why open source? Advantages of open sourcing.

about mozilla:
*More on how mozilla contributes to open source and how does it help?
*How is mozilla withstanding the competition with many other profitable and non profitable organisations in today's market? 
### Agenda

Informative and interactive session.
Q & A session.
Sharing of personal experiences in open sourcing by the participants themselves.
Moreover its an attempt to spread awareness about Mozilla and it's success stories, and thus encourage participants into open sourcing and contribute to mozilla.
### Participants

Information sharing via an auditorium would be a great alternative.
For any number of participants, it will be a really descriptive and informative session.  
### Outcome

Mailing list
Meets on IRC 
Page or a group on any social media
Driving most of them into programme's like FSA, SuMo, ReMo, etc. 
Contribute to the technical team as well as volunteer.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
