### ISSUE TITLE
Create your own projection mapping with Parapara Animation

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#252]
**[ Google Spreadsheet Row Number ]** 227
**[ Facilitator ]** Noriatsu Kudo
### Description

This session provides a projection mapping workshop. In the workshop, participants will make objects with paper clay and draw animation to project on them. Animation will be made with customized version of parapara animation (http://parapara.mozlabs.jp/). Through the workshop, participants will learn the mechanism of how animation and projection mappings are made and by making their own. The experience are of making objects are related to making 3D items on computers. Also, mapping animation on their objects are very first stage of mixing computing world into the real world. The goal of this session is participants to feel and understand that the Web can be a part of our real life, and computers are the tools to make it happen.
Also, the activity is designed by university students for teenager to learn IT technology. Target age and level of skill for this activity is elementary school students or beginners. 
### Agenda

First of all, participants will watch the sample projection mapping and learn the mechanism. Then participants will start design and make their own. This activity will be a personal activity. Therefore, participants can work with their own pace. 
The making process is divided into 4 steps. First step is making story and plan on paper. Second step is create objects with paper clay. Third step is draw animation on tablet with parapara animation. Final step is project animation on the paper clay object and adjustment. After the creation, participants are welcome to shoot movie of their work.
Over all experience will be about 30 minutes.

Example of MAKEs
・ https://www.youtube.com/watch?v=Aamj5Xw4uPI
・ https://www.youtube.com/watch?v=nx_xSvFSDUU
### Participants

It is depends on the space and number of facilitators and projectors. However from the previous experience in Mozfest, our workshop is designed for max of 5 participants. If more people are coming to the space, they can see and discuss with staff but not the one to make. We will give students (elementary to teenagers) the priority to make. For educators and parents, we will have discussion with them about the system, teaching plan etc..
### Outcome

This session is designed and organized by a Japanese community group called “Co-mozilla lab”(http://en.mozillafactory.org/post/108725520614/co-mozilla-lab). Most of the participants in the community are university students and operation of the community is . Therefore, experience to held workshop in other country is important. Also, discussion with other exhibitors, researchers, educators gives a lot of feedback. It will make the community more active.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016

**Comment by EPIKhub** [comment]
@Melechuga as you suggest re-opened and accepted cc/@Saallen

**Comment by Melechuga** [comment]
Thanks @EPIKhub!!

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
