### ISSUE TITLE
Dear n00b

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#253]
**[ Google Spreadsheet Row Number ]** 224
**[ Facilitator ]** Emily Withrow
### Description

The web was built by people, in all its messy, constantly evolving glory. "Dear n00b" aims to give that community a friendly, welcoming face by pulling together seasoned professionals to record video notes for beginners. The session aims to personalize open web technologies and make it more accessible by showing off the people who work with it—not by showing off the amazing things they've built, but by celebrating the awkward stages that brought them there.
### Agenda

We'll put together a series of prompts for participants to answer—during the first part of the session, we'll work with participants (beginners and experienced alike) to come up with a meaningful list of questions that would highlight important learning experiences, epic failures, most embarrassing online moments, early victories, inclusive advice, etc. We'll then come up with some kind of tagline for the video: like "We are the web," but maybe a reference fresher than 1985. Finally, we'll set to work recording the testimonials.
### Participants

One way to scale this is to determine whether or not we do the recording during the session. With a small number, we could do it on the spot; with a larger number, we could outsource the recording to an open booth or similar.
### Outcome

After the festival, we commit to editing and producing this a series of videos that would be published to YouTube and could live on the learn.knightlab.com site. We would continue to work with the material on an ongoing basis, producing additional videos throughout the year.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by ryanpitts** [comment]
Emily is part of Knight Lab, and already has travel support to attend MozFest.

**Comment by EPIKhub** [comment]
I like the human aspect of this session and think it will resonate really well with our persona's

**Comment by EPIKhub** [comment]
@Saallen @chadsansing this is a great visual session, Emily really has a clear idea of what she needs and wants from this, which spaces do you feel it would best fit?

**Comment by EPIKhub** [comment]
@simonaramkisson this is a really strong piece and Emily is very passionate about woman in Tech, I think this might well fit well with your other selections @jvallera

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
