### ISSUE TITLE
    Starting small, but starting right - exploring the minimum needed for a successful website

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#255]
**[ Google Spreadsheet Row Number ]** 223
**[ Facilitator ]** Majken Connor
### Description

 So you want to create a website, but you're overwhelmed on what to include. Let's talk about how getting back to basics is the key to designing a successful, and manageable, web presence. We want to exchange ideas on identifying the right goals for your website, the basic elements needed to reach those goals and how to use data to know when it's working.
### Agenda

The session is designed to include free-form participation (eg everyone just tosses ideas onto post-its at once), group discussion, and creative exercises (eg experimenting with lego). We will: 1) establish clarity on the session's scope and purpose 2) explore the benefit of using personas and goals as a tool 3) brainstorm on the problems that might be encountered and solutions for overcoming them 4) discuss using data and metrics to measure your success 5) compile our results into a hackable document that can be used as a guide/reference
### Participants

Whether a section will be free-form or group discussion will depend on the size of the overall group ensuring both types of participation are always included. A longer description is available, but won't fit in the space provided here!
### Outcome

```
Our participants will be able to use what they learned in the session, and from the hackable guide to maintain more efficient and more effective websites for their projects and communities. They will be able to decide, for example, if they really need a blog, or if it will just create unnecessary work to maintain. We will use the learnings from the session to design a starter template for Mozilla Community Sites as they're just getting off the ground. We also have old community sites that are no longer being maintained that we'd like to replace with something static, but useful, rather than taking them down altogether.
```

**Comment by marcwalsh-zz** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
