### ISSUE TITLE
GitHub 101

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#256]
**[ Google Spreadsheet Row Number ]** 226
**[ Facilitator ]** Jessica Lord
### Description

This session introduces newcomers to the essentials of Git and GitHub. Our goal is to give everyone an approachable and hands on experience with the tools as well as the common practices and social nuances in open source, gaining confidence to get involved themselves.
### Agenda

This session is a workshop in which participants will be guided to learn-by-doing the fundamentals on GitHub. They’ll create accounts, create new repositories, branches and pull requests. We’ll cover the basics of the GitHub Flow and best practices around open source contributions. All participants will leave with a merged Pull Request.
### Participants

Our workshop scales to work for both small and large groups. Independent learners can tackle the content challenges at their own pace, while other people can team up together or in small groups with a mentor.
### Outcome

Participants will leave the session empowered with skills to start contributing to open source. The jargon will be defined and new concepts made clear. Furthermore the concept of contributing in the open will be shown to not to be an anxiety-riddled-it-must-be-perfect experience—all shared work is valuable.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin jessica's session on this will probably be a great entry point . Jessica teaches , and works at Github

**Comment by emmairwin** [comment]
@ryanpitts we have Jess in our space for another Github session, wondering if we can have this one as well (in our space).  Fits participation very well.

**Comment by ryanpitts** [comment]
@emmairwin I think you'll want to check in with @acabunoc and/or @kaythaney here -- this session is part of a collaborative pathway between Journalism and Science, but was officially accepted by Science team and would be hosted there at this point.

**Comment by emmairwin** [comment]
@ryanpitts ok  as this is part of our pathway for learning experiences I'm interested in the cross over there as well.

**Comment by emmairwin** [comment]
Opting for :  https://github.com/mozilla/mozfest-program/issues/325  instead as a github participatory session that will be run in our space.   sorry for lat minute, assuming doesn't affect anything for Jessica or other groups.  Let me know if that's not the case.  thanks

**Comment by abbycabs** [comment]
@emmairwin -- I'm happy either way! This is meant to be held join between Journalism and Science right now, happy to include Participation :smile:

**Comment by emmairwin** [comment]
Thanks Abby.  I think this is the right choice for our space right now, although when we are doing coaching sessions for our leadership cohort, this may get included on a personal pathway

**Comment by arlissc** [comment]
@emmairwin -- we have Jess scheduled for this session on Saturday (Block 1 & possibly Block 2).  This is the first session for us in the "Tools and Analysis" pathway.  Does that conflict with your scheduling ?

**Comment by emmairwin** [comment]
Spoke with Jess today, we have her on block 2 Saturday.  All is well if you
stick to block 1

On Tue, Oct 27, 2015 at 11:05 AM, Arliss Collins notifications@github.com
wrote:

> @emmairwin https://github.com/emmairwin -- we have Jess scheduled for
> this session on Saturday (Block 1 & possibly Block 2). This is the first
> session for us in the "Tools and Analysis" pathway. Does that conflict with
> your scheduling ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/256#issuecomment-151589869
> .

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Mentor

**Comment by emmairwin** [comment]
sorry Block 2 Saturday

On Tue, Oct 27, 2015 at 11:05 AM, Arliss Collins notifications@github.com
wrote:

> @emmairwin https://github.com/emmairwin -- we have Jess scheduled for
> this session on Saturday (Block 1 & possibly Block 2). This is the first
> session for us in the "Tools and Analysis" pathway. Does that conflict with
> your scheduling ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/256#issuecomment-151589869
> .

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Mentor

**Comment by abbycabs** [comment]
Hey Emma! We gave her block 1 & 2 on Saturday (2 block long session)

**Comment by abbycabs** [comment]
Our schedule (for reference):
https://www.mozillascience.org/mozfest-2015

**Comment by emmairwin** [comment]
@acabunoc that works - she is in our afternoon block.  our schedule:  https://docs.google.com/spreadsheets/d/1Em8vJh1WFKhNUUbaRjTgAN3jYU7TwHyABmK5nab6mCY/edit#gid=1849284233   though we need to beautify it now I've seen yours.

**Comment by abbycabs** [comment]
Ah, all is good :) block naming is confusing sometimes!
