### ISSUE TITLE
Self-publishing on the web - how to host your own website

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#257]
**[ Google Spreadsheet Row Number ]** 225
**[ Facilitator ]** Tanner Filip
### Description

```
Just like artists gain greater control over their works through self-publishing, our session will teach participants how to self-publish on the web. We will do this by teaching them to host their own web content and applications, in this case, WordPress, using basic operations skills, alongside the importance of security for privacy.
```
### Agenda

In this workshop, participants will learn the basics of hosting websites while walking through creation of their own self-hosted WordPress blog. We will start with the basics of the Linux command line and security. We will then apply that knowledge to configure FOSS software on Linux in preparation for installing the server software. We will then guide them through the fundamentals of configuring nginx/MySQL so that they can experiment, with our support, on hosting WordPress alongside static content. They will then walk through how to make changes to their site, emphasizing the importance of their freedom to hack and remix FOSS tools. Throughout the session, participants will be encouraged to support each other and ask questions. With extra time, we can allow more experimentation while still completing the WordPress set-up by the end of the session.
### Participants

 Ideally people will be grouped into 2s and 3s sharing one device, pairing up those with more experience with those who are new, and so everyone can still see the screen they're working on. Working in groups also allows us to teach how to host more than one site on the same server, which is a common real-world experience, and emphasize that it is normal to learn from others when configuring a website. Everybody will be encouraged to teach, and learn from, each other, not just their group members.
### Outcome

  Our participants should take away at least an understanding of why self-publishing is beneficial and that it's possible! They should also have a good grasp of the basics of how websites are hosted, and feel empowered to choose to host their websites themselves. This session also supports Community Ops and Youth's efforts in building an Ops curriculum. We will review what worked and what didn't in the session, including feedback from participants, and invite those interested to help us build the curriculum.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016

**Comment by Saallen** [comment]
@EPIKhub do you have space for this session in your area?

**Comment by thornet** [comment]
cc @EPIKhub wha's the status of this session? Is it taking place?

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
