### ISSUE TITLE
Make and discuss WoT with CHIRIMEN - Moz Open Hard Project -

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#258]
**[ Google Spreadsheet Row Number ]** 228
**[ Facilitator ]** Noriatsu Kudo
### Description

CHIRIMEN is a full open source hardware with software to control I2C and GPIO devices from the Web. It is designed for Web designers to extend their creativity to outside the screen (to real worl) Last year, the team had an ideathon at the Mozilla festival to discuss specification and architecture. This year, we would like to show several manufacturing sample boards at the session. Those are functional and participants can touch and try the WoT world at the booth. 
Also, we would like to have a hands on session 2 or 3 times a day during the festival. In the hands on, participants will design and develop WoT application with CHIRIMEN. The session’s goal is to have a discussion with developers. Since CHIRIMEN’s software is under development, we are expecting suggestion from hackers to improve quality, discussion about standardization, and start collaborating with new contributors.
### Agenda

Touch and try session will be exhibition style. Participants are welcome to stop by any time to see the demo anytime. There will be a demo staff showing CHIRIMEN and the demo application. Participants can touch the sensor and make small change on the application.
At the hands on session, instructor will talk about development environment and architecture of CHIRIMEN environment first (10 minutes). After that, participants can create WoT application using CHIRIMEN with sensors and actuators (30 minutes). Participants will show their activities to others and have discussion about development environment (20 minutes). All the resource required for development is provided by instructor. 
### Participants

Because of limited equipment, hands on session are targeting about 5 participants for each session. However touch and try is exhibition style, able to provide demo for a lot of people all the time.
To fill the gap between the hands on session and exhibition, we would try to have small ideathon to have more communication with participants. 
### Outcome

We are expecting feedback from participants. Both hardware and software are still under development phase, feedback from our community is very important. Also, we need more contributor for this project to make the technology standardized. At the festival, there will be a lot of people who has experience on that, hackers who has interest on WoT, and a lot of people who is working on related area. We are looking forward to start working with them to make CHIRIME community bigger and stronger.

Project web page
http://mozopenhard.mozillafactory.org/

**Comment by soapdog** [comment]
cc @soapdog -- I believe this session has a lot of potential. Currently the WoT work being done with CHIRIMEN by Mozilla Japan is the best candidate we have for a platform for IoT under our control. This could be used by MLN for technology discovery activities in Clubs and Hives in the future. I see power here!

**Comment by soapdog** [comment]
cc @geroter

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
