### ISSUE TITLE
Publishing and Hosting on GitHub

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#259]
**[ Google Spreadsheet Row Number ]** 231
**[ Facilitator ]** Jessica Lord
### Description

This session shares all the ways in which you can utilize GitHub’s free hosting for all repositories and accounts. Attendees will learn how to set up static websites and blogs for their projects or documentation.
### Agenda

This session is a workshop and will cover the basics of creating web pages with GitHub Pages in a few ways: single page sites, Jekyll or other static site generators, and forking other pages. Participants will be guided through creating their own Jekyll site.
### Participants

Our workshop scales to work for both small and large groups. Independent learners can tackle the content at their own pace, while other people can team up together or in small groups with a mentor.
### Outcome

Participants will leave the workshop with new resources for communicating their projects and furthering their impact. We hope, too, to see the ecosystem around documentation and fork-able web pages grow.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by soapdog** [comment]
cc @soapdog this is interesting and relevant to LD since it empowers anyone to put their voice online...

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin community edu platform is built on jekyll / p2pu course in a box, would be a good challange for participation tech perhaps. Also Jess works for Github so lots of opportunity for questions.
