### ISSUE TITLE
Open Cosmics: cosmic-ray physics for everyone

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#260]
**[ Google Spreadsheet Row Number ]** 249
**[ Facilitator ]** Gabriella Azzopardi
### Description

The main goals of our session would be:
1)  Learning about cosmic rays, their importance and devices used to detect them.
2)  Learning about the grid and it’s significance.
3)  Open Cosmics Data Format.

These will include:
1) Short description on particle physics and cosmic rays and a further description on the devices used for detecting cosmic rays, namely Cloud Chambers and Cosmic Pi, accompanied by videos and images taken first hand.
2) Introduction to Open Cosmics and technologies used for our grid of cosmic devices.
3) Introducing the Open Cosmics Data Format and the NASA FITS format.
4) Introduction to CrowdCrafting.
5) Tutorial on contributing to our project on CrowdCrafting.

Take Away: Contribution to a citizen science project, knowledge about Open Cosmics and cosmic rays.

Bonus Take Away: Access to the Grid, knowledge and technical know-how of extracting useful data from videos captured by cloud chambers and other devices.
### Agenda

The session will be in the form of a workshop, where there will be:
1) Short description on particle physics and cosmic rays.
2) Introduction to Open Cosmics, including but not limited to:
    a) DIY Cosmic device
    b) The Grid
    c) Technologies used for our grid of cosmic devices
3) Brief discussion about NASA FITS and why we use it.
4) CrowdCrafting:
    a) Introduction to CrowdCrafting. 
    b) CrowdCrafting as an educational platform: 
        1. Participants will be shown images of different particle tracks and will be asked to distinguish between the tracks through CrowdCrafting platform.
    c) How CrowdCrafting is helpful to this project. 

Take Away: Knowledge about Open Cosmics and contribution to the project.
### Participants

The session will be about teaching participants about cosmic ray physics and encouraging them to contribute to it. Tutorials and videos will be prepared explaining how to use all aspects of the application, irrespective of the number of participants. With less participants, it would be possible to give more individual attention and the session can be more interactive instead of following an agenda, but even with more people we can still strive towards that aim. 

Easy paced hands on about image analysis will invite many collaborators. The hands-on part of this session will not be very demanding making it straightforward for groups to follow, no matter the size. More participants would result in a larger contribution to our project on CrowdCrafting, resulting in more people being able to access the Grid and contribute to it. 
### Outcome

After the session, participants will be able to:
    1) Use our application from home and be able to access cosmic ray detectors around the world and view the data whenever they please.
    2) Contribute to other CrowdCrafting projects as well as invite others to contribute to Open Cosmics.
    3) Contribute towards the expansion of Open Cosmics grid by collaborating with other detectors. We hope to turn Open Cosmics into a Citizens Science project.
    4) Take hands-on activities home: 
        a) Learn about what goes on in the cosmic ray detectors like cloud chambers and be able to visualize it.
        b) Understand image analysis and possibly try to apply it from the raw videos of the cloud chamber. (Detailed methods will be provided in the session).

**Comment by marcwalsh-zz** [comment]
cc @kaythaney

**Comment by abbycabs** [comment]
This group will be in our Open Research Accelerator
