### ISSUE TITLE
Tools for growing an inclusive diverse project

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#261]
**[ Google Spreadsheet Row Number ]** 222
**[ Facilitator ]** Larissa Brown Shapiro
### Description

This session will provide resources, recommendations, and tools, to build foundations for inclusion and diversity in your project, team, group, club, or class, and to grow participation from diverse voices.  Attention will be paid to how to understand and work on specific issues including unconscious bias, working as an ally (or needing allies), impostor syndrome, intersectionality, and more.
### Agenda

This will be a participatory workshop including:

Overview of key concepts, including Unconscious Bias, how to be an ally, the role of mentoring and outreach, what intersectionality is, what kind of metrics work for diversity  and how to keep them, and more

Practice exercises and activities to do with groups you work with, including working through the DICE workshop (see: https://github.com/lsblakk/dice-workshop), use of other interactive activities, and discussion of open source curriculum available for unconscious bias, allies, and impostor syndrome workshops (see: http://geekfeminism.wikia.com/wiki/Allies_training and https://adainitiative.org/what-we-do/impostor-syndrome-training/.

Review of resources, including books, courses, further development for teams and groups

Extensive discussion and action planning
### Participants

If we have 5 participants this will be an in depth action planning and design session, where everyone will go through their plans together as an interactive team and co-design. We will also have time, with a smaller group, to work through specific concerns and situations and brainstorm how to build inclusion and diversity into our programs together.

If we have 15 people, we'll do small groups with the same goals. With a very large group, I'd also ask for facilitators to work with parts of the room (those will be named in advance, in the event we need them)
### Outcome

The central idea is that everyone in the workshop will leave with an action plan for concrete steps they can take to make their group/project/class/team/community more inclusive. 

These plans will include both specific actions they can take right away (curriculum to use, activities to do) and resources for further development. We also will seek to build an online connection so we can share successes and learnings after the festival and stay in touch.

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter
