### ISSUE TITLE
Empowering the next billion......

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#262]
**[ Google Spreadsheet Row Number ]** 237
**[ Facilitator ]** Akarsh Sanghi
### Description

This session is aimed to spark a discussion and generate ideas amongst the participants on the power of mobile web and how free and open internet has resulted in a massive change of society in one of the biggest democracies of the world, i.e. India. Taking inspiration from the 2014 General Elections of India, this session would explore how can we empower billions of more people to come online and have their voices heard in different parts of the world. Through this session people would be exposed to the intricacies of how an open web can impact different segments of society and therefor the participants would then engage in hashing-out/brainstorming newer ideas on how different problems can be solved that plague our society in a big way. 
### Agenda

The session will be conducted as a mix of a workshop and a fireside chat. The tentative agenda can be as follows:

->Introduce the topic and co-create the brief with the participants
->Break-out into teams
->Brainstorm ideas
->Provide feedback to different teams on their ideas
->Final presentation of all ideas amongst the group
->Discuss/debate the ideas and their impact in the real world as a fireside chat

P.S. (All the materials required to conduct this session would be provided by the facilitator itself)
### Participants

The ideal number of participants for this session would be around 15-20. Team size can vary between 3-4 members per team depending on the number of participants. 
### Outcome

The outcomes of this session would be to make people aware of the power of a free and open internet in the world. The ideas which the participants will develop can be taken forward as individual initiatives in their own countries, cities, regions etc. The participants can also carry forward the ideas by conducting similar sessions on their own in different regions of the world. In this way the message we are trying to impart can reach a larger audience.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
