### ISSUE TITLE
Cyberspace Gods -design a digital privacy game with Open Source 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#263]
**[ Google Spreadsheet Row Number ]** 241
**[ Facilitator ]** Eva Pascoe
### Description

Co-create a game about the world where Digital Rights for all, strong encryption and our privacy protection is not just a dreamed-up Utopia but a legal reality. What our Internet would look like when we hold all rights to our personal digital data? We will use Twine and Open Source forum  to create a collaborative Bill writing game and give you tools you can use for your own Hack The Bill digital activism. Based on our House of Commons experiences of collaborating on games for digital activism, we will share the tips and tech for making change and examine Open Source game platforms  as best practice for collaborative games action for successful campaigns.
### Agenda

You are invited to a game workshop, where our group will play Cyberspace Gods. Imagine that the Internet is only just starting and design a quest where the players need to overcome the obstacles,  fight privacy invaders, duck Venture Capital Dragons,  duel with cookies and AI Machine Learning demons using Open Source tools to reach the destination of Digital Rights for All Utopia. Each of the players will have a 'privacy' credit to spend against the 'convenience temptations' offered by the Privacy Invaders and Data Sirens. By the end of the workshop (ets 2 hours) the players will have a good knowledge of Twine 2 and Open Source Forum tools in order to design their own Games-For-Change.
### Participants

We can scale up the the numbers- if 5-15 participants joins, we will create one game, with one facilitator providing Twine support for the newbies and coaching the players to delivery a playable, fun game. For a larger group, we will provide more facilitators and run a concurrent multi-game making workshops to make sure every participant can interact and contribute fully to each of the steps of the Cyberspace Gods game - we will provide a board and a game space for  each game circle of 15, so for 50 we will run 3 separate groups to deliver intimate and creative game-collaboration space for everyone.
### Outcome

Collaborative game writing is an increasingly used tool for campaigners in all areas. The ability to design and run a collaborative game making workshop will be useful for all participants, as they can take the acquired experience from the workshop and put it into practice for their own digital campaigns.  We expect the participants to take the learnings and embed them in their own groups, communities and campaigns on both local and wider level.
Based on Open Source tools and the framework of Heutagogy (https://en.wikipedia.org/wiki/Heutagogy )we provide an introduction to a group self-learning based on free software tools that will be useful for both informal as well as more structured group learning through games.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
