### ISSUE TITLE
Role of service providers in fastest-growing space of internet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#264]
**[ Google Spreadsheet Row Number ]** 236
**[ Facilitator ]** Gaurab Patra
### Description

Service provider can be categorized into two : 1. internet service provider - who provides infrastructure and services for data transfer, 2. service providers who uses internet as the medium for providing their services. Both of them has a big role in maintaining etiquettes of the world's largest resource and help it spread out to more number of people in a more usable and accessible way.
### Agenda

The session focuses on:
1. Different types of service providers
2. Etiquettes of maintaining the resources of internet
3. Etiquettes of using the internet as a facilitator to provide service
4. Internet service providers' social responsibility and growth avenue
5. Internet users' responsibility to spread the internet and maintain it.
6. The changing scenario.
7. Diversified scenario in different countries

The session expects an interactive participants to share their views on the topic.
### Participants

The varying number of participants tests the facilitator's ability greatly. With growing number of participants the challenge comes to the facilitator to make it engaging, whereas small group enables more detailed analysis and sharing of views, sharing practical experiences and the scenario in their field.
### Outcome

I wish the participant who gets the maximum benefit from the session will be me. I'm looking forward to learn, share my thoughts and gather others' thoughts so that all of us become more enriched.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
