### ISSUE TITLE
Building Virtual Reality Worlds on the Open Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#265]
**[ Google Spreadsheet Row Number ]** 235
**[ Facilitator ]** Josh Carpenter
### Description

In this session we will build and explore virtual reality web experiences using Firefox, the open web, and new VR headsets. No programming experience required. With new tools from Mozilla we'll have our first worlds started in a few minutes, and then learn how to add animations, images and 3D models to our scenes, what the best practices for VR world design are, and how to share our creations with others, no matter what browser or device they own. For more advanced creators, we'll also touch on the underlying technology that makes WebVR possible, and walk you through creating and sharing your own custom WebGL building blocks.
### Agenda

Workshop format. Session leader takes attendees through creating their first site. Attendees can simply watch, but are encouraged to participate by building on their laptops.
- Welcomes and brief introduction to virtual reality.
- Hands-on demos! Many people have not tried VR. Start the session by giving them a chance to see what all the fuss is about. Using GearVRs and Oculus Rifts.
- Intro to WebVR: what it is and how to get started with it (download Firefox Nightly, flipping the right switches, plugging in a headset, what to do if you don't have a headset, etc)
- Building our first world
- Adding new elements to our worlds
- Testing our worlds on desktop, mobile and in VR.
- Creating our own building blocks.
### Participants

5-15 people: single presenter, able to be quite hands-on. More likely to result in every participate walking away with something they've built.

15-50: More challenging to ensure everyone is keeping up, given inevitable skill variances. Would want to bring a TA (or two, the higher we go). Someone to float and answer questions 1-on-1 while presenter keeps overall flow going. Ensuring each person gets a VR demo at the start becomes more difficult at this size, for lack of headsets.

50+: At a certain crowd size can see us moving to more of a screencast model, with some pauses for people to keep up, and some space for questions, but less ability to coach individuals. Perhaps we do a screencast-ish first half, and wander-the-floor-helping-people second-half. Need multiple TA's at this point. WebVR demo booth in common area for duration of event would be release valve for individual demos.
### Outcome

Feedback from users: do they care about building virtual worlds (as opposed to experiencing them). Are they excited by the tools we provide? Where in the learning  curve do they get confused? What new tools should we add? Etc.

Growing the WebVR community: more content, more participation, more momentum. We want to dramatically increase the vitality of WebVR by making it more accessible, and more fun. We would love to see a wave of new creators coming away from MozFest, from beginners publishing links to their first sites, to experienced developers creating and sharing their own custom building blocks and tooling improvements.

**Comment by marcwalsh** [comment]
@kay

**Comment by marcwalsh-zz** [comment]
cc @kaythaney @cubicgarden

**Comment by EPIKhub** [comment]
@kaythaney @cubicgarden Ive milestoned it but feel free to add it under science, just making sure it was Milestoned for either of our spaces :)

**Comment by EPIKhub** [comment]
@Saallen This session will not be taking place, clash of events with ViewSource but they will be working with the other VR session Ive accepted to share what their plans were and technical expertise
