### ISSUE TITLE
MDN – Tools to document the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#266]
**[ Google Spreadsheet Row Number ]** 233
**[ Facilitator ]** Jean-Yves Perrier
### Description
1. LEARN. At the MDN table, teachers of the Web will learn what resources are available on MDN and learn how to contribute and extend these resources.
2. IMPROVE. In a workshop-like session, teachers and learners will discuss and study how to improve discoverability of MDN tools. They will check the quality of the UX. They will also identify missing tools.
3. SHARE. In daily end-of-day wrap-up sessions, at the MDN table, Web devs enthusiasts will discuss interesting tools they discovered elsewhere at Mozfest during the day.
### Agenda
1. Discovering the MDN resources and tools happens at a table, in groups. This would happen throughout the  week-end. People will see demo of the tools, but we’ll also be able to use them and perform simple tasks, after creating an account.
2. Workshop about tools. Each group (number variable, adapted to the amount of participants) will be assigned a tool: they will first analysis if it fits its goal, then make proposals to improve it.
3. Daily wrap-up session, people will join at a fixed time (next to the end of the day) for an informal but slightly moderated chat about interested tools they saw the same day at MozFest. If more than 10 people show up (we have 5-8 last year), we would split the in two groups. The wrap-up session would happen at the MDN table, so people can drop by during the chat.
### Participants
1. MDN Table: each demo (10'-20') can cover up to 5-7 participants. But with several demos spread over the day, it can handle a lot of people over the week-end.
2. Workshop: we can split the audience in group of 5, each working on a different tools, with presentation of the findings to the whole gang (we have up to 10 different tools to discuss)
3. Wrap-up session: about 12 people can participate to a chat. We can hold two chats in parallel. There is a moderator asking questions to launch the discussion.
### Outcome

MDN Table: they will have learned to use some tools of MDN, they will have created a MDN account and know where to find information in it.

Workshop: they will have learned analysis technique and 1-2 tools of the MDN

Round tables: the informal chat leads to shares of URL of the different project encountered. We envision to write a summary blog post covering the 2 wrap-up sessions.

**Comment by marcwalsh-zz** [comment]
cc @mixedpuppy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
