### ISSUE TITLE
How to build planet friendly websites

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#267]
**[ Google Spreadsheet Row Number ]** 240
**[ Facilitator ]** Chris Adams
### Description

The goal of this session is to help people understand how the energy needs of powering the internet currently result in planetary CO2 emissions on a scale similar to aviation, and what steps they can take to work towards a more environmentally sustainable world wide web: from redesigning slimmed down, faster webpages, to choosing greener suppliers of products and servers, and designing to reduce the need for ever faster devices to provide a decent user experience.

They'll learn that a happy side effect of this is usually a faster loading sites with better user experiences, that work for wider audiences.
### Agenda

After providing a brief background on the subject, we'll map out the supply chain involved in delivering the world wide web to a user's browser, from devices, to data centres, to the infrastructure that powers them. 

We'll then use this map to split into groups discuss the various elements we've identified, and explore the steps that makers can take at each stage, and users of sites and services can ask of them.

Finally we'll bring this back together to create an annotated map, listing the steps at each stage people can take, so they can leave the session with a checklist, to build a more planet friendly internet.
### Participants

If we have 5 people, we might just look at one part of the map: maybe how to tell if cloud computing services rely on renewable power instead of coal, and choose them instead over ones relying on ‘dirty’ power, or how to encourage existing people building such services to switch to greener options.

If we have more people, we'll be able to look at more parts of the map, or as the group sizes grow, break down our map into smaller sections, so groups have a chance to dive deeper into each subject.

We might split "design for sustainable web" into supporting lower end devices reducing the need for device upgrades, or and have a group cover common techniques you can use that both improve the load times of a site, as well as making them lighter on the network in terms of energy usage.
### Outcome

Creating a map listing the areas people can focus their attentions on would provide an ideal structure for creating an online guide that can be fleshed out at later events, and for people to refer to online, and update after the festival.

In Cleanweb London and Cleanweb Berlin, we already have an existing community interested in this field, and we have been running monthly, environmentally focussed tech events since 2012, to hear from experts about their experiences building a more sustainable web.

While these events provide a focus for people to share their learnings in person (and online in the form of recorded talks), creating this map here would mean we can capture this knowledge more effectively for others to use, and build upon, and incorporate into their own efforts building a more planet-friendly world wide web.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
