### ISSUE TITLE
Ping Your Politician : Using the Web to Connect the People to the Powerful

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#268]
**[ Google Spreadsheet Row Number ]** 232
**[ Facilitator ]** Rainey Reitman
### Description

We're bringing together civic hackers from the US, UK and beyond to show how they built simple web tools that let voters talk to their representatives - by email, fax, phone and blimp (really!). We'll demonstrate APIs, confess our biggest mistakes, and work together to brainstorm new tools for civic engagement, from pinging your local mayor to catching the eye of the United Nations Human Rights Council.
### Agenda

A mixture of story-telling and workshop, we'll first tell the story of a decade of experiments in contact representatives, from the Nineties' FaxYourMP to EFF's new Democracy.io and MySociety's latest work worldwide. We'll pick apart how they work using public (and not so public) web APIs, then brainstorm with attendees about projects that can use these APIs to reach other reps, no matter the country or the scale. 
### Participants

With five participants we'll bring them into an equal roundtable conversation and probably pick their brains for new ideas, or trial our skunkwork future projects. 

With fifty participants, we'll start off with the funny stories, and then divide into groups based on the participants desire to dig deeper into various aspects. Then we'll bring people back for summaries and to show them a incremental improvement that they can make to tracking and contacting representatives in their own country. 

If we really max out at 150, we'll find out where everybody is from, tell our tales, and then spring into a bite-sized demo of how to contribute to building a map of representatives, and work together to help everyone make their own contribution to their local contact-a-representative tool. It's not a MozFest session unless you make a thing!
### Outcome

EFF and MySociety have both built fantastic decentralised communities working on making the connection between voters and their representatives, in the US, UK and worldwide. We're working this year to link those communities more tightly, and we'd love to have Mozillians be part of that wider joint endeavour.

**Comment by Melechuga** [comment]
Should confirm that they're bringing together the civic hackers.

**Comment by Melechuga** [comment]
Withdrawn.
