### ISSUE TITLE
Clearing the writer's block

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#269]
**[ Google Spreadsheet Row Number ]** 250
**[ Facilitator ]** Priyanka Nag
### Description

Blogging, writing articles, creating simple promotional materials or writing a nice press release...all of these need one simple skill - writing. We often suffer from a psychological state called the "Writer's block" due to which we either procrastinate our writing plans or often just don't feel confident enough to pick that paper and pen up and start writing. Through this workshop, I would like to take my participants through the simple ways of overcoming the "Writer's block" and be able to write!
### Agenda

I am planning to do a simple workshop where I am going to make my audience write. I will give each participant a different topic and ask them to start writing something on that topic. Some will write and some will be hit by the writer's block. 
Then I will take them through the different ways of overcoming writer's block, one step at a time. At each step, we will do a little extra writing till, by the end of the session, all the participants have done a fair amount of writing and have overcome their writer's block.
### Participants

This session will not be effected by the number of participants that we have. Whether we have 5 or 150 participants, the process will remain just the same. All I am planning to do is make them write...which is a self driven process.
### Outcome

I often hear from Mozillians that they don't blog about their events cause they are scared to blog. They think they are not good bloggers, not good writers or that no one will be interested in reading their blogs. 
I will try and break all these myths. I want my audience to know that writing is simple.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
