### ISSUE TITLE
Redesigning your Context: A Design Thinking Approach

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#270]
**[ Google Spreadsheet Row Number ]** 230
**[ Facilitator ]** Cristol  Kapp, Librarian, Clifton Hills Elementary School, @mrs_kapp
### Description

Cristol Kapp, a TeacherPreneur, completely transformed the Clifton Hills Elementary School Library into a library makerspace. She has created a space that offers students the opportunity to explore, make, learn, and share at their pace. In this session you will learn how to use Design Thinking to reimagine your context. Together, we’ll create a design board centered around the challenge of redesigning a space to allow participants to soar.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
cc @LindseyFrost

**Comment by cubicgarden** [comment]
Sounds pretty interesting, for the diverse ways of thinking @cubicgarden

**Comment by chadsansing** [comment]
Have spoken w/ @LindseyFrost & Cristol Kapp previously re: Cristol's work & would very much like to include this proposal for consideration in teacher/librarian-facing Learning & Leading.

**Comment by LindseyFrost** [comment]
@chadsansing I think it' an awesome one for Learning & Leading having seen an iteration of this workshop done locally in CHA

**Comment by EPIKhub** [comment]
@chadsansing as a progression piece at a local level Ive had a meeting with Cristol today for the youthZone and we are going to work together to localise her session so a UK audience can take a leaf out of her book to recreate what she did here. We are also going to work on creating a universal (any location) teaching kit followed by an article for UK Liberians to learn about her work which will include visiting 3-4 local schools and their library, school visit at Cristol request which I have agreed to help her with. Is that ok with you Chad?

**Comment by chadsansing** [comment]
@EPIKhub, @LindseyFrost: is the progression piece post-MozFest or during, i.e. is this being moved out of our Milestone and into the YouthZone?

**Comment by chadsansing** [comment]
@EPIKhub, @LindseyFrost: any guidance on this session? Is it an interconnected one, or going to one space or the other? Clarification appreciated :) Curious as we milestoned this & time is running out on this part of the planning. Would love to have it in Learning & Leading as a librarian-facing leadership development session, too.

**Comment by LindseyFrost** [comment]
Hi @EPIKhub @chadsansing  - I think this is a really important one in the L&L MLN Pathway.  I've seen the work, and it's important. Let's try to have it as a cross-pathway session.  Failing that, I'm sure Crystol would also be willing to do it twice if schedules can't be coordinated.

**Comment by chadsansing** [comment]
Great, @LindseyFrost - we'll move ahead and keep it contact with @EPIKhub re: scheduling a second session if need be.

**Comment by EPIKhub** [comment]
@chadsansing @LindseyFrost I've accepted Cristol on her other session submitted so will work with her on that one issue #344 so no need for a second session for #270 Ill combine it all into one
