### ISSUE TITLE
Campaign Hack - Codesigning a Framework for Activism

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#271]
**[ Google Spreadsheet Row Number ]** 242
**[ Facilitator ]** Sue Smith, Jen Hunter

Twitter: @HackAye
Organization: Hackeye
### Description

Today's activist campaigns are innovative and connected, leveraging the web to build collective voice. Open source practice could amplify the power of contemporary activism by sharing resources and learning outcomes openly between movements. In this session we will use GitHub to codesign a framework for planning activist campaigns. It won't be too technical - if you can use a web browser you can learn to use GitHub during the session! We'll create a template to guide new movements with the benefit of your past experiences and together start to build a community-led repository for open source activism.
#### Bios:

Hack Aye is a new organisation based in Scotland. We use collaborative arts and technology learning experiences to engage people in activism and hack participation in work/community. Sue Smith has worked as a developer and technical writer with various organisations including Mozilla Foundation. Jen Hunter has worked as a musician, music promoter, arts development officer, activist, and organiser at the Musicians' Union. http://hackaye.com

**Comment by Melechuga** [comment]
Combining with "Building Grassroots Communications Campaigns" (https://github.com/mozilla/mozfest-program/issues/198); Paul will facilitate with Sue Smith -- he'll reach out.
