### ISSUE TITLE
Are We Ready For Anonymity?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#272]
**[ Google Spreadsheet Row Number ]** 239
**[ Facilitator ]** Magdalena Taube
### Description

Anonymity is a controversial issue in the post-Snowden world. While serving as a vehicle for criminalization of various cultures, many communities experiment with concepts that try to resolve the destructive potential of anonymity (i.e. The Coral Project). How to create common sense and a healthy “we” with regard to anonymity? 
In my session “Are We Ready For Anonymity?” I will present a storytelling project of the same name that will be created by a group of international journalists in Oct 2015. 
The project I present tackles the world of online forums in the field of journalism and will foster a discussion among participating journalists, activists and coders. 
### Agenda

My session will be a workshop. The aim is to bring together a variety of people who work in the field of journalism and who deal with digital communities on a regular basis. 
The first part of the workshop will contain a 10 minute presentation of the storytelling project "Are We Ready for Anonymity". 
On the basis of that input we will discuss the experience of the participants regarding anonymity and community building. In a short mapping session (5 - 10 mins) we will figure out the most common problems (i.e. hate comments, trolling) etc. After that we will form small working groups and will give each group 30 mins time to come up with solutions to these problems. The solutions will be collected in a shared pad and presented by the groups in the end. 
### Participants

With a small nummer of participants like five people we will all work together and not form groups, the agenda of the workshops stays the same. With 15 participants we can easily split up into three groups. In case of a large groupf of participants I will sign up 2-3 people as co-moderators and we'll still try to form working groups. The presentation time for each group would have to be very short. 
### Outcome

Firstly the workshop is a chance for media workers (journalists, coders, activists) etc. to reflect the problem of anonymity in digital communities and to find solutions. Secondly it is a chance to learn from each other. The storytelling project I'll present has a focus on Europe (Belarus, Portugal, Germany, France). People who come from other journalism cultures have a chance to get insights into European problems and solutions. And above all they can learn from the other people participating in the workshops: What are best practice cases? What are the specific problems of communities in different countries? etc.

**Comment by ryanpitts** [comment]
assigned to the Digital Citizenship milestone, but we're also considering this for Journalism's "Community" pathway.

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Building Online Communities" pathway.
