### ISSUE TITLE
What does being participatory & playful in a learning setting look like?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#274]
### Google Spreadsheet Row Number

246
### Facilitator

Name: Shreyas Narayanan Kutty
Twitter: @dun3buggi3 
Org: Scrollback
### Description

This session contains the core ideas of the Mozilla Learning Network, which is, "Teach like Mozilla". As opposed to conventional learning methods that include watching & listening, we are going to explore participatory,inclusive and fun ways of teaching. These include examples of sessions that worked in our local communities, for example:Teaching HTML using Lo-fi/No-fi methods in remote villages in India with the help of bricks and LAN houses (internet cafe's in Brazil) where people are taught web literacy skills. The attendees of our session would have a better understanding on the importance of fun and participatory learning activities.

**Comment by soapdog** [comment]
cc @soapdog
