### ISSUE TITLE
Social entrepreneurship and innovation for sustainable development

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#275]
**[ Google Spreadsheet Row Number ]** 248
**[ Facilitator ]** James  Njeru
### Description

This session will allow people to understand social entrepreneurship and innovation by having activities that enable them to engage,learn and interact.These activities will focus on identifying the impact, challenges and opportunities in this sector and also develop prototypes  based on participants experience and proposals. These prototypes will be developed based on brainstorming and focus group sessions held to identify social problems and their solutions.
### Agenda

I plan to have 5-10 minutes presentation on social entrepreneurship and innovations with Africa as a case study, then have focus groups based on thematic areas as proposed by the participants i.e education, agriculture,health etc. These focus groups will be challenged to identify social problems and come up with solutions which at the end of the session they should develop prototypes on paper and present to the audience for peer to peer review.
### Participants

5 participants- Will have a presentation on social entrepreneurship and innovations with Africa as a case study and then have participants have open brainstorm discussions.Participants will be invited to share their individual experiences and  identify social problems. Based on the  social problems we will identify one which has a major impact,come up with a solution and prototype it.
15  and 50 participants- Split them into groups and select group leaders. The groups will then select a focus area i.e health,education or agriculture but it's not limited. Based on these focus areas the groups will identify a social problem, come up with a solution and develop a prototype and later make a presentation for peer to peer review.
### Outcome

Outcomes and way forward
Participants will  be able to learn how to develop sustainable solutions for various social problems.  
Develop proposals to develop various solutions.
Identify implementing partners for various solutions.
Implement the proposed solutions.
Write session report and blog which we expect to aid in identifying implementing partners/collaborators.
Stir the pot of social entrepreneurship and innovation.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
