### ISSUE TITLE
Design Sprint For Mozilla Science Lab

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#276]
**[ Google Spreadsheet Row Number ]** 247
**[ Facilitator ]** Milap Bhojak
### Description

The goal of MSL is testing out new ways to help the Science Lab community build tools and solve problems. My session would be on how to build a new tools for science using design sprint approche. The sprint is a five-day process for coders, designers and researchers to answering critical questions through design, prototyping, and testing ideas with end uses. As there would be designer, coder and researcher so they would have to do what they are good at like researcher would have to find problem from particular area, Designer would design a product and coder would write beautiful code at the end team would get prototype of data product.
### Agenda

This could be a workshop if i would get more time even we can run small Design sprint at mozfest. I would talk about how 5 days would help us to a build prototype. 

Monday: Unpack(People would unpack their ideas and knowledge)
Tuesday: Sketch(During Sketch day, your team will work individually to draw detailed solutions on paper. As you sketch, everyone works separately to ensure maximum detail and depth with minimum groupthink)
Wednesday: Decide(You’ll have over a dozen solutions to choose from. That’s great, but it’s also a problem, because you can’t prototype and test a dozen solutions. You’ll have to narrow down and make tough decisions)
Thursday: Prototype(Thursday in the flow, being ridiculously productive. We show you our systematic plan for doing the impossible: build an entire realistic-looking prototype in just eight hours)
Friday: Testing(On Friday, you’ll show your prototype to real customers or end users in 1-on-1 interviews)
### Participants

Impact is more important than numbers. I would make sure every participant would learn something at the end of festival and Design sprint is all about team of 4-5 people. If I would have 5 people then would make 1 team if 15 then 3 and if 50 then 10 teams. 
### Outcome

Participants would able to convert their ideas into reality and they would learn 3 things at the end of festival
1. Team work
2. How to create a prototype of data product
3. Knowledge and information exchange from team mates

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
