### ISSUE TITLE
Arduino: Changing Life

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#277]
**[ Google Spreadsheet Row Number ]** 238
**[ Facilitator ]** S. M. Mohi-Us Sunnat
### Description

Arduino is an open-source electronics platform based on easy-to-use hardware and software. So I select this Arduino project as a session in Mozfest. Participants will learn and can make some small projects after this session. They will be motivated to make some awesome big projects which can be used in their daily life.  It's intended for anyone making interactive projects.
### Agenda

-- Introduction to Arduino
-- Showing some projects
-- Provide Arduino devices and resources to make some funny and awesome projects (Limited Resources)
-- Making through learning
-- Sharing the learning through making
### Participants

I am preferring a peer to peer session and 15 to 20 people will be the best size as I am hoping for an hacking session with all the participants. Creating some groups who knows about Arduino and who don’t and sharing their experience in the group and then sharing outside the group. If I have 5 people, I will start showing projects in a small team and make projects together.
### Outcome

-- Participants will be interested to work with Arduino
-- They can make some daily necessary projects
-- They will show projects to others
-- Some Hacking ideas will come out which can be followed by for Arduino workshops in other communities or events.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
