### ISSUE TITLE
Your data is good, my data is good, OUR data is incredible!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#279]
**[ Google Spreadsheet Row Number ]** 244
**[ Facilitator ]** Jacob Tomlinson
### Description

Together we will design and create small JavaScript browser applications (or Firefox OS applications) which will mix multiple open data sets together to create useful information. The takeaway thoughts will be that data is useful, but combining multiple data sets together is even better!
### Agenda

The session will start out with a short round table chat which will provide some example datasets and visualisations which can be found online. This will certainly include Met Office data and other well known data sets from organisations such as the Environment Agency, Ordnance Survey and TFL. We can go over some examples of successful uses of combined data and a little bit of idea generation.

It will then open out into a workshop style session where attendees form small groups and start mixing data sets together. Using simple JS frameworks such as bootstrap, jQuery and D3 attendees should be able to knock something together quickly.
### Participants

We will encourage attendees to form groups of no larger than 5 and set them off working on their own project. That way it doesn’t matter if we have 1 group or 10. 
### Outcome

We will encourage that everything we produce is made available in a GitHub repository which will be hosted on GitHub pages as a website. This way people can explore the apps which have been created and build on them in the future.

**Comment by msaunby** [comment]
cc @msaunby  This session from Met Office Informatics Lab.  If you'd like it changed, merged, etc. just let me know.
