### ISSUE TITLE
From specifications to tests: Test the Web Forward primer

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#280]
**[ Google Spreadsheet Row Number ]** 251
**[ Facilitator ]** Ben Boyle
### Description

Gain confidence in translating web specifications into tests and contribute to Test the Web Forward.
### Agenda

Explore the language of web specifications, discuss and share what we learn as a group. Test out theories using testharness.js from Test the Web Forward.
### Participants

I will only be available to host this session remotely (I will be in Australia, not London), but there is the possibility of running multiple sessions during the festival. Small groups would be best so we can collaborate together.
### Outcome

Participants will gain greater confidence in understanding web specifications and an introduction to Test the Web Forward preparing them to contribute further!

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
