### ISSUE TITLE
Hacking Games for Web Literacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#281]
**[ Google Spreadsheet Row Number ]** 245
**[ Facilitator ]** Matteo Menapace
### Description

Are you a gamer? How about becoming a game designer for a couple of hours? In this session you will work in teams to hack an existing game with a new goal: to teach people about Web Literacy. Using paper, markers, pawns, dices and other props, you’ll make a playable prototype of your new game, which other people can play for fun and use as an educational tool. Here’s our formula for success: existing board / card game + Web Literacy = new game What do you want to teach? Can you make a board game that lets players immerse themselves in that topic? What aspects of your chosen topic do you want players to focus on? How will you change the existing game mechanics so that they reflect your goal/topic?

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by matteomenapace** [comment]
cc @matteomenapace

**Comment by matteomenapace** [comment]
This session proposal is a fork of [Hacking games with verbs](https://github.com/matteomenapace/hacking-games-with-verbs), which I presented at Mozfest 2012.

By focusing on board games and Web Literacy, we aim for participants to leave with an actual game prototype, rather than a game idea.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.

**Comment by chadsansing** [comment]
Re-opening as part of the Learning & Leading Pathway in the MLN space.
