### ISSUE TITLE
Training the Next Generation of Physical Web Researchers

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#282]
**[ Google Spreadsheet Row Number ]** 259
**[ Facilitator ]** Nick Taylor
### Description

This session aims to crowdsource the design of a new PhD program exploring the open, physical web. 

We’re excited about the possibilities of Web-connected objects, but we want to see it done right—in a way that is open, interoperable and community-driven. Our intention is to look past current IoT tends towards the next generation of technologies and applications, but more importantly towards the next generation of thinkers who are going to help drive this vision forward. What does the Mozilla community need them to be? We want to know what values they should hold, who they should connect with, what skills they should have and what skills they need to develop. 

By the end of the session, we hope to have outlined the kind of person we want on an Open Physical Web PhD and the training we need to give them.
### Agenda

We want to make sure anyone with an interest in the Physical Web and its future development can contribute. You might be a developer or a technology company. You might be part of a community that has done work with researchers in the past, or who would be interested in working with them in the future. You might be a researcher yourself or someone who thinks that a PhD in the Open Physical Web is the thing for them. 

The session will begin with introduction of attendees, the topic and our reasons for attending the session. We will split into breakout groups, with each group discussing a specific topic. There will be a pre-prepared set of topics (e.g. communities, skills, technologies, values), but attendees will also be encouraged to suggest their own during the opening session. In the second half of the session, we’ll reconvene to share out thoughts.
### Participants

The design of session lends itself to flexibility: the number and size of a breakout can be varied according to the number of people attending. Although this will probably work best around 15 people working as groups of 3–5, a very small number of people could work intensively as a single group. 
### Outcome

The outcomes of the session will directly influence the design of a new PhD program at the University of Dundee. We hope that participants will chose to stay involved, and we’ll be collecting contact details in order to let them know how things progress. We’ll also be documenting the session on the MozFest hashtag. With luck, we’ll be back to tell you about it next year!

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
