### ISSUE TITLE
Blinds and deaf

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#283]
**[ Google Spreadsheet Row Number ]** 258
**[ Facilitator ]** Albin Albert
### Description

Who said blinds and deafs cant interact with common ppls ?

It is a common thing in our society,its very difficult for the blinds and deafs but We are sayin that it is absolutely wrong

They can interact our innovation will gave them a chance
### Agenda

We will divide our participants ,We  will teach them using games and puzzles,yes it will be intresting
### Participants

No matter 5 or 50 our team consists of qualified professionals

Dont Worry We will manage

Lets see whats gonna to be happen 
### Outcome

We strictly belive this innovation can change the world 

We will create the community which will change the world

**Comment by marcwalsh-zz** [comment]
cc @kaythaney

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
