### ISSUE TITLE
Building badge-based pathways to employment

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#284]
**Google Spreadsheet Row Number**

252

**Facilitator**

Gráinne Hamilton

**Description**

Open Badges can be used to build bridges between learners and employers. There is increasing demand for evidence of soft as well as hard skills for employment but these are not always presented in verifiable ways or linked to careers, apprenticeships or further learning. We will introduce how Open Badges can capture and communicate skills and provide social tools to help participants learn about and make badge-based pathways towards destination points such as careers, apprenticeships or further learning. Examples of badge-based pathways to employment will be provided.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin participation pathways to employment
