### ISSUE TITLE
Allergy Detector

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#285]
**[ Google Spreadsheet Row Number ]** 257
**[ Facilitator ]** Albin Albert
### Description

Now a days world is suffering from lot of diseases due to allergy.We think our innovation can block the after effects of allergy.Sorry not after effects from the initial stage we will cure it  .We Think our innovation is smart by using a smart phone
Lets say good bye diseases
### Agenda

We Will divide the the folks into diffrent groups.Our team will demonstrate the theme to participants through different activities,it will include fun  and much more  .We prefer all kinds of people in this group,no matter whether it is  aged or new born baby because allergy can affect all ppls.
### Participants

No matter whether it is 5 or 150 We will manage because our team consist qualified professionals and much more

Lets see whats gonna to be happen  
### Outcome

We will introduce our new innovation to the world which can build a community which changes the world

**Comment by marcwalsh-zz** [comment]
cc @kaythaney

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
