### ISSUE TITLE
Online (Behavior) Privacy Awareness

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#286]
**[ Google Spreadsheet Row Number ]** 253
**[ Facilitator ]** Andi Darmawan
### Description

The vast technology penetration in emerging countries (such as Indonesia) led to a lot of people become online. The problem arises when they don't care or aware about online privacy which can lead to criminal activities such as fraud, scam, kidnapping, etc. There are a lot of tools that can enhance privacy in online world. But the main problem is online behavior. This session will discuss how to make people change their online behavior. 
### Agenda

The session will start with the background of online behavior in emerging countries. Give some sample criminal case in result of bad online behavior. And then start discussing how to make people aware of their online privacy. Everyone should give their experience and story and suggestions.
### Participants

With less than 15 people, the session will be a small discussions. With more than 15 people, the participants will be split into several groups and each group should propose an ideal campaign for online privacy awareness
### Outcome

The outcomes are several ideas or suggestions for online privacy awareness that me and the participants can implement in daily life to our surroundings.

**Comment by cubicgarden** [comment]
Interested too @cubicgarden

**Comment by cubicgarden** [comment]
Ties nicely with https://github.com/mozilla/mozfest-program/issues/575
