### ISSUE TITLE
Advancing the Open Web: An introduction to the development and standardisation of web platform technologies

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#288]
**[ Google Spreadsheet Row Number ]** 255
**[ Facilitator ]** James Graham
### Description

The aim of the session is to take people who have some knowledge of web technologies and teach them how the web itself is developed. This will allow them to leverage their existing knowledge of web
development to become leaders in future development of the platform.

In detail the session will cover the process of proposing and standardising new technologies and features on the web platform. It will also cover the techniques we use to ensure that web technologies are compatibly implemented across multiple browsers.
### Agenda

The session will take the form of a workshop, starting with an introduction to the process of standards development and proceeding with activities designed to simulate participation in the a standards working group, allowing participants to experience the process of submitting and critiquing an idea for a future web standard. It will finish with a brief introduction to the process for testing and obtaining interoperability on web technologies, which will be an ideal lead in to MDN Fellow Ben Boyle's more testing-focused session proposal.
### Participants

The session will mostly be run in small groups, so it will be possible to scale with the number of participants by dividing into more groups. With a small number of attendees it will be possible to give clear 1:1 attention to each participant and tailor the activities to their preexisting skills. If the attendance is larger, I anticipate working in a series of small groups with clear guidelines to ensure that everyone actively participates. Therefore the session will be flexible with regard to size.
### Outcome

After the festival participants should feel confident that they understand how the open web platform is developed. They will be empowered to participate in the process of standardising web technologies, with a clear idea of how to present their ideas for the future of the platform in an effective way. They will also understand the stages that a web technology goes through before it is
implemented, and be aware of opportunities to get involved with other aspects of the platform development such as testing.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
