### ISSUE TITLE
Using open community support as a community building tool

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#289]
**[ Google Spreadsheet Row Number ]** 254
**[ Facilitator ]** Madalina Ana
### Description

deeper community participation using one of Mozilla's support tools (Army of Awesome) as a case study. We will use this to discuss and share what participation techniques and processes work in the open space and comment on challenges and opportunities.
### Agenda

We will split the session intro three parts

Part 1: Overview of case study
Part 2: Break into small groups and have a discussion about approaching participation in the open space
Part 3: Share back findings
### Participants

The session will consist of an overview of the case study and then a discussion. Depending on the number of participants we will either do it as a single group or split into smaller groups to share our experiences.
### Outcome

Deep-dive on some of the processes and tools discussed and analyze how they can be applied within the organization. Use the findings to do some experimentation and boost community participation.

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter
