### ISSUE TITLE
[Pathway] Backdoors + Cryptowars

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#29]
A proposed pathway that focuses on encryption. In this pathway, sessions will teach people why they should encrypt, how to use certain tools, build on existing tools, and design creative ways to teach others about encryption. Participants will learn about real-world experiences where journalists and/or whistleblowers were targeted, and how they successfully protected themselves (or didn’t) from prosecution or worse fates. An Open Web Fellow working with Amnesty International will provide technical expertise on how encryption works, and the experiences of online activists in oppressive regimes like Russia and Azerbaijan.

Sessions include: 
- [ ] #25 
- [ ] tbd
- [ ] tbd

**Comment by ekr** [comment]
Hi Michelle,

I'd like to suggest that it's confusing to call this Let's Encrypt because there's already an existing effort by this name with a different mission that Mozilla is heavily involved in.

https://letsencrypt.org/

**Comment by Melechuga** [comment]
@ekr @thornet We're happy to change the title; have edited to "Backdoors and Cryptowars." Hope that works.

**Comment by Melechuga** [comment]
cc @ekr this was the original issue -- previously labeled "Let's Encrypt", which we happily changed 3+ weeks ago. I hope this works. Thanks!
