### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#291]
**[ Google Spreadsheet Row Number ]** 264
**[ Facilitator ]** Anoop George Muttath
### Description

Healthy life is the current issue of human life . The toxic content in the fruits and vegetables affect the human very much .This issue can solved by our idea. 
### Agenda

We will divide our team different group. it will include  fun ,matter ,games and much more...
### Participants

No matter whether 5 or 150 we have professionally qualified team. we will take care lets see what's gone to be happen.
### Outcome

we can provide quality to the world . quality in the sense for fruits and vegetables .

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
