### ISSUE TITLE
LEGO2NANO: an Open Atomic Force Microscope Project

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#292]
**[ Google Spreadsheet Row Number ]** 268
**[ Facilitator ]** Joe Bailey
### Description

Imagine an open source microscope that is powerful and cheap enough for school children to study the nano world, the world of atoms and molecules that is 1000 times smaller than what traditional optical microscopes can see. That is the objective of the LEGO2NANO project. This workshop will introduce to you the hardware and software developed so far for the world's first open source atomic force microscope. We'll also introduce how we are documenting this project on the Web, how we are involving Chinese school children in building and using the microscope, and sharing data from the microscope for crowdsourced analysis in Web-based citizen science projects. LEGO2NANO is in an international summer school in China, involving students and mentors from University College London, Tsinghua University, Peking University, Academia Sinica, MIT, Tufts University and University of Geneva. http://www.openafm.com 
### Agenda

This is a one hour workshop. After introducing the overall goals and achievements of the project so far in about 20 minutes, we'll divide the audience into teams, according to their interests, to learn more about the hardware, software, crowdsourcing and educational aspects of the project, in the remaining 40 minutes.
### Participants

With 5-15 participants, we'll work through all aspects of the project together, for 16 or above, we'll split into teams with one mentor for each team, and focus on one aspect of LEGO2NANO per team. 
### Outcome

We expect some of the participants in this workshop to be sufficiently motivated to join and start contributing to the open source community that we are building up around LEGO2NANO.

**Comment by EPIKhub** [comment]
@acabunoc is this session accepted in Open Science as a session? If not I will accept them into the #youthZone

**Comment by EPIKhub** [comment]
@acabunoc I have accepted their session into the youthZone now and sent email to confirm this to them

**Comment by abbycabs** [comment]
Thanks Dorine! Sorry I missed this earlier. We didn't accept it in case you were planning to. Thanks!

**Comment by EPIKhub** [comment]
@acabunoc I am really pleased you did not ;) this is an amazing project, had a skype meeting with the session leader, we will aim to link this project into British schools.
