### ISSUE TITLE
Micromundos Tangible Interface

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#293]
**[ Google Spreadsheet Row Number ]** 262
**[ Facilitator ]** Christian Parsons
### Description

People will explore, use, play and re-think through a tangible computing interface. The (low cost) device allows people to bridge the virtual and the physical worlds through tinkering with different kinds of simulations, games and art conceptions.
There are low-cost laptops for children to learn computation, but they based on the personal computer (GUI model). We need portable low-cost devices for children to learn computation through tangible interfaces (TUI model).
Micromundos is a construction kit that provides a playground for people to tinker with complex and dynamical systems while building spatial contraptions with their own hands and transform low-cost materials in computational artifacts on-the-fly.
The mid term goal is to enable learning of systems thinking, problem solving and creative expression through tangible computing.
### Agenda

Hands-on session: people playing, testing and doing things with the machine. After some free play and hands-on activities there will be an informal talk to discuss ideas, collect feedback and start to build a community around the project.

People connect their browsers to the device while others are playing on the table. The browser lets them visualize some of the inner processes behind the scenes and perform some "remotely controlled" actions over the tangible games. This graphical-tangible user interface connection will leverage different levels of abstraction on the human computer interaction loop (tangible - iconic - symbolic)
### Participants

15: sessions of play of 15' minutes 4 or 5 participants by session and a talk latter
50: sessions of play of 15' minutes 4 or 5 participants and a talk at the end of the day
(150: same idea)
### Outcome

We see a fertile ground to share and collect ideas and a powerful opportunity to present the device to people of all around the world and begin to build a community around the tangible computer control

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
