### ISSUE TITLE
Developing tools to understand learners

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#294]
**[ Google Spreadsheet Row Number ]** 260
**[ Facilitator ]** Adwait Sharma
### Description

We have created a learning platform based on the premise that adding physical artifact and emotional design to the system can help improve creativity and cognition. 

This session emphasises on tactile-learning paradigms to enhance the learning process as well as the common concerns of the user: a system that celebrates when user succeed and sympathize when they fail. This include guidelines for creating an inclusive curriculum for the novice user that connects all the major development phases: ideation, prototyping and development. Also, methodologies for building user engagement through context-based learning experience. This allows user for observing and manipulating the environments in which they live and use programmability to convert these intuitions into formal learning. This learning model is re-purposable, and can be applied for training new skills and knowledge.

To validate this model, we have tested it amongst 3 different user groups: i)young kids, ii) teenagers, and iii) adults. 
### Agenda

The attendees will go through a self-driven learning system that will yield a prototype of each attendee’s idea. It includes a sensory framework that allows accessing the smartphone sensor values in real-time from the computer, tactile interaction blocks to create a sense of touch for programming, and a virtual companion. We are developing a sensor-based application because, developing such applications is considered as a complicated process and requires task-relevant knowledge. Additionally, this system helps in finding the right sensor and choosing the correct values according to the application.

In the end, we will discuss the end results, share views, suggest improvements and the impact to the community about how this methodology affect in learning. Furthermore, these mechanics are now adapted by the university students of user experience design module.

This session requires zero programming or sensors knowledge.
### Participants

The aforementioned tutorial system runs in the web-browser and it is not dependent on the number of participants. However, more people taking the tutorial simultaneously will provide a rich collaborative learning experience while engaging maximum people in brainstorming and other playful activities involved in the system.
### Outcome

Presently, the visual programming blocks work to make programming easier. However, they do not work for everyone. Maintaining the level of user’s motivation and keeping them engaged is a difficult job, which can be overcome by developing the learning systems that sense and respond.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
