### ISSUE TITLE
How fast you can Swim

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#296]
**[ Google Spreadsheet Row Number ]** 261
**[ Facilitator ]** Albin Albert
### Description

We know that there are so many environment issues
Give us a chance to block it whatever it may be dogs flies or insects  ,We dont care

We will are going to  create a world wide movement against this issue, Just belive us :P
### Agenda

we will split our participants into diffrent teams, We belive that our creative thinking and implementation Wont make our team members bored :D
### Participants

NO matter We will take care .We have a Perfect team which consist a software and network Engineer

One more guy a MCA graduate
### Outcome

We will produce a community by this this community We can spread innovation and its just a beginning

**Comment by marcwalsh-zz** [comment]
cc @kaythaney

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
