### ISSUE TITLE
Pollution

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#297]
**[ Google Spreadsheet Row Number ]** 271
**[ Facilitator ]** Anoop George Muttath
### Description

Now a days environment is polluted .we can see in the news paper's and news in television. our project will help to solve this problem.
### Agenda

We will divide our team different group. it will include  fun ,matter ,games and much more...
### Participants

No matter whether 5 or 150 we have professionally qualified team. we will take care lets see what's gone to be happen.
### Outcome

We can provide a good Environment . which means pollution less Environment.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
