### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#299]
**[ Google Spreadsheet Row Number ]** 266
**[ Facilitator ]** Anoop George Muttath
### Description

Attacks from stray dogs or any animals while cycling, walking, jogging, etc. This is our current issue . Using our idea we can keep dogs and other animals away at an effective range up to 20 feet (about 7 meters) with a prime operating range of 5 to 6 feet. 
### Agenda

We will divide our team different group. it will include  fun ,matter ,games and much more...
### Participants

No matter whether 5 or 150 we have professionally qualified team. we will take care lets see what's gone to be happen.
### Outcome

We can provide a safe society for all human being .

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
