### ISSUE TITLE
Science in the Browser with WebGL

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#301]
**[ Google Spreadsheet Row Number ]** 274
**[ Facilitator ]** 
name: Michael Saunby
twitter: @msaunby
organization: Met Office
name: Rachel Prudden
twitter: @RachelPrudden
organization: Met Office
name: Niall Robinson
twitter: @niallhrobinson
organization: Met Office
### Description

Using ThreeJS and other Javascript libraries we’ll explore the opportunities presented by Firefox and other desktop and mobile browsers for interactive 3D graphics in scientific data collection, visualisation and image analysis. 

Some HTML and Javascript skills will be needed. Geometry and matrix algebra will be useful.
### Agenda

We’ll come along with examples of our own to show what we’re doing with environmental data, all in GitHub ready to fork for your own projects.  

Then we’ll split into groups to share, search for, and imagine, what might be possible in other fields - medicine, psychology, archaeology, geography, astronomy…  (whatever takes your fancy).

We’ll use hackpads to collect information from each of the groups.  

Close with a group discussion of the most promising tools available now and what we’d like to make over the coming weeks and months.
### Participants

With 5 we can work on an existing project and enhance or re-purpose for a different user community, e.g. build something from weather tools to help archaeologists.

With more we'll form teams to share what we all know about science needs and the new opportunities from browser based apps. 
### Outcome

We’d like to see more examples of science in the browser and to share techniques and tools between disciplines.

**Comment by thornet** [comment]
cc @msaunby @kaythaney
