### ISSUE TITLE
Extending open web tools in service of open licensing policy advocacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#302]
**[ Google Spreadsheet Row Number ]** 282
**[ Facilitator ]** Timothy Vollmer
### Description

Open licensing policies are gaining momentum, and are necessary for governments to guarantee legal access and reuse rights to taxpayer funded digital materials, to maximize the impact of public investments, and to promote innovation and entrepreneurial uses of content. Our collaborative session will: 1) raise awareness about the importance, opportunity, and activities related to open licensing policies, 2) learn from existing experts and advocates in related areas about the tools and practices they’ve used in support of the open web and how we can extend them to educate about open licensing, run effective issue campaigns, and assist in implementation of open licensing policies, 3) gain new advocates to the idea and crucial work of getting open licensing policies for publicly funded resources, and 4) connect sister organizations and individuals together in support of open licensing policies, and describing concrete engagement opportunities.
### Agenda
1. introductions from all participants answering short prompt from organizers
2. description of session goals
3. brief overview of CC licenses and open licensing policies
4. full group exercise: identifying existing tools, strategies, issue campaigns, communication tactics within the broad open web community
5. small group exercise: connecting the dots 
   5a. discuss current policy issues and tools, strategies, issue campaigns, communication tactics that can be leveraged for advocacy and education around open licensing policy for publicly funded resources
   5b. take the make “Open Policy” physical building blocks and build their own DIY draft open policy  
6. full group report-back: small groups will come up with three (3) ideas and share back with larger group
7. organizers with synthesize ideas and invite closing discussion with participants about possible opportunities for collaboration and involvement in open licensing policy education and advocacy
### Participants

With 5 participants we will organize the session around an informal group discussion. We will have more flexibility in exploring in more depth a particular topic brought forward by one of the participants or an organizer. With 15 participants we can run the session as described in the agenda above. With 50 participants we will need to have a session chair in order to keep us on schedule and cover all the points in the agenda. In addition, we will identify small-group leads from within the organizers to accommodate the larger numbers of individuals in the breakout groups. This is so that the breakouts are productive and inclusive of all participants. Regardless of overall session size, we will take notes on a collaborative hackpad. 
### Outcome

We will publish a blog post on the Creative Commons and/or Open Policy Network site after the event with the outcomes of the session in order to share with others that weren’t able to attend. At the end of the session we will have identified tangible opportunities for collaboration and involvement in open licensing policy education and advocacy. We plan to continue working on two (2) tools, communication tactics, issue campaigns, etc. that were surfaced at the session and invite participants to explain and share these activities with existing projects such as the Open Policy Network monthly meeting. We will plant the seed of Open Policy and giving participants a take home documents that they can show and support within their communities. We will invite participants to join the Open Policy Network.

**Comment by Melechuga** [comment]
Adapt into Dino's Den + CopyBetter.
