### ISSUE TITLE
Hacking Mental Health: Changing Views in Tech

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#303]
**[ Google Spreadsheet Row Number ]** 292
**[ Facilitator ]** Jennifer Geacone-Cruz
### Description

Mental health is an ignored corner of the tech world for far too many of us. We know it's an essential part of our personal and working lives, yet so little attention is paid to it due to stigma or lack of awareness. We all have some level of personal experience with it, whether we realise it or not. 

This session will be addressing the changing place that mental health occupies in tech. We will discuss the past and current state of mental health and emotional wellness, factors that exist that affect it, and ways that we can change views and create a more supportive space for the growth of mental health in our community. Personal, cultural, political, economic and technological influences will be examined and combined in discussion and exercises to facilitate ideas about how to hack mental health in tech.
### Agenda

The session will be a combination of chat, brainstorming and workshop. The aim is to help us to see the current state of our awareness, learn some basic guidelines that can be applied in a granular way, and to brainstorm ideas on how we can apply better approaches to mental health every day.

Examples of planned interactions include awareness self-assessments on topics such as stereotypes or stigma, the role of empathy, identifying one's own needs for maintaining healthy work-life balance, brainstorming  about creating support networks, and being respectful of others' experiences.

There will also be discussion and brainstorming about how our relationship with technology is affecting the issue of mental health in tech. Does technology isolate us further, or bring us closer together in our search for better mental wellness? If both, what is that crucial unifying factor and how can we harness it to make our experiences better?
### Participants

With 5 participants, whole group activities and brainstorming can be easily facilitated. With 15, participants would be broken into groups of 3 or 5. With 50 the session would take more of the form of a seminar, with breaks for self-assessments and brainstorming in groups of 5.

Actual self-orientated level participation is crucial to maximising the awareness impact and motivation to improve  mental health awareness in tech.
### Outcome

A positive outcome after the festival would see participants more aware of not only their own levels of well-being, but also those of their colleagues. Empathy and a sense of work-life balance and basic needs would be fostered. A sense of mental and emotional well-being as a fundamental part of a healthy professional life, as well as the role that technology would play in that will be clearer to participants on individual levels.

**Comment by cubicgarden** [comment]
Sounds like it could fit with the talk about the happiness talk - https://github.com/mozilla/mozfest-program/issues/450. @cubicgarden

**Comment by cubicgarden** [comment]
@Melechuga Could we tie up this talk with the #450 talk? It would make a much stronger workshop and I could give you space in the Library for it
