### ISSUE TITLE
Git Hack

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#304]
**[ Google Spreadsheet Row Number ]** 278
**[ Facilitator ]** Sagar Chand Agarwal
### Description

Launching a prototype or developing some new product or getting involved in technologies requires teamwork and proper planning.

Teamwork without hassle is cool, when we properly segment our works and do each part according to its need.

In Open Source, coding forms an important part in a project be it code contribution, solving bugs and creating issues, git is used everywhere.

Under Mozilla, Marketplace is still in development and do not fetch a lot of contributions from individual, part of it  is unable to use git.

By this session, attendees will able to achieve the prospects of git and use it to contribute to Mozilla Marketplace and give rise to Firefox Os.
### Agenda

Knowledge of git will surely help in fetching newer contributors to Mozilla and helping them understand the flowchart of code process.

Our Session will be in a form of workshop and comprise of Discuss, Collaborate, Learn and Fun.

Learn and Discussion of git will go hand by hand. To make concept to sink in, fun sessions involving trivial quizzes, or working on real game projects by doing some implementions and many more.
### Participants

Like in earlier part, I threw some light on the progress of event as it will be pure learning, discussion and fun event.

I along with other cool peoples, will impart the working of git and it effectiveness in open source mission under Mozilla.

To ease out learning and getting in with new concepts, fun activities will be there to relax.
In addition to it, a collaboration task or fun project will be also included as a team project.

A session without collaboration is a vain, so that will be a part of it.
### Outcome

Getting everyone to know more about Mozilla and its open Source mission and how it achieves it by its products like Firefox, Firefox Os m WebMaker and others(quite a long one :) )

Plus, this workshop will also onboard newer contributors to Mozilla Marketplace and also they can teach their own community about git.

Knowledge getting transferred to other sources with mission of Mozilla.

**Comment by marcwalsh-zz** [comment]
cc @Melechuga

**Comment by sagaragarwal94** [comment]
Any updates on my proposal ? @marcwalsh @Melechuga @mmmavis

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
