### ISSUE TITLE
Mozfest News laboratory: editorial and technical collaboration under the microscope

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#305]
**[ Google Spreadsheet Row Number ]** 276
**[ Facilitator ]** Federica Cherubini
### Description

A hackday that brings together multiple news labs and journalists working on a common goal.
Journalists and news labs still often operate in silos within their respective organisations, a hackday run in the spirit of openness will be designed for these two groups to work side-by-side to really uncover the true potential of this kind of work. On the other hand, news labs have learned so much in the relatively short time they have existed. Yet, there is surely a bounty of common knowledge by now that remains closely guarded for obvious competitive reasons. For one day lets open the doors so that nobody has to start from scratch and we can build on everything that has been done before. The collaboration will foster the relationship between newsrooms and their news labs/R&D teams as well as the connection between news labs at different organisations. 
### Agenda

The session will be structured into three parts: an intro session to describe the event and its goal, set the topic of the hack and divide teams; the Collaboration/Hack part; the debrief to share lessons learnt during the day and to define a common ground for future interactions. 
The hackday will last between 6 and 8 hours. 
The session will be a learning opportunity and it will also represent an editorial as well as a technical challenge that requires the two sides to work together very closely. 
Potential hacking topics (to discuss): structured journalism, meta-tagging, archives. 
### Participants

We’re planning to gather beforehand at least 5 experts from each side: 5 from the news labs/techies and 5 from the journalists/storytellers side. This minimum number will assure the execution of the hackday. The bigger the audience, the more teams we will be able to form. 
Journalists, developers, interactive news teams, data journalists will be the natural audience for this session. 

Potential participants might include: 
BBC News Labs
The Times/Sunday Times’ news development team 
WSJ Europe 
New York Times R&D Labs
### Outcome

On the day: create a project that best shows off the potential of collaboration of this kind.
After the festival: Create a place or platform for news labs and journalists to share best practice and learning (GitHub style) in order to move news innovation forward at a faster pace. This platform might follow the path of the Journalists Toolbox project carried out by BBC News Labs, The Times/Sunday Times and Goldsmiths college.

**Comment by thornet** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
