### ISSUE TITLE
Corporatism and Intellectual property: where private ends and rent begins

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#306]
**[ Google Spreadsheet Row Number ]** 279
**[ Facilitator ]** Dejan Strbad
### Description

Idea of workshop is to present concrete examples (from technology, medicine...) where harm is done to the end user in the name of Intellectual property. Also, libertarian view on that matter will be presented and similarities with open source and free software movement. 
All of the participants will have opportunity to present their examples or discuss similar related matters that bothers them throughout workshop.  
Goal of the workshop is to build blog where all the reports can be presented and where people can ask for advice on matter of IP or dubious regulations in their countries. All of that is affecting free and open Internet and individual liberties. 
### Agenda

Session type: workshop
First, short presentation on topic would be held and few examples would be presented (global and one local from Croatia).
After that, participant would split in groups and work together on some of the other examples (e.g. from their countries), they would get forms that would direct them.
Once that's over, we would all together discuss and prepare reports for blog.
### Participants

Ideal would be not to have group of participants larger than 30. Though, presentation can be held for more than one group of participants.
### Outcome

Build blog with form so that people can ask, discuss or even report examples of IP abuses that affects their individual liberties. 
Also, desired outcome would be to connect people with different backgrounds to cooperate on the matter of liberties. Mozilla is much more than a technology company, it affects public policy as well, so it would be nice to connect two worlds  - Mozilla and European Students for Liberty, since we're fighting for the same cause.

**Comment by cubicgarden** [comment]
Sounds interesting @cubicgarden

**Comment by blahah** [comment]
Is this session no longer happening?

**Comment by thornet** [comment]
Unfortunately, this session is not taking place.
