### ISSUE TITLE
London Calling 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#307]
**[ Google Spreadsheet Row Number ]** 297
**[ Facilitator ]** Yu Liu
### Description

During the session we provide delegates with the understanding for the urgent need for the "London Calling’ Project, and to clarify the two major parts  - the Universal Mobile Project - handset software-defined-radio and the Universal Network Project - wireless mesh.  We want to ignite passion within the community around delivering an open source hardware/software combination for FFOS to assist the poor in the global south to access the mobile web on a completely-open-platform at a ideally free-cost. During the session we set out to define the model of the project, including setting plans for a detailed-prototype for a mesh routing protocol that can fit the topology and will also sketch out ideas for the SDR algorithm which runs behind the protocol. Finally, we want to galvanise a healthy open source community around the this Project - both across our London University Partnerships, but more importantly through the Mozilla community.
### Agenda

The ‘London Calling’ Project is all about bringing a genuine open mobile web experience that so many of us want into the ‘last mile’ to service the rural poor in the last unconnected  corner of the planet. To accomplish this we planned to build UNP - a community-owned mesh network to expand coverage and lower costs that the rural poor in the developing nations can afford. So during the session, we will brief the delegates on the need for the project motivations and its ultimate goal. We want to have a general discussion about architectural design and planning in order to achieve our goals. Since Mozfest is a developer conference for open web development, we are delighted to have this chance to make connections beyond our university partnerships so that we may create a deeper coalition with this talented developer community which can help turning this ambitious project into reality.
### Participants

With 5 participants (and based on skill-set) we would hold a panel discussion and brief each of the participants with the details of the project in order to attract their attention and try to bring them aboard so that we can push the project forward. For 15 participants, we plan to separate the project into different parts to apply a division of labour strategy. When it comes to 50 participants, we will have the idea of crowd-sourcing or maybe even having a hackathon so that we can produce some real deliverables for the project by the end of MozFest. 
### Outcome

In order to take the activities forward, we will establish regular MeetUps across our university partner campuses for all London-based developers and will also create a GitHub/Develop Open Source Project Management area on the web  that will allow registered participants to build a London Calling Project community online. We know the importance of keeping project members engaged. We also intend to have sprints with regular software releases so that we can have our early testers. Since this is going to be an open source project we certainly intend to use a crowd-sourcing model and also to engage the online community  and brand partners to support the project through our own crowd funding platform.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
