### ISSUE TITLE
Learn to prototype apps today, make a difference in your community tomorrow.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#309]
**[ Google Spreadsheet Row Number ]** 298
**[ Facilitator ]** Sandra Gonzalez
### Description

People in this session will 
Learn:
- To brainstorm ideas for apps that can make a difference in their community.
- Create a backlog of features for their app.
- Prioritized app features in order to create a Minimum Viable Product (MVP).
- Paper prototype the MVP.
- Research the idea by guerrilla testing it with people in the festival.
- Integrated feedback into their prototype after research
- Create a digital version of the app with Webmaker for Android (optional).

Make:
- A paper prototype of an app that would make a difference in our community.
- A digital prototype of the same app (optional).
### Agenda

This workshop will be structured with three hubs: Brainstorming, MVP and Design & Iterations

The idea is that each hub is self-contained and will help participants produce a deliverable that they can take to the next hub. 

Brainstorming Hub Agenda
To introduce brainstorming techniques and ways to identify opportunities to make a difference in the community via technology.
Deliverable: A problem statement.

MVP Hub Agenda
To help participants list ideas that would help solve the problem with the intention of selecting one solution which can be executed with the creation of an app. From this solution a list of app features will be created and then organized in order of priority. 
Deliverable: A list of features needed to create a MVP for an app that will address the problem statement.

Design & Iteration Agenda
To create design a solution that address the MVP features previously identified.
Deliverable: A paper prototype
### Participants

Because there are three hubs to this workshop, each hub will have at least one facilitator, which will help make the workshop very scalable.
Each person will go to the Brainstorming Hub first, and then move on to the MVP hub and finally to the Design & iterate hub. 
Any one waiting for help or instructions will be asked to help research the app ideas by volunteering to become testers for other participants (for about 3 min). 
The structure the workshop will allow anyone to come in at any time of the workshop and go through the three hubs at their own pace. There is not set start time, but it is recommended to come at least 30 minutes before it finished. 
All the materials for this workshop (mainly note pads, colour stickers and markers) will be provided by UX for Change.
An Open Badge will be given.
### Outcome

After the festival, anyone that have given this workshop a try will have a higher level of confidence on becoming app makers to solve challenges in their community. 

They will had gone through a full brainstorming, design and iteration process for an app idea. This session is also open to children and young adults. I also have a very keen interest to train teachers how to take this same workshop into their classroom. 

This workshop is inspired by the believe that every community has unique problems to solve, therefore it is absolute key to give them tools to learn the design process and not just hope that corporations or any other entity not closely related to the community would solves the problem.

I am certain this workshop will go a long way :)

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @Saallen @marcwalsh
