### ISSUE TITLE
Tree lines

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#31]
- Jamie Jackson
- "Tree line - act now on climate change, an Arts Council England funded project. 
  A co-production of digital artwork leading to a national exhibition. 
  Tree line brings art, technology and science together using people’s mindset shift, behavior change and participant's inspirational actions to create an incremental cultural resilience to climate change through digital art, learning through making.Artists will work with participants, exploring their actions on climate change. Drawing together moments of mindset shift / behaviour change and people’s inspirational actions to create high quality digital artwork for a national tour.
  Activity will be:
  • Relational artists running participatory workshops with Mozfest participants
  • Creation of the best contemporary artworks created for digital platforms
  Tree line will tour the resulting digital artwork installations using latest motion capture and touch screen technology. Created by leading national digital artists in partnership with some of the UK's best scientists and academics."

*Using Mass observation diaries as research material

**Comment by abbycabs** [comment]
duplicate of #144?

**Comment by Saallen** [comment]
@acabunoc yep we added as an example.- will close
