### ISSUE TITLE
Caught in the Web - How to understand how information you consume online fits together

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#310]
**[ Google Spreadsheet Row Number ]** 277
**[ Facilitator ]** Michael Martinez
### Description

Web articles lead people on long journeys of hyperlinks and tab accumulation. This spreads the information out and can hurt your ability to see how it all connects. The session will focus on the discussion of these information networks and how they can be visualized. There will also be a group oriented activity that will have people working together to design a tool/UI that can be used to aid in this process.
### Agenda

We would open the session with a brief discussion of the average person's experience with the web, especially in the frame of reading articles. This will then be guided towards the topic of information loss through the methods and practices of hyperlinking today. Some technology or practices that have taken a stab at fixing these problems will be presented and then critiqued. Then session participants will break up into groups to participate in a design exercise with the goal of creating a tool, UI, or practice that could help fix the problem. After the exercise concludes, each group would be given time to present their design and to talk about their approach. Time will then be allotted for discussion of the designs between the different groups.
### Participants

The discussion portion of the session would function relatively they same for larger and smaller amounts of people. If there are 50 participants, there could separate time allotted for small group discussions after the initial prompting of the session and the facilitators could move between small groups (of around 10-12 people) to help guide discussion. During the design exercise, groups of 5 or less would be ideal. If there are 50 people, then having 10 groups of 5 would produce a good amount of designs to discuss with a good amount of variety.  
### Outcome

Session participants will leave with a new perspective on how focusing on the bigger picture of news and information on the web can affect the outcome of the overall story or narrative. The designs that they create can hopefully inspire new projects and future tools to be made. The openness of this problem allows many different approaches to be made to try to fix it, so the diversity of experience and expertise of the participants will have people learning about new ways of tackling problems.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by ryanpitts** [comment]
Michael is part of Knight Lab, and already has travel support to attend MozFest.

**Comment by thornet** [comment]
cc @LauraReynal @secretrobotron to connect with research pathway.

**Comment by thornet** [comment]
cc @ryanpitts @LauraReynal to confirm in Github and in the schedule spreadsheet the status of this session.

**Comment by thornet** [comment]
This session will not take place.
