### ISSUE TITLE
Lets' make for MILE

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#311]
**[ Google Spreadsheet Row Number ]** 289
**[ Facilitator ]** Aman Sehgal
### Description

MILE is a project which is aimed to literate and enlighten the target audience about internet and the opportunities on it. The target audience is the one who is not aware or moderately aware with the internet resource.The main agenda of this session is to make web literacy teaching kits for teaching poor and underprivileged sections of society about internet. It will be a brainstorming session wherein participants will interact with each other and develop teaching kit in order to help underprivileged  people to explore seamless opportunities on web.
Goal : To develop at least 2 tools for different age groups i.e teenagers, youngsters, adults and elderly people.
### Agenda

It would be a workshop wherein the participants will be explained about the ground reality of internet education in India. Then, after explaining the scenario, the participants will be asked to contribute to this project by suggesting their ideas according to their experience and ideology. This project has been aimed to get more and more people on the internet. The participants will be asked to join this initiative whose design is based on Mozilla's Mission.
### Participants

I will be dividing participants into multiples of 5,7 or 10 as per requirement. To each and every group I would be giving a case study which will include a domain and the age group. They will then be asked to design web literacy teaching kits, keeping in mind that user of their tool has little or no knowledge about internet.
### Outcome

Post event we will share these tool kits with representatives of global open source communities who work for various web literacy campaigns. We will help them in conducting workshops for underprivileged people so that they can make use of internet with better understanding and are aware of their privacy and security. On the other hand participants can continue building tool kits at their own place and help in community building that will act as a bridge between  the learners and the makers.

**Comment by amirad** [comment]
cc: @amirad

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
