### ISSUE TITLE
[Student Shark Tank] Come bring Firefox into more schools!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#312]
**[ Google Spreadsheet Row Number ]** 280
**[ Facilitator ]** TJ Lee
### Description

Session will ask participants to get creative and strategic about bringing the presence of Mozilla and its products to more college campuses. We will share marketing best practices, public speaking tips & tricks, the how-to in becoming a student leader for the Web at their school, and more!
### Agenda

Participants will receive an intro to Mozilla & our products & the student program. We'll then dive into fun and interactive marketing and public speaking exercises. A brief case prompt will be presented: "If you were a Firefox Student Ambassador, how would you go about bringing Mozilla mission & products into your school?" They will then split up into groups to work on a campaign idea that would help Mozilla connect with more students at colleges around the world. Students can get very into it, coming up with club names and designs, new event festivities, and more! From super effective to downright wacky ideas  - let's have the students decide! Groups will present their campaign at the end.
### Participants

If there are 5 participants, they will work as a group to come up with a more elaborate plan from pre-planning to logistics to execution. 15 participants in 3 groups, and 50 in 10. But if we reach participation, presentations at the end will be a lightning pitch round!
### Outcome

Goal is to encourage more students to bring Mozilla mission & values back to their school in a more physical form - events, boothing, fliering, starting a student club. We all know they'll carry the ideas back but let's encourage them to take action on spreading them! University students who participate will have the opportunity to sign up the the actual program.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by thornet** [comment]
cc @amirad for connection to clubs pathway, @emmairwin @geroter to participation space.

**Comment by amirad** [comment]
Is TJ coming as staff to Mozfest? Would be cool to have her in our space though this session doesn't fit within the goals of our pathway.

**Comment by thornet** [comment]
cc @emmairwin @geroter to sync up with this and the participation space. Unsure of TJ's travel status.

**Comment by Saallen** [comment]
Tj is not being sponsored to attend under participation travel stipend cc @thornet @amirad

**Comment by Saallen** [comment]
I will not close this until I hear from you both

**Comment by emmairwin** [comment]
TJ will be at Mozfest and part of the Participation Space
