### ISSUE TITLE
The MozFest Soundtrack

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#313]
**[ Google Spreadsheet Row Number ]** 290
**[ Facilitator ]** Jonathan  Susman
### Description

We will have a series of "recording booths" set up throughout the university site for attendees to record their own piece of a song, create a new song, or just have fun with existing projects. There will be microphones for singing, electronic drum pads, synthesizers, keyboards, and other instruments for individuals to play/record with at each station. 
### Agenda

I see us creating a series of projects that will begin with simple rhythmic patterns from a drum pad. Individuals can walk up to a station and record on top of an existing project or create a new project. What I would love to see happen is have finalized projects submitted by a certain time before the end of MozFest and have a group vote on one that could be the theme song for the weekend. 
### Participants

We will only be able to accommodate one person at each station at each time, but we can impose a time limit at each one to ensure everyone gets a chance to play around with a project. 
### Outcome

We will comprise the tracks for the contest, but also after the event ends and find a creative way to present solid projects to the group via our website, youtube, etc.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
