### ISSUE TITLE
Open Practices for Scalable, Professional Contributions in Community-based Projects

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#314]
**[ Google Spreadsheet Row Number ]** 288
**[ Facilitator ]** Robert Friedman
### Description

This session will explore the ongoing challenge for community-based programs, non-profit organizations, and NGOs to make the best use of professional volunteers to achieve an impactful outcome. Participants in the session will identify the most scalable contributions to an open-source technology project (in particular) and co-construct a framework for engaging professional volunteers.

The perfect balance between a volunteer’s skills, availability and interests, and an organization’s needs is a tricky target to strike. When it is done successfully, there is a great mutual benefit to everyone involved. However, the most impactful contributions are those that provide a sustainable structure and enable an organization or project to scale. 

Together with Mozilla designers experienced in limited-contribution, professional volunteer experiences and Mozilla educators experienced with community-based projects, participants will create an open, shared standard for structuring a professional volunteer engagements to maximize the success, impact, sustainability and scalability of a professional volunteer contribution.
### Agenda

The session would open with informal conversation around exemplary models of professional-level volunteer contributions to community-based projects. Facilitators will have examples ready to share with participants about their own experience that demonstrate varying levels of contribution and successful outcomes.

Participants will work in small groups, rotating through each of the following prompts: 
- Identify the elements of an open-source or community-based technology project that have the greatest impact on a project's ability to spread or scale: these might be strategic plans, style guides, documentation, communication templates, etc. 
- Identify contributions that have the greatest appeal to professional volunteers, considering general interest and professional development potential;
- identify the parameters of a successful collaboration: relationship building, project scope, prioritization, etc.

To conclude, the whole group will review and consider http://catchafire.org as a model, then identify where the platform captures, misses or adds to their ideas in a SWOT style analysis.
### Participants

With smaller numbers, the session will simply work in fewer small groups that would focus on all three prompts simultaneously. Smaller numbers might also mean fewer audience-sourced examples, in which case facilitators would spend more time presenting and discussing their exemples.

Given more participants, we would host more small groups of four to five people, with the ideal number being about 15 participants. As the group size grew, we would continue trying to cluster in triplets of 5-person groups. In this instance, we would leave more time for sharing out at the end in order to have consensus building or continue the work after the session asynchronously through etherpads and social media.

If the group became too large, we would sub-divide the whole session into the three focus areas above, and then do a gallery-walk style share-out at the end to move people around and form new connections.
### Outcome

We hope that the main outcome is a more intentional strategic framework for bringing professional support into open-source, community-development projects from Mozilla or other partners. This framework will inform immediate efforts through Mozilla Learning Networks and we hope participants leave the experience excited to build their own local networks that can create compelling contribution opportunities.

We also hope that this work can begin to build an open-source platform that can compliment existing micro-financing and volunteer matching platforms to target the more specific needs of projects that are hosted on and make use of the open web. In this spirit, we envision that the session will also illuminate ways that designing for the open web is part of a successful, impactful, sustainable and scalable strategy.

**Comment by secretrobotron** [comment]
cc @secretrobotron re #51

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin
