### ISSUE TITLE
Empowerment -- A Weapon Against Trolls

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#315]
**[ Google Spreadsheet Row Number ]** 291
**[ Facilitator ]** Hallie Saber
### Description

Curt Schilling, Alanah Pearce and “Target’s Customer Service” are just a few people who’ve made news with creative ways to expose and shut down trolls on the Internet.  In this interactive session, iKeepSafe will share and request feedback on two projects designed to empower those who want to foster greater civility and respect online.  The first project, a partnership with Beyond Differences, is designed to address root causes of negative behavior by working with schools to promote inclusion and kindness.  The second project, working with the Tyler Clementi Center for Law & Policy at NY Law School, will provide education and resources to students, families, lawyers and judges as well as a first-of-its-kind law clinic dedicated to helping victims of online harassment.  During our session, we will explore ways to ensure these projects are inclusive and address real needs and will invite attendees to share their own ideas and projects.
### Agenda

Patterned like a giant working group, the session will provide each participant with an opportunity to interact and engage with each other. We will explore the genesis of the two iKeepSafe projects focusing on (1) combating social isolationism in youth; and (2) developing online harassment resources for all  (including reducing legal barriers).  We will ask for collaboration and ideas to ensure these programs are useful and responsive to need and will ask for input on additional ways we can address online harassment.  In contrast to a lecture-style presentation, our discussion will evolve organically as participants weigh in and personally respond to questions.
### Participants

We can accommodate the varying numbers of participants by being flexible with the format.  If we are less than 10, we can facilitate a round table discussion with the iKeepSafe member providing direction and ensuring each participant is able to share their insight.  If we have more than 10, we will have small group sessions covering targeted issues, allowing participants to share their ideas and evolving thoughts with the full group.  The iKeepSafe member will float among the groups to facilitate discussion and encouraging full group participation.  In either case, the session will highlight concerns, solicit input and share questions --transforming everyone in the room into both a student and teacher of the topics at hand.
### Outcome

All important ideas, observations and insights from the participants will be woven into the two iKeepSafe projects -- which are at the key stage of being tangible but still adaptable.  In addition, iKeepSafe will be looking for ways to highlight and support other approaches to online harassment from the other attendees at MozFest.

**Comment by Melechuga** [comment]
iKeepSafe
