### ISSUE TITLE
Webmaker App "A Digital Lo-Fi, No-Fi! Teaching Kit"

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#316]
**[ Google Spreadsheet Row Number ]** 293
**[ Facilitator ]** Mayur Patil
### Description

Webmaker App can be used as “A Digital Lo-Fi, No-Fi! Teaching Kit” for people who want to teach the web offline. Access to computers, projector or any other digital devices may be an issue sometimes. But we can overcome that if replace those digital devices with our smart phones. Majority of the organizers have smart phones so they can use the WEBMAKER APP to create integrative learning apps and teach the kids.
Text, Images and navigation buttons can be easily added in the app. That will help us create interactive learning application.
Demo app on the topic:  What are computers? 
App Link: https://beta.webmaker.org/#/project?user=57508&project=22177

Demo app on topic: How Email works?
App link: https://beta.webmaker.org/#/project?user=57508&project=21438
### Agenda

Interactive Learning is fun and impactful. So it necessary to make the learning process more interactive and creative. Webmaker App is a best option. Webmaker app will allow the educators to add images and text for explaining particular topic.

Webmaker App can be used to represent the following:
1)Educational topics
- Computer knowledge
- Environmental science
  2)Story telling
- Mythological stories 
- Historical stories
- Character building stories
  3)Comic book creation

All these topics can be represented in a digital interactive app using the WEBMAKER APP.
### Participants

A Booth system is a best option for accommodating any size of the crowd. We can also keep a handson for the attendees.
We can give themes or topics to the attendees and ask them to create a interactive app for that particular topic.
We can demonstrate the best apps on a screen as the webmaker apps can also be viewed on desktop browsers.
### Outcome

1) Great number of learning apps will be created and those apps can be used or remixed for future #teachtheweb sessions. 
2) Parents/teachers can use this app to teach their kids.
3) Webmaker app will serve as A Digital Lo-Fi, No-Fi! Teaching Kit for the #teachtheweb events.
4) We can get live feedback and suggestions from the attendees that can help us improve the product. 
5) Users of the webmaker app will increase.

**Comment by chadsansing** [comment]
cc @chadsansing
