### ISSUE TITLE
Programming without code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#317]
**[ Google Spreadsheet Row Number ]** 287
**[ Facilitator ]** Heather Billings
### Description

The goal of this session is to teach people how to think about programming. Most "learn to program" sessions get caught up in syntax and language choices, when, in reality, programming's central necessary skill is structured thought. But the concepts behind writing code are, at their core, logical constructs.  We will start with basic concepts like variable assignment, if statements, and loops. If time allows, we will work through some more complex problems that require putting together multiple programming concepts.
### Agenda

This session will introduce first by demonstrating how to think about the programming concept. Then participants will have a chance to break pre-prepared example problems down into logical steps that a computer could execute. We'll use a variety of activities to break these problems down.
### Participants

With a small number of participants, we will work through each problem together. With larger numbers of people, we will break into groups and spend a few minutes on each exercise before we debrief and move to the next one.
### Outcome

I think this is a good basis for people who want to learn what programming is and how it works, but may find it intimidating. By learning the logic before the syntax, my hope is that they will be encouraged in future code-writing endeavors when everything breaks because they missed a semicolon.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by ryanpitts** [comment]
Heather is part of Knight Lab, and already has travel support to attend MozFest.
