### ISSUE TITLE
Regenerate Neighborhoods

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#318]
**[ Google Spreadsheet Row Number ]** 283
**[ Facilitator ]** Alexander Fishman, Regenerate Neighborhoods & Civic Artworks, @djsardine @RegenNeighbrhds
### Description

Let's hack civic engagement for youth. Civic decisions on the local and national level directly impact young people's lives and their built environment. Use an innovative digital platform tested by Chicago youth, to tackle the built environment challenges of your neighborhood. Give feedback and share your insights on practical ways that networking youth can empower them. Experience the learning in real-time and share feedback that will impact youth today.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by cubicgarden** [comment]
Sounds like it could fit with something I'm about to post @cubicgarden

**Comment by Zebetus** [comment]
@EPIKhub Once again a great way to get youths thinking about their greater community
