### ISSUE TITLE
My Experiments

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#319]
**[ Google Spreadsheet Row Number ]** 273
**[ Facilitator ]** Anoop George Muttath
### Description

Reaction of chemicals is very dangerous we cannot test what will happen when two chemical react it may cause sever accidents. our idea helps to solve this problem. 
### Agenda

We will divide our team different group. it will include  fun ,matter ,games and much more...
### Participants

No matter whether 5 or 150 we have professionally qualified team. we will take care lets see what's gone to be happen.
### Outcome

We can provide safety analysis of chemical reaction without affecting human or those who are doing experiments.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
