### ISSUE TITLE
Making Online News More Engaging

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#320]
**[ Google Spreadsheet Row Number ]** 285
**[ Facilitator ]** Talia Stroud
### Description

Online news sites serve as a way for people to stay connected with their communities, but many are not engaging with their readers like they could. So how do we improve audience engagement?  In this session, the Engaging News Project will share the latest research on strategies for improving engagement on news websites. Our research has examined topics such as the use of interactive quizzes, the effects of homepage design, and engagement techniques for comment sections, to name a few. We also will have time to brainstorm with participants about other ideas for improving engagement. 
### Agenda

We will spend the first half of our session, which will be formatted like a workshop, sharing our strategies for improving engagement. We also will demonstrate how to use the free tools we offer – because all the tools are available on our website, participants will be able to try them out during and after the session. For the second half of the workshop, we will facilitate a brainstorming session where participants can share ideas on audience engagement. We have hosted two News Engagement Workshops with digital leaders over the past year which have been well-received. We would base the second half on the successful techniques we developed during these workshops.
### Participants

The first half of our session will be the same regardless of the number of participants. For the second half – our brainstorming session – if there are fewer participants we will brainstorm all together, and if it is a larger group we will split participants up into smaller groups. 
### Outcome

After the workshop, we see our participants bringing the ideas and tools we share back to their newsrooms or organizations, possibly leading to them to make changes in their engagement strategies. For us, we hope to leave the festival with ideas for future research projects.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
