### ISSUE TITLE
Frontend development with Node.js and Asciidoc

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#321]
**[ Google Spreadsheet Row Number ]** 299
**[ Facilitator ]** Thomas Parisot
### Description

The main goal of the workshop is to learn about frontend development using Node.js. The participants will learn by designing and writing the content of a chapter. This chapter will be part of a book available under Creative Commons license.

Through the session, participants will learn about frontend development tooling, browser testing, automation process, continuous integration, package management, sharing code between Node.js and the browser (isomorphic/universal JavaScript), codebase optimisations, compiling and distributing code and assets.

Aside of the technical knowledge, attendees will experience and learn about technical book authoring with the help of GitHub and the Asciidoc format… and that it is not necessary to be an expert to contribute: questions will help to clarify points or to surface them.
### Agenda

The workshop will have an ideal duration of one hour and a half (90 minutes), organised as below:
- 5 minutes of context, presentation and guidance
- 10 minutes for ideas/topics proposals which fit in these sections:
  -- tooling (Less, Sass, Grunt etc.)
  -- universal JavaScript
  -- testing
  -- project workflow
- 5 minutes to split into groups of common interests around the above topics
- 60 minutes of group work around the most voted proposals
- 15 minutes retrospective where each group presents the findings of their work
### Participants

Because of how the session is organised (cf. previous question), the content structure (sections) roughly even groups will be is organically distributed around each topic. The number of groups will depend on the number of participants.

We will take care to balance the knowledge base across the groups – by either making experienced developers responsible for steering their group, or the session organisers to help facilitate groups which lack experienced developers. The facilitation can be done through giving a starting point and other leading questions to address.

If there is only a small number of participants, it will not be detrimental: a single group will be made to explore one or two topics during the session.

However if there is a large number of participants, they will be split into an adequate number of groups (max 7 people per group) which will work on different topics.
### Outcome

Participants will leave with a great understanding of what is possible with Node, frontend development and where to go next in their learning process. They will be able to reuse the knowledge they gained at work or for their personal projects. Eventually, additional resources can be communicated to investigate similar or complementary areas of frontend/Node.js development.

Secondly, the content produced by participants will be accessible as a GitHub repository. The content will be either Asciidoc files, JavaScript examples, questions and suggestions through issues and comments. A more readable version of the repository will be published automatically as a static website.Participants will be able to continue contributing to this repository.

Participants will also equally benefit from ‘royalties share’ of the aforementioned published book. And each share has to be redistributed to any member of the Node.js community of their choice (npm publisher, Node.js contributor, Meetup organiser etc.).

**Comment by Saallen** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
