### ISSUE TITLE
Connecting your community - Why we chose Discourse

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#322]
**[ Google Spreadsheet Row Number ]** 286
**[ Facilitator ]** Leo McArdle
### Description

We are in talks with MozFest organizers to host a Discourse instance as the online forum for MozFest. This session works better if that is the case, but we can still use the Mozilla Community Discourse as an example. This session would allow people to learn why we chose Discourse, give feedback on their experience with it, and learn a bit more about how it works. It will also focus on the benefits of a good communication tool, and the process of choosing the right one. Should they try Discourse for their community, or will something else work better?
### Agenda

We would start with a fireside chat Q&A about what people liked, didn't like, and what they couldn't figure out how to do. First, we'll focus on how having a tool helped enhance the conference experience and helped people stay connected before and during MozFest. Then we'll focus on the specific features of Discourse that worked and didn't. During this portion we can emphasize the benefits of choosing an open source platform that we host ourselves and control. This can lead into discussions on alternative tools as well as potential improvements. We would then break into groups, some focusing on choosing tools, and some focusing on designing the improvements people would most like to see.
### Participants

With many participants we may use the good old post-it trick to brainstorm questions and feedback for the Q&A and then address the popular points as a group. With a smaller session, we would get to the break-out groups sooner, and try to have groups address more than one topic.
### Outcome

Our participants should have a better understanding of the impact made to community when communication works well. They should also have some good ideas on how to improve communication within their communities, or be inspired to use a tool like Discourse if they aren't already. As session organizers, we want some real world feedback that we can apply to the Mozilla Community Discourse, and hopefully even attract some interested developers.

**Comment by marcwalsh-zz** [comment]
cc @Melechuga

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
