### ISSUE TITLE
Fostering Healthy Relationships as a Foundation to a Civil Online Environment.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#323]
**[ Google Spreadsheet Row Number ]** 295
**[ Facilitator ]** Marsali Hancock
### Description

At iKeepSafe, we want to foster a civil, respectful and healthy online environment for all.  We believe education is a key element in reducing sexism, racism and aggression online and offline.  For this reason, we partnered with the Center on Media and Child Health at Boston Children’s Hospital, to create a K-12 curriculum for Healthy Relationships.   In this interactive workshop, we will explain the research and methodology for the curriculum and will encourage the participants to share their thoughts and ideas for (1) activities to make the lessons come alive and (2) to help identify and create other resources for schools. 
### Agenda

Patterned like a giant working group, the session will provide each participant with the matrix for the iKeepSafe Healthy Realtionships K-12 Curriculum.  We will explore the research supporting the content and the activities in the curriculum and explain the critical need for evaluation of effectiveness.  We will then ask attendees for feedback -- substantive (such as ways to improve, ideas for activities and/or themes to include) and nonsubstantive (ideas for distribution).  We will also seek to crowdsource ideas for additional ways to ensure the educational system is equipped to foster healthy relationships in the offline and online world.  In contrast to a lecture-style presentation, our discussion will evolve organically as participants weigh in and personally respond to questions.
### Participants

We can accommodate the varying numbers of participants by being flexible with the format.  If we are less than 10, we can facilitate a roundtable discussion with the iKeepSafe member providing direction and ensuring each participant is able to share their insight.  If we have more than 10, we will have small group sessions addressing the targeted issues and allowing for them to cover and report to the full group their ideas and evolving thoughts.  The iKeepSafe member will float among the groups to facilitate the discussion and encourage full group participation..  In either case, attendees will help highlight concerns, answer questions and share feedback, --transforming everyone in the room into both a student and teacher of the topics at hand.
### Outcome

In addition to sharing the curriculum, we hope the attendees of the festival will be sharing the core concepts supporting the curriculum to create additional resources that will be effective for youth and adults in a variety of settings (e.g. youth organizations, support groups and businesses) about fostering a civil and healthy online environment.

**Comment by simonaramkisson** [comment]
Unable to attend due to funding, removing Voices of Diverse Leaders voice label 

@marcwalsh @Saallen

**Comment by MozStacy** [comment]
Hallie Saber will be attending for iKeepSafe.  She has advised that they need to reduce to one session, so this one will not be in play.  She will be presenting "Empowerment, a Weapon Against Trolls."

**Comment by Melechuga** [comment]
@jvallera Do you still want this session in your track? Her travel is covered so she'll be there. We've asked her to focus on a different session, but you can reach out to her for this one if you'd like.

**Comment by jvallera** [comment]
@Melechuga we are pretty full so not sure if we have room for this. @simonaramkisson what do you think?

**Comment by simonaramkisson** [comment]
@Melechuga @jvallera We are pretty full and we already told them that we couldn't provide funding initially (we didn't allocate them any of our 3 travel stipends). I think we are going to pass but it is great that they are going to be there.

**Comment by Melechuga** [comment]
@simonaramkisson @jvallera Thanks! I'm going to close the issue then.
