### ISSUE TITLE
Mine your space

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#324]
**[ Google Spreadsheet Row Number ]** 296
**[ Facilitator ]** Shagufta Gurmukhdas
### Description

This session is to teach people how to mine the web, especially the social networks to extract information. I believe, if people actually get down to mining and getting their hands dirty with this experience, then only will they clearly understand the negative side of it i.e the risks associated in the cyber world regarding the privacy and also the mindsets of hackers and web miners who can get private information through this. Thus they understand the importance of keeping information secure and private even on social networking sites like facebook or twitter in which people generally trust too much.
### Agenda

I will be teaching them how to mine the big data on twitter, facebook, LinkedIn, emails(especially gmail), GitHub and how to find out who is talking to whom about what,how often, etc. This will lead them to realize how the web works and what all can be mined without even our knowledge. Then there will be open discussions with everyone talking about there viewpoints and/or solutions.
### Participants

This session is suitable with any number of people as audience. If the number of participants are more, they will be forming groups and exploring each other's cyber space on the web and it will be even more fun. The discussions can be debates among the groups.
### Outcome

The major outcome will be that other than actually knowing how to mine the web, the participants will know the negative sides of it, and will understand the importance of privacy and security on the web. The participants will learn the importance of keeping their data safe and will better appreciate all this in the future. I, as a true Mozillian and woman Rep, understand the importance of it the most and  am determined to share this knowledge among people and accomplish Mozilla's mission of web literacy.

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
