### ISSUE TITLE
Getting down with GitHub

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#325]
**[ Google Spreadsheet Row Number ]** 300
**[ Facilitator ]** Phillip Smith
### Description

[Here’s the session in a nutshell: https://raw.githubusercontent.com/phillipadsmith/2014.phillipadsmith.com/master/files/colonize-github-100px.jpg ]

What would it take to simplify and unlock the collaborative power Github for all? 

Today, Github is virtually everywhere. It’s become a part of most developers’ daily lives, and is increasingly spreading to the lives of non-developers too. From civic hackers, researchers and policymakers to educators, journalists and project managers, it seems like the whole world is “going Github.” 

The problem is: Github is still surprisingly hard for most everyday users to unlock. Non-technical users hit big barriers when trying to understand what Github is all about. And even experienced users struggle to keep up with all the new features, integrations, and innovations. 

The goal of this session will be to brainstorm and hack on solutions to that problem. 

We’ll map out Github’s territory, ask the question “What if…?,” and explore what’s possible in this new world of open, networked, co-creation.
### Agenda

In true MozFest fashion, developers and techies will work side-by-side with non-techies to learn directly from each other.

In this 60-minute workshop, we’d kick off with a mapping exercise, aimed at collectively capturing everything we know about the current terrain: from organic Github knowledge memes like the “Awesome Lists”, to the best learning resources for beginners and experts, to hidden gems and tricks for making Github do more.

From there, we’d break into two or more groups to tackle questions like: “How could Github be easier for beginners?” “What could we grow in Github’s fertile ground?” We would use small group conversations to build momentum, Idea Rating Sheets to collect and improve ideas, and an Etherpad to capture the session outcomes. Then eventually move the distilled outcomes to Github (of course!). 
### Participants

As far back as Penguin Days and more recently with Hacks/Hackers, I’ve facilitated groups both large and small.

The mapping exercise and Idea Rating Sheet exercise are designed to work with a group of any size. For the mapping exercise, we would work in groups of five participants -- each group developing it’s own mini-map and then reporting back to the larger group. This model can scale to accommodate any size -- if there were only five participants, we’d have one group and more time to work on the entire map within that group. If we had 50 participants, we’d have 10 groups of five and would plan more time for the reporting back and making the big collective map. 

Idea Rating sheets are great for collecting improvements and feedback with a large group. But I’ve also used them many times with smaller groups of five people.
### Outcome

One important outcome would be an evolving “map” that lived on Github. It would be similar to the “curated list of awesome lists” (https://github.com/sindresorhus/awesome) and would focus on the theme of Github itself: Where are the best tutorials and entry points for beginners? And what are the biggest _gaps_ or current needs within that list? What still needs to be written, built, or developed? Flying our pirate flag on Github will help to attract contributors who are similarly obsessed with the coming Github World Order.

An aspirational outcome would be to take the highly-ranked ideas from the “What more can we grow in Github’s fertile ground?” question into hands-on makers sessions at Mozfest, agitating for participants to start prototyping new tools, services, and so on. A Github-powered tool as worldchanging as Bostock’s bl.ocks.org could be the next thing to come out of Mozfest.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter current challenge for community contribution to curriculum  / relevant.

**Comment by OpenMatt** [comment]
cc @openmatt

**Comment by emmairwin** [comment]
Last minute add to our pathway - and space.

**Comment by OpenMatt** [comment]
I'd like to re-title the session to: "Getting down with GitHub", but I don't seem to have permissions for that. @mmmavis do you?

**Comment by OpenMatt** [comment]
We're meeting w. @emmairwin Wed to discuss. + Phillip and I will work on a  blog post to have published pre MozFest

**Comment by ldecoursy** [comment]
cc @ldecoursy

**Comment by emmairwin** [comment]
@OpenMatt - noted, and also updated in our data source for the Mozfest scheduler to "Getting down with GitHub"

**Comment by Mte90** [comment]
I'm interested to help for that session :-)

**Comment by phillipadsmith** [comment]
@Mte90 Great! :+1:  Would you like to meet up with me and @OpenMatt tomorrow to do a little sprint on the session format? If so, let me know the best way to get in touch with you to organize.

**Comment by Mte90** [comment]
Ok there are no problems ☺

**Comment by phillipadsmith** [comment]
@Mte90 If you're keen to help with some planning, come find us in the "quiet zone" of the library 4th floor.

**Comment by Mte90** [comment]
Actually I am at the meeting when finish I arrive.

**Comment by Mte90** [comment]
I am in the library

**Comment by Mte90** [comment]
Where are you?

**Comment by phillipadsmith** [comment]
@Mte90 Ack! We moved upstairs! On the 5th floor "participation space" ... look for a sign with our session name!

**Comment by phillipadsmith** [comment]
For anyone hoping to attend or help out, just look for the sign!

![getdownwgithubsign](https://cloud.githubusercontent.com/assets/34128/11000686/1281ea66-849b-11e5-8905-3f68c28fa17e.jpg)

To find out what we're up to, start here:
http://phillipadsmith.com/2015/11/getting-down-with-github.html

**Comment by phillipadsmith** [comment]
Some initial ideas on "cupcakes" that we could prototype this weekend:
http://phillipadsmith.com/2015/11/help-us-bake-tasty-github-cupcakes-at-mozfest.html
