### ISSUE TITLE
Neither Pod nor Cast: designing the future of podcasting

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#326]
**[ Google Spreadsheet Row Number ]** 281
**[ Facilitator ]** Joe Germuska
### Description

In our session, we'll consider how far we've come from the days when iPods were the bomb and informed the name of what's now the hot new medium. Gone are the days when audio file downloads needed to be scheduled overnight. Are we ready to move beyond MP3 files?  And how can we do all of this with open standards? By the time we're done, we'll have descriptions of one or more possible evolutions of podcasting. Some of the ideas may even become fodder for future projects at Northwestern University Knight Lab.
### Agenda

The session will be a design workshop. At the beginning, we'll take the measure of the room, regarding who among us consumes podcasts and who might create them. We'll discuss unique characteristics of the form compared to other media: when and how do we listen? What annoys us about podcasts? Why do we not talk about video podcasts? As creators, what do we wish we could include in our podcasts? What kind of analytics would make things work better? 
### Participants

The design workshop model adapts well to groups of various sizes. Once we get on the same page, we'll split up into groups of 4-6 to dig deeper on specific topics. If we get up to as many as 50 participants, we will probably make the groups more like 8 people.
### Outcome

As director of Northwestern University Knight Lab, I'd like to see media creators come to agreement on standards that enable a healthy balance between creators and the audience, not to mention tool makers, distribution facilitators, and financial backers. As a relatively new medium, podcasting feels like a domain where such standards could be described and adopted with less friction. Knight Lab is interested in furthering the conversation, and where it makes sense, we can contribute staff skills to standards coordination or building prototypes.

**Comment by Saallen** [comment]
cc @ryanpitts

**Comment by ryanpitts** [comment]
Joe is part of Knight Lab, and already has travel support to attend MozFest.

**Comment by ryanpitts** [comment]
Journalism is accepting this session.

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by cubicgarden** [comment]
I am interested as part of the future of radio... @cubicgarden

**Comment by ryanpitts** [comment]
Joe is a great facilitator, this one should be really good @cubicgarden!

**Comment by ArtsAward** [comment]
@EPIKhub Possible Arts Award pathway out from the Youth Zone
