### ISSUE TITLE
The Expressive Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#327]
**[ Google Spreadsheet Row Number ]** 301
**[ Facilitator ]** Kawandeep Virdee
### Description

Many of our experiences on the web are mediated by capitalist values around products and commerce.  Furthermore, technical tools are seen as means to solve problems.  How might these tools and technologies be used for expressive means? What exists now, and what could exist if creativity were valued more? The goal is to observe, create, and share sketches of expressive media on the web - to allow us to express ourselves and tell stories in more ways, from simple noisemakers to rendered complex narratives.
### Agenda

The session is a workshop. Participants will be split into groups of 6, and will go through a series of exercises. Part I: Existing inspiring and expressive apps (What is the technical inspiration, and the more creative expression in it?) Part II: Underserved technologies. Brainstorming web technologies that may be underserved for expressiveness. Part III: Idea jam on tools and experiences to be built (VR, mobile, realtime, physical computing + the web) that include the open web. These ideas will be sketched and shared via twitter and instagram. I run a whimisical workshop at Brown/RISD on prototyping products, and would love to focus the theme on the open web. 
### Participants

Because it is based on groups of 5-6 it can scale accordingly. If the total participants is 5, it will just be like having one group.  
### Outcome

I hope to see people looking at web tools not as a means to solve problems, but also including the ability to be expressive and creative together. What are other ways that I can be seen, interpreted, and interacted with on the open web? How might this be a means of creativity? In the end, I am looking to cultivate absurd, surreal, and artful works involving the open web.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
