### ISSUE TITLE
Demonstrating autistic talents through Open Web Games

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#328]
**[ Google Spreadsheet Row Number ]** 302
**[ Facilitator ]** Fabienne Cazalis
### Description

~Participants are invited to create scientific video games aimed at understanding autistic talents~

Individuals on the autistic spectrum possess rare cognitive abilities. However, they are misunderstood, since research has so far failed to describe the full range of such skills.

Our citizen science project uses video games as a source of informative data on how autistic brains process information. 

As science suggests the existence of specific autistic perceptive and intellectual processing, we are using game mechanisms that target such processes in order to confirm their existence and measure their range. Using our open source video game engine RedWire.io, professional and amateur scientists can create such games and record their data using the open source game analytics tool RedMetrics.io. Games can be played online by individuals on the spectrum and by their neurotypical peers, yielding massive and unique data that can help us identify new skills.
### Agenda

-1- Short presentation of autistic cognition and neurodiversity
-2- Q&A
-3- Demo: presentation of RedWire.io and RedMetrics.io, presentation of existing games
-4- Hands-on: participants can 
**\* play existing games (and contribute to data construction)
**\* discuss hypotheses on autistic intelligence with the scientists from our team
**\* improve existing games
**\* create new games
**\* all of the above
-5- Wrap-up: sharing and discussion.
### Participants

Self-organization will be fostered. Session format can be adjusted to spontaneous interest of participants, be it work alone or in small groups. Our five facilitators will be able to accommodate any structure that the session will adopt. For larger numbers of participants (over 15), we will split into smaller groups of 3-5 for the 4th part of the session. We will then reunite the groups at regular intervals so that they can share what they have done.
### Outcome

Our research team will leave London enriched by news and original ideas, as well as by new games and increased data.
Participants may take home a sense of what citizen science can be, a better understanding of autism, a feeling of empowerment by valuably contributing to an ambitious project.
Participants will be invited to keep in touch with us and help us expand the project, by advertising it towards concerned citizens, as well as by programming new games and/or by playing our existing games.

**Comment by cubicgarden** [comment]
Could be interesting and fit with the library neurodiversity theme? @cubicgarden

**Comment by thornet** [comment]
I love the term "neurodiversity"!

**Comment by cubicgarden** [comment]
@Saallen and @marcwalsh I like it but the workshop doesn't work for the library sorry

**Comment by EPIKhub** [comment]
@Saallen Ill start a conversation with them and see where it might lead
