### ISSUE TITLE
Conservation: breaking the consumerist trends in the tech industry

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#329]
**[ Google Spreadsheet Row Number ]** 303
**[ Facilitator ]** Majken Connor
### Description

Most of us care about conservation in other aspects of our lives, but are at a loss for options when using computers and mobile devices. This session will explore ways to give users more choice over things like their data usage, power consumption and device upgrade cycle, and ultimately their effect on the environment. Participants will have the opportunity to form an advocacy group with us to shift the market from its hyper-focus on new and shiny over consciousness. 
### Agenda

The session would start as a fireside chat exploring the different aspects of conservation. Lessening the tech sector's negative effects on the environment is "big picture" but we know we're not going to solve climate change in this session. There are many "small picture" topics, like using less data, preserving battery life, and preserving the life of a device, all of which cost the end user and support corporate profits. We'll focus on the small picture ideas that have answers right now - like writing more efficient web sites, choosing apps that use less power, and break into groups to document solutions. My co-facilitator is a 15yo who can provide a counter-narrative to the stereotype that teens always want the newest, fastest devices. In reality many can't afford to keep up and just want their devices to keep working.
### Participants

5 participants who are passionate on this topic would be plenty. Rather than breaking out we can just huddle up, write down our ideas, and hit the ground running. 50 participants would be amazing, after the group discussion on the different aspects of conservation, we can split up based on area of interest to brainstorm problems and solutions in that space.
### Outcome

We are forming an advocacy group to promote the ideas encapsulated in this session. We'd like to have a start on some how-to and best practices guides. We'd also like to find like-minded participants to join the group. Participants should feel inspired to keep conservation in mind when making choices either making, or using tech, just like they do when grocery shopping, or choosing a vehicle and to speak up when they don't see valid options.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
