### ISSUE TITLE
[Pathway ] Mapping Your MozFest Learning Journey

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#33]
Participants will:
- Be able to map their unique MozFest learning journey 
- Know about Open Badges and badge-based learning pathways
- Be able to pledge a badge from anywhere in the world

The learning objective would be for each individual to map their own learning pathway and gain insight into their motivators for learning and engaging with MozFest. They would learn about how they can use Open Badges to develop learning pathways and recognise their learning and how to issue, earn and share badges using the Open Badge Academy. On top of this, participants will be able to pledge their own badges and add these to a world map.

Ideally we would like to enable continuation of the badge pledging from MozFest by creating a skin for our Badge the World map. This will allow people to pledge badges before, at and after MozFest and refer back to them as motivators to create their own badges. The Badge the World map would also act as a means of highlighting the learning taking place at MozFest 2015 and badge based activities going on around the world."
- [ ]  #36
- [ ]  #37 
- [ ]  #38

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by mattdigitalme** [comment]
Exact copy for Pathway:

There is a lot going on at MozFest and a lot to engage with. It can be challenging to know the best route through the festival to get the best learning experience from it. There will be an optimal pathway for everyone but this will be unique to each individual and can be difficult to identify. 

We will support people to identify their motivators for engaging with MozFest by providing tools and experiences. We will also recognise your learning and achievements with Open Badges.

After experiencing our pathway, participants will:

Be able to map their unique MozFest learning journey 
Know about Open Badges and badge-based learning pathways
Be able to pledge a badge from anywhere in the world

**Comment by mattdigitalme** [comment]
Twitter Handles:

@digitalme_
@mattdigitalme
@grainnehamilton

Github:

@mattdigitalme
