### ISSUE TITLE
Is the hyperlink dead?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#330]
**[ Google Spreadsheet Row Number ]** 305
**[ Facilitator ]** Meghan  Sali
### Description

Rapidly-changing digital policies across the world are contributing to the decline of the democratizing power of the hyperlink and its ability to create the interconnected information space that was imagined by Tim Berners-Lee. One such example is the ancillary copyright law implemented in Spain in 2014–a proposal that was rejected EuroParl for EU-wide implementation, but threatens to return with the drafting of updates to the Copyright Directive. To fight back against these policies, an international network of over 90 digital rights organizations, businesses, journalists and Internet users from 30 countries have convened under the banner of “SaveTheLink” to catalogue and push back against sustained threats to the link. In this session, participants will learn about new policies that make it easier for governments and corporations to demand and implement link censorship, and will help identify threats and brainstorm tactics/solutions to address these threats to the link in an interactive workshop.
### Agenda

We will open with an overview of the ‘right to link’ across the globe, touching on specific government policies and practices that threaten this right, as presented by session facilitators from OpenMedia (Canada), Creative Commons (USA), and IGEL (Germany), and Hodor.com (Iran). After introducing the participants to the right to link, we will begin a group brainstorming exercise, where participants can contribute additional threats to the link from their regional/national experience, crowdsourcing a  ‘threats-map’ that will feature on SaveTheLink.org. We will then move into smaller breakout groups where individuals will discuss (i) public messaging strategies, (ii) mobilization tactics for allies/advocates, (iii) communities of digital rights/open culture advocates who we can engage on this work, (iv) unreached audiences who can join our call to protect the open web. We see substantial overlap between this session and Mozilla's goal to "Build a Global Movement to Protect the Free and Open Web".
### Participants

Our initial overview of threats to the link will familiarize participants with the issue, offering a variety of viewpoints and examples of how the link is essential to accessing culture and information online. Subsequently, in small breakout groups, participants will brainstorm different strategies for communicating the threats posed by losing the right to freely link online. This will include public messaging, engagement tactics, and others identified above. With a greater number of participants, our facilitators will each help lead a breakout group on one of the above topics before we return to the larger group and report back on progress. Participants can choose a breakout group with a topic that most suits their area of interest. Post-session, the Save the Link network will prepare a post-mortem blog/resource to bring individuals who were not able to attend the session into the discussion.
### Outcome

By the end of the session, each participant will understand global threats to the right to link, and have access to educational resources and an action platform to defend the open web. The hyperlink facilitates the distributed power of the Web: but this essential tool is at risk. “Every day” Internet users - and those who advocate on their behalf - must be able to communicate how policies and practices will affect they way that we access knowledge and culture online. After this session, participants will be able to speak to the issue of link censorship in ways that are real and tangible to Internet users, and identify some of the leading threats to our right to link. They will also have helped to launch a crowdsourced map of threats to the link which will continue to be built upon by pro-Internet citizens across the world.

**Comment by cubicgarden** [comment]
Sounds interesting could work in the library @cubicgarden

**Comment by thornet** [comment]
cc @Melechuga as well. Reading the other facilitators are: 

Dr. Till Kreutzer, Founder, IGEL/Initiative Against an Ancillary Copyright (Germany); Timothy Vollmer, Public Policy Manager, Creative Commons @tvol (USA); Hossein Derakhshan, Iranian-Canadian blogger–hoder.com, author of “The Web we have to Save” @h0d3r (Iran)

**Comment by Melechuga** [comment]
Happy to label this within our pathways too (R-E-S-P-E-C-T and What's Your Policy?), but don't have space to guarantee travel.
