### ISSUE TITLE
Building a web literate planet with young environmental leaders

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#331]
**[ Google Spreadsheet Row Number ]** 308
**[ Facilitator ]** Jacob Caggiano
### Description

We are sustainability hackers who created the free and open source Que Pasa Riachuelo[1] and Hey Duwamish![2] community monitoring platforms in the most polluted areas of Buenos Aires, Argentina and Seattle, USA. We are the founders of a growing partnership to connect troubled watersheds across the planet with open technologies and web literacy training.

This is a session designed to empower ed tech professionals, environmental educators, and young sustainability leaders to first have a better understanding of open web ecosystems, and then learn to harness the web as a core component in addressing Earth's ecological crises.

People will learn about our curriculum with youth leaders from Seattle's low income South Park neighborhood, which runs along a polluted Superfund cleanup site. We will help participants flesh out their ideas and fork their own curricula. They can also make interactive maps like ours, it's all open source software ;)

[1]http://quepasariachuelo.org.ar
[2]http://heyduwamish.org
### Agenda

We will begin with the story of our collaboration between the Global South (Argentina) and the North (Seattle) - where two social entrepreneurs connected through Mozfest back in 2013. Two years later, we've both launched community mapping and engagement platforms for underserved neighborhoods affected by heavy pollution. We are now entering a new phase where we are training hundreds of youth to reclaim the lost identities along the troubled river using the open web as the platform for their voices.

After demoing our interactive monitoring projects, we will workshop the curriculum we are developing to link the dynamic online ecology with immediate challenges we face on planet Earth.

We will have technologists, storytellers, educators, and young leaders on hand to rapidly prototype open web solutions and catylize efforts to address ecological challenges in the areas that matter most to session participants.
### Participants

5: We dive deep into curriculum ideas and show front to back how open web technologies can meld with environmental education

15: We pair up technologists with young leaders and educators and get prototypes going

50: We divide the room by ecological region of interest as well as technology skill and community organizing experience. The more prototypes the merrier :)
### Outcome

Back in Seattle, we are working to change the school system through a group of teachers and students called "Sustainability Ambassadors." The goal is to replace classrooms and textbooks with outdoor neighborhood projects that involve tackling hard environmental challenges.

While the program is forward-thinking, it continues to lack a strong web literacy component. Many teachers feel intimidated or overwhelmed when it comes to explaining how the web works and how to self-design online tools and strategies to make big ideas come to life. We seek to change this.

We invite you to help us lead the evolution of environmental education and online organizing across the globe. We want to help Mozfest participants return home with working tools and a strong campaign plan, using web literacy as its core foundation. Most importantly, they will be a part of our growing network in Buenos Aires, Seattle, Ecuador, and communities along the Amazon.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by soapdog** [comment]
cc @soapdog -- I believe this could go under "Voices of diverse leaders"

**Comment by Zebetus** [comment]
@EPIKhub

**Comment by thornet** [comment]
cc @amirad as Jacob mentioned in another conversation he wanted to tie this workshop to clubs.

**Comment by amirad** [comment]
Jacob! Jacob! This session is super cool @thornet but our pathway is super full right now so can't take more sessions on.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
