### ISSUE TITLE
Game On! A Playbook for Building Learning Innovation Networks

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#332]
**[ Google Spreadsheet Row Number ]** 319
**[ Facilitator ]** Matt Hannigan, Sprout Fund, & Ryan Coons, Sprout Fund
### Description

The Remake Learning Playbook is an ambitious project to open source the project code for learning innovation networks. The playbook covers the theory and practice of building authentic local communities of practice; details the resources and strategies required to put networks into action; describes the impact on schools, museums, libraries, and ed-tech ventures; and, provides the tools to make the case for transformation to different audiences. This fast-paced, engaging session will give attendees valuable insights into Pittsburgh’s Remake Learning Network, identify new strategies for collaboration based on their experiences, and generate a “gameplan” with steps to build innovation networks for teaching and learning back in their home communities. Attendees will not be passive recipients of information, but rather active learners equipped with actionable plans upon leaving the session.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by matthannigan** [comment]
Hi, I'm Matt Hannigan, I'm the lead facilitator on this session. Looking forward to London!
