### ISSUE TITLE
Debugging Javascript on Mobile Browsers

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#333]
**[ Google Spreadsheet Row Number ]** 309
**[ Facilitator ]** Pankaj  Malhotra
### Description

The session aims to answer some of the questions and introduce tools to debug Javascript on mobile platform.

Introduce Javascipt debugging tools for mobile browsers. Live Demo of various tools like Weinre, Vorlon and JSConsole. Discuss their advantages and limitations.
Compare remote debugging protocol with JS Injection techniques.
Demonstrate tools like Valence + WebIDE and Chrome DevTools built over remote debugging protocol.
Discuss how Chrome DevTools can be extracted out of the Blink source and deployed locally for JS Debugging.
JS debugging solution for mobile browsers located remotely.

https://speakerdeck.com/bitgeeky/debugging-javascript-on-mobile-browsers
### Agenda

This is how the talk is going to be split over an hour.

(15 min) Introduction to JS debugging tools, using Javascript injection.
Apache Weinre, Vorlon JS, JSConsole, Adobe Edge Inspect etc.

(10 min) Remote Debugging Protocol Introduction. chrome://inspect demo and DevTools information.

(15 min) Taking DevTools out of the Blink source and deploying locally.

(10 min) Using Mozilla Valence + WebIDE for cross platform debugging.

(10 min) Doubts, Suggestions and Discussions.
### Participants

Previously spoken and gave sessions on a lot of conferences, have experience to adjust to audience size, agenda will mostly remain same but the talk will be trimmed down, more practical with less people, and more of talk with more people.
### Outcome

With increase in mobile ecosystems, there's a strong need about web literacy on mobile browsers. A developer must know his tools for the browser he's working on. 
After the session everyone will become familiar with tools available for debugging web applications on mobile browsers.
They can form a community and ecosystem around it and continue it further, there have been many projects on this before but no standard common debugging solution. 

One of the movements was initiated but didn't go much ahead was http://remotedebug.org/

It can possible bring enthusiasm to start participating in such moments that aim to develop cross platform solutions rather than developing for a particular platform.

**Comment by thornet** [comment]
cc @secretrobotron as possibly of interest re: open product development.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
