### ISSUE TITLE
Crowd Sourcing Facts in Journalism

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#334]
**[ Google Spreadsheet Row Number ]** 306
**[ Facilitator ]** Stefan Wehrmeyer
### Description

Talk crowd sourcing in journalism! Be it filling out questionnaires, annotating a giant pile of documents or help you gather facts around a complex topic – readers can help media organisations find stories. We want to share projects, tools and ideas and find ways to collaborate!
### Agenda

This could be a group discussion/workshop format with brief intro, project presentations, some idea sharing and then a breakout into smaller groups focussed on specific ideas with a summary of the results in the end.
### Participants

5: just have a friendly discussion
15: discussion group and workshop
50: presentation of crowd sourcing projects by the participants and then a moderated discussion
### Outcome

We want to connect with other crowd sourcers and stay in contact to collaborate on tools in the future. Setting up a mailing list around the topic (or promoting an existing one) seems appropriate. We will then send contact details around.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
