### ISSUE TITLE
Find and Create Your Own Geocaches!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#335]
**[ Google Spreadsheet Row Number ]** 307
**[ Facilitator ]** Laura Lantz
### Description

In the first part of the session, participants learn how to use their GPS-enabled devices to search for, discover, and log Geocache finds. In the second part of the session they learn the logistics and etiquette of hiding Geocaches for others to find, and explore considerations for designing satisfying Geocache experiences. 
### Agenda

The session runs in a two-part workshop format, with participants encouraged to arrive with the Geocaching app pre-installed on their GPS-enabled mobile device. Those who are new to Geocaching should definitely attend the first part of the session, while some experienced Geocachers may prefer to come for the second part only.
### Participants

With 5 participants, the session supports a high degree of participant/facilitator interaction and feedback. As the number of participants grows, the session format shifts to make more use of visual aids, breakout activity/discussion groups, and roving facilitators. In addition, those session participants who already identify as experienced Geocachers can be distributed among the breakout groups and invited to assist with facilitation in their groups.
### Outcome

By the end of the session, participants will see Geocaching as a way of using technology to reconnect with nature and become part of a playful international treasure-hunt. Those who were previously unfamiliar with Geocaching will know enough to continue their explorations independently. In addition, both new and experienced Geocachers will have made face-to-face connections through the session, which will encourage continued sharing and collaboration with one another through the worldwide Geocache community.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
