### ISSUE TITLE
“The story of the story: how to evaluate impact of stories online” 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#336]
**[ Google Spreadsheet Row Number ]** 313
**[ Facilitator ]** Alexis Wichowski
### Description

Stories can change minds. But with so many voices vying for audience online, it’s hard to know whether your story made a dent with either your target audience or the broader public. This session will share methods for evaluating the impact of stories online. Drawing on social science, statistics, and contextual interpretation, this session will share lessons learned from a decade of evaluating the impact of digital stories. Participants will examine a story that deals with a social issue they care about using these methods, and come away from the session with a deeper understanding into evaluating impact beyond metrics and anecdotes alone. 
### Agenda

PT I - BACKGROUND
1. What it is (background on science and art of evaluating impact of narratives online) 
2. How we do it (tested combination of quantitative and qualitative methods)
3. Examples speed-through that sum up process, including: 
- a story (e.g. news story, documentary, fiction film, TV  show, Internet meme)
- what social issue it highlighted
- how we measured it: quantitative methods
- how we measured it: qualitative methods
- results: what we can now say about the impact it had
  PART 2 – WORKSHOP
- break into groups according to social issue (participants  suggest topics, choose group)
- identify story to work from
- apply quantitative methods (NOTE – will not be scientifically valid – for demo purposes only)
- apply qualitative methods (“ “)
- rough results to indicate impact 
  PART 3 – DEBRIEF
- reflection on process
- surprises
- lessons learned
### Participants

This session can accommodate anywhere from 5 to 50 participants simply by varying the number of groups 
- 5 participants: 2 groups with 2-3 to a group
- 50 participants: 9-10 groups with 3-4 people to a group  
### Outcome

Evaluating the impact of stories is an emerging field, informed by new technology, new methodologies, and new forms of storytelling. This session could form a working group to continue sharing lessons learned as we continue to adapt the to changing evaluation tools that emerge and the evolving digital storytelling landscape.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
