### ISSUE TITLE
Modelling a local community for effective participation and sustainability

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#338]
**[ Google Spreadsheet Row Number ]** 310
**[ Facilitator ]** Emmanuel James San
### Description

Community is the heart of Mozilla, however, many tend to suffer from challenges of poor organization which in turn affects participation. In this session, we will develop effective models for organizing local communities. The models will help over come challenges unique to each community and build a stronger community.
### Agenda

We will begin with a given model and then hack it with the participants by delving into the peculiar challenges of their local communities. We will seek to understand, why it does not suit and how we can remodel it to be useful.
### Participants

In a case where we have more than 15 members, we will break up into small groups with similar challenges and each of these groups will come up with its own model that is most effective. 
### Outcome

Community organization models that suite different communities, especially in Africa and Asia. These models should make the formation and management of a local community more effective and drive more participation within Mozilla. The communities represented will also continue to work together to implement these models and support each other to be more organized and sustainable.

**Comment by amirad** [comment]
cc: @amirad

**Comment by emmairwin** [comment]
cc / @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
