### ISSUE TITLE
[Pathway] Research Pathway 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#34]
By following this pathway, people will learn about what it means to do design and ethnographic research. They will discover different methods (experience 1 and 2) and learn some tips to do it themselves and bring it back to their community (experience 3). 
- [ ] #39 
- [ ] #40 
- [ ] #41

**Comment by lauradereynal** [comment]
cc @secretrobotron @lovegushwa

**Comment by lauradereynal** [comment]
150 words 

This pathway is made of three design research experiences. 
- The research story: an exhibition where you can learn about our Global Web Literacy studies from Chicago, India, Bangladesh, Kenya and Rio.  You will be taken through a visual journey of our explorations. 
- Learning from our users: a session with Webmaker users. We will reflect on a few weeks of usage of Webmaker and learn what users think of our product. We will then engage in a co-design session to improve Webmaker.
- Collaborative toolkit: we will combine tips from various skillsets to ensure the success of your research project. This session is for everyone who wants to learn about design research and who wants to contribute to a set of guidelines and tips. How do we provide feedback to designers ? How to ask interview questions? How to do UX testing ?

**Comment by thornet** [comment]
This pathway is not taking place.
