### ISSUE TITLE
Architecting Against Online Harassment

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#343]
**[ Google Spreadsheet Row Number ]** 312
**[ Facilitator ]** Sarah Jeong
### Description

To begin thinking about online harassment as a technical problem as well as a social problem—one that can be both mitigated and exacerbated by technology and the technologists that create it. The framework discussed would empower creators, rather than leaving them to be helpless in the face of deep social ills that are reflected in online spaces. The session would summarize and build on top of my book, The Internet of Garbage, using the work of Randi Harper (GG Autoblocker) and Jacob Hoffman-Andrews (Blocktogether) as case studies.
### Agenda

The first half of the session would be a talk that sets up the problem and background, which some people may be unfamiliar with. This would be drawn from The Internet of Garbage. It would discuss both what online harassment looks like, its effects on people, how it disproportionately effects women and minorities, and the idea that harassment is similar to spam insofar as they can both be thought of as technical problems regarding unwanted behavior and content on the Internet. It would also discuss free speech concerns around both spam and harassment.

The second half would be a directed discussion centered around a case study that illustrates how technology can exacerbate harassment, what a technical solution to harassment looks like, the potential pitfalls around it, and the real benefits to users. 
### Participants

The fewer the participants, the more involved the second half would be—the session would be more of a discussion and less of a talk. The more participants, the more directed the discussion would become. At some point, the discussion would be curbed in order to keep things running smoothly.

5 - The first half (the background) would be tailored to the participants' understanding of online harassment, which might be quite advanced. The majority of the session would be centered on the case study.

15 - The first half would proceed as prepared. The second half would be a directed discussion.

50 - The first half would proceed as prepared. The second half would be tightly directed discussion of the case study.
### Outcome

Some participants would take this knowledge with them to build better platforms that incorporate these insights about online harassment to begin with, thus stymying online harassment before it becomes a problem. Others would create open source tools to help targets of harassment. 

Rather than waiting for society to "move forward," or for humanity to "become better," participants can actively go out and move the Internet forward to an egalitarian future that we have only dreamed about.

**Comment by ryanpitts** [comment]
assigned to the Digital Citizenship milestone, but we're also considering this for Journalism's "Community" pathway.

**Comment by ryanpitts** [comment]
Hi @Melechuga & @MozStacy! Curious about this one too -- since it's assigned to the Digital Citizenship milestone, we're just wondering if you've already decided to definitely accept this session.

**Comment by Melechuga** [comment]
Hi @ryanpitts, 
No decisions yet; we've just marked all potential sessions with the milestone "Digital Citizenship" so we can filter with this function. If you don't mind holding off until next week, I'm sure we can get through all the sessions by then. Thanks!

**Comment by Melechuga** [comment]
Could potentially include in the panel on women's harassment online; could also change the name of the panel to just Online Harassment, and have panelists discuss different experiences: https://github.com/mozilla/mozfest-program/issues/7

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin this for community builders

**Comment by ryanpitts** [comment]
Has this session been accepted? If so, that's awesome, Journalism would like to send people there from one of our pathways. If not, we'd accept it so it can be on the program.
