### ISSUE TITLE
Embracing the chaos of 21st Century learning

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#344]
**[ Google Spreadsheet Row Number ]** 321
**[ Facilitator ]** Cristol  Kapp
### Description

In 2014, I completely re-imagined my school library by creating the first elementary school library makerspace in my district by collaborating with the Chattanooga Public Library, the PEF, Leadership Chattanooga, and HiveCha. Initially, I wanted to provide my students with access to technology.  The makerspace is essential to the development of 21st Century Skills because it provides a space for students to explore, make, share, and grow as independent learners. 
Make: Create a design journal.  My journal is the catalyst for change.  Here, I curate ideas, record my learning, reflect on the process, and celebrate success and failures.
Learn: Disrupting the status-quo often brings chaos. To make progress in reaching dreams and goals you have to get comfortable with the chaos that comes with the process.  Chaos promotes questions: Is it really not working? Is this a failure or is it a pathway to future success? 
Do: Advocate for change. 
### Agenda

I’ll share my story of creating a library makerspace for my students. 
Participants will choose a platform for creating their design journals.  If possible, I would like to have some fun materials for them to create their own design journals.
Do: We’ll discuss the importance of advocacy in the midst of the chaos. Participants will be encouraged to consider the needs of patrons, students, community members and to speak up for those needs. 

This session will be part workshop and part discussion. 
### Participants

5-We’ll chat as we create our new design journals.  This journal is the catalyst for change and a place to make the chaos of change productive. 
15+After introducing my story, we’ll divide into smaller groups and chat while making our design journals. Guiding questions will be provided to aid the discussion. We’ll come back together to share ideas for advocacy. 
### Outcome

-Participants will leave with a dream journal as a place to curate ideas, record learning, reflect on the process. This is the place that serves as the catalyst for bringing change.
-Participants will leave with an understanding that embracing the chaos is part of the process of bringing change to the education community. 
-Participants will craft a plan for advocacy for 21st Century Learning and Web Literacy.

**Comment by chadsansing** [comment]
cc @chadsansing
