### ISSUE TITLE
Monitoring (deleted) tweets for the media

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#345]
**[ Google Spreadsheet Row Number ]** 316
**[ Facilitator ]** Basile Simon
### Description

Learn and share your solution to monitor (deleted) tweets and to give your results for journalists to find stories. Write your own Twitter scrapers, automate screenshoting, and expose the results on the web with blazing-fast GUI-based search.
### Agenda

We will present a fully-functional open-source toolkit, discuss the ethics (in light of the closing of Politwoops), and show how these solutions can be implemented. The workshop will use Python, MySQL and/or ElasticSearch as a reference, but solutions are quite identical in other languages, such as Node and Ruby. We can bring USB drives with the toolkits. Laptops recommended but not compulsory.
### Participants

With a small group, we'll hack some prototypes based on our toolkit and walk through the different solutions. With more participants, the workshop will be more about sharing, discussing the ethics, and debating the different solutions available for this monitoring. A large group will also bring a very welcome diversity in terms of programming languages, implementations, and points of view.
### Outcome

The ideas, links, and resources will be compiled in a Github repo/Gist for future reference. The participants will have a good grasp of what can be done in regards to accountability and transparency online and what tools are available to them. Hopefully, they'll take one of these back to their newsroom/office. Depending on the size of the group, it may already be ready to use! We'd be keen on seeing some kind of mailing-list about this topic.

**Comment by evaconstantaras** [comment]
Better for Tools, Analysis, & Storytelling track.

**Comment by ryanpitts** [comment]
Basile is based in London, so travel would not be an issue.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
