### ISSUE TITLE
Trickle down, trickle in & trickle up

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#346]
**[ Google Spreadsheet Row Number ]** 324
**[ Facilitator ]** Leo McArdle
### Description

Think about how to empower communities, not just manage them, through exploring the different paths knowledge can take between an organization and its community: teaching contributors established knowledge (trickle down), attracting contributors with the skills you need (trickle in), allowing contributors to experiment and bring new knowledge to the community from within (trickle up).
### Agenda

We want to introduce the concepts of "trickle down," "trickle in," "trickle up" and then ask participants to "interview" each other on experiences they've had with each concept, capturing the pros and cons of each. We'll also ask them to explore the concept they have the least experience with, and imagine how it could change the shape of their community.
### Participants

With a smaller group we'll ask participants to interview each other 1:1, with a larger group, we'll ask them to split into small groups, to manage the number of groups that are reporting back findings.
### Outcome

We're hoping to promote "trickle up" within Mozilla and other organisations. We want participants to have new ideas on how to empower, not just manage, their communities.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
