### ISSUE TITLE
Web Literacy Lesson Plan Jam

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#347]
**[ Google Spreadsheet Row Number ]** 326
**[ Facilitator ]** Cristol  Kapp
### Description

Participants will work together to design engaging lesson plans to teach the web. 
### Agenda

We will work together to design lessons based on best practices of instruction. We'll begin by reviewing the Web Literacy Framework. We will also review applicable technology standards. Finally, we will begin drafting lesson plans. 
### Participants

5 or less-we will choose one area of focus and work together to craft lessons for primary, intermediate, middle and secondary learners. 

15+ We will divide into groups based on areas of interest to draft lesson plans. 
### Outcome

Participants will leave with a collection of lesson plans ideas for teaching the web.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
