### ISSUE TITLE
Get your Flareon with Firefox OS

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#348]
**[ Google Spreadsheet Row Number ]** 322
**[ Facilitator ]** Pilar Huidobro
### Description

I've created a fun gameified health tool for Firefox OS:
I combined the easy to play element of Nekoatsume and the intense fun of Pokemon and created an on rail Pokemon game which calculates the steps you've taken  to create random Pokemon battle  encounters. The more you walk, the faster you'll catch them all!

I'd love to share the story of how I went from studying biology to pursuing my dreams of making a game. I'd like to share the problems I faced and demo the game to show others how easy and fun it was to make, and to inspire them to go out and make things too.
### Agenda

I would love to be able to show the app, basically how it works and even if anyone has firefox OS share it with them so they can play around with it and experience some of the features first hand.

I'd also like to share the problems I ran into, because I feel it's extremely important, especially for less-experienced developers, that we show our mistakes and how we over-came roadblocks, not pretend that it's all magic.

It would depend on how large the number of participants is but it would be a workshop/inspiring talk or chat.
### Participants

If there are more participants then the session would be more like a talk or a chat. If there are fewer (~5 participants) we could even hack on the game and add features or look into features that they find interesting. We could also work on their own ideas, if they're interested on expanding them.
### Outcome

I hope that this session inspires others to try their own hand at making fun apps and going after their dreams. I'll also be sharing the resources I used to create the game so that if someone needs help or resources for creating their own things, they'll have a nice collection to start with.

**Comment by marcwalsh-zz** [comment]
cc @cubicgarden @Melechuga

**Comment by Zebetus** [comment]
@EPIKhub Once again talking about getting youths involved with firefox OS and pokemon is as gooder way to do so

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
