### ISSUE TITLE
Build your own FM radio station for $25 and control it from your phone

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#349]
**[ Google Spreadsheet Row Number ]** 318
**[ Facilitator ]** Basile Simon
### Description

With a Raspberry Pi, a bit of wire, and a phone, learn how to convert your Pi into an FM transmitter for your house-share of community cafe, and load it with audio content that everybody in range can edit and playlist.
### Agenda

We'll bring along all the resources needed: the Modipy-based toolkit composed of a back-end and a front-end, and the web-app. It would be great to discuss the use cases and what we've done with the prototype.
### Participants

In any case, we'll walk through the tools themselves and their setup and installation, as well as through our open source code. With a small group, we'd create a couple of these radio transmitters and put them around the conference centre. With a large group, we'd change the focus to chat about the project and the perspectives it offers to a large news organisations.
### Outcome

We hope to see many of these local radio stations popping up! Hopefully it will also give ideas to news organisations to follow our projects aiming at helping underserved audiences reaching our content.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts
