### ISSUE TITLE
Comms protection for nomads

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#350]
**[ Google Spreadsheet Row Number ]** 317
**[ Facilitator ]** Basile Simon
### Description

Protect your online communications while travelling. Learn the basic rules, encrypt your data and your traffic... so you can finally use the hotel or the coffee shop's wifi hotspot.
### Agenda

After walking through the threats zeroing on the careless traveller, the workshop will be as hands-on as possible, offering participants several solutions that they can implement right away or toolkits they can deploy or set up before catching a plane. Laptops recommended but not compulsory.
### Participants

With less than a dozen participants, we would explain, prepare and/or set up VPNs and other basics for everyone. We'd expand the focus with more participants and discuss how to assess threats and travel safely by sharing experiences.
### Outcome

The ideas, links, and resources will be compiled in a Github repo/Gist for future reference. It would be great to find people to get involved in the support and creation of ever more user-friendly and simple tools to protect oneself. And hopefully, all participants will be more careful and better equipped and prepared to travel safely.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
