### ISSUE TITLE
Science X Kickstarter

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#351]
**[ Google Spreadsheet Row Number ]** 323
**[ Facilitator ]** Francois Grey
### Description

Science X Kickstarter was a weekend hackathon held at ITP, NYU Tisch School of the Arts in February 2015. During the hackathon, teams helped prepare 16 science projects for Kickstarter campaigns. Ranging from antimatter experiments to beer genomics, the projects have started to launch on the Kickstarter platform, with varying degrees of success.
### Agenda

This session is a fireside chat. Several participants in Science X Kickstarter and other science-related Kickstarter projects will share their thoughts on what makes a successful crowdfunding campaign, how important being open is for getting support, and what crowdfunding could mean for the future of scientific research.
### Participants

As this is a fireside chat, any number of participants is possible provided the room will seat them.
### Outcome

The purpose of the fireside chat is to share lessons learned, and answer frequently asked questions about crowd funding of research. Outcomes should include stimulating other science-related projects to launch on Kickstarter and similar platforms.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
