### ISSUE TITLE
Mozilla Festival East Africa

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#352]
**[ Google Spreadsheet Row Number ]** 325
**[ Facilitator ]** Emmanuel James San
### Description

In its second year, MozFestEA has become a major event in Africa and a key launch pad for innovation attracting participants/partnerships and sponsorship from accross the globe. 
This session will inform participants about the festival, what we achieved and how it impacted the community. It will also inspire those who would love to ship MozFest to their local communities on how to approach it and finally, it would allow for knowledge sharing on how to improve MozFestEA 2016 whose planning is already under way.
### Agenda

The agenda will include feedback from MozFestEA session lead about the festival planning, execution and post event activities, questions and answers from the participants. Discussions on challenges faced and brainstorming solutions. 
### Participants

After a general introduction with all participants, they will break into groups to discuss challenges and come up with solutions and ways to improve MozFestEA.
### Outcome
- More people eager to ship MozFest to local communities
- Solutions to the challenges encounter organizing MozFestEA
- More ideas on how to improve MozFest EA and London.

**Comment by thornet** [comment]
cc @amirad @emmairwin @geroter for consideration of how to support and improve large community-run Mozilla events.
