### ISSUE TITLE
Mozilla Participation Space

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#353]
**[ Google Spreadsheet Row Number ]** 330
**[ Facilitator ]** Mrinal jain
### Description

Participation team volunteers will focus on motivating people for  developing and being accountable for delivering on specific plans in 2016 to invest in the skills of Mozillians. This will involve creating amazing online and in-person learning and participation experiences that will help increase the impact of Mozillians (and potential Mozillians) and communities. 
Committing to an ongoing effort to build participation throughout 2016, 17 and many more years including action plans, being part of community calls and some reporting. People in this cohort will get regular coaching and mentorship.
### Agenda

These could include training sessions and workshops, onboarding, hackathons, meetups/gatherings, mentoring, or other creative participation ideas.
the community engagement team  volunteers will be in one on one discussion with the people present at Mozfest and we will  have lightning talks for individuals also.
### Participants

The participation team has more than 25 volunteers who have peak knowledge about the contribution areas ,this will help in dealing   with the ever-changing number of people  .
### Outcome

Being part of a global community of practice to build the skills and leadership of Mozillians.
the goal of the leadership team will be to find the impact contributors for Mozilla and also to create a lot of potentials contributors to Mozilla

**Comment by Saallen** [comment]
@geroter @emmairwin

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
