### ISSUE TITLE
Facilitating curiosity, fearlessness, and resourcefulness in non-structured environments

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#354]
**[ Google Spreadsheet Row Number ]** 336
**[ Facilitator ]** Kathryn Barrett
### Description

This session aims to encourage discussion and collaboration around self-directed learning and how private tech educators can facilitate curiosity, fearlessness, and resourcefulness in non-structured environments. Academic grading has influenced youth (9-16) to rely heavily on direction and framework from their educators, influencing them to lack in the development of the “maker mindset”: creating for the sake of creating, and not for the sake of evaluation. With so many makerspaces and collaborative environments popping up all around the world, we want to encourage youth to participate in tech-based exploration and play. At this session, we’ll focus on the following questions: how do we teach youth to embrace the maker mindset and explore different tools without structure? How can we, as tech educators, encourage youth to see the value and be driven to learn and contribute to the community? What kind of action plan can we create together to see this through?
### Agenda

To open up the session, we’ll compare structured learning environments to non-structured learning environments (using pros and cons) and discuss some of our own personal experiences as tech educators. Using sticky notes, we’ll ask the group to quickly jot down adjectives that describes a kid who has a maker mindset and what that might look like. Workshop attendees will then be able to split off into smaller groups to discuss action plans for how to teach and encourage: 1) curiosity 2) fearlessness 3) resourcefulness/problem-solving. To conclude the session, we will debrief as a group and discuss important take-aways.
### Participants

The more the merrier! But the number of participants does not affect the agenda of this session. More participants = more ideas = more diverse action plan!
### Outcome

Our goal is to support other youth tech educators from all the around the world, and work together to ensure that youth become confident builders of our future. We hope this session provides insightful knowledge for how we can better teach in non-structured environments, and how tech education can co-exist with academic grading in a positive way. We look forward to building 3 solid action plans and sharing them with our community back home, and the MozFest community all around the world.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Zebetus** [comment]
@EPIKhub

**Comment by EPIKhub** [comment]
@chadsansing is it you dont have space or they cannot come?
