### ISSUE TITLE
101 Alternatives to the Paywall

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#355]
**[ Google Spreadsheet Row Number ]** 335
**[ Facilitator ]** Michael Workman
### Description

Major media companies have largely focused on one model for non-ad revenue: the metered paywall. This approach has at least two major faults. First, it is based on an arbitrary browser feature (the page load) rather than focusing on the job the user is trying to do. Second, it limits access to important information that is a building block of democracy. The goal of this session will be to break out of the tyranny of this arbitrary measure and find fresh new ways of generating revenue while serving our users' needs. We'll mainly be coming up with ideas, but we will also have materials to illustrate those ideas through sketching and paper prototyping.
### Agenda

We'll begin with a look at the landscape of major media companies and how they earn revenue, then we will assess and prioritize what users are seeking from news web sites. Next we will break into teams, and each team will first have  a limited period of time to brainstorm as many solutions as possible, with no limits on how crazy the idea. Then the teams will have time to evaluate the ideas and determine which ones do the best job of generating revenue while meeting user needs. Each team will present its top ideas, with the goal being to end up with at least 101 ideas. So if we have 5 teams, that would be 20 ideas per team. Finally, once we have all the ideas we will all vote on them to produce the best ideas. We'll also have funny prizes for the wackiest ideas, etc.
### Participants

With 5 participants, we'll probably have trouble getting to 101, but we'll come equipped with some ideas to seed the process. The main goal is to generate as many ideas as possible, more participants means more and better ideas.
### Outcome

The hope is that in coming up with and publicizing these ideas, we will show media organizations that there are other viable ways to generate revenue that respect the needs of the user. We hope to begin reorient the conversation toward our readers and consumers and spread those lessons to organizations around the world.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
