### ISSUE TITLE
Identifying, Supporting and Assessing Computational Thinking with Scratch

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#356]
**[ Google Spreadsheet Row Number ]** 327
**[ Facilitator ]** Francisco Cervantes
### Description

This session is open to all programmers who want to reflect on their computer programming practices, with particular relevance to Scratch educators. Facilitators will first introduce the MIT Media Lab and Harvard’s Graduate School of Education Computational Thinking framework. Participants will practice identifying computational practices through video co-viewing of previously recorded student interviews using screen capture technology and engage in discussion on their observations. The session will focus particularly on describing the process of construction, and design practices that programmers engage in while creating their projects. Participants will learn how to interview computer programmers on their strategies used for making projects, and to help support the development of computational design practices. At the end of the session, facilitators will remix and design classroom activities that promote inquiry and encourage students to build an identity as a computer scientist through engagement of computational practices.
### Agenda

This session will follow a hands-on workshop format, engaging participants in conversation about their computational products and practices. 

Understanding the Computational Thinking Framework
Facilitators will present a definition of the computational thinking that involves three key dimensions: (1) computational concepts, (2) computational practices, and (3) computational perspectives. 
http://scratched.gse.harvard.edu/ct/defining.html

Practices in Practice
Participants will watch screen capture videos of student interviews and analyze and discuss the strategies used by programmers. 
http://scratched.gse.harvard.edu/ct/assessing.html

CT Interview Protocol
Participants will practice interviewing their workshop peers using a research-driven CT interview protocol. Educators will also conduct a self-reflection to critically examine if (and how) computational practices are being encouraged.
http://scratched.gse.harvard.edu/ct/files/Student_Interview_Protocol.pdf

Bridging Computational Practices Across Programming Environments
Participants will learn to design and remix classroom activities that employ computational practices as a bridge across programming environments. Facilitators will share some sample materials (http://coder-second.com) for remixing, but also encouraged to build on their own lesson sequences.
### Participants

During much of the workshop participants will be grouped in teams of two. Participants will engage in analyzing the videos in pairs, while later reporting their findings to the larger group for discussion. With a larger group, participants would share their observations and findings with nearby individuals, perhaps sitting at the same table. A group of 30 participants is preferred. 
### Outcome

An intended outcome is to better equip educators to understand the key dimensions of computational thinking, identify and evaluate the existence and delivery of those components in their current programming, and provide the skills and strategies to help educators design and deliver high quality CT programming in varied settings.

Another intended outcome is for programmers whom are engaged in the design of interactive media will learn to self-reflect on their activities. 

As a facilitator, I would like to get feedback on the CT framework, video screen-captures, instruments, and opportunities for potential resources.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by jvallera** [comment]
@jvallera @chadsansing These are Hive NYC members. Francisco is a very active MLN community member and would be great to have with us this year. Currently working on a grant to bring Web Lit PD to hundreds of teachers in NYC.

**Comment by Zebetus** [comment]
@EPIKhub could be interesting and a good way to link youths and devs (considering scratch it taught in most primary schools)

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
