### ISSUE TITLE
Advocacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#358]
**[ Google Spreadsheet Row Number ]** 328
**[ Facilitator ]** Christopher Momanyi
### Description

I will sensitize the participants about making the internet safe for all especially children who are likely to be exposed to pornography and the damage inappropriate content can cause to users. the participants will learn how advocacy from those concerned about safe internet will help educate users on their role to make the internet safe for all 
### Agenda

My session will be a panel discussion. There will be a presentation on facts on inappropriate content on the internet and what various stakeholders are doing to create awareness and ask relevant authorities to act 
### Participants

Each participant will be given a certain topic to present in a given time period based on the allocated time. The audience will be invited to ask questions for clarification from the presenter on certain issues. the chief presenter will make a summary of the presentation and make a few suggestions 
### Outcome

I will create an online group discussion where issues on safe internet will be discussed by members making their suggestion and getting others responses improving their views. where it is necessary, the relevant institution that is supposed to act will be  informed and given the facts from members

**Comment by marcwalsh-zz** [comment]
cc @Melechuga

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
