### ISSUE TITLE
NewsPress: Building WordPress for News

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#360]
**[ Google Spreadsheet Row Number ]** 342
**[ Facilitator ]** Ændrew Rininsland
### Description

WordPress is by far the world's most widely-used content management system, and news organisations are using it more and more as time goes on. However, due to its roots as a humble blogging platform, WordPress always requires a substantial amount of configuration to work in a larger journalistic context. The Times and Sunday Times are working across the industry to collaboratively build NewsPress, an open source project intended to enable newsrooms to quickly and easily deploy WordPress preconfigured to support common newsroom features like multiple authors, enhanced media library metadata, JSON output and multi-user workflows.
This session is designed to be a collaborative workshop intended to create a series of standards and best practices for using WordPress for news, which will later be recommended for implementation as part of NewsPress.
### Agenda

Chris and I will start things off by getting a sense of the participants' backgrounds and their prior experiences using WordPress for news. A "SWOT"-style diagram will be created in order to better understand how the group perceives WordPress' strengths, weaknesses, opportunities and threats as it current exists as a newsroom CMS. From this we'll break the group into smaller units intended to create solid proposals that will later be implemented into NewsPress. We'll then reconvene at the end of the session to discuss each small group's proposals.
### Participants

The workshop nature of the session means it should scale without too much difficulty. We're hoping to gather a large number of journalists, editors, newsroom developers and other people who regularly use WordPress in a journalistic capacity in order to get a solid picture of WordPress's existing pain points. Technical skill or experience developing WordPress is by no means a prerequisite, and we welcome discussion by non-developer WordPress users simply wishing to make the platform work better for journalism. With a smaller number of participants (less than 5), we may not break into small groups and instead do that segment of the workshop as a single large group.
### Outcome

We plan to take the list of proposals and canonise them into the broader documentation for NewsPress (currently at newspress.hackpad.com), which will then be used to inform the development of open source tools intended to improve WordPress when used in a journalistic context. The goal of NewsPress is less to create a bunch of plugins and more to collaboratively generate a set of best practices newsrooms can implement when creating WordPress websites. Given the cross-organisational and open source nature of MozFest, there is no better place for us to come together with other newsrooms in order to find solutions to some of the most common problems we all continuously reinvent the wheel trying to solve.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
