### ISSUE TITLE
New Technology for Open & Collaborative Research

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#361]
**[ Google Spreadsheet Row Number ]** 351
**[ Facilitator ]** Mary Anne Baynes
### Description

This session will focus on new technologies that make science and research faster, more open, more discoverable and accessible to everyone. We can improve scientific collaboration and communication to increase efficiency in the accumulation of knowledge – and to best achieve this, science should look to improve technologies to document and connect the entire lifecycle of research projects. What are these research technologies and how are they best used to increase the accumulation of knowledge? This session will gather information from the group and discover how others are using these technologies, which are working best and what gains are being made through their use.
### Agenda

This session will be set up as a fireside chat, a way for people to discuss how they are and are not leveraging new open and collaborative research technologies in their own fields. How have these technologies helped or hindered their goals?

Everyone should come prepared to discuss real-world examples and ideas and they can expect to leave with new technology knowledge and tools that can be implemented and used in their own setting.
### Participants

The fireside chat set-up can accommodate up to 25 people per group. Depending on the number of participants, we will either have 1 or 2 fireside chat groups. Each group will be seated in a circle, allowing everyone to see and hear each person as they speak. Alan and Mary Anne (co-organizers) will lead each group with a series of questions to spark discussion (we will take notes as needed - if there are 2 groups, we can share what is discussed after).  We will then have a conclusion discussion as a full group – Alan and Mary Anne will go through pertinent information discussed if there were 2 groups or final thoughts it’s only 1 group.
### Outcome

All notes about new technologies, tools, techniques and tips will be distributed to the group after the event. This will allow attendees to have easy access to the information that was discussed which will include technology names, URLs, etc. for ease of reference and research.

**Comment by arlissc** [comment]
This session will be co-facilitated by Tim Alby (Overleaf) and Al Hyndman (Figshare) as per Mary Anne Baynes, original session proposer.
