### ISSUE TITLE
Make Parallels

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#362]
**[ Google Spreadsheet Row Number ]** 331
**[ Facilitator ]** Steven Dale
### Description

We’ll facilitate a fun, playful, interactive workshop, guiding participants through a paper-based storytelling game. Participants will collaboratively remix a new creative work from bits + pieces of media we provide, related to a fictional narrative, found scattered across many digital services + platforms. 

Our goal is to explore how a holistic, digital system based on these interactions + principles might work, and to uncover its potential social + data privacy implications. 

We’re also hoping these ideas inspire our participants to join our community of contributors, early adopters and testers, interested in the potential of our vision: a tool helping storytellers unlock their creativity. Please see:

https://vimeo.com/136997295 (video)
https://makeparallels.herokuapp.com (live demo)
### Agenda
- Brief introduction of who we are, and the project (5 mins)
- Discussion of game mechanics + short demo of key ideas (5 mins)
- Gameplay activity (70% of available time)
- Feedback discussion (30% of available time)
- Project lightning talk (5 mins)

We'll provide bits+pieces of media as printed cards, originating from newspapers, books, social networks, and many digital sources. The gameplay mechanic encourages fluid movement between individual + collaborative construction, and the stitching together of these fragments + connections into a patchwork of text + images.

Some of the participants experimented with this technique as part of an academic research project:
http://www.cstreams.com/projects/spark

and the outputs will look something like this: https://drive.google.com/file/d/0B4zhzWwgaF63NVZ6LWZPMUt6SkE/view

We’ll do a lightning talk (5 mins) at the end, to share more about our project goals, and to close the loop of what the activity was meant to explore.
### Participants

Participants will form small groups, and facilitators will move continuously between groups to answer questions, help ensure a balanced representation of ideas, and generally keep things flowing. 

We'll have at least 2 facilitators. Hopefully 3, and possibly 4. We'll print many materials to accommodate large groups and the lofi nature and simple mechanics should scale well.

The number of participants who arrive will determine the length of gameplay rounds. We can design the game accordingly to the time slot given and also shift the mechanic based on the number of participants that arrive. 
### Outcome

We'll document our process + the result. With the permission of our participants, we hope to post the outputs on our blog and share the research with a) our community of 30+ contributors  and b) our community of nearly 400 early adopters.

This will be the first public-facing workshop we conduct as part of our design process. This lofi prototype + outreach will be pivotal for our research, helping us test some of our current assumptions, and giving us an opportunity to iteratively design, test and implement what we've learned.

We're also hoping to find new collaborators, spread awareness of our project, and generally connect with many in the Mozilla community who are passionate about the open web, open source, and data privacy.

Most importantly, we hope our vision inspires our participants to explore + discover on their own, and question the status quo.

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
