### ISSUE TITLE
Leadership Development as a tool for decentralizing knowledge

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#363]
**[ Google Spreadsheet Row Number ]** 332
**[ Facilitator ]** Simeon Oriko
### Description

A number of people around the world do not have the opportunity to engage in the process of knowledge creation at places like Mozilla Festival. Even fewer are aware of such opportunities.

As such, our session aims to engage participants in exploring how leadership development can be used to decentralize knowledge, skills and resources while simultaneously honing the skills of local leaders and finding opportunities to use them.

The ideas and outcomes of the session are targeted at developing the capacity of local leaders around the world to promote web literacy and open culture in their regions. 
### Agenda

Our session will take a hybrid format blending a workshop format with ideation. The session will explore the following questions:
1. How do we take what’s happening in the web literacy and open culture movement globally and seed it locally by through leadership development?
2. How can we better engage/involve local communities in global initiatives?
3. How can we support local leaders to lead initiatives back home?
4. How can local leaders find opportunities that will enable them to practice their skill?
### Participants

For an audience of 5 to 20 people, we will primarily focus on brainstorming. For an audience larger than that, we will change the format into a mini design thinking workshop
### Outcome
1. Co-create a guide that details strategies to develop leadership capacity of local leaders around the world
2. Develop a strategy to bridge the opportunity gap between local leaders and their target beneficiaries
3. Collaborate with teams of knowledge creators to use the above mentioned strategies to decentralize their resources to local leaders
4. Work with local Mozilla communities around the world to nurture and develop local leaders to champion web literacy and open culture through service learning initiatives

**Comment by amirad** [comment]
closing this as simeon will be running his other session instead and looping info from here into the other one.
