### ISSUE TITLE
Help sketch, plan or code the most inclusive, fun & effective app for democratically shaping organisations, your local c

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#364]
**[ Google Spreadsheet Row Number ]** 334
**[ Facilitator ]** Luke Flegg
### Description

•Meet each other, hear briefly about each other & explore what skills & resources we can offer each other and what dreams we share
•Learn our hopes & fears regarding the workshop, so that we might better understand people
•Help code the app, improve the promotional materials for it, develop our strategy, make drawings, develop contacts, affiliations & opportunities and deepen research in an open collaborative digital commons.
The app will be open source and part of a bigger (super inclusive) project called ChangeTheFuture, inspiring, educating & equipping all kinds of people to do all kinds of open, collaborative activities like the co-creation of this app. What we build belongs to everyone, forever, and will be organised into the bigger picture of our activities.
### Agenda

3hrs:
5min: brief intro on us; vision, workshop motivation & goals
5min: sociable energiser
20min: learn about each other in circle
5min: sociable name game/energiser
10min: frame format & agenda, then more on what we want to achieve and different opportunities to contribute and collaborate
10-30min: anyone interested in potentially working on leading something (within ultimate goal) steps forward to explain and invite collaborators (we'll film this) 1 response and 1 reply to response permitted
40min: form groups based on what you're drawn to and go off and do your thing! (floating facilitation. Breath of air encouraged in last few mins)
25min: feed back regroup- summarize & respond
40min: break out again, identifying synergies and reforming groups (go for walk/air before next part!)
25min: final feedback summaries and next steps events and online space to continue together
10-30min: optional feedback on workshop for facilitators + pieces to camera about workshop
### Participants

It won't make much difference the format or facilitation other than the length of time I give people going around in a circle (eg.introductions) because of the use of open space. I may use group numbers + titles if there's 30+ people, to help people move easily between breakouts groups
### Outcome

Concrete outcomes will not be set in advance but I will share my enthusiasm to 'develop designs and plans for the app geared towoards inspiring educating and equipping all people (diversity of creators & users being encouraged and celebrated) which would include critique of all existing designs, planning, sketches for user interface, storytelling for user journeys & vision, coding, theory or strategy contributions including research or affiliation'... we will capture all outcomes and share in Digital Commons where it will remain open to collaborative development. We will use video and collaborate in open discussion space we facilitate, such as Rizzoma, to synthesize outcomes and foster continued collaboration.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
