### ISSUE TITLE
Open - Sourcing Collaborative Educational Projects

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#365]
**[ Google Spreadsheet Row Number ]** 340
**[ Facilitator ]** Julie Koslowsky
### Description

Our session will focus on the idea of open-sourcing educational projects to target educators themselves to encourage their work with educational organizations. Using the example of a professional development calendar, created to support teacher-learning with civic and cultural institutions and organizations, we would like to showcase the benefits of open-sourcing an educational project within a community. 
### Agenda

Using the example of our educator professional development calendar we will share our struggles and triumphs of working on an open-source educational project. We will delve into our approach, what networks we ignited, roadblocks we encountered, and ultimately how this project came to fruition. We will share out our best practices for developing this type of open-source educational project and there will be ample time for attendees to ask questions about the process and get feedback on specific initiatives they may be attempting to implement themselves to see what information we have that may be transferable to their projects.
### Participants

With 5-15 participants we would be able to have a roundtable discussion about the process for creating an open-source educational project as well as some small group work around the ideas that we think are key to understanding how to make such a project successful. If our attendance is closer to 50 we would present the highlights of our project and best practices as well as facilitate small group discussions around the key elements of the project.
### Outcome

As an outcome to the festival, it would be useful for us to take what we have learned from participants and apply it to our current calendar project. To take learning forward, we would love to see organizations take the idea of educational open-source collaboration and apply it in their own way, whether that be creating their own educational calendars or providing more opportunities to share their work directly with other educators. We also hope to take what we learn in this session and to build upon it by hosting some inter-generational hackathons where educators and teens can work together to create new PD opportunities. Lastly, we hope that attendees will take our open-source approach and apply it to their existing, ongoing, and future projects.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by jvallera** [comment]
cc @jvallera applicable to Voices of Diverse Leaders if needed. Hive Chicago community members.

**Comment by chadsansing** [comment]
@soapdog, @jvallera, @amirad, @simonaramkisson: anyone see space for this as per Robert's suggestion on our Google doc?

**Comment by jvallera** [comment]
yes. adding to Divers LEaders pathway @chadsansing

**Comment by chadsansing** [comment]
@jvallera - HUZZAH. Thnx!

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin

**Comment by omnignorant** [comment]
Just curious if this is accepted or not? The team is asking me and Hive Chicago might have to support travel.

**Comment by jvallera** [comment]
@omnignorant this did not make it to our acceptance list, but is in our backup list. We will know monday if we have the space to accept it @emmairwin @chadsansing did you accept?

**Comment by omnignorant** [comment]
Oh, bummer! I saw their project in the accepted proposals list on that etherpad that got shared around and got excited for them.

**Comment by omnignorant** [comment]
Hey @emmairwin I see this is in your pathway as part of the program! Is that confirmed? Have they been notified? I'm only asking 'case they keep pinging me and I am trying to track for them. Thanks!

**Comment by emmairwin** [comment]
@Saallen   @jvallera   If this session has a Mozilla Learning pathway, does that mean acceptance has been sent by that track lead? Or does this remain to be done?  Thanks!

**Comment by jvallera** [comment]
@emmairwin @Saallen this was not accepted into our track. I removed it from the MLN milestones. @emmairwin if you want to include it into your pathway please do! looks like a good one

**Comment by omnignorant** [comment]
@emmairwin @jvallera I was under the impression it was accepted based on exchange with @emmairwin. These folks are already booking travel.

**Comment by emmairwin** [comment]
ok was just making sure we weren't duplicating.  Removed Learning milestone and replaced with ours Will send.
