### ISSUE TITLE
Calling all Minecraft Builders! Using Minecraft to foster civic engagement, self-efficacy & agency

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#367]
**[ Google Spreadsheet Row Number ]** 337
**[ Facilitator ]** Gina Grant
### Description

During this session  participants will learn to leverage student excitement of Minecraft and how it connects to making a positive impact on the Web and in the real world. This session seeks to explore how we might better build tomorrow’s leaders through digital citizenship, design thinking and civic engagement by exploring self efficacy and agency in the built environment- both virtual and real. 
### Agenda

The session will allow participants to engage in a fireside chat around the use of Minecraft as a Web Literacy tool. The facilitators will use the Nominal Group Technique (NGT) to brainstorm and identify similar problems in the real world that can be explored through a virtual world while encouraging participation from everyone- like the Web. 
### Participants

With 5 participants a round table discussion is appropriate. As the group grows beyond 10, facilitators will use a multi-voting technique to ensure that everyone in the group is heard and the session is both manageable and productive. The nominal group technique will enable facilitators to keep the discussion focused on the most controversial or important topics. At the end of the session, the group will be able to share a formative summary of discussion and how they might be addressed in Minecraft with tangible and actionable resources referenced. 
### Outcome

After the festival, we hope to have a broader and more connected group of civic Minecraft practitioners who seek to build tomorrow’s leaders through digital citizenship, design thinking and civic engagement. By exploring self efficacy and agency in the built environment, both virtual and real, we also hope to identify new tools and techniques that speak to sustainability, science, tech, engineering, art, mathematics (STEAM), civic leadership, adaptability, youth voice, and other outcomes available through exploration of the virtual built environment.

**Comment by EPIKhub** [comment]
News to me! Pathway + teaching kit
