### ISSUE TITLE
Hacking your Firefox OS Phone

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#368]
**[ Google Spreadsheet Row Number ]** 345
**[ Facilitator ]** Alex Lakatos
### Description

The session will teach people to hack their own Firefox OS phone, using Firefox OS add-ons. They will be empowered to truly make the phone and the OS their own.
### Agenda

The format of the session is a workshop, in which people with a Firefox OS phone and a laptop will learn how to create their own small Firefox OS add-ons. We'll de tag along live coding, going through the basics of creating a Firefox OS add-on.
### Participants

I'll share my screen so people can tag along and ask questions. That scales easy enough for up to 50 people.
### Outcome

I'd like to see the Hackerspace repository on Github having more activity, but I'll settle knowing that all the participants are empowered to change their icons to squares.

**Comment by soapdog** [comment]
cc @soapdog -- if this session is picked up, I would love to help the facilitator.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin would be better as a participatory 'learn by doing' workshop, but teaching addons for ffos seems like a good goal .

**Comment by Zebetus** [comment]
@EPIKhub talking about getting youths involved with firefox os

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
