### ISSUE TITLE
Tailored learning experiences via MDN Modular Content Kits

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#369]
**[ Google Spreadsheet Row Number ]** 339
**[ Facilitator ]** Istvan Szmozsanszky
### Description

The session will introduce participants to the MDN Modular Content Kits format, a method for developing online teaching/learning resources that encourage collaboration, and that are created to be easily tailored by the trainer to accommodate a diverse range of target audiences.
A more complete description resides at http://flaki.github.io/ck-service-workers/#modular
Participants get acquainted with Modular Content Kits and learn about creating their own, for their own domain of expertise during the session by outlining and testing it on other participants.
Goal is for some of the participants to start using the technique later in their day-to-day activities, or contributing to existing resources, improving this easily-accessible source of knowledge and teaching material.
### Agenda

Format is “collaborative workshop.”
Starts off with a short presentation, introducing Content Kits, what are they and what are the main motivations behind the format. The advantages of Modular Content Kit-s are fleshed out in more detail, then they are presented through actual kits & custom, easy-to-grasp “mini-kits”, intentionally designed for demonstrating the concept.
As attendees get sufficiently comfortable with the subject, they are then asked to create the outline for a Modular Content Kit in their respective area of expertise, then seek out a person in the group, ask questions and try to tailor the newly-created kit to their needs, address issues along the way and improve the initial outline.
In the end, discuss, gather ideas & feedback during a wrap-up brainstorming session.
### Participants

The format accommodates a wide variety of audience sizes. While larger groups give way to a more diverse crowd, which in turn positively effects the results in the “create-your-own-content-kit-outline” and brainstorming phases, smaller groups could work more closely together, getting to know each other a bit better and thus participants might be able to target/tailor their content kit outlines better in the presentation phase.
### Outcome

For teachers, with the Content Kit format we hope to give a new and improved tool and better insights into designing curriculum that they could easily mold to accommodates their audience’s changing needs, which we hope they will use (and make a good use of) after the session.
Some then (due to the open and participatory nature of these kits) may end up contributing to the existing MDN Content Kit collection due to this new awareness.
For non-teachers we hope they gain useful insights along the exercises into designing learning resources with collaboration in mind, the importance of empathy in human interactions and benefits of highly targeted, tailored content in maximizing impact.
We also hope that some may use the existing cache of Content Kits as a learning resource for self-improvement later.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin sumanth is already creating a content kit for web security, which includes participation.

**Comment by emmairwin** [comment]
cc/ @marcwalsh @Saallen
