### ISSUE TITLE
No Stack for Social Justice

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#370]
**[ Google Spreadsheet Row Number ]** 349
**[ Facilitator ]** Nikki Zeichner
### Description

We want to collaboratively create a reference/tool kit of existing digital tools that nonprofit social service providers can use to improve the way that they do their work.
### Agenda

In this hands on workshop, (1) we'll introduce personas of people involved nonprofit social service work, and (2) our participants will engage in a design exercise to match up the existing digital tools that could help these folks broaden the impact of their work.
### Participants

We plan to work in groups of 5 or less. If there are many participants, we will break out into groups and the two of us will facilitate.
### Outcome

Hopefully, we'll have created a new resource to support the work of those involved in social justice work and who operate on shoestring budgets. Additionally, we hope to inspire our participants to think more about how they can continually contribute to this space as technologists and creative people.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
