### ISSUE TITLE
From Disaster Relief to Green Tech Innovation - the Role of Innovation Hubs in Society.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#371]
**[ Google Spreadsheet Row Number ]** 338
**[ Facilitator ]** Tayo Akinyemi
### Description

The purpose of this session is to challenge current thinking about the role of African tech hubs in society by sharing insights from research on hubs as creative spaces—institutions that engage in complex problem solving. There are at least 90 African tech hubs that serve as infrastructure to catalyze technology, entrepreneurship, and innovation. Not only do they act as physical infrastructure, providing access to power, internet, and space, but they also offer access to human, financial and social capital. By distributing these resources more efficiently, hubs make it easier to build start-ups, develop tech, and foster innovation. 

But can hubs also create better solutions to complex social problems? Many tech hubs are engaged in developing tech solutions for education, health, and governance challenges. However, there is an opportunity to push past “there's an app for that” thinking and reconceive tech hubs as creative spaces that foster tech-enabled, innovative problem solving. 
### Agenda

This session will have a hybrid structure designed to provide context-setting insights while providing an opportunity to debate the interpretation and implications of what is shared. As such, the session will begin with a TED-talk style presentation articulating the working hypothesis about hubs' role in society. Following this is a mini-panel composed of a hub founder/manager, researcher, and entrepreneur will debate the validity of the question, as well as how to interpret and/or apply the findings. The session will conclude with an open dialogue with the audience about the role of hubs in society as complex problem-solvers and beyond. Alternatively, the session could transition into a workshop-like experience during which participants would be divided into Art of Hosting World Café groups to discuss the role of tech hubs in society, with the feedback to be harvested and shred with the entire group. 
### Participants

With 5 participants, there’s a fantastic opportunity to share the research findings and then transition into a coffeehouse chat about the core question—the role of hubs in society, and more specifically as complex problem solvers. A small number of participants provides the flexibility to discuss other perspectives on the role of hubs and their potential impact.

With 15-30 participants, the three-part approach originally described would apply. We would start with the TED-style talk, transition into a debate, and then open the dialogue or conduct World Café conversations.

With a much larger number of participants 30-50 or more, the third portion of the dialogue could definitely morph into smaller group World Café discussions organized around the perspectives shared by the debaters and/or other perspectives that were not discussed but should be.
### Outcome

AfriLabs is heavily invested in advancing the dialogue about the future of African tech hubs; it started before the festival and will continue afterward. For example, AfriLabs hosted a dialogue series on hub sustainability last fall followed by a bar camp session at the Global Innovation Gathering (GIG) at re:publica, that is culminating in a hub sustainability workshop (an initiative of AfriLabs, iceHubs and Impact Hub) to be held in December. Additionally, the research project upon which this session is based is likely to continue past November. Consequently, the release of the findings will present a new opportunity to re-engage in the dialogue. Finally, surely there will be other complementary, conversation streams that could be brought to light by session participants and carried forward.

**Comment by cubicgarden** [comment]
Not so keen on the TED styled talks but could be interesting as a workshop @cubicgarden

**Comment by thornet** [comment]
+1 to making it more hands-on. and cc @Geralbine for her pathway.

**Comment by thornet** [comment]
@Geralbine shall we apply your pathway label so that Tayo doesn't receive the decline notice today?
