### ISSUE TITLE
Charting Achievement: Using Open Badges to Design Learning Playlists

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#372]
**Google Spreadsheet Row Number**

343

**Facilitator**

Dustin Stiver 

**Description**

This session will empower participants to explore open badges and the development of interest-driven learning playlists, especially for youth. We will use participatory facilitation strategies, 40% learning and sharing, 60% designing and making, to accomplish 3 goals: (1) learn about open badges, (2) design local engagement strategies, and (3) visualize learning playlists. 

Open badges recognize learning wherever and whenever it happens. A badge is a digital representation of an achieved competency that includes details of the learning experience and evidence. Playlists are a group of learning experiences that share a theme and are structured towards a specific outcome.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by emmairwin** [comment]
cc @geroter @emmairwin there's something connective here with participation pathways, desire pathways (which we are facilitating ) and the idea of learning playlists for particiaption.

**Comment by DustinStiver** [comment]
Co-facilitator is Margaret Black of Big Thought @MargaretBBlack margaret.black@bigthought.org

**Comment by DustinStiver** [comment]
@mattdigitalme Here's my updated session descritpion: 
This session will explore open badges and learning playlists in the context of the new LRNG platform. We will co-design learning playlists by combining resources (static content), XPs (in-person or online experiences), and badges (digital credentials). On the LRNG platform, a learner explores resources while stacking XPs to earn badges, which visualize progress through playlists of learning. Join us to hack these ideas and design a learning playlist of your own.

**Comment by DustinStiver** [comment]
@mattdigitalme Will we have A/V in our space?
