### ISSUE TITLE
Full Moon Academy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#373]
**[ Google Spreadsheet Row Number ]** 341
**[ Facilitator ]** David Bovill
### Description

We will create a new form of decentralised learning experience together, where everyone has their own data, their own domain, and can run these on their own hardware.

We will connect the learning space we create at Mozfest to other spaces around the world, so that participants can experience this new way of writing, creating and researching together. Nominally the topic is about the science of space, and the moon. However we will use this subject to explore collaboration, science and federated learning.

Participants will:

  1) Learn to set up and install software on a Raspberry Pi
  2) Learn to set up and install a NodeJS server running Fedwiki
  3) Learn how to share data and media with other spaces using a serverless architecture based on decentralised technologies such as IPFS

Finally we will have a lot of fun, exploring the moon.
### Agenda

We will use a modified "decentralised" World Cafe format, where participants split into small groups around a table with a Raspberry Pi serving a Fedwiki based academy connected to the Interplanetary File System (IPFS).

Each table will represent a planet, around which we research together the science, and science fiction surrounding the present and future of our relationship with the planets. 

Aside from learning the technology involved, and learning how to create their own sites, the format will allow us to talk about issues such as collaboration, governance, decentralisation and federation.

Participants will discover how to fork, and share what they write and research with other people on their table, other tables and finally remote locations. Each table has a server, and participants will be able to use their own laptops, mobile phones to participate. We will use LED projectors, and a main projector to enhance the visual experience.
### Participants

We will arrange participants into small groups of 3-6 people. We call these groups PODS. Even a small number of participants will find the session exciting as they learn to connect, research and write with participants around the world without using a central server.

Larger groups are easily accommodated by adding another table. Each table will have a facilitator, and should we have enough participants for several tables, people will be encouraged to move from table to table in order to experience the decentralised nature of the learning architecture.

We will encourage online participation, and for people to continue this process after MozfFest through a series of Full Moon happenings that we are organising around the world. In this way people who turn up on Saturday, can take part at home on Sunday, and continue their involvement through the monthly Full Moon events.
### Outcome

MozFest is a place to meet, connect and interact. We will furnish participants with the skills, and tools to continue working in small groups online, and in their community centres. They will have their own site, their own domain, and they will take with them their own open data.

Participants will take with them, one of a range of ways to run a decentralised learning experience. They can take with them an SD card that they can run a server on a Raspberry Pi, a mobile app that they make for their own academy, or they can set up a Node server under their own domain that they can access from anywhere.

Our aim is to connect, people, projects and communities. We hope that participants will return home and set up their own learning community using the skills they learn at Mozfest, taking this forwards each full moon.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin an opportunity for participation tech challenge

**Comment by Zebetus** [comment]
@EPIKhub this could be another amazing way to link the science and youthzones
