### ISSUE TITLE
Learning through Virtualisation

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#374]
**[ Google Spreadsheet Row Number ]** 347
**[ Facilitator ]** Deepak Jain
### Description

In my session participants will learn about the virtual reality, like what is virtual reality, how it works and experiencing the virtual world. In this session the participants will also learn to make their own virtual headset using cardboard. The main goal of my session is to  make the people aware about the latest and future technologies of world, and virtual reality is one of them. Using virtual reality people can experience the thing that they want to do but are unable to do like the people who fears from sitting in roller coaster can experience the fun of sitting in roller coaster using virtual reality headset. Apart from this people can play games, watch videos and experience lots of other things by just using their mobile phone and headset made by cardboard.
### Agenda

In the beginning of  session the attendees will get to know about the overall agenda of session and then I start with the introduction of virtual reality and then they will experience the virtual world by using of already created headset of cardboard and at last the attendees will learn to make their own virtual reality headset. Overall It will be a workshop where people will learn, make and do fun. The attendees can make their own VR(Virtual Reality) Headset within few minutes.
### Participants

This is a session in which I can follow the same activities for 5, 15 and 50 participants. If there are 5 participants then I can go in the depth of Virtualisation and can give more time to the individual participants. If the participants were 50 in number then I will Follow all the activities of my agenda and in addition I will choose some volunteers from participants who can also give their valuable points on this session.
### Outcome

From my view the outcome of this session after the festiival will be very good. I will be in touch with all the participants through social networking sites and IRC. The participants can share/teach all the things that they learned during the session. They can also teach other people that how they can make their own virtual reality headset at the very low cost. The children, young people and Adults, all can learn to make their own headset and use that.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
