### ISSUE TITLE
No Stack for Social Justice: How can we remove barriers to tech for those advocates on the ground?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#375]
Google Spreadsheet Row Number: 344

Facilitators: 

name: Tiffany Andrews
twitter: @TiffiAndrews
organization: Code for America
name: Nikki Zeichner 
twitter: @nikzei
organization: Code for America 

Description:
Participants will learn about online resources for advocacy work and how to connect them in order to create online platform to serve their communities. This will be a hand-on workshop where participants will identify non-technical advocacy users, user technical needs and free or low cost technical solutions that do not require high-technical skill for installation or implementation.

**Comment by marcwalsh-zz** [comment]
cc @emmairwin @geroter

**Comment by simonaramkisson** [comment]
@marcwalsh @Saallen
