### ISSUE TITLE
Learn Python

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#376]
**[ Google Spreadsheet Row Number ]** 350
**[ Facilitator ]** Safwan Rahman
### Description

The youth need to learn to solve problems with code. though everyone does not need to be a software Engineer, they need to learn code to solve their everyday lives common problems. in the session they will learn about the basic of python programming language and how to solve the common problems with this
### Agenda

first, I will talk about what is code, how computer works and then how program works. Then I will describe about the common problems of our everyday life and how writing program can help us solve them. Then I will start showing about Python. How to write python, how to implement a logic, how to solve problem etc. Then some problems will be throw to them to get it solve. they will try to write Python program to solve the problems and I will mentor them if they fall in any difficulties.
### Participants

If there are 5 participants, I will describe the things. show them how to code and also will do hands on.
If there is 15 participants, I will show and describe the things and let them solve the problems
If there is 50 participants, I will show them about the things and also how to get it work. Then will separate them within groups and throw each other different problems to get solve
### Outcome

The outcome after the festival will be really huge. The participants will learn about how easy is to do programming, how easy to solve many problem and some of them will be interested to learn python to solve their problem or be a geek in programming. Moreover, they will learn the basic concept of programming as well as Python language

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
