### ISSUE TITLE
Fail Up Like a Comedian

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#377]
**[ Google Spreadsheet Row Number ]** 348
**[ Facilitator ]** Willonius Hatcher
### Description

This session will teach audience members how to develop a comedians' mindset in life and business. As a stand up comedian and improviser, I have to risk failure daily in front of large groups of people. While this can be scary at first, in time it has helped me developed a fearless and courageous mindset and point of view. 

My intent is to show how to take these principles from the stage and apply them in real life.   
### Agenda

The session will be a fireside chat that includes audience participation. 
### Participants

I will start will an opening talk. After my talk I will break the group up into smaller groups depending on the sizes and we will perform fail exercises to get the creative juices flowing.
### Outcome

After attending my talk participants will view their work and lives differently. They will be more open minded and see opportunities in every situation, much like comedians do.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
