### ISSUE TITLE
Bringing VR to the masses with your story! on the Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#378]
**[ Google Spreadsheet Row Number ]** 359
**[ Facilitator ]** Rabimba Karanjai
### Description

The session will show the capability of WebVR for interactive and immersive storytelling, and how to bring VR to anyone with a smartphone.

Participants will make cardboard VR cutouts from a provided template, which they can use with Firefox installed on their off the shelf Android phones. No expensive hardware required!

It can be presented as a limited-length session, as an all-day (or all festival) exhibit, where  people can periodically stop by and learn and create.

The goals include:
- Creation of DIY cardboard VR viewers! We will provide templates, scissors, and fun things to decorate them with!
- Show participants the capability of VR for telling stories on the Web.
- Teach participants to create immersive content with consumer-grade 360/180 degree cameras. They will be able to see contents from the camera with WebVR
- Teach them to hack on example stories, to tell their own stories in WebVR.
### Agenda

We will introduce WebVR, show demos of storytelling with virtual reality content, and then will have an interactive session for the participants to create their own content using WebVR.
- We will first show them a few examples of how to consume VR content in phone.
- Then we will have an interactive session to build a VR story scene.
- We will go through a short demo of shooting a 360 degree (or 180 if we don't get that camera) video of the workshop and will then experience it in MozVR right within the demo!
- How we can build more demos (or games if anyone is ambitious!) using the building blocks of our present demos!

This will mostly be workshop style. Or we can make it a booth if more people become interested.
### Participants
- With 5. Real time hacking with the code! Change it. Test it. Hack it again. With everyone! So at the end of session everyone will have their own demo up and running
- With 15. Make teams and make them hack on that! End goal. Still we should have a few unique demos!
- With 50. We work on making cardboard work! The more cardboard the more people can participate in enjoying VR.
- With 100. We change the mode of presentation and make it an exhibit style event to handle everyone
### Outcome
- Participants have an understanding of the potential of virtual reality for immersive and interactive storytelling on the Web.
- They have created their own DIY VR viewer for use with their smartphone.
- They understand how to use consumer 360/180 degree cameras and to publish the content as WebVR.
- We will have a website to list participants' WebVR stories for everyone to share and build on.

**Comment by Saallen** [comment]
cc @kaythaney @cubicgarden

**Comment by Moonlapse** [comment]
@EPIKhub 
I think this would be pretty rad for the Youth zone, especially with the hands on building of the viewer and story hacking. Hopefully it would lead to the participating kids showing their friends, making viewers post Mozfest as well.

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
