### ISSUE TITLE
Building an Offline Web with Outernet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#379]
**[ Google Spreadsheet Row Number ]** 353
**[ Facilitator ]** Thane Richard
### Description

Our goal would be to build out piece of the Outernet broadcast. This could be through the development of an app that gets broadcast over Outernet, the curation of web content for a particular section of the Outernet archive, or working on aspects of the Outernet's open source architecture.
### Agenda
- Description of Outernet. This would be me giving an explanation of why Outernet exists, how it works, and how people can contribute. 
- Q&A/Discussion. Typically there are lots of questions about the functionality of Outernet and how things like the editorial selection of content work. This would be a small fireside chat.
- Workshop on building Outernet. I would lead participants into different groups of focus. Those with less coding experience could help collect content while those wanting a more hackathon experience could begin creating an Outernet app.
### Participants

Regardless of the group size, I would break participants down into smaller groups to work on different types of projects. In advance, instructions for contribution would be published on our blog and members of the Outernet team would be available remotely via chat or video to assist different groups in tasks. Breaking into smaller groups will allow different skill levels and interest areas to each participate in a way that makes their contribution feel valuable.
### Outcome

All work will be documented in the Outernet wiki and will essentially form a dedicated sprint of an ongoing Outernet activity, whether editorial curation or development. Therefore, all work done will build on work that has come before and will form a living part of the project. If possible, I would also point a satellite dish and set up a live demo feed of Outernet to let participants see their work offline in real time.

**Comment by cubicgarden** [comment]
Interested not quite sure its a fit but could be... @cubicgarden

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
