### ISSUE TITLE
Gain a Badge

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#38]
"Participants will:

Gain a badge. Participants would gain badges, which could be for a variety of activities: 
- Gain a MozFest Pathway Participation badge for:
  - Evidence of having engaged with at least 3 things at MozFest, eg takeaways from 3 stands (broad knowledge)

We would work with Mozilla and others contributing to MozFest to define other badges that would align with their pathways and themes. Possible other badges could include -
- Evidence of having learnt at least 3 new things about something specific (deep knowledge)
- Demonstrating Lead, Teach, Make attributes, e.g. gain a Showcase badge by providing evidence of what you’ve made. This could act as a continuing / fringe activity linked badge
- We would like to link to the Maker Party on the Sunday - issuing Showcase badges to those showcasing what they have made
- OBA 101 badges for learning about badges and badge design

When participants receive their badge, they would learn about how to design, issue, earn and share badges using the Open Badge Academy app.

We will provide hard copies of a Badge Canvas that can be taken away for participants to start designing their own badges. We will provide links to this online so that those participating remotely can also create their own badges."

**Comment by mattdigitalme** [comment]
cc @mattdigitalme
