### ISSUE TITLE
CopyBetter: Copyright Reform in the EU

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#381]
**[ Google Spreadsheet Row Number ]** 362
**[ Facilitator ]** Gerv Markham
### Description

Participants will learn about and discuss issues around copyright reform in the EU, including current state of play, Mozilla's stance, foreseen obstacles that could come up in 2016, and what our coalition partners say. 
### Agenda

This session will be in the format of a fireside chat with plenty of opportunity for participants to contribute their ideas, raise issues, and ask questions.
### Participants

With fewer people, the conversation is more intimate. With 5, it will most likely be a round-table discussion. With 15-50, it could start with an introduction from the facilitators, followed by break-out groups that discuss different issues and contribute perspectives, then come together at the end to share their ideas with the larger group.
### Outcome

We foresee two main outcomes:
1. The community will have a better understanding of copyright law and reform happening in the EU, and know how to engage with Mozilla to take action in their countries.
2. The Policy Team will have a better understanding of the community's understanding of the current issues regarding copyright reform in the EU, and be able to tailor campaigns accordingly. Moreover, the team will make connections with the participants and have better ties to the community for future campaigns.

**Comment by Melechuga** [comment]
Gerv + Raegen on point for this -- both are MoCo staff, based in the EU, and coming to MozFest already.

**Comment by Melechuga** [comment]
Including speaker from https://github.com/mozilla/mozfest-program/issues/302
