### ISSUE TITLE
Building 21st Century Civic Hacker

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#382]
**[ Google Spreadsheet Row Number ]** 355
**[ Facilitator ]** Noel Hidalgo
### Description

Over the course of 20 mins, BetNYC wants to outline its vision of a unified civic hacker curriculum. For the last 30 mins, the session will be opened to a workshop where participants remix the curriculum and fill in the voids. The last 10 mins will spent on group presentation. We will walk away with shared values and concepts on how to build the next generation of civic hackers.
### Agenda

Start with a presentation.
Move to group work though a presentation.
End with collective ideas and goals.
### Participants

We want this conversation to be as open as possible. We will use presentation only to frame the conversation, goals, and what is being done in the United State.
### Outcome

A better picture of how to use technology to improve people's lives while building a global movement of certified, educated, civic hackers.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by cubicgarden** [comment]
One for you @Saallen and @marcwalsh
