### ISSUE TITLE
Hacks/Hackers as a Global Entity

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#385]
**[ Google Spreadsheet Row Number ]** 376
**[ Facilitator ]** Peter MacRobert
### Description

Hacks/Hackers is a global network of meetups, all at different stages of maturity. However, it is now in a space where it have the potential to harness the power of the network to support its growth.
Based on a successful workshop at Mozfest 2014, Hacks/Hackers London would like to build on the discussion to create ways for  chapters to share, collaborate and support each other globally. 

In addition, we would like use this session as an experiment to help find model for how Hacks/Hackers global stakeholders interact in future.
### Agenda

The session is intended for Hacks/Hackers chapter organisers and/or members to brainstorm the future of movement - allowing chapters to discuss their needs. We propose a session split into a Q&A style approach.
Starting off, each organiser (current or future!) introduces themselves, to lend context to the conversation. 

Then, they each list their top 5 challenges, needs and opportunities for their group. This should take about 10 minutes.

Then we move into a round-table discussion where each party talks about their needs, and and the group responds with suggestions and constructive feedback. All outcomes are documented against the original needs.
### Participants

If we have 5 participants we will work as one group. Otherwise we will split off into smaller groups (split regionally) and report back and share at the end.
### Outcome

There is a global conversation taking place around how to work together across time zones and taking into account different local conditions. We’d value input into how Hacks/Hackers’ UK chapters can work with other chapters worldwide in an effective way.

**Comment by ryanpitts** [comment]
Journalism is reaching out to this facilitator and suggesting a joint session with https://github.com/mozilla/mozfest-program/issues/528

**Comment by ryanpitts** [comment]
closing and merging with https://github.com/mozilla/mozfest-program/issues/528
