### ISSUE TITLE
From Banhammers To Lovebombs: Dealing with Harassment and Creating Welcome Online

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#386]
**[ Google Spreadsheet Row Number ]** 364
**[ Facilitator ]** J. Nathan Matias
### Description

Learn and discuss 40 years of approaches to dealing with online harassment and fostering respectful, positive community online. If you are a moderator, facilitator, activist, social bot maker, or platform designer, this session will help you become more aware of the social, technical, political, and legal aspects of dealing with harassment, hate speech, and sexism online. As we share resources, get connected to others doing similar work and contribute to a wiki of scholarship, design, and action.
### Agenda

(agenda for 1 hour session. Would prefer 90 minutes, but the schedule is flexible)
=> Introduce the session (8 minutes)
=> Icebreaker and interest sharing (5 minutes)
=> Choose top 4 interests from a list:
- What is harassment/bullying?
- Who are harassers
- Moderators
- Platform policies
- Prediction/detection
- Propagation of misinformation
- Publics, counter-publics, anti-publics
- Online harassment and offline harassment
- Reporting and flagging harassment
- Positive interventions for healthy online community
- Voting and Rating systems
- DIY responses
- Bystanders and secondary trauma
- Mediation and dispute resolution
- Legal interventions
- Online harassment internationally
  => Sequential discussions or breakouts on these 4 topics, depending on size (10 mins each, if sequential)
  => Report back and documentation (10 mins)
### Participants

With 5 participants, we would have a sequential conversation  on the top 4 items. With 15, we would have two breakouts. With 50, we would have 6 or 7 breakouts. I have facilitated MozFest sessions of 6 people and sessions of 50 in previous years.
### Outcome

Our goals are to:
- empower communities with resources and scholarship on online harassment
- connect participants with others doing work in this space
- contribute to shared resources

**Comment by ryanpitts** [comment]
assigned to the Digital Citizenship milestone, but we're also considering this for Journalism's "Community" pathway.

**Comment by ryanpitts** [comment]
Hi @Melechuga & @MozStacy! Since it's assigned to the Digital Citizenship milestone, we're just wondering if you've already decided to definitely accept this session.

**Comment by Melechuga** [comment]
Hi @ryanpitts, 
No decisions yet; we've just marked all potential sessions with the milestone "Digital Citizenship" so we can filter with this function. If you don't mind holding off until next week, I'm sure we can get through all the sessions by then. Thanks!

**Comment by thornet** [comment]
Unfortunately, Nathan won't be able to come to Mozfest this year due to other commitments. He's asked me to withdraw his proposal, so I'm closing this issue. Bummer!
