### ISSUE TITLE
Democracy Street

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#387]
**Google Spreadsheet Row Number**

372

**Facilitator**

Joseph Cavalla

**Description**

Democracy Street is an interactive digital arts and learning project, developed and curated by the artist Jon Adams. Commissioned by the Houses of Parliament, and created in collaboration with Mozilla, Democracy Street aims to raise awareness of the power of democracy and the importance of free and open information.

Users create pockets of data for every badge earned and discovery made in the mobile web-app -from which Jon generates artwork. Jon will be on hand to help participants go on their own journey's of discovery, and to encourage people to create artwork, with the results contributing to the final exhibitions.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by mattdigitalme** [comment]
@chadsansing Is this the same proposal as https://github.com/mozilla/mozfest-program/issues/61 but with a different name?

**Comment by chadsansing** [comment]
@mattdigitalme, I think so - thnx!
