### ISSUE TITLE
Thimble for Android

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#388]
**[ Google Spreadsheet Row Number ]** 357
**[ Facilitator ]** Muhammed Hasan Ahmed
### Description

The Webmaker app for Android is great for people who do not want to write code to create a project. However this also results in a backlash from coding-minded users who want to utilize their coding capabilities to create projects.

By using the Thimble app for Android, those coding-minded users will be able to add HTML, CSS, JavaScript code to create their makes, projects, website, etc.
### Agenda

We will be working closely with the Mozilla Learning Network Team to convert the Thimble tool into an Android app.

We also want to be where our users are, so we will be looking to bring the Thimble app to other mobile Operating Systems too like iOS, Windows Phone, etc. (This should be true for the Webmaker app as well, we should strive to bring the Webmaker app to other mobile Operating Systems as well like iOS, Windows Phone, etc.)

Format: Fireside Chat will probably work best as it is just an idea. So we would be able to discuss this proposal with the Mozilla Learning Network Team and other participants. Another reason for the Fireside Chat format is that this is merely an idea, plus I am not a developer so I do not have any working prototype.
### Participants

The format remains the same irrespective of the number of participants due to the reasons mentioned above. However, the more participants there will be, the more insightful our session will become. So the more, the merrier :)

All I am looking for is healthy input on this idea.
### Outcome

The ideal outcome would be the approval of this idea. I will be really looking forward to working with the Mozilla Learning Network Team to bring this idea to reality. And who knows, maybe there will be another app (Thimble) developed by Mozilla in the Google Playstore by this time next year before Mozilla Festival 2016 :)

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
