### ISSUE TITLE
Data and the Open Web For Sustainable Development

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#389]
**[ Google Spreadsheet Row Number ]** 356
**[ Facilitator ]** Leonida Mutuku
### Description

This session aims to explore different ways in which data on the open web could be harnessed to achieve sustainable development. In several developing regions, data collection through official means is quite tedious, under-resourced and not timely. This session aims to gather ideas around new ways to source data on the open web, analyze seemingly unrelated data publicly shared and present this data to varied audiences with an aim of making information more accessible to the public. This session aims to build on/provide comparative outputs to a session held in Nairobi in August http://www.ihub.co.ke/blogs/25499/data-for-sustainable-development by engaging an international community.
### Agenda

We expect the session to run as a design thinking ideation session. We will present three challenges to the participants, asking them to brainstorm, and go far wide with ideas (written on several colorful stickies) on how to solve these challenges (the emphasis here will be on quantity of ideas not necessarily quality). At the end, participants will select the best two ideas and build paper-based (low fidelity) prototypes of how they see these ideas weaved into a product. Of course, we will have great background music and snacks to keep the participants psyched and energized!
### Participants

We are planning to have the participants work in groups and so the number of groups formed and the members of each group will vary according to total participants. As material needed for the workshop is inexpensive, we will aim to have as much material as possible available to accommodate as many participants as the room allocated can allow. Co-facilitating and visual cues will also help us keep the sessions interactive and accessible to all. 
### Outcome

We would like to see the most viable of these ideas implemented and will work with our partners (at the Global Partnership for Harnessing the Data Revolution for Sustainable Development) to support and implement the ideas (Definitely if viable, we will start with Kenya).

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
