### ISSUE TITLE
Organize Better, More Inclusive Hackathons: It's Easier Than You Think

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#390]
**[ Google Spreadsheet Row Number ]** 368
**[ Facilitator ]** Leah Bannon
### Description

The Tech Lady Hackathon is a civic hackathon and training day with hundreds of women from many different backgrounds. (See for yourself, check out #techlady on instagram, etc.) I have organized it annually for three years now, and it has had a significant impact on diversifying the tech scene in Washington DC. Making this happen isn't easy, but it's _not_ rocket science. There are a few significant (and a lot of small) reasons why this works, and I want to share those at MozFest. This will be an interactive workshop where participants learn those important lessons and share ideas from their own experiences about what makes a hackathon more (or less) inclusive and successful. (Advice on structuring this is very welcome.)
### Agenda

The workshop includes 3 main components: 
- I share and discuss the lessons I've learned organizing the Tech Lady Hackathons and other civic hackathons.
- Design studio brainstorming on post its about things that have made hackathons more or less inclusive. And dot voting (always).
- Q&A and discussion of the above two.

I'd love advice about improving this format or making it more engaging.
### Participants

I'd definitely appreciate advice on this as well, but the above format lends itself well to breaking out into groups. For a smaller crowd, there would be more discussion/q&a with the entire group. For the larger crowd, I would break the room into groups more for the discussions and then groups would briefly present their best ideas (after dot voting!) to the rest of the room. Ideally, I would shuffle the groups between discussions.
### Outcome

Attendees would go home and organize better tech events that expand their tech communities! I started doing this because I was learning so much and growing my network from civic hackathons and tech meetups, and I wanted more women to feel comfortable attending these events so they could benefit, too. I wanted them to know that tech events weren't just for tech experts; they're also excellent ways to learn tech, its jargon, trends, etc. I know women who attended their first tech event at Tech Lady Hackathon and are now full time developers.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc / @geroter @emmairwin running better more inclusive  participation hackathons

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Healthy Events & Networks" pathway.
