### ISSUE TITLE
Privacy and Libraries

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#391]
**[ Google Spreadsheet Row Number ]** 358
**[ Facilitator ]** Seeta Gangadharan
### Description

Join librarian and technologist colleagues to problem-solve around some of the biggest privacy challenges facing public libraries. Based on a project on privacy and data literacy in metropolitan New York, this session will present common questions and concerns arising from library professionals and engage session participants in a group exercise to troubleshoot questions that libraries  are often hard pressed but under resourced to deal with.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by cubicgarden** [comment]
Interested in having this in the library cc @cubicgarden
