### ISSUE TITLE
MozFest Pandeiro Orchestra

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#392]
**[ Google Spreadsheet Row Number ]** 363
**[ Facilitator ]** Adriano  Cupello
### Description

This session will enable people to learn a digital musical instrument version of a traditional Samba instrument called pandeiro, using a webapp similar to the 80`s game Simon. They will be able to record their own creations and share them with others to improve their technique. After the session they will also capable to actually play the real instrument. We'll form a digital pandeiro orchestra during mozFest and exchange original songs with one another.
### Agenda

The session will be held as a workshop where people will use their mobiles, tablets or laptops to learn how to play the pandeiro. We will learn the beats and we are going to jam together and also  bring some real pandeiros to test what they are learning on the webapp in the real ones. In the end they will be able to publish their own creation for others to listen and remix.
### Participants

We can easily deal with 5 to 50 people. The web app turns each device into a digital instrument allowing as many people as we have to learn and play together. Also, this kind of instrument here in Brasil is taught to large groups and the more people you have, more fun it will be!
### Outcome

Everyone will be able to play, listen and remix each others creation. Our musicians will be able to teach others how to play pandeiro, using the same hands-on participatory learning method used in our workshop. Also the webapp is open source and one can adapt it to their own traditional instruments. This workshop can also be used as an activity in a Mozilla Club context.

**Comment by Zebetus** [comment]
@EPIKhub this is a way to get music involved

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
