### ISSUE TITLE
Espruino Pico and IoT

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#393]
**[ Google Spreadsheet Row Number ]** 369
**[ Facilitator ]** Giovanny Andres Gongora Granada
### Description

People will learn how to use JavaScript for IoT projects with this incredibly small board. They will learn the basics of the components, how to make it run, modify and learn something new. It's all about imagination.
### Agenda

Introduction to Javascript
What is IoT?
Let's meet the Espruino Pico
What you can do with a Espruino Pico
Examples
Solve the challenge
### Participants

People will group in 3, take an Espruino Pico and start trying it with hardware modules, leds and connect wires to add functionalities.
### Outcome

They will have a clear idea where to start when they want to build Javascript and IoT projects in the future.

**Comment by soapdog** [comment]
cc @soapdog @geroter

**Comment by Zebetus** [comment]
@EPIKhub maybe for the tech pathway

**Comment by marcwalsh-zz** [comment]
@cubicgarden

**Comment by soapdog** [comment]
I would love to help Gio facilitate his session.

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
