### ISSUE TITLE
How to run a global, volunteer-run opensource charity on a shoestring budget

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#394]
**[ Google Spreadsheet Row Number ]** 361
**[ Facilitator ]** Hera Hussain
### Description

The idea of this session is to share the organisational model & templates which allows Chayn to operate on the spirit of volunteers alone. Over the past two years and a half years, Chayn has launched two crowdsourced platforms, hackathons, and international toolkits. The impact report can be seen here: http://chayn.co/impact/
### Agenda

30 mins: Talking through the Chayn model, challenges & learning
Remaining time: People  are handed copies of the model and can discuss particular challenges in their organisation.
### Participants

The session won't be impacted by growing or decreasing numbers though it will be more fruitful in less numbers.
### Outcome

I want to write up a blogpost about what I learnt, the projects and tools I heard about and publish it on my & Chayn platforms.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
