### ISSUE TITLE
Link Technology to Social Innovation

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#395]
**[ Google Spreadsheet Row Number ]** 375
**[ Facilitator ]** Maurizio Gioli

Description: 
It will give them an overview on how it is possible to integrate technology and innovation with Social Values and Ethics. Some guidelines how what does being a social innovator means and why they should consider this as the best time and opportunity to make a difference and embrace a social activities into their company culture.

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by simonaramkisson** [comment]
Accepted and will be sending

**Comment by simonaramkisson** [comment]
### Agenda

The sessions can vary. We could deliver a 30 to 45 minute one with a Keynote and some Q&A at the end perhaps one in the morning and one in the afternoon on each day or we could structure it as a workshop of 90 minutes. One per day (Sat-Sun)

### Participants

The structure of the sessions will allows the delivery of it to be also adaptable to the audience. If the number is limited can become an interactive session (workshop type) and if the number is higher we could instead use a keynote and Q&A model

### Outcome

It would be a great opportunity to see what is out there and also connect and relate with the other participants. I am sure there will be a lot of information and insights that we could use in our on-going activities.
