### ISSUE TITLE
Critical Care Datathon: Answering clinically relevant questions with the MIMIC Critical Care Dataset

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#396]
**[ Google Spreadsheet Row Number ]** 365
**[ Facilitator ]** Tom Pollard
### Description

In September 2015 our lab, the MIT Lab of Computational Physiology, will be publicly releasing MIMIC-II, the latest version of a unique, publicly accessible critical care database. The data comprises detailed information on ~60,000 patient stays in critical care. 

In the workshop we will work with participants to carry out an analysis of the dataset using SQL and Python. Our aims include (1) emphasise the value of open health data (2) teach analysis and computing skills (3) create teams who will go on to publish research studies using MIMIC (4) and ultimately lead us towards better patient care and outcomes. 

The workshop would be based on the "MIT Critical Care Datathons" that we have held at MIT: http://criticaldata.mit.edu
### Agenda

The session would be a workshop, Software Carpentry Style. We will provide access to a new release of a unique critical care database called MIMIC via a Postgres instance running on a cloud system: https://mimic.physionet.org/database.html. 

After setting up the participants computing environment (Shell, IPython), we will demonstrate how to connect to MIMIC. We will then walk through the data collaboratively using IPython Notebook and plots to demonstrate the richness of the data. We will work through the method of a research paper published using MIMIC to reproduce the analysis. 

We would then work with participants to identify new, publishable research questions to undertake. We will provide ongoing assistance to facilitate the studies. The following article is an example of a study published from a previous MIMIC hackday: http://www.ccforum.com/content/19/1/13
### Participants

We have run several hackathons in the past using the MIMIC dataset, with numbers ranging from ~5 to 100. Small groups are great: we can progress quickly and provide one-to-one support. Larger groups require careful planning, but can still be very effective. We follow a similar pattern to Software Carpentry - a demonstrator leads from the front, but participants are encouraged to help each other out, with help from the team when needed.
### Outcome

I hope that the workshop would lead to participants:
- learning the skills needed to carry out analysis on a de-identified patient dataset;
- leaving with strong recognition of the importance of health data in improving patient care and outcomes
- advocating for open approaches for health data;
- leaving with a research question to explore using the MIMIC dataset, along with a group of collaborators
- at least some of the research questions leading to published research papers.

**Comment by Saallen** [comment]
cc @Melechuga @kaythaney
