### ISSUE TITLE
The Iceberg Model

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#397]
**[ Google Spreadsheet Row Number ]** 371
**[ Facilitator ]** Henrik  Mitsch 
### Description

We will explain the iceberg model from Otto Scharmer's Theory-U.
Following that there will be a discussion on how to apply his theory in our community work.
### Agenda
- 5 mins introduction of people
- 15 mins presentation of the framework
- 20 mins group discussion (maybe using World Cafe facilitation technique)
- 20 minutes sharing results
### Participants

Works from 5 to 50 people. Scaling via World Cafe model. 
### Outcome

In the first place this is simple "skill training". As we also discuss our experiences, there will be a great learning factor.

**Comment by marcwalsh-zz** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
