### ISSUE TITLE
How to talk about our mission

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#398]
**[ Google Spreadsheet Row Number ]** 366
**[ Facilitator ]** Mariot Tsitoara
### Description

People will learn how to talk about our values and mission to other people. They will learn to inspire new users and new contributors.
### Agenda

I see it in the simplest form. It will be a fireside chat between friends to talk about our goals and how to share them.
### Participants

With 5 or 15 participants, the session can be held outside or during diner time. With 50, a small room will be needed.
### Outcome

Their task after the festival will be to inspire people to help them achieve our goals. Guide them through our programs and help them to be their best.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin this could lend to other sessions

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
