### ISSUE TITLE
Build your own block-based coding app with Blockly

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#399]
**[ Google Spreadsheet Row Number ]** 370
**[ Facilitator ]** Champika Fernando
### Description

This session will use Blockly to allow participants to design and create their own block-based programming app or activity. We'll focused on building interest-based coding apps - music, dance, math, animation, storytelling etc.  
### Agenda

We'll start with an overview of block-based programming apps and a demo of how Blockly works. We'll then facilitate a group brainstorm on the types of interest-based apps that could be built with Blockly. The remaining time will be used to break into groups and build. 
### Participants

With fewer participants 5, 15, 30, we'll keep with the proposed format above. For a larger audience we will do a brainstorm in smaller groups that focus on specific topic areas (coding apps for music, coding apps for animation). And building will also happen in these smaller groups. 
### Outcome

For our team we'll gain valuable insights into the types of things people might want to build with this tool and also the shortcomings of its current state. We hope that participants will leave feeling empowered to design and create their own coding apps and even better contribute to our open-source project.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
