### ISSUE TITLE
[Pathway] Accessing the Global South

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#4]
A pathway that looks at online access and participation in industrially developing countries. We’ll hear from an Open Web Fellow working on the African Declaration of Internet Freedoms and Rights, have sessions that focus on Mozilla’s stance on zero-rating/equal rating, and what that means, plus we can tie this together with Webmaker’s research on user experiences in India, Bangladesh, and Kenya.

**Comment by Melechuga** [comment]
Combined with R-E-S-P-E-C-T pathway.
