### ISSUE TITLE
Learning from 10 artists using Webmaker 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#40]
For 2 months, 10 english artists are going to be using Webmaker regularly, and providing us with on-going feedback. This experience aims to answer 4 main research questions: 
- Can Webmaker provide enough creativity for users? 
- Can Webmaker allow artists to bring their art beyond the gallery ?
- How do user feel about our product after 2 months of regular use ?
- Did participant learn anything with Webmaker ? did it shift their perception of the Web?

This experience could take place as follow: 
1. The artists will start by sharing their experiences, talking about both their art on the web, but also their overall experience with Webamker and the web.
2. Then we will discuss the key findings from this study. 
For example: ""We learned 4 main points from this study which are XYZ""
3. Make and do with the audience. 
The audience will then reflect together on those learnings and engage in prototyping and ideation. 

Example: 
From this study, we learned that Artists did not see the Remix button, nor did shift their understanding of the web. 

Design challenge1 : How might we introduce Remix in Webmaker ?
Design Challenge 2 : How can we make learning more obvious in Webmaker?

=> The audience gathers in 2 groups and prototype around these 2 challenges "

**Comment by secretrobotron** [comment]
cc @secretrobotron re #51

**Comment by Saallen** [comment]
@secretrobotron assigned you to this issue- or should it be @LauraReynal? 
<strike>This is a descritption issue on your pathway. If you pull any sessions under this pathway they should be referenced here.</strike> my mistake this is issue is just outlining a session :disappointed:

**Comment by lauradereynal** [comment]
I'm working with the artists on this one. I'm waiting to see if they have other ideas for their session before we refine our agenda. 
Will keep you posted here.

**Comment by thornet** [comment]
This will not take place as a formal session.
