### ISSUE TITLE
How will artificial intelligence change our interactions with each other?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#400]
**[ Google Spreadsheet Row Number ]** 374
**[ Facilitator ]** Nathan Miller
Jessica Riches, Chelsea Chen, Hongbin Zhuang, Jan Medvesek, Jonathan Gomez, Zafiris Fountas, Rosie Goldsmith, and Ramin Abbassi.
### Description

Our session will introduce participants to the process of AI design in a human-centric and empathetic way. Participants will have the opportunity to design the system rules for their own AI and will the co-create some potential societal impact scenarios that these designed AIs will have on relationships we have with each other, technology and the world at large. 
### Agenda

The session will be a workshop with an introduction. First we will present a framework for designing AIs which participants will then use to create scenarios which will be improvised and play acted in groups and or pairs, where one participant will take on the role of the AI and the other participants those interacting with the system. The groups will then report back on their findings, discussing what their initial  assumptions were and how those assumptions changed with improvised interaction. The groups may then iterate the design of their AI and see what the interactions are like for a second round before reporting back final conclusions. 
### Participants

Having facilitated a workshop at Mozfest in 2013 that started as less than 10 participants that grew to 25 during the course of the workshop time, I would suggest that a similar workshop format of having participants grouped into small working teams will allow for varying amounts of participants in the workshop. We will also have multiple facilitators. Running the karaoke for the 2013 Mozfest Saturday party also exhibited my experience of accommodating groups of varying volumes!
### Outcome

We would like to produce some content (a video and a blogpost) that will continue the discussions of the learning from the workshop. We would also like to, if possible incorporate some of the learnings into the robot product we are building and launching on Kickstarter at the end of November. Those who are particularly interested are more than welcome to contribute to our robotics project and community, as a living embodiment of continued learnings and engagement from the workshop.

**Comment by thornet** [comment]
cc @cubicgarden -- reminds me of your internet ethics chats!

**Comment by cubicgarden** [comment]
Links with https://github.com/mozilla/mozfest-program/issues/575
