### ISSUE TITLE
Why There Is No PageRank For Data?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#402]
**[ Google Spreadsheet Row Number ]** 367
**[ Facilitator ]** Rebecca Williams
### Description

As more open data is released, discoverability has become a real issue. Finding and comparing data often means guessing the terms and wading through a lot of false matches. Search engines used to be similarly reliant on page keywords, until Google’s PageRank advanced the state of the art by looking at the links between pages for relevance. We need something similar for data. We’ll explore some possible means of citation and other metrics that let news organizations show their work, engage their readers, and let data search engines better discover relevant content.
### Agenda

We’ll start by looking at some of the available metrics for measuring the “impact” of a data set – downloads, mentions, FOIA requests – and their drawbacks. We’ll talk about some possible mechanisms for explicit citation and other ways in which we might derive which news story has used a dataset. People will learn new approaches to managing and sharing data sources for journalism, and research, best practices for data citation, and innovative approaches to collecting analytics on how your data is being reused. 

The format will be a presentation/brainstorming hybrid, with the ratio of each depending on the size of the group.
### Participants

The object of this session is to: share best practices and to brainstorm creative approaches to data citation. After the facilitators share their varied experiences and observations with data citation, participants will be led in a discussion and brainstorming/prototyping session. For groups <15 there will be a facilitated roundtable discussion and brainstorming activities (using the Internet & games). For groups over 15, teams will be formed to brainstorm emergent focus areas of interest (e.g. tools, citation design, metrics). 
### Outcome

I hope we can derive a practical approach for data citation that could be cited by data journalism operations. This could in turn be added to things like Data.gov to reveal the kind of stories possible with a dataset. More TK.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
