### ISSUE TITLE
VR Journalism, WTF is it: Hype or here?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#403]
**[ Google Spreadsheet Row Number ]** 381
**[ Facilitator ]** Robert Hernandez
### Description

It's not the Holodeck, but VR is more real than a hoverboard. This session will demo and explore diverse virtual reality experiences created for journalism, and discuss how you can begin producing these emerging experiences. The goal is to explain why this tech is real and why to you should begin developing for it now.
### Agenda

This is more a fireside chat where we'll play some VR experiences, but discuss how they are produced. Breakdown the process and offer practical entry points into producing VR.
### Participants

In small groups, the participants could actually try one different VR experiences through Oculus, Samsung Gear VR or Google Cardboard. If larger, we will demo via video, but the hands-on-ness will be limited. The gear will still be available to be on displayed.
### Outcome

Ideally, this session will inspire and empower the participants to explore producing VR experiences for non-fiction storytelling. We want to prepare for another disruption to storytelling that will come with these experiences.

**Comment by ryanpitts** [comment]
Journalism is accepting this session.

**Comment by ryanpitts** [comment]
Unfortunately Robert will not be able to be in London for MozFest. Closing this one.
