### ISSUE TITLE
Parenting and Web Censorship

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#404]
**[ Google Spreadsheet Row Number ]** 378
**[ Facilitator ]** Jake Brown
### Description

This sessions goal is to introduce people to the idea of parental controls online - and how they don't look like parental controls in the traditional sense, and what that means in the context of internet censorship and privacy. Attendees will ask the question "How do I balance protecting my child with maintaining the freedom and openness of the internet?" by evaluating the "profile" of a child, and then building a corresponding "ideal internet" on paper - what's there, what isn't (if anything)? It's meant to be subjective, no right or wrong answer - just asking a question and enabling participants to walk away with "food for thought."
### Agenda

This is a workshop that's very scalable with very few material requirements. (When I lead the session "Intro to Mesh Networking" at Mozfest 2014, I learned that the fewer materials you have the better.) Attendees would group together (in groups as small as one or as big as 5), and each group would receive a child profile - a description of the child's background, interests, and hobbies. Each group would then engage in a discussion about what kind of internet they want for that child. Some will say no restrictions, some will vote for restrictions - the point is to spark a debate between group members about Internet Openness and Parenting in the digital age. How would they, personally, strike balance?
### Participants

This session is infinitely scalable, it's limited only by the number of child profiles which are generated at random. Assuming groups of 3, just 8 child profiles would be enough to fill up the average Ravensbourne space. Assuming 5 participants, we would group into 3 and 2, with each of those two groups receiving a profile. With 15, 5 groups of 3. So on and so forth. This session is also not aimed specifically at adults, to the contrary youth involvement in this session would be ideal. Perspectives from all backgrounds, age included, will make for a more productive discussion.
### Outcome

I want to see participants continue this conversation far after the session is over, especially parents. This session is not about promoting an agenda, or a product, or an ideology, it's about starting a discussion with kids, teens, and adults alike about balancing internet freedom and privacy for youth with the guidance and direction of parents.

**Comment by EPIKhub** [comment]
could we have 2 sessions on this? one on satureday and one on sunday, so more than one space can play with this session? I think this one is really relavent to the YouthZone @MozStacy @mixedpuppy

**Comment by EPIKhub** [comment]
@MozStacy @mixedpuppy Jake is willing to do 2 session
