### ISSUE TITLE
Git and contribute - Best practices to open source contributions

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#405]
**[ Google Spreadsheet Row Number ]** 383
**[ Facilitator ]** Sudheesh Singanamalla
### Description

The aim of the session is to make people familiar with Git, the widely used version control system and how to use git with the current workflows Mozilla (gaia, kuma, b2g etc..,) have on github. This also focuses on how to make open source code contributions to mozilla while making sure that the patch undergoes a review process and needs corrections. It is a time saver to a new contributor into the world of open source.
### Agenda

The workshop session would initially start with Git, its origin and its usages, the areas where this has been used, the concepts of remotes. This would then be followed by a live tutorial on how to contribute to mozilla-b2g/gaia the Firefox OS UI layer source code present on github.

The next step would be advanced concepts like branching, fetch, rebasing, merging and also reviewing others code to make the life of the reviewers assigned those pull requests easier. This would then be shown with a live demo of preparing a branch, the reasons to use branches, keeping updated with master code and avoiding major conflicts in the code.

This should get the new contributors acquainted with git, the command line tools and sending their initial patches without major problems towards open source contributions.
### Participants

The varying numbers would be quite a challenge. If there are 5-10 participants, The best to do would be to take the participants step by step practically through the whole process of using git and cloning the gaia code base, setting it up and sending a patch.

In case the number of participants is between 10-40, the session would proceed with an overall showcase of git and a live demo of the different functionalities as well as a graphical notation for making it easier to understand the operations and how the version control changes the active directory and the data in it.
### Outcome

The outcomes after the festival would be to on board 7-10 new active code contributors to any of the mozilla/servo/b2g code projects hosted on github.

At the same time, A larger number of contributors understanding bugzilla and the review process and helping out other contributors by reviewing their code, supporting the others and sending the required patches to fix issues for the required repository.

Involving students would be a definite icing on the cake because it would make it easier to identify dedicated contributors who can propose a well thought idea towards working in the summer as a part of the GSoC projects in the upcoming year with Mozilla.

**Comment by thornet** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
