### ISSUE TITLE
inonge 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#406]
**[ Google Spreadsheet Row Number ]** 384
**[ Facilitator ]** inonge lamaswala
### Description

To bring Mozilla Zambia Community to every school in Zambia .To promote the use of Mozilla browsers for  mobile phones and  also  for the Zambia School of Education in Zambia to have Mozilla Browsers in them.We  would like to help  shape the Zambia School Curriculum  by using Mozilla  Mobile and Mozilla languages to enhance  participants. We  would like to ease the affordability in  terms of internet access in  schools.This can be  done by helping  schools with Mozilla  programme
  to be  taught in schools in Zambia.We  can also organize  mozilla clubs in  ICT hubs in Lusaka .Help using Solar Powered Efforts for Internet and Mobile Mozilla Phones.
### Agenda

WE  are  hosting  a workshop on Mozilla Zambia .We  will host in Lusaka possibly BongoHIVE .As  sometimes  students mostly cannot afford cost of Network Operators Calls .We  would like to encourage  Schools in using Mozilla powered phones that can call each other for  free  using Mozilla Firefox OS  for  free using Mozilla VOIP frameworks  a means of interacting and pushing the  agenda.Also in learning more on the Internet of things and how Facebook and Mozilla maybe working together to make this a reality.As  Facebook is very popular in Zambia.Workshop is  a format most commonly used  and I think since it is a familiar way of  working  for most  students and organizers in general.
### Participants

Our target is at least 50 -150 per class in Zambia .Most schools have more pupils on that average.As we  will be  able to demonstrate this ideas to all schools in Zambia.To educate and to implement the suite of Mozilla as a browser as well as an Educator's  tool for all schools in Zambia..
### Outcome

I know that we are always sharing across the net via facebook, workshops and in the Curriculum in School of Education.So this will not prove to be  difficult.This will be  a Web literacy for children as well as help in intensifying and identifying talented leaders in different communities  who can demonstrate what they have learnt from us .this should be  a seamless  transfer of knowledge as well as  a  window of opportunity to give equal access of knowledge .This will also be  a major factor in bridging the digital divide in emerging economies and raising the veil of  darkness and ignorance.
There are  a lot of campaigns  by NGOs in terms of literacy and also financial literacy.This will also be a facilitator in more than one aspect.

**Comment by thornet** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
