### ISSUE TITLE
Contributing to help users using SUMO

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#407]
**[ Google Spreadsheet Row Number ]** 382
**[ Facilitator ]** Andrew Truong
### Description

The audience will be allowed the ability to first see what contributors like I do for SUMO, the impact that they can make. They will then be provided with the resources to get started and contribute step by step so they are familiar and hopefully get the feeling that they are home and will help to contribute on a constant basis. 
### Agenda

I see this working with first explaining to them what SUMO is, what they do and who are the people behind it. After that, I will dive into the areas and sections of SUMO and show them what and how they can what other contributors are doing. 
### Participants

With 5, I can do a hands on approach where I can coach and provide feedback individually to our contributors. Through 15, I will do a bit more show and tell then go around and assist wherever necessary with the help of experience contributors that may be helping out. Lastly, with 50, we could do a presentation, then guide the whole audience to follow us on screen step by step. 
### Outcome

I see more people contributing SUMO and to bring more awareness around what is done at SUMO. I will take notes and relay this information back to the leaders and managers responsible.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
