### ISSUE TITLE
Making Together

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#408]
**[ Google Spreadsheet Row Number ]** 392
**[ Facilitator ]** Erica Tiberia
### Description

The goal of this session is to explore how the maker-centric learning environment itself can be used as a tool for creating more opportunities to teach others. By harnessing the potential of our community, we can increase access to opportunities for making and sharing.
How can we, as educators or parents, inspire kids (and other adults!) to make with us, and empower them to take their new knowledge and skills to share with their family, friends or classmates? 
What levels of engagement and understanding are required to make us feel as though we are able to take what we have learned and show it to someone else? How can we design workshops that empower participants to do that? 
With these goals in mind, we will learn how to make a small project, and then share our new knowledge and skills by teaching another group how to make it too.
### Agenda

Participants will split into two groups, and will learn one of 2 hands on activities, including squishy circuits and how to make your own switch, and answer some pre-activity questions. Participants will make one of these small projects, and then find a partner from another activity group. They will teach each other how to make what they have just learned, and discuss some reflection questions together. We will then discuss as a group.  
With an emphasis on sharing information, we will reflect on what it was like to teach someone else a skill that we may have just learned, and how that impacts our own learning. We will talk together about how we can incorporate teaching others as a step to learning maker skills, and how can we inspire and empower more people around us to make and share.
### Participants

As long as at least two participants are present, it will allow for the same "learn one, teach one" opportunity. Enough materials will be present to accommodate up to 50 participants, and the more participants the better for the discussion based portions, but any feedback and discussion or reflection on the experience is extremely valuable. 
Any size group will be split roughly in half, and one group will learn the first activity, and the other group will learn the second. They will also during this time answer some pre-activity questions. They will then find a partner from the other group, and they will teach eachother the project they just learned, and discuss post activity reflection questions. We will then discuss as a group. This model will accommodate any size of group. 

This activity is great for kids and adults, and I hope  to see both to discuss kids teaching us!
### Outcome

I am hoping to share my knowledge of incorporating teaching others into maker activity workshops to help scale the goal of reaching as many kids as possible. Often, the self-directed, project based format of maker-centric learning makes it difficult to maintain the same teacher-learner ratios as found in classic learning environments. In my workshops, I always emphasize that I am not the only expert and that the makers should always look to eachother as knowledge resources. I want to explore this further and find out more about other people's experiences so that it can be done even more effectively. The activities that we will be doing together during the workshop will be able to be brought back to the schools, families or organizations of the participants - how to prepare for them and run them with kids will be shared.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
