### ISSUE TITLE
Building Federated Learning with Open Source Tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#409]
**[ Google Spreadsheet Row Number ]** 394
**[ Facilitator ]** Greg McVerry
### Description

This session will gather folks interested in delivering organized learning experiences on the web.  We will brainstorm different tools that Mozillians can use to create a distributed learning experience. Given the number of respondents to the Pledge to Teach CTA who asked for professional development from MLN we will need to level up the instructional design of RCs, CCs, and metnors. We will focus on building classes that use open source tools and empower learners to develop their own content and learning pathways.
### Agenda

We will begin by sharing a few examples of open learning spaces we have developed and facilitated. We will then brainstorm as a group a list of tools that could be used. Finally we will break up into smaller groups and mock up what an Open LMS could look like if it was built using Thimble as the hub.
### Participants

We can fork for any audience size. Ian and I have experience presenting to any size of the group. No matter the size of the group the goal will be to get them making as soon as possible. For small groups we will do more hands on development combined with small group discussion. For a large audience we will break into teams and "jigsaw" different elements of instructional design.
### Outcome

We will build a framework that can be used to deliver open online learning experience. While the tools will work for students and learners the focus will be on developing professional development tools targeted at educators who are turning to MLN to fill the learning needs formal education is not providing.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter also I would like to attend this one.
