### ISSUE TITLE
The collaborative Research toolkit 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#41]
This session is designed for anyone to contribute to a ""research toolkit"". There is a strong focus on community, so maybe this will be renamed ""community research toolkit"" but let's figure this out later.

Deliverable : a toolkit for anyone to conduct their own quick research, when they need, for anyproject. 

Methods: 
1- involve a set of different experiences, from community members, academic researchers, full-time researchers, product and program designers, and total newbees. 
2 - Select the 3 main chapters of the toolkit together. For example, this could be:
a. Asking questions or how to do an interview
b. Analysing 
c. Prototyping 
For each chapter, we will document together in a collaborative manner, the ""10 tips to do a good interview"", the "" easy way to analyse data"" etc etc 

The great thing about having multiple expertises is that people will have different levels, and then the experience will be more rich in learning. For Example, Raj from India, will share knowledge about approaching different cultures. Robert from Hive could share some academic research perspective. I could share how it's like to work with a team of designer and how to provide feedback. (actually that might be a better thing from a designer )"

**Comment by thornet** [comment]
This is not taking place.
