### ISSUE TITLE
 Physical Computing with the Raspberry Pi

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#410]
**[ Google Spreadsheet Row Number ]** 393
**[ Facilitator ]** Femi Owolade-Coombes
### Description

The session will introduce people to the awesomeness of the Raspberry Pi, electric circuits and coding with Scratch and Python.  They will learn about using the command line, setting up electronic circuits safely, what the GPIO pins are used for and just having a bit of fun with blinking LEDs and resisters. It will also introduce them to Computational thinking and problem solving.
### Agenda

This will be a small workshop - 3 or 4 computers with people sharing navigator/driver roles (working in pairs). They will set up the Raspberry Pi, have an intro to basic Electrical circuits/safety, test out hardware by connecting to 3.3v pin and then re-assign jump lead to Pin18 before launching Scratch/Python.  They will use these applications to control the LED lights, set up a traffic light system and other electronic components, if time permits. More experienced participants can experiment with capacitors/sensors etc.
### Participants

With larger numbers, the session can be just 20 minutes long, so more people can have a go. We would need extra workstations/volunteer mentors to work with a greater number of participants.  We can limit sessions to just setting up one LED light to blink and change rate of blinking. When there are as few as 5 participants, the session can be longer and incorporate the use of Scratch (visual/graphic programming) and then controlling the LEDs using Python (high level programming language). Capacitors and other sensors could be introduced to the more experienced.
### Outcome

Participants get a good introduction to the Raspberry Pi, have lots of fun and get to learn/ask about how they are set up. They would be able to continue experimenting at home by taking the worksheet home - will a list equipment required and references to free Raspberry Pi/coding websites for additional resources/projects. It's a great starting point for Robotics, too.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
adding Femi's blog here as its really cool, like his session proposal!!
http://hackerfemo.com/

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by mattdigitalme** [comment]
cc @Saallen @EPIKhub just wanted to make sure this was happening in the YouthZone space as we haven't had any real contact with Femi

**Comment by EPIKhub** [comment]
Yes all's good, been talking to his mum :)

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by mattdigitalme** [comment]
@EPIKhub Awesome news!! :)
