### ISSUE TITLE
Collaboritive Video Editing on The Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#411]
**[ Google Spreadsheet Row Number ]** 385
**[ Facilitator ]** Mike Nolan
### Description

This session will be centered around video content on the web. It will focus generally around mozilla/popcorn-editor which is a modular javascript library which allows users to implement the editor from popcorn.webmaker.org. While this session is primarily discussion based I will also go over a simple tutorial of implementing the editor on a website and then dive into creating additional plugins into the editor. For instance, for the demo we will go over implementing an index plugin which allows users to associate specific keywords with events in the video and then store this data in the project metadata.
### Agenda

The workshop will begin as a simple discussion. I plan to have it be very informal in hopes to encourage discussion of how media content on the web is shared and how to make remixing that content more accessible. Depending on how well the discussion goes, we can move into a more technical demo of implementing the popcorn-editor library.
### Participants

The smaller the number of participants the more informal the talk. If there are just around 15 or less I'll probably just sit down and have a normal discussion with people chiming in as needed. As the audience size grows, I will structure it more as a talk and demo. I will likely have slides and demo materials ready but if the audience size is small enough I might ditch them and have us all work together on implementing the editor.
### Outcome

I hope this will encourage a greater awareness of the state of editing and re-using video content on the web. Only recently has the tooling for users to easily modify video content become available but there is still infrastructure to be built. Maybe some good ideas on projects for using this existing tooling will happen and at very least I hope this will push Mozilla's initiative for getting Wikimedia Foundation to use the popcorn editor tool in their websites for video content.

**Comment by cubicgarden** [comment]
We are more interested in theory and architecture level of this. @cubicgarden

**Comment by benrito** [comment]
@cubicgarden what's your current thinking?

this is a very interesting thing forming with wikimedia:

http://www.benmoskowitz.com/?p=1083&preview=true

we could be getting a working integration with mediawiki this weekend.

**Comment by cubicgarden** [comment]
Thanks Ben, its interesting and I hope we finally get a chance to chat
about this.

Have a look at this session -
https://github.com/mozilla/mozfest-program/issues/559
