### ISSUE TITLE
Hack Your Router: Privacy, anonymity, and security with OpenWRT

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#412]
**[ Google Spreadsheet Row Number ]** 386
**[ Facilitator ]** Jake Brown
### Description

In this session, attendees of all skill levels will learn in a hands on manner how to hack their home WiFi router by installing open source firmware and configuring open source utilities that enhances their security and privacy online. In my past MozFest experience, I've found that the less internet your session requires the better! So this entire session is workable with no internet connection.
### Agenda

Attendees would break out into groups of 5 or less, and each group would receive a wireless router with factory firmware. We would then review the security flaws prevalent in this default configuration and how this affects user privacy. Then we would walk through how to install OpenWRT, an open source router firmware, on the router, and configure it for use in a home. We would talk about using third party DNS to mitigate ISP spying, configuring a proxy and what that is, and forcing HTTPS connections when possible for enhanced end-to-end security. This session is especially relevant given recent FCC mandates that router manufacturers not allow users to install open source firmware. The goal of this session is to inform users of good security practices and make them aware of the legislative movement against their right to use their own devices how they see fit.
### Participants

We have over 30 battery operated routers at the ready, assuming a maximum of 5 people per group we could support up to 150 people! They're super small and easy to transport and use. In the AWESOME situation that more than 150 people wanted to attend, we could scale up the amount of people per group. For example, with 6 people per group we could support up to 180.
### Outcome

I would like for people to walk away from this session understanding their own home networks basic security, and what things they can do to enhance online privacy passively. But more importantly, they should leave the session thinking about their rights with their own devices. "Shouldn't I be able to install whatever software I want on devices I own?" As an added bonus, non-technical attendees would gain a new vocabulary in basic networking and security they might not otherwise have!

**Comment by Melechuga** [comment]
Possibility for Privacy Lab.
