### ISSUE TITLE
Prototyping Crowd-Powered Projects

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#413]
**[ Google Spreadsheet Row Number ]** 377
**[ Facilitator ]** Amanda Zamora
### Description

The goal for this session would be to outline and practice basic methods for developing editorial projects that actively enlist audience participation. 
### Agenda

The session would include three parts. 1 - basic principles for crowd-powered projects (how to enlist audience participation in storytelling). 2 - paper prototyping a crowd-powered project in teams. 3 - pitching projects for group feedback.
### Participants

I ran this as a 3-hour workshop at Hacks/Hackers BA for 50 people, broken into about 10 groups, and it worked pretty well. I would want to improve on that experience. 
### Outcome

Participants would return to their newsrooms with tools for pitching more audience-driven projects in their newsrooms, at small or larger scales.

**Comment by thornet** [comment]
cc @geroter @emmairwin and @ryanpitts 

Hacks/Hackers Buenos Aires + designing for participation angle.

**Comment by emmairwin** [comment]
cc/ @Saallen @marcwalsh
