### ISSUE TITLE
Webmaker and WoMoz

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#414]
**[ Google Spreadsheet Row Number ]** 399
**[ Facilitator ]** Tanha Islam
### Description

My session will be based on ‘Webmaker for Android’ and the main target would be women (especially young ones). However, guys can join as well. People will be able to know about the WoMoz program and Mozilla while creating contents about them. They will be given some specific topics to create content which will be related to Mozilla, open web and online privacy. My main goals are: people will learn about open web, online privacy, Mozilla and the WoMoz program while using the application. They will surf on the internet about the topics and know in more efficient way. From web users they will become web makers. Since young people learn fast it will be great opportunity to work with them.
### Agenda

My session will be an interactive one, where people will have hands on experience about the Webmaker app and following that, they will be able to create contents while learning the given topics. This will be a workshop type session with the goal: listen, observe, make and learn.
My agenda will be: 
Intro to Mozilla, open web and Webmaker for android(15 minutes)
Make a basic content using the application and demonstrate while making(10 minutes)
Let people plan and jot down their ideas on paper(10 minutes)
Make the content(20 minutes)
Best maker(s) will be given special goodies and all participants will be given goodies(5 minutes)
(total 1 hour)
(I will be needing Wi-Fi and android devices in case any participant doesn’t have one) 
### Participants

My participant number target is 20-25. They can sit on the floor at the venue. There will be several groups of 5 people with a facilitator. He or she will instruct them during the event if they get stuck or need any help while creating a content. If the place is open and anyone can see my session, they can also join but my focus will be young people. If anyone who knows webmaker for android can also join in my workshop.
### Outcome

Mozfest is basically a hub to learn, create and share and I believe that after my session, people will be able to create their own makes and can implement the same idea or the event format in their school or home. They will be inspired to host their own maker parties and spread the information to others. They will be able to discuss and organize events in more efficient and interactive way. People will be able to learn about Mozilla, the WoMoz program and open web. This session will be an initial point to promote the openness among the young people. This is how my session will be successful.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter

**Comment by emmairwin** [comment]
also https://github.com/mozilla/mozfest-program/issues/94 is womoz focused.

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
