### ISSUE TITLE
How to localize web application

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#416]
**[ Google Spreadsheet Row Number ]** 391
**[ Facilitator ]** Ali Al Dallal
### Description

Learn how to localize web application using new technology or learn what needed in order to fully localize a website.
### Agenda

Showing people an English version of the website and describing them what part of the website we will need to localize then we will start to localize them together until we have a fully localized web app.
### Participants

For a small group we will have a task to go through them together, but once the audience got larger I will be the one to drive and show them how it's done and we can go along together.
### Outcome

People will learn that localizing web app is not just doing the translation, but there are much more into that and will learn how to do them and hopefully everyone will have better understanding and know how to accomplish that for their app in the future.

**Comment by hjbailey** [comment]
cc myself I would like to follow this.

**Comment by hjbailey** [comment]
@edrushka Hey just if you would like to follow this

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin assuming this involves new technology for l10n could be tech challange for particiaption.  not quite sure what tools are involved though.

**Comment by hjbailey** [comment]
I am going to take this one out - does anyone know more about this or feel like they need it to stay in.

**Comment by hjbailey** [comment]
@marcwalsh @Saallen I am chatting to Ali. Looks like we might add this to our facilitator list.
