### ISSUE TITLE
Line Follower Robot

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#417]
**[ Google Spreadsheet Row Number ]** 387
**[ Facilitator ]** Priyank Agarwal
### Description

Primary Goal: To spread the importance of coding in the modern century and promote Web Literacy. The session is designed in such a way that it makes the attendees realize that coding and computers has been becoming an important part of each and every society and industry.

Activity: Hands on Session on Arduino Uno to make a Line Follower Robot
In this activity, we will make a Line follower Robot with the attendees just like we have been doing in Maker Parties in the past. We will make use of Arduino Uno for programming the Line Follower Robot. The attendees will be explained the code of the line follower robot and later, how they can make use of MDN to explore and learn certain programming languages and concepts. Please note that this is a completely hands on session.
### Agenda

Format: Hands on Workshop
Agenda: The topics covered in the session are:
1. What's a Computer Program
2. Importance of Coding
3. Importance of Open Source & Web Literacy
4. Hands On Session Line Follower Robot
This session is divided into two parts: 
(a) Background: Under this, the attendees will be taught about the hardware setup of the robot and Arduino. They will be shown how to install and setup the programming environment.
(b) Making: This is final stage of the workshop where the attendees will design the hardware, assemble the components on PCB, write the code and test it. They will do all of these things with us.
(c) Testing Phase: The Line Follower Robot made by the attendees will be put to test. 
### Participants

As I have been associated in Teaching Web Literacy in schools of North India for last two years, crowd management is a skill that I have learned by testing. 

For handling varying number of participants, we will divide the attendees into various teams based upon number of attendees.  Since there are 4 mentors (facilitators) in the session, different no of teams can be led by required number of mentors. 
### Outcome

After attending the session, the attendees will carry a new passion to code in themselves. The attendees will get the idea about the programming of micro controllers using Arduino Uno. They'll also be able to understand electronic components and their assembling such as IC's , LED's etc.
They'll be able to write codes for Arduino Uno. The attendees will have the capability to design embedded robotic applications. 
We will also share relevant teaching kits at the end of session for empowering them to learn and explore in future.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
