### ISSUE TITLE
Department of Sharing

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#418]
**[ Google Spreadsheet Row Number ]** 390
**[ Facilitator ]** Marion Walton
### Description

Join a hands-on mobile coding demo where you can experience an alternative environment for offline coding (Processing/APDE/PirateBox). 
We show how young people are learning to code at Ikamva Youth in Khayelitsha, South Africa. Here only a quarter of young people have computers at home or school. Three quarters have their own phone. Learning to be a coder here requires a great deal of creativity and ingenuity and young coders aren’t benefitting as much as they should from free “learn to code” resources and live-coding environments (such as Mozilla's WebMaker tools).

We’ve been building mobile tools and offline wifi ‘cloudlets’ allowing young people to practice coding as much as possible, on their own devices. The Department of Sharing is a digital storytelling app that creates Android apps, gif animations, photo stories and tiny printed books. 
### Agenda

You should attend if you work in a country where internet access is not reliable or affordable. In the workshop, you will get hands-on practice writing code on a mobile phone,  and exporting digital stories for sharing. You’ll be introduced to tools suited to conditions in the majority world, where expensive mobile data, slow connections, and unreliable or intermittent internet access make it hard to “learn to code”. 

If you have an Android phone or tablet you can bring it along. You can choose to code your own stories or translate the stories that have already been produced by young people in Khayelitsha.
Either way you’ll have something unique to take home with you. 
The workshop will conclude with a brainstorming session to explore the ways in which WebMaker tools could change to be more useful they would need to change to be more useful.
### Participants

We have a mobile lab of twenty devices which will all be set up for live demos and mobile UX experiments. If we have more people attending we can share devices and groups will work together around translation, digital storytelling and UX experiments. 
At the end of the session, participants will hear report-backs from individuals or groups who were assigned to complete other tasks
### Outcome

1) Original digital stories, exported as apps, gif animation, photo stories, and tiny printed books.
2) Translations of Ikamva Youth stories, exported as apps, gif animations, photo stories, and tiny printed books.
3) Lesson plans, materials and suggestions that will expand WebMaker tools to accommodate offline mobile coding and sharing.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
