### ISSUE TITLE
"How does information spreads online? Memes explain"

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#419]
**[ Google Spreadsheet Row Number ]** 397
**[ Facilitator ]** Rayna Stamboliyska
### Description

Understanding how memes convey opinions and how their spread relates to the spread of rhetorics behind those opinions but also to the spread of fake information, and intox in general is the overall goal of the session. We follow the way politically-charged information spreads online and can go viral. To this end, we track the spread of memes online using image search platforms, network reconstruction and mapping the changes in their rhetoric across their lifetime. 
### Agenda

The session will be hands-on workshop where each participant will explore whatever meme they like, and attempt to tell a story with it. We are building a prototype tool that the audience will use to do their own discoveries, and learn from them. In a nutshell, we will present our aim, our tools and give a few examples from our work. We’ll then offer participants the opportunity to either pick a meme of their own choice, or to work and enrich our ongoing cases. At the end of the session and if relevant, we will do a short show-and-tell.
### Participants

A group of 5 is quite straightforward to accommodate: we can either decide on a per-meme mini-project for each participant, or for one ‘memestory’ for the group where each participant would lead on a different stream of exploration. This can then be applicable to larger groups of 15 people, where a gamification element can be included; e.g., focus on a memestory that ‘escalated quickly’ or that sprung at a given point in time, etc. If we get 50 people joining, then we would be even happier. As MozFest attendance is international, such a large group would enable explorations to encompass different languages. In such a case, participants may group on a per-language base, for ex.
### Outcome

We wish to turn this into an easy-to-use tool for anyone and a Firefox plugin. Using it for research purposes but also for information verification in newsrooms are two immediate streams that we are exploring. Naturally, it’s an open source tool that anyone can contribute to. We will publish the outcomes of the explorations on our website and use them as case studies/demonstrations. We will ask participants to license these under permissive licenses that allow sharing and modification so that the widest number of people can enjoy exploring such scenarios.

**Comment by Saallen** [comment]
cc @ryanpitts

**Comment by cubicgarden** [comment]
Interested @cubicgarden
