### ISSUE TITLE
Coderdojo and Open Badges

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#420]
**Google Spreadsheet Row Number** 

396

**Facilitator**

Pete O'Shea

**Description**

CoderDojo has integrated Open Badges into their new community platform as a rewarding system. Find out about the badges and how they have encouraged people to take part at their local Dojo and how you could use badges to reward participation in clubs, classes or schools.

**Comment by chadsansing** [comment]
@chadsansing

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by emmairwin** [comment]
cc @geroter @emmairwin badges have mixed feedback and value in community, it might be an interesting session for particiaption evaluation of badges moving forward, for both learning and building community based on new understanding of what's worked/not worked for others.

**Comment by mattdigitalme** [comment]
@DigitalMe we think this will be an awesome session, looking to explore how badges can reflect recognition of learning in a variety of contexts.

**Comment by EPIKhub** [comment]
@mattdigitalme Are you taking this session into your space?

**Comment by mattdigitalme** [comment]
@EPIKhub Yup - its going to be running in our Pathway on both Sat & Sun
