### ISSUE TITLE
Off Grid - Exploring digital rights through entertainment

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#421]
**[ Google Spreadsheet Row Number ]** 395
**[ Facilitator ]** Rich Metson
### Description

Taking part in the opening and closing demo parties, by showing 'Off Grid', a video game about digital rights. Then a session where participants will be facilitated to have a round table discussion of how films, games and TV portray digital rights, surveillance, and hacktivism, and what needs to be done to further the cultural exploration of these themes.
### Agenda

The demo will be a playable version of 'Off Grid' (www.offgridthegame.com) available for participants to explore on the show floor at the opening and closing parties. The session set up as a round table discussion, starting with a presentation and some clips from well known entertainment and media that portray these themes as a starting point for discussion, and then opening up several key questions for participants to tackle and debate.
### Participants

The sessions will be very flexible and will scale well with anything from 5 - 50 people, as essentially it is a Q&A format, if we have the higher end of that scale participate a then a microphone may make it easier but will be fine either way.
### Outcome

Participants will be able to go away with a deeper insight into how culture and media portrays these important subjects, how to dissect them, and potentially a reading list/watching list of things to look out for that will help further their knowledge and explore the themes in their spare time in an entertaining fashion!

**Comment by ryanpitts** [comment]
Assigned to the Digital Citizenship milestone, but we're also considering this for Journalism's Games & Understanding pathway.

**Comment by Melechuga** [comment]
Science Fair or Privacy Lab candidate; not a standalone session.
