### ISSUE TITLE
Discourse instance for MozFest

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#422]
**[ Google Spreadsheet Row Number ]** 400
**[ Facilitator ]** Majken Connor
### Description

[Note this is an offer of resources, not a session proposal, submitting here per Sarah Allen] We would like to host a Discourse instance specifically for MozFest attendees. This will allow attendees to get to know each other before the event, and potentially make plans to meet. This will allow attendees to ask questions about sessions beforehand, and also help session runners get a better feel for who is interested in attending their session. It will create a "single source of truth" for continuing discussion and planning work that comes out of the sessions (session runners are free to use the forum to direct attendees elsewhere, but this gives people one place to look).
### Agenda

```
Discourse is a flexible online discussion platform (https://discourse.mozilla-community.org/). We propose creating a category for sessions, and then a sub-category per session to allow multiple topics to emerge from each session, and to easily group all topics from a given session. This is flexible, we could have categories per topic as well, categories can always be renamed and reorganized, even after people have started using it as it redirects well. Discourse is mobile friendly and after the first time loading it, uses few resources, so should stay usable for participants at the event even if the network is having issues. We will provide Webmaker ID as a login option as well as the typical social logins.
```
### Participants

[How will we handle logistics] - We can increase the back-end resources as needed to meet demand during the festival. We host our Discourse instances on MoFo infrastructure with the support of Simon Wex and his team. Tanner Filip will be dedicated on-site admin. He can handle issues server-side as well as helping create categories on demand and moderate topics on the front end, with assistance from Kensie. Leo and Yousef will also be at MozFest so we'll be able to respond quickly should disaster strike!
### Outcome

We would like to see participants use the forum after the event to stay in touch and make sure they follow through on actions and ideas identified in their sessions. They're free to use this instance of Discourse for that work if they don't have another space. We would like to gather feedback from attendees, and apply anything relevant towards improving the Mozilla Community instance. We are hoping that it will attract more code contributors for the Mozilla Discourse instances.

**Comment by thornet** [comment]
cc @geroter @emmairwin

**Comment by emmairwin** [comment]
I'm not sure why we would need a new instance - we could use existing with a new category.  will discuss.

**Comment by MajkenC** [comment]
@emmairwin Yes, the form didn't leave enough room to describe in detail why we wouldn't just use a category on an existing Discourse. We were talking to Sarah about this via email so she has more info, but she asked us to submit here for tracking. We have a demo up, happy to share the link if anyone asks for it, but don't want to post it publicly.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
