### ISSUE TITLE
Connecting online + in person communities

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#423]
**[ Google Spreadsheet Row Number ]** 402
**[ Facilitator ]** Nick Weinbegr
### Description

Building a strong online and in person community:

Communities can exist online, in person and many times, both. When communities live successfully online and in person, they can really compliment one another. However, at times, they can feel very disconnected and like two separate communities. How can we bridge the gap between the online and in person, to ultimately create a more integrated community that builds momentum? How do you engage these two different types of communities in a way that gets them connecting with one another and breaking down that digital barrier?
### Agenda

I'd like to see this as a fireside chat that leads into a hands on  workshop using littleBits to gets participants thinking of wild and completely out the box ideas/inventions to solve some of the problems being discussed.
### Participants

I can bring enough littleBits to support a workshop of up to 20 people.
### Outcome

I hope that the workshop leads to each in person community finding better ways to connect with the online community to create a more unified one.

**Comment by marcwalsh-zz** [comment]
cc @geroter @emmairwin

**Comment by amirad** [comment]
@emmairwin - Hey! Have you talked to Nick? He submitted many sessions and only meant for 1-2 of them to get approved so I am meeting with him soon to decide which ones are strongest. His sessions are going to take place in the clubs pathway if that's okay as they were submitted (and are being funded!) specifically for there!

**Comment by emmairwin** [comment]
@amira I have sent approval emails. Sending 1:1 scheduling and follow up
over the weekend.  Does this mean I should remove this session from our space and pathway; or that this session still is tentative on the outcome of your discussion?
