### ISSUE TITLE
Retaining and growing communities online and offline. 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#424]
### Google Spreadsheet Row Number

403
### Facilitator

name: Nick Weinberg
twitter: @nickDOUBLEyou
organization: littlebits
### Description

Once you’ve built a community, how can you build enough momentum to retain them and keep them active? How can you continue to attract new, diverse and dedicated community members, while avoiding self-gentrification? This session will focus on conversations around best practices for retaining and growing your local community and also keeping them active. While also focusing on how communities can exist online, in person and many times, both. How can we bridge the gap between the online and in person, to ultimately create a more integrated community that builds momentum? How do you engage these two different types of communities in a way that gets them connecting with one another and breaking down that digital barrier?

Hear how littlebits tackles these questions, discuss solutions as a group and get hands-on experience making with littlebit kits.

**Comment by emmairwin** [comment]
cc @emmairwin @geroter there might be somethign here for technolgoy & participation if littleBits is part of it http://littlebits.cc/how-it-works
