### ISSUE TITLE
Introducing MozClass, an initiative to work building a knowledgeable contributor base.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#425]
**[ Google Spreadsheet Row Number ]** 406
**[ Facilitator ]** Md Anisur Rahman
### Description

It will introduce the participants (who will be mostly the FSA Seniors, RALs and e-board members) to MozClass, an initiative to teach the FSA Trainee about all Mozilla contribution possibilities and pathways, so that we can have a knowledgeable contributor base who not only will represent Mozilla in their institutions but also actively have core contributions and leads on different Mozilla projects. The participants will look, hack and brainstorm to address & get a solution of all the challenges we might experience and then create the best possible structure of the initiative to run it as pilot to 3-4 clubs to have a clear practical insight of the outcome, so that we can mass implement it on all Firefox clubs. I hope this will have a great impact to have an educated volunteer base: future leaders. MozClass in details:
1. https://mozclass.etherpad.mozilla.org/mozclass
2. https://mozclass.etherpad.mozilla.org/class-structure
### Agenda

The session will be a Fireside chat. The agenda will look like below:
1. Introducing MozClass: what, why how.
2. Questions and suggestions from the participants.
3. Hacking the challenges we might experience.
4. Addressing some probable solutions.
5. Creating a good healthy class structure.
6. Creating some functional small teams or tasks groups to be handled by volunteer from the participants and facilitators.
7. Choosing some probable Firefox Clubs to run the pilot into.
8. Conclusion
### Participants

I'm targeting 15 max in the session as i have mentioned earlier, the participants will be FSA Seniors, RALs and e-board members only as we are going to launch a pilot out of this. Still anyone interested is welcome to join. We might sit somewhere in a small place where it will be quite and comfortable enough sit in a circle and then hack on the idea on spot. After having a total idea and understanding, we will divide us into some small groups to monitor some functional area to make the idea running and well documented, so that we can have a proper initiative after the successful pilot.
### Outcome

I believe after the festival we will have a quite good set of agenda to give this initiative a clean and well-planned go. We will have a well-structured FSA teaching outline with which we will teach them what are the opportunities we have as a contributor to contribute in Mozilla and which to choose. Instead of redirecting the interested faces to some online documents we will show them in real time as a mentor and then suggest the document so that they never lose interest rather find their own proficiency level and suitable pathway where they will be more than comfortable to start contributing rather switching around to have a may be good one. Me with my participants will form some small groups to have this pilot well documented and monitor the selected clubs activities under the pilot.

**Comment by amirad** [comment]
cc: @amirad

**Comment by thornet** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
