### ISSUE TITLE
Dream tech stack for journalism. Open source journalistic tools that news organizations should not miss

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#426]
**[ Google Spreadsheet Row Number ]** 416
**[ Facilitator ]** Letizia Gambini
### Description

This session will explore some open source journalistic tools that news organisations should not miss on. All newsrooms have a set of tools, either developed internally or outsourced, that form the precious know-how and help journalism supporting data visualization, monitoring, user-generated content verification, etc. (you name it). 

An example of Open Source tools for journalism is NewsLynx, a platform for measuring the quantitative and qualitative impact of journalism. - http://newslynx.org/

How can we get the most out of these individual tools in benefit of newsrooms? Integration is the answer. During this session, we will bring together journalists and editors from major newsrooms as well as developers and startups to discuss how to integrate tools to facilitate the work of journalists and editors in their daily work. 

Join this session to come and help us find out of what is the dream set of tools for newsrooms!
### Agenda

The format of this session is hybrid. It kicks off with a roundtable where journalists (e.g. The Guardian), editors (e.g. BBC) and developers (Sourcefabric) will present their ideas on the role of tools in the newsroom and it continues with a workshop where the audience will be divided in groups to brainstorm on the different phases of engaging with tools in the newsroom.

This second part of the session will be a requirements-gathering exercise for the group: what are the requirements for a smooth and useful integration of tools in the newsroom. The discussion will will focus on 3 different aspects: 
- which tools?
- how to include it in workflows?
- how to integrate in the newsroom management platform?
### Participants

Small audience: 5 participants will be able to brainstorm together on the challenge and to discuss more informally with the speakers from the panel in a round-table discussions that involves everyone.

Medium audience: 15 participants. We will be able to form two groups and receive input from the groups on the list of tools and strategy. The results will be presented to each other group and receive feedback.

Big audience: 50 participants will be able to be divided in 5/10 groups and discuss on different aspects. The results will be presented at the end.
### Outcome

The expected outcomes of this session are a list of tools that every newsroom should have and a strategy on how to best integrate them in newsroom workflows.

Superdesk is Sourcefabric’s end-to-end news open source platform. Just as there is a super desk at the centre of every newsroom, Superdesk was built to be a central connection point in the newsroom. With its API-first approach, it is built to collect and integrate tools to facilitate the work of journalists and editors. Sourcefabric aims at using the outcomes of this session to improve the integrations of Superdesk.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin might be slightly long-shot , but fun to challange tech leaders about hacking on tools like this for participation goals.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
