### ISSUE TITLE
Tell Your Story

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#427]
**[ Google Spreadsheet Row Number ]** 405
**[ Facilitator ]** Nick Weinberg
### Description

There are so many incredible stories coming out from the different clubs around the world. What is the best way to capture them and disseminate these stories out the world?

How do you translate that magic? 
### Agenda

This would definitely be a hands on session, where participants will not only discuss best ways to tell different stories through different mediums, but also tell THEIR story using littleBits in a hands on workshop.
### Participants

I can bring enough littleBits to support a workshop of up to 20 people.
### Outcome

I hope participants are exposed to new ways and forms of storytelling that allow them to tell theirs better.

**Comment by chadsansing** [comment]
cc @chadsansing
