### ISSUE TITLE
Cultivating leadership by having fun: the Cynefin Lego Game

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#428]
**[ Google Spreadsheet Row Number ]** 421
**[ Facilitator ]** Francesco Iovine
### Description

Cynefin Lego Game is a playful way to learn and experience four of the five domains of the Cynefin Framework (https://en.wikipedia.org/wiki/Cynefin), a leader’s framework for decision making which can be used to understand situations in organisations and in teamwork, and to decide how to approach them. By going through different exercises in which the problem to solve and the context will change, the attendees will learn the challenges behind each domain, and why we have to tackle them in very different ways. The game will let attendees experience the domains of Dave Snowden’s Cynefin framework, teamwork and the decision-making process in different scenarios. And have fun with Lego bricks of course :)
### Agenda

Using Lego, attendees go through four exercises where the problem to solve and the context they work in is designed to create a simple, complicated, complex and chaotic system. In the simple domain, the challenge is to sort the bricks into colours, as quickly as possible, and create one heap for all special pieces: in the following levels new challenges and rules are added, and after each level a debriefing allows attendees to discuss what happened in terms of planning, communication etc. 

More info: http://www.agile42.com/en/blog/2011/12/25/cynefin-lego-game/ 

Cynefin Lego Game is a workshop. 
### Participants

We will arrange tables for groups of three/four, about 200 bricks of Lego in 6-10 colours in different sizes with about 10% special bricks (flowers, wheels, ...) per table. With 5 participants (+3 facilitators) we would arrange 2 tables of 4 people, with 14 participants 4-5 tables, with 50 participants 10+ tables.
### Outcome

While Cynefin Lego Game does not introduce attendees to the full potential of the sense-making framework, it is well suited to get a first impression and raise interest in learning more about it! Although Cynefin is at the heart of this exercise, the debriefing focuses on outcome that is not necessarily part of the model.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
cc @amirad

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin this would be a fantastic session for community leaders attending

**Comment by ghost** [comment]
We're pleased to know that our workshop proposal has been accepted :) CC: @mamoo
