### ISSUE TITLE
From The Rainforest to Your Cupboard

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#429]
**[ Google Spreadsheet Row Number ]** 407
**[ Facilitator ]** Dian Ina Mahendra
### Description

Identify products that uses palm oil. Understand the impact of palm oil plantation towards the rainforest and biodiversity. 
### Agenda

Short talk with a flipchart showing pictures from the rainforest and palm oil plantation. Activity with participants to describe the connection between consumer, products, biodiversity and the rainforest. 
### Participants
- With 5 participants, there will be more time for Q&A and activities. 
- With 15 participants, Q&A and activities will be shorter. 
- With 50 participants, there will be more activities than Q&A
### Outcome

Participants of this session will reduce using products that contain palm oil and share this with their friends and family, so that this issue will move forward.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
