### ISSUE TITLE
Find Faces

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#43]
In the experience two we will examine the found faces-in-places we photographed in experience one, review them and choose the preferred “smiley” (or any other emotion-full) face. We will draw or transfer the face(s) onto paper using our preferred mark-making tool (pencil, pen, ball pen, marker, etc.). The experience two drawing session will take about 1–2h to complete.

**Comment by metodb** [comment]
Photographing Smilies (instead of "Find Faces")
The visual basics—how to see when we are looking—will help us find faces in the most unexpected places. These faces-in-places found in sinks, walls, street furniture, architecture, etc. will be photographed in and around MozFest for our next session.

> Metod Blejec / @metodb (Twitter)
> Session 1/3 — Saturday AM (10:00)

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
