### ISSUE TITLE
Learning through playing (with the Arduino)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#430]
**[ Google Spreadsheet Row Number ]** 414
**[ Facilitator ]** Alistair MacDonald
### Description

In this session the participants will play with Arduino technology and I hope will have some fun at the same time. This will be a slightly adapted version of a workshop I run for Northumbria University design students, and more recently (and oddly) circus performers looking to create wearable technology. The entire point if this session is to show how play can be used in education and how a small reward loop can be used to push people further.
### Agenda

Each participant or small group are supplied with a kit. In the kit is a base set of examples than can be done. Participants are asked to start work on these examples and to show is when it is working, or to seek help when it is not. The facilitators will be circling the room and monitoring progress, helping and explaining where needed, and suggesting extra tasks where appropriate. These tasks are predefined but not documented to encourage creativity and discourage rushing to complete. Different tasks are selected depending on the ability of the participants. The aim is to get the participants to create something they want to do while accidentally learning the fundamentals of programming.
### Participants

With the first 25 we will have enough equipment for individuals to work individually or in pairs if the would prefer. Above that people will be asked to form pairs or small teams. The session has been successfully run with over 30 groups in the past so with an extra assistant we should be able to scale it.
### Outcome

My hope is this session will have two outcomes. First that the participants will get the Arduino bug and start programming if they have not already. Also, and perhaps more importantly, they will see how using play and natural interest to get across concepts quickly and easily without the student realising they are learning.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc @emmairwin @geroter - exploring play can be used in education, can bring a fun angle to participation learning/training/educating lens

**Comment by EPIKhub** [comment]
@Saallen Due to other commitments this session will not be able to run
