### ISSUE TITLE
Portable Allergy detector

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#432]
**[ Google Spreadsheet Row Number ]** 418
**[ Facilitator ]** Nidhin  Antony
### Description

Now a days quality of air is degrading through out the world which is a major cause of concern because it leads to several allergies and diseases such as asthma COPD and Lung cancer.hence it is becoming increasingly important to have a portable device to measure the quality of air in real time . We propose a solution using smart phones integrated with miniature gas sensor that could alert air quality
Be smart using your smart phone and keep 
### Agenda

Here we will introduce our new idea how to avoid the problems which is caused due to air problems
1. Divide into groups
2. Introducing real life scenarios
3. Interactions based on identified life scenarios
4. Solution
5. Live demo
### Participants

No matter whether it is 5 or 50 we will divide participants into groups . We have fun ,discussions and much more

Our Team have enough have enough resource to manage our participants
### Outcome

Our new idea will bring solutions for air polluted problems which is affected by the entire world.

Solutions for skin issues.

We  will be able to make people aware of the drastic changes in environment happening around us. This can raise a collaborative effort in reducing pollution.

We will create a healthy community for a better future

**Comment by Saallen** [comment]
cc @kaythaney

**Comment by thornet** [comment]
and cc @msaunby for the garden. ^-^

**Comment by msaunby** [comment]
cc @cubicgarden do you want this for the garden?

**Comment by msaunby** [comment]
cc @ileddigital

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
