### ISSUE TITLE
Tech Strategies for Grassroots Advocacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#433]
**[ Google Spreadsheet Row Number ]** 415
**[ Facilitator ]** Dirk Slater 
### Description

This session will give advocates and developers alike an opportunity to explore how they can work together to develop and utilise tools that will help promote social change. We will look closely at how to articulate tech’s intended impact on stakeholders to create a specification to ensure successful development of tools, along with being able to identify sustainable business models that can assure survival of tools that advocacy campaigns rely on. An intended outcome of this session is a ‘best practices’ list for successful collaboration between advocates and developers.

**Comment by thornet** [comment]
cc @Melechuga
