### ISSUE TITLE
Opening up secret deals: Opportunities for business and citizens from open contracting data 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#434]
**[ Google Spreadsheet Row Number ]** 419
**[ Facilitator ]** Georg Neumann, Tim Davies
### Description

Worldwide, $9.5 trillion dollars are spent in government contracts on things such as roads, medicine, and paperclips. But some of these trillions, 13% of global GDP, also flow into cognac, over-priced products and services, and fake medicines. 

The session will focus on the benefits and opportunities for government, citizens and business coming from opening up this data on government contracts through the open source Open Contracting Data Standard. The objective of the session is to develop clear use cases for this contracts data. Ideas for use cases span creating platforms and apps for the web that allow for timely access on business opportunities, ensure civic participation by tracking and monitoring existing developments, or dashboards that track specific elements in government contracting such as efficiency, timeliness, or fairness. It will present existing data sources (EU Tenders, state of public contracting data globally) and some early examples.  
### Agenda

This workshop would combine brief lightening talks (3 minutes maximum) as a form of introduction  into the topic. These would cover a general introduction into the need for opening up contracting data and one or two examples of existing platforms. The idea is to put the data out for discussion and provide a sense of the panorama and opportunities that already exist. 

Following, the participants would split into smaller groups and work collaboratively in developing clear use cases focussing in on three areas: government, business, citizen. It will look at how do we surface open contracting data with web tools and services for those that use the web for development (civil society, government, business, journalists, etc).

The workshop ends with brief presentations by the groups on their key idea for opening up secret deals. 
### Participants

The workshop is designed to be flexible and can accommodate a variety of participants. By splitting into group work, the number and size of the groups can be adjusted. Ideal break-out group size would be 5-10 people. With a larger group (50 people), 2 groups each could focus on the same use case per audience and pitch the best against each other. With a smaller group (until 15 people), participants in break-out groups can be reduced easily. With less people, a decision on the focus of the break-outs (business, citizens, government) will be made. 
### Outcome

The outcome would be to have a solid set of uses cases (3-6) that can moved forward either by enthusiastic participants in collaboration with the Open Contracting Partnership or by the Open Contracting Partnership alone. In any case, these innovative use cases will inform ongoing developments in countries globally and shared in different formats (blog posts, schematics, brief summaries). The hope is to infect a new audience with the idea that something can be done to make government contracts more transparent and create a benefit for society.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Data & Impact" pathway.
