### ISSUE TITLE
Digital Purdah or how the web helps maintain restrictive social norms 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#436]
**[ Google Spreadsheet Row Number ]** 409
**[ Facilitator ]** Emrys Schoemaker
### Description

This session will help people learn how social media can be used to maintain restrictive social norms, and explore strategies to address these
### Agenda

Format: presentation and discussion 
Presentation: overview of theory and description of case study from ethnographic research in Pakistan followed by discussion. 
### Participants

The same....
### Outcome

Identification of strategies to address the maintenance of social norms can inform policy and practice by activists in country and internationally.

**Comment by Melechuga** [comment]
Candidate for panel

**Comment by Melechuga** [comment]
Move to panel.
