### ISSUE TITLE
Prototype an ICT for Womanity Learning Network

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#437]
**[ Google Spreadsheet Row Number ]** 410
**[ Facilitator ]** Servane Mouazan
### Description

Using design thinking principles (What Is, What If, What Wows, What Works), the participants will look at a few examples of civic organisations that harness ICT to prevent violence against women and jointly brainstorm to see how to maximise their impact through a global network. 
At the end, we’ll have a model and a plan, more people aware of what ICT for Womanity is and could do, and potential founding members!
### Agenda

The group will jointly explore the following steps and create visuals, doodles, notes, on paper or tablets, to capture their conclusions:
1- What is: Who are these organisations that prevent violence against women using ICT? What do these organisations go through in their day-to-day practice? What difficulty they are facing, what prevents them to make a difference at a wider scale, what are their strengths. What do people think they are doing?
2. What if: using the power of networks, how can an ICT for Womanity learning network solve the bugs mentioned above?
3. What wows: shaping a foundation format with key activities and messages for the network to launch with a first group of members
4. What works: establishing a way to measure results of the network activities and to disseminate ICT products and advocacy efforts to a mainstream audience. 
### Participants

The format works with either 5, 15 or 50 participants.
From 9 participants onwards, we create sub groups to look at the same steps. The groups then reconvene and share their results after each phase of the process, and learn from each other, building up a rich insights bank.
### Outcome

We can then launch the ICTforWomanity network in January 2016 and share on-line the conclusions of the workshop in a spirit of transparency. Any good practice suggested collected during the workshop will become part of a convener that the network members will adhere to and aspire to implement. 
Every year, during a physical event or on-line event, we review the good practice and see how the members have evolved. 
- The participants can either be part of organisations using ICT to prevent violence against women and immediately be part of the network founding members 
- They might be end users or survivors of violence themselves and become ICTforWomanity “advisors”
- They can be part of either or both groups above, or none yet feel really involved with the topic and contribute to write about or disseminate information and insights collected as we go. They become “ambassadors”

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
