### ISSUE TITLE
Supporting collaborative festival coverage

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#438]
**[ Google Spreadsheet Row Number ]** 412
**[ Facilitator ]** Raphael Velt
### Description

Participants will design 'services' to improve crowdsourced and collaborative coverage of festivals.
This could be anything from a 'Mozilla Webmaker' for live content aggregation to Internet of Things-based services or even something entirely paper-based that doesn't use any electronic/computer tech.
We are especially interested in creating services that connect people together, both on-site and off-site.
### Agenda

This will be an informal workshop.
Participants will introduce themselves by explaining why they joined the workshop and what their agenda is (e.g. do they want to make event coverage something more personalised?, are they interested in legal issues such as content licensing and ownership?, is their goal to promote digital literacy?, etc.)
The issues raised in this part will be written on a flipchart as an inspiration for next part.
Depending on numbers, participants will then be split into groups, be asked to come up with ideas that address these issues and present them as user scenarios.
The last phase of the workshop will be about pitching these scenarios and get constructive feedback from other groups.
### Participants

The number of groups will depend on the number of participants, with ideally 4-5 participants in each group, more if there's a high number of participants. The duration of the pitching/feedback phase will be adapted to the number of groups to give time for feedback.
### Outcome

The short-term outcome will be to understand opportunities and issues around crowdsourced coverage of events.
The long-term outcome will be to start working on an open-source toolkit that will help event organisers and participants around the world to create crowdsourced coverage of events.
Participants in this workshop will be asked if they're interested in participating in the facilitator's subsequent research and may be contacted to take part in more in-depth prototyping workshops.

**Comment by thornet** [comment]
cc @secretrobotron might be of interest re: using Webmaker creatively.
