### ISSUE TITLE
Best Practices for Onboarding

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#439]
**[ Google Spreadsheet Row Number ]** 404
**[ Facilitator ]** Nick Weinberg
### Description

What are some of the best ways to onboard new members to your community? What types of activities are needed to help new community members feel welcome? This session will focus on best practices for onboarding.
### Agenda

I'd see this is a fireside chat, where participants go around and share what's worked well for them and what hasn't.
### Participants

I can bring enough littleBits to support a workshop of up to 20 people.
### Outcome

I hope participants will find new ways for onboarding new community members into their communities.

**Comment by emmairwin** [comment]
cc @geroter @emmairwin

**Comment by amirad** [comment]
Closing this session as Nick will only be doing one of his sessions now!
