### ISSUE TITLE
Teaching the Basics of Privacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#440]
**[ Google Spreadsheet Row Number ]** 423
**[ Facilitator ]** Tom Farrow
### Description

This session will allow people to teach web privacy at a basic level. They will have a good knowledge of key concepts such as data permanence, cookies, tracking, third party data mining and how they can introduce these concepts to others with little to no knowledge on the subject. This session will empower the participants to facilitate sessions of their own and create their own session material.
### Agenda

This session is a 90 minute crash course that will introduce participants to tools which help with teaching the amount of tracking which you are exposed to through websites, especially including making the number of third party sites which track your use of the internet. As a part of this we will be teaching an understanding around cookies, and how these concepts can be taught to different audiences, often using analogies. We will also introduce the idea of data permanency and how it works in a discussion style setting covering how exposing data today can affect your life in the future. To help with these discussions we will encourage the use of personal experiences and will also have some real life examples ready. We will also introduce participants to the curriculum and session plans mozilla already has.
### Participants

With small groups of 5 we will be looking at running a whole group discussion using videos and examples to encourage conversation and discussion about the topic matters and then show how they could plan and facilitate their own sessions in a similar fashion.
With a larger group of 15 people we will be looking at splitting the group into half with one facilitator running discussions within each group or very large groups of 50 will be split up into groups of 6-8 with the facilitators moving between the groups to help the discussions progress about the topics. 
Video resources can be shown using a projector, and with texted based resources can be give out as handouts to each group to be used to help along their discussions and then looking into sharing ideas and opinions in between the groups after each discussion finishes.
### Outcome

We want attendees to be able to leave the session being able to run their own sessions on web privacy to others. We’d like to see potentially global activation of web privacy being taught by people of all experiences, ages and backgrounds as this is a topic which affects all internet users. they should have some real life examples of how the topics discussed can affect people.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by cubicgarden** [comment]
Interested @cubicgarden

**Comment by emmairwin** [comment]
@geroter  intersection with youth and participation pathway on scaling learning experiences. Can also coach here.

**Comment by emmairwin** [comment]
removed from our pathway but will include tom in our coaching/pre-mozfest leadup
