### ISSUE TITLE
How to tell stories with VR, Drones and Telepresence?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#441]
**[ Google Spreadsheet Row Number ]** 413
**[ Facilitator ]** Martin Nahuel Rabaglia
### Description

In the last year journalism it was invaded by two technological devices Virtual Reality. In this workshop we will show concrete examples and play a bit to understand how this technology sets the pace for the telepresence, immersion and understanding of situations.
We will try to see ways of telling stories that may occur using this technology. Each person may apply in their stories or articles otes using technologies.
### Agenda

This session will be a workshop for journalist+filmakers and developers.
The agenda of the workshop will mix, traditional storytelling activites with some development.
This workshop will go for around 2hs and 30 minutes.
The agenda for the activity is : 
-Live Lab: Explore current status quo of inmersive storytelling.
- What is Inmersive Journalism?
- Differences between Vr,Ar, 360 video.
- Activity: Create a Storyboard with 360 video.
- Drones vs Quadcopters
- Drone Storytelling
- Workshop > Unity and VR > Quick example.
### Participants

This workshops will be for 50 participants. max, divided in 5 teams of 10 participants.

All of them should have their own laptop.
### Outcome

The goal is to motive to journalist, developers and film makers  to define the rules and frameworks of storytelling after cinema. 
After this workshop, the will have the tools and knowledge to kick off any project of post storytelling.

**Comment by thornet** [comment]
cc @marcwalsh for including in a "what's possible with VR and Mozfest" conversation with Josh Carpenter.

**Comment by Saallen** [comment]
@thornet is this still going ahead?

**Comment by thornet** [comment]
Not to my knowledge. I suggest we close it since it hasn't be labeled by anyone else.

**Comment by ryanpitts** [comment]
Late addition to Journalism
