### ISSUE TITLE
Raspberry Pi youth section workshops

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#442]
**[ Google Spreadsheet Row Number ]** 411
**[ Facilitator ]** Andrew Mulholland
### Description

In our sessions young people will learn an introduction to creative programming and basic electronics through workshops in making music with Sonic Pi, hacking Minecraft Pi with Python, playing with electronics with Python and ScratchGPIO and creating games with Scratch.
### Agenda

We are hoping to do a number of 45-60 mins workshops over the 2 days in the youth section using the Raspberry Pi with groups of 20-25 young people.
A majority of the sessions will be different (although there may be a few repeats). It opens with an 5-10 min introduction to what the Raspberry Pi is, then a guided workshop on that topic where the young people work towards creating an awesome final projects.
We already have a team of 10+ volunteers to run the workshops and help out with them.

Proposed sessions:

> Using Minecraft Pi and Python to work with real geographical locations
> An introduction to using Scratch with the GPIO pins on a Raspberry Pi
> Using fruit your 1 of 5 a day! (and anything else that doesn’t move fast enough) as a keyboard
> Coding castles and hacking hardware in Minecraft with Python
> THE sense HAT workshop
> Astro Pi workshop to space and beyond (2 of these are going into space in November)
> Sonic Pi - Make your own music
> Pi dot to dot and see it in Minecraft
### Participants

The sessions can take up to 25 young people, although can easily run with less than that.
The limit is imposed due to the limitation of equipment.
The Raspberry Pis are being provided on lend for the weekend from Farset Labs, the Northern Ireland Hackspace.
### Outcome

As the Raspberry Pi is extremely affordable, it would be very easy for the young people to go home and get their own Raspberry Pi if they wanted. But, a lot of our activities use software that is also available on Windows and Mac OS including Sonic Pi and Scratch, meaning they can easily continue at home for free without needing to get a Raspberry Pi.
They will also be invited along to attend the free Covent Garden Raspberry Jams if they are interested in learning more.

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
