### ISSUE TITLE
3P's to Participation - People, Places, Perception and how they change the dynamics of involvement.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#443]
**[ Google Spreadsheet Row Number ]** 425
**[ Facilitator ]** Soumya Chakraborty
### Description

This will be an interactive session which evaluates the pillars of participation and encourage the participants to engage in an activity of identifying how the above 3P's influence the involvement in their region/country.

Mozilla being a global community of people, its important to do a yardstick measurement on participation based on the above 3P's and have a plan of action for the new team.
### Agenda

I prefer this session as a workshop.
Agenda - 
1) Participation and Mozilla
2) 3P's of participation
3) How each of them determine the mechanics of participation.
4) Feedback from session participants about involvement in their community.
5) Chalk out a figurative plan of participation based on the input from the workshop.
### Participants

5 Participants - 

1) Discuss with each other about their inputs on participation and how easy/difficult is to get people involved.
2) Get the action points and plan to take it back to the community we belong.

15 Participants - 

1) Have an interactive questionnaire on 3P's of participation.
2) Discuss all the answers and try to draw a line of how 3P's affect participation.
3) Get the action points and plan to take it back to the community we belong.

50 Participants -

1) Divide among 10 groups and discuss the questionnaire given regarding 3P's in each group.
2) Each group comes up with the challenges and positives, they think,  participation faces due to variation in 3P's.
3) Get the common action points and learnings back to our respective communities.
### Outcome

Participation is a new team and discipline in Mozilla and is very crucial for the overall success of the organisation.

Outcome of the session/festival is to figuratively discuss the crucial components of participation and deduce that we can't use the same yardstick to implement, measure or plan the participation methodologies all over the world. 

Mozilla Festival being the mothership of involvement will also give vast knowledge about how different people from various places with similar perception (somewhat) unite to leave such a great footprint.

I hope each participant from my session and generically takes away the actions points for participation in their respective communities and implement them. Also they learn to overcome temporal and behavioural challenges faced during the growth of participation across any community in the world.

**Comment by amirad** [comment]
cc: @amirad

**Comment by thornet** [comment]
cc @geroter @emmairwin

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
