### ISSUE TITLE
Learning not to fear the future by sharing what we know

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#444]
**[ Google Spreadsheet Row Number ]** 424
**[ Facilitator ]** 
name: Helen Storey
twitter: @ProfHelenStorey
organization: University of the Arts London
name: Michael Saunby
twitter: @msaunby
organization: Met Office
### Description

We’ll explore the opportunity, and urgency, for all of us to shape our shared future, through co-creation by designers, technologist and all who use the web.

It's not necessary for everyone to understand the details of, say climate change, to act now and do something about it.  There's a parallel with technology here as anyone can use the web, without knowing all the detail of how it works. User, and consumers, shape its future just as much as those who design build and design.  Fashion is like this too, consumers determine the future as much as designers.

Helen Storey and Michael Saunby will lead an exploration of how we can use the web to share visions of the future and calls to action, whether it be to ensure the freedom of the web or protection of the environment.  
### Agenda

 25 years in 5 minutes'  will bring everyone up to date with Helen’s career as a fashion designer.

It will then open out into a workshop style session where the challenges of building communities can be discussed and actions or investigations proposed.
The session is most definitely not just for vocal activists, indeed we’re particularly keen to meet quiet reflective types who are at their most comfortable expressing themselves on-line. The web provides the technical means for everyone to have equal voice, so how might we make that a reality?
### Participants

After the initial opening chat we’ll open to everyone to share any questions they might have regarding the use of the web to share calls for action.  In particular we’d like to think about how goals can be shared with disparate communities, for example languages, faiths and ages. These questions can then be further investigated in small groups.

For a small number we'll have a cozy chat, for larger numbers we'll have quiet groups, vocal groups, and more as needed.

We’re particularly keen to see this session contribute to the Building a Crowd pathway, and happy to adjust the sessions to provide either idea generation or idea selection and focus for participants in that pathway.

Perhaps we can also provide other experiences for participants in the relevant pathways.
### Outcome

We’d like to provide widely applicable guidance and tools for those driven to make the world a better place, and others who’d just like to help or observe.  Somewhere to share both triumphs and failures that others might have more of the good stuff and less of the bad.

**Comment by thornet** [comment]
cc @msaunby

**Comment by thornet** [comment]
cc @msaunby @cubicgarden as I believe you're working with Helen on this, right?

**Comment by cubicgarden** [comment]
Yes thats right... thanks @thornet, added to Global Village

**Comment by EPIKhub** [comment]
@cubicgarden just had a chat with Micheal, we would like this session #444 to happen after https://github.com/mozilla/mozfest-program/issues/206 Sheduled for 11am on Satureday morning as one of my opening sessions that helps people explore the wider festival and all its spaces. Helen will attend our session and we will then signpost youth to hers

**Comment by cubicgarden** [comment]
Right OK I have Helens session for the afternoon on Saturday

**Comment by EPIKhub** [comment]
@cubicgarden thxs :)
