### ISSUE TITLE
Building Networks Through the Art of Conversation

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#445]
**[ Google Spreadsheet Row Number ]** 420
**[ Facilitator ]** Bhuvan Shrivastava
### Description

By the end of the session, the participants would be able to:
- Have more effective conversations, regardless of how diverse their audience might be
- Easily connect with and talk to someone from a very different professional or cultural background
- Ask questions that allow others to want to share their knowledge or experience with you
- Empathize with others
- Build stronger personal and professional networks
- Make others interested in something you are passionate about
### Agenda

The session will focus on peer-to-peer learning by allowing participants to learn from each other. 
- We will first start with a short exercise where pairs meet and talk to someone they don't know for a few minutes.
- We will then break them into small groups, and ask them to think about 'bad questions' to ask someone during their first conversation
- We will then ask the groups to share their list of questions with everyone else. Hopefully, this would be a good group ice-breaker with a few laughs
- Lucy and I will pull out some common themes from these questions and give a few, easy to remember tips
- We will then pair the participants again ask them to repeat the first exercise again, this time based on their learnings so far
- We will then ask everyone to share their experience with everyone again.
### Participants

Depending on the number of participants, we would split them in pairs or small groups. Lucy and I will jump between groups to observe and help them along if they get stuck during their activities. The number of participants would determine how much personal attention we can give to each group and how often we can mix-and-match the participants between the activities
### Outcome

The best outcome after the festival for us and the participants would require that:
- It becomes easier for us all to be able to relate with a diverse audience, and connect with people more effectively through conversations
- The participants are able to replicate the simple exercises of the session with people around them, to help them learn the same skills as they did during our session

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by bhuvanshri** [comment]
Cc: @bhuvanshri @LucyeoH

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
