### ISSUE TITLE
Science Inquiry and Game Design, A Harmonic Convergence

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#446]
**[ Google Spreadsheet Row Number ]** 426
**[ Facilitator ]** Ashlyn  Sparrow
### Description

This session will explore the convergence of educational practices and design frameworks, drawn from a range of content area foci and program types, that can help foster youth-led, production-centered learning environments. Participants in the session will identify how these practices and frameworks can be applied to their current learning programs whether they be online, in-person, or a combination of the two.

The session seeks to bring together educators, technologists, game designers and players to identify challenges and success with current educational techniques while exploring explore game-based learning and its convergence with scientific inquiry and other domains. Together with educators and program designers from Game Changer Chicago Design Lab at The University of Chicago and Chicago Academy of Sciences/Peggy Notebaert Nature Museum, session participants will explore, create and share game-based tools for education. Participants will identify games and game design as effective tools for student learning and assessment.
### Agenda

The session will begin with a brief overview of the Nature Museum’s TEENS program and the Game Changer Chicago Design Lab’s Project S.E.E.D.; the out-of-school time programs led by the session facilitators.  Project S.E.E.D. is an extended game with an underlying narrative, played over three weeks using a variety of activities to solve Science, Technology, Engineering, Math and Arts-related challenges. The Nature Museum’s TEENS program is a six week summer program focused on urban ecology where students design and carry out field-based citizen science projects. Facilitators will highlight commonalities in the design frameworks used in these programs. Attendees will then workshop how these frameworks could be applied across learning contexts and subject areas, as well as design and develop small game-based experiences.  At the end of the session, groups will share out their designs.
### Participants

Our current structure allows a flexible number of participants for this session.  With a small number of participants, we will work as a one large group following the same agenda; with a larger number of participants we will breakout into multiple groups following an initial introduction by session facilitators.  
### Outcome

The desired outcomes of the session are:
• “Hackable” game-based science curricula used as the building blocks for developing educational youth programs.
• A web-based document on why, when and how to incorporate game-based learning into the classroom and after-school space, with an emphasis on STEM education, to be shared with all Mozfest participants.
• Game designers (and educators) learn to develop educational games, mapping game mechanics to learning goals and their outcomes.
• Educators and organizations incorporate game-based learning and play into their programs  as a means to help foster the development of inquiry skills.
• Educators view games and game design as valid and effective tools for student learning and assessment. 
• Educators utilize the design frameworks to help develop meaningful youth-led, production-centered learning environments across contexts and subject areas.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by ryanpitts** [comment]
@acabunoc we'd definitely like to include this session in our "Games & Understanding" pathway, and would be happy to send out an acceptance notification on behalf of the Journalism space. Not sure what your plans were here, though, so maybe this is one we can discuss when we chat on Tuesday?

**Comment by abbycabs** [comment]
happy to let you take this one, @ryanpitts!

**Comment by ryanpitts** [comment]
:+1:

**Comment by abbycabs** [comment]
I'll keep the tag on in case we find a good pathway to include this in (& send ppl to your floor)

**Comment by Zebetus** [comment]
@ryanpitts @EPIKhub once again can we sign post this to some of the kids from the youth zone (especially considering that it is looking at youth led)
