### ISSUE TITLE
Drafting the Robot Code of Ethics: speculating on dystopian futures, changing/understanding dystopian presents.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#447]
**[ Google Spreadsheet Row Number ]** 427
**[ Facilitator ]** Zara Rahman
### Description

Imagine a world in which all information gets processed by sentient algorithms. Now imagine that our new robot overlords decide to give humanity a chance to define a set of rules to guide them in ethically, responsibly managing our data. You are invited to be part of an elite group of responsible data specialists tasked with creating the Robot Code of Ethics: a set of guidelines that might just be humanity’s last chance of preserving a free, open and ethical space for communicating and living safely and responsibly.

By imagining a dystopian future, we hope to better understand our present. In 100 years, what will we wish we had thought of right now? We’ll call upon the power of participants’ imaginations to scope out areas that the responsible data programme could focus upon - whether that is in this century or the next, remains to be seen… 
### Agenda

This session is a collaborative workshop for technologists, thinkers, researchers, and anyone invested in critically thinking about how to preserve people’s right to free and responsible sharing and ownership of information in a machine-mediated world. The session will use speculative design techniques to get people to use their imaginations in thinking about ethics, machines and the future. The workshop will be divided into three sections:

“It is the year…”: The participants will create a shared narrative about the futuristic world they are inhabiting.

Drafting the Code: participants split into groups, each tackling a specific issue that was defined in step one. At the end of this step, we will have a working set of principles for each issue
Report back and completion of the Robot Code of Ethics: each group will share their segment of the Code, and they will be combined together to create the final Code.
### Participants

The structure of the workshop is meant to accommodate varying numbers of participants, by splitting them into larger or smaller groups. If there are more than 20 participants, the group will self-select group leaders to assist with coordination and report back.
### Outcome

In addition to a draft ‘code of ethics’ itself, which will be shared on the Responsible Data programme site (https://responsibledata.io/), if relevant and useful we will create an online space (wiki, github-powered website, or any other tool that suits the purpose), for participants and the wider community to comment and interact with the results.

**Comment by thornet** [comment]
cc @Melechuga @cubicgarden -- responsible data FTW!

**Comment by Zebetus** [comment]
@EPIKhub This could be a really interesting way to get young people thinking about the future and a way for kind of bring in some more serious notes (get that wider impact)

**Comment by EPIKhub** [comment]
@Zebetus I do see the scope here, now the question is could it be adapted to work with our kids!?

**Comment by Zebetus** [comment]
@EPIKhub If possible maybe something either along the lines of we schedule this for just after one where they make their own robot or in the same day and encourage those that do make a robot to come to this and change the style to "make the code of ethics for your robot"? and if that is not possible there could be the option to have people just draw there own robot make it super colourful there and then they make a code of ethics for that? (would be what i would suggest)

**Comment by thornet** [comment]
cc @cubicgarden and @ileddigital again for consideration!

**Comment by cubicgarden** [comment]
@thornet and @ileddigital closing this one...

**Comment by EPIKhub** [comment]
@thornet @cubicgarden Its a shame as @Zebetus really liked this one but they did not think they could make it work within the youthZone

**Comment by thornet** [comment]
cc @marcwalsh @Saallen to notify the facilitator.

**Comment by marcwalsh-zz** [comment]
cc @marcwalsh-mozfest
