### ISSUE TITLE
Locating and collecting geospatial data to empower youth and communities

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#448]
**[ Google Spreadsheet Row Number ]** 430
**[ Facilitator ]** Stuart Lynn
### Description

Public and open data can help us all make better personal decisions and better decisions for our neighborhoods and communities. Often though its hard to discover relevant data , process it in to a form that facilitates insight or the data might not even exist. The goals of our session is to introduce data discovery services, data processing and visualization tools and data collection strategies and plans to use them all together to answer and empower young people and communities
### Agenda

The session will be a workshop and the proposed format is to first talk with the attendees about problems or issues they face, help them identify data sources and tools that might help and discussing how data might be collected to better understand the problem. We will then have attendees collect data aimed at answering questions about MozFest from around festival and use various tools to explore and visualize  this data.
### Participants

We see this scaling by splitting the participants in to groups or 10 - 20 and have quick feedback from each group after each of the tasks in the session. We will have at least 2-3 facilitators to help each group . 
### Outcome

We hope that after leaving the session our participants will feel more capable of identifying public data that might have an impact on the problems they face in their lives or community, be aware of the tools that can make sense of this data and be able to identify gaps in this data and devise strategies to use tools like epicollect to gather this data and make it publicly available to their peers.

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by abbycabs** [comment]
@acabunoc -- 'open data'

**Comment by Zebetus** [comment]
@EPIKhub once again a great way to tie in youth with science and this one looks at impacting the community around
