### ISSUE TITLE
Virtual Proximity for Social Value

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#449]
**[ Google Spreadsheet Row Number ]** 429
**[ Facilitator ]** Niberca Polo
### Description

Part of becoming digital literate is the ability to understand the  world wide web, and the ways in which we can use virtual spaces to engage and motivate, teach and learn, and ultimate affect the world in positive ways. In this workshop students will:
- understand the importance of social media as open-source,  learning tools
- learn about open source apps and platforms that can be used by students and teachers equally, for research, writing, collaboration, etc. 
- work collaboratively (teams) in Popplet.com to create visual maps to brainstorm posts' ideas/concepts, and OpenProcessing to share final concepts with all participants 
- Create posts in different platforms, such as Instagram, Pinterest, Twitter, and Facebook as a way to get immediate feedback and measure the social relevance of posted content. *social relevance (value) will be assessed based on re-tweets, likes, shares, etc.
### Agenda

WORKSHOP:
1- icebreaker/acrostic 5 min
(Slideshow)
1. Open source technology and social media to measure "social value: 
2. briefly explain
3. demonstrate different platforms to use in workshop
   20 min
4. Work in teams on Popplet (mindmaps of ideas for posts) and OpenProcessing (final ideas/concepts for sharing)
   45 min. To 1:15 min, depending on size of group
5. Look at activity on social media and reflect on effectiveness of concept posted. 
   30 min. 
6. Wrap up; reflections on overall activity, comments/suggestions. What we learned? Q&As
   30 min. 
### Participants

Depending on the group size, participants will split in mini-groups; however, there is a portion of the workshop when participants would need to work independently. 

**space should have computers; if the group is big and there are not enough computers, participants could use mobile devices, such as tablets, and smart phones. Internet connection (WIFI) is needed. Projector + white board would help demonstrate some processes. 
### Outcome
- Be able to easily navigate various social media platforms
- Understand ways to use open source technology, like social media outlets, for research, collaboration, teaching, and testing. 
- Learn ways in which the "social value" of learning exercises/productions can be measured out in the world. 
- understand the dimensions of the impact of such productions in the world
- apply learned knowledge in both in-classroom and everyday learning experiences

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
