### ISSUE TITLE
Collective gaming session

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#45]
A collective game session in which all the participants in the session play a multiplayer game together using their phones. They must work together in teams (though they might not know who their team members are) to accomplish goals in real time, and their progress is reflected on the projector. Afterward, they’ll be group discussions about their experience, what types of things they were able to learn, and what topics are particularly suited to being taught with mass participation. Participants will also get some resources to help them create games like this on their own.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
