### ISSUE TITLE
Happiness in the Digital Era

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#450]
**[ Google Spreadsheet Row Number ]** 428
**[ Facilitator ]** Laura Gordon
### Description

Fun and games - ways of practically creating happiness in the digital era.
### Agenda

A series of questions and possibly some short interviews to inspire discussion among participants. I'll aim to create a environment where participants feel free to speak candidly and show vulnerability. 
### Outcome

Ideas, fun and play. Every participant will create some happiness for others and feel inspired and empowered to create positive interactions in their work and daily life. Awareness of the role of the individual in creating positive effects on themselves and their community digitally and offline. Positive psychology in action!!

The main point is to discover which people and business and technologies are supporting positive individual and social psychology and which are negatively affecting and our role within them so that people take that perspective into the software and marketing they are producing.

**Comment by cubicgarden** [comment]
Hoping we can tie this to the #303 one if @Melechuga agrees?
