### ISSUE TITLE
Breaking the curse (of dimensionality)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#451]
**[ Google Spreadsheet Row Number ]** 440
**[ Facilitator ]** Anatoly Bondarenko
### Description

People will learn how to get sense of multi-dimensional (more then 3 variables) data sets in a visual way, with a help of a browser and JavaScript based web tools. 
Specifically we will learn how to search for patterns, correlations, exceptional values. We will use such a methods as scatterplot matrices, interactive tables, and dimensionality reduction algorithms. We will work with example data sets to make a practical exercises. 
### Agenda

This is workshop in which short demonstrations will be mixed with practical excercises.
- Short introduction: problem formulation (15 min)
- Working with scatterplot matrices (30 min)
- Working with interactive tables (30 min)
- Working with faceted views(crossfilters) (30 min)
- Working with dimensionality reduction (45 min)
### Participants

I think the number of participants doesn't matter until up to approximately 20 people. If number will be bigger we have to increase total time by one hour,
because  time to complete an exercises will be bigger
### Outcome

After festival participants will have a practical knowledge how to explore multidimensional data sets in browser, how to find some insights and "stories" in multidimensional data . Moreover, they could use specific JavaScript libraries in their own projects.

**Comment by Saallen** [comment]
cc @ryanpitts

**Comment by ryanpitts** [comment]
Journalism is accepting this session.

**Comment by ryanpitts** [comment]
@acabunoc this could be a nice addition to our "Tools & Analysis" pathway. What do you think?

**Comment by abbycabs** [comment]
@ryanpitts :+1:
