### ISSUE TITLE
Getting Started with Open Source Contributions 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#452]
**[ Google Spreadsheet Row Number ]** 431
**[ Facilitator ]** Gloria Dwomoh 
### Description

My session will allow people to learn how to get started with open source contributions. Sometimes getting started can be daunting and this workshop hopes to lessen the learning curve. In a nutshell people would be walked through the steps on how to get started contributing to open source from the ground up. Raging from things as opportunities to translate, coding, close captioning, documentation and much more. Having a list of beginner friendly projects of Mozilla that are in need of contributors will be a great addition to the program, as then we can promote opportunities within Mozilla in addition to other open source projects.
### Agenda

It will be a workshop broken into 3 sections. The first will be a general section. An ice breaker and a place where people will briefly learn what is an open source project, why is it important and why their contribution matters. The other two sections will be broken into technical and non - technical. In the technical we will go through a road map on the basic know-how to get started such as GitHub, git, virtual environments, knowing how to effectively look for tools, how to get started learning programming and every basic knowledge needed. The other section will be non technical, how people can help with localization, documentation, donations and other non technical means to contribute to an open source project or product they love. 
### Participants

I will follow the same plan be it 5, 15 or 50 people. However if it is 5 people all of them will work as 1 team. If it is 15 people or 50 they might be asked to split into smaller teams and collaborate by doing mini challenges at each of the 3 stages or they might  be asked to collaborate to do small contributions on specific projects for practice.  
### Outcome

I believe that after the festival a lot more people will now know how they can contribute to opensource projects. Them knowing why open source products/projects are important, how they can contribute to it, in which way it impacts their daily lives/careers, and have a vast amount of open source opportunities they could be a part of, I believe, will be something they will strongly consider working on, and at the same time the number of Mozillians might increase out of this experience.

**Comment by EPIKhub** [comment]
News to me! pathway

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter
