### ISSUE TITLE
Open Tools for Network Measurement 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#453]
**[ Google Spreadsheet Row Number ]** 434
**[ Facilitator ]** Chris Ritzo + Fereidoon Bashar
### Description

Measurement Lab (M-Lab) has a number of tools for measuring network state and performance, and we're looking for help on digital campaign to promote our new Measure app. We’ll demo our “Measure App” and talk about ideas participants have on how their communities might use it. People will be able to install and use the app.

Also: In countries with growing Internet censorship policies, it is expected that heavier information controls will be imposed around political events such as elections. This workshop will look at current efforts by researchers and civil society actors to document and report on information controls, and to reduce disruption to online information and communications by proactively developing alternative modes of connectivity via circumvention technologies in response to various scenarios that could be induced by the authorities in Iran.
### Agenda

We would engage with participants in a “science fair table” format, where we demo the M-Lab Measure App with groups and individuals on a regular schedule, and informally discuss how different constituent groups might utilize it. We would have copies of the App available for offline installation on all supported platforms.
### Participants

Since this would be a science fair table demo and discussion, to accommodate different numbers of participants we would have staff available at the table at all times to discuss the project and to talk with interested people. We would also schedule demos to occur at specific times throughout the conference, as well as be available for ad-hoc quick demos in between.  Additionally, we would schedule alternate times for highly interested groups if desired. Ideally we would have a display where our demo could be shown to attract passers-by. We would also prepare all materials in advance to be online, and promoted through giveaways like stickers or other schwag.
### Outcome

Our goal is to broaden our understanding of our community of users to construct  campaigns 
to build a community around the Measure app. For users and groups interested in global net neutrality, and consumer protection, a post festival outcome will be increased global awareness of a strongly vetted citizen-science tool, which can be readily used by CSGs and individuals to understand the health of connections in their regions.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts @Melechuga

**Comment by Melechuga** [comment]
Science Fair

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016

**Comment by Melechuga** [comment]
Reopening this as it's a Fellows partnership organization; I'll deal with the comms. Thanks.
