### ISSUE TITLE
Machine Learning 101

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#454]
**[ Google Spreadsheet Row Number ]** 438
**[ Facilitator ]** Francis Tseng
### Description

Attendees will learn core machine learning techniques and basic data analysis skills, how to apply them with popular Python packages like scikit-learn and pandas, and the pitfalls and ethical dilemmas that can occur. 
### Agenda

I have three iPython notebooks, each teaching one set of machine learning techniques, based around immersive narratives which help motivate the use of each technique. I'll introduce each technique then setup a problem for participants to apply what they've learned.

The notebooks from past workshops are here: https://github.com/ftzeng/ml101
### Participants

With a small number of participants, we can all work through the problems together. With larger amounts, participants can break into smaller groups and work through them that way.
### Outcome

After the workshop, participants will be able to identify problems which could benefit from machine learning, which could help them see stories where they didn't before, and then apply these techniques to uncover the interesting aspects of these problems and present them to others.

**Comment by secretrobotron** [comment]
Whoa. Cool. Sign me up.

**Comment by marcwalsh-zz** [comment]
cc @ryanpitts

**Comment by ryanpitts** [comment]
@acabunoc something that Science would also be interested in?

**Comment by Zebetus** [comment]
@EPIKhub this could be really cool to get youth involved with especially because python is being taught at so many schools

**Comment by ryanpitts** [comment]
Woo! Another one for the joint pathway between Science and Journalism called "Tools & Analysis."
