### ISSUE TITLE
Allow me re-introduce myself, my name is .... (tools to teach the web)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#455]
**[ Google Spreadsheet Row Number ]** 439
**[ Facilitator ]** Hannah Kane
### Description

The Mozilla tools to teach the web have evolved - some new, some updated and some are the same old gems. Participants will learn about the changes and how to continue to use the tools to teach core Web Literacy skills. This includes X-Ray Goggles, Thimble and Webmaker. 

(This session is being submitted as part of the Clubs pathway of the MLN Space)
### Agenda

We'll provide an overview of each of the three tools, in a round robin style (one station for each of the three tools; participants spend a few minutes at each station). These overviews will emphasize what has changed about the tools over the last year. Then, we'll demo some examples of how each can be used in the Clubs context, and share best practices for incorporating the tools into lesson plans and group activities. We'll reserve most of the time for people to play around with the tools and ask questions of the facilitators and each other, and we'll challenge everyone to come up with one new way to incorporate the tools into their Club activities.
### Participants

This session will work well regardless of the number of participants, though if there is a large number, we'll ask if anyone self identifies as an "expert" on any of the tools so they can serve as mentors for others.
### Outcome

Participants will leave with the spark of an idea for incorporating our tools into their Club activities. We'll follow up with them afterwards to see if they have new content to share with the community.

**Comment by marcwalsh-zz** [comment]
cc @LindseyFrost @samueledyson

**Comment by soapdog** [comment]
cc @soapdog

**Comment by Saallen** [comment]
@EPIKhub do you have room for this session to take place within the youth zone as a teachers focused event- Hannah is a MoFo :)

**Comment by EPIKhub** [comment]
@Saallen added

**Comment by Saallen** [comment]
:+1: :cake:
