### ISSUE TITLE
The Local Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#456]
**[ Google Spreadsheet Row Number ]** 433
**[ Facilitator ]** Josh King
### Description

The Local Web will explore options for local communication when the wider internet is not available. This will include self-hosting, community and mesh networks, device-to-device communication, delay tolerant networking, service discovery, and more. This workshop will explore possibilities for using the web and other internet technologies on a local, rather than global, scale.
### Agenda

The session will be a workshop where participants will be encouraged to explore options for local communication. Everyone will be given an opportunity to try out different options for communication, and challenged to use these tools to pass messages and other information to each other without using the internet. Participants will have an opportunity to brainstorm solutions and new tools to overcome the obstacles they encounter.
### Participants

There will be a selection of different tools and projects for participants to use. With only 5-people, participants will try out these different tools in a single group, going from one to the other to try and communicate locally. With a larger number of participants, people will split off into smaller groups in order to try out different tools, and then report back to the group as a whole. We will ensure there are enough different tools for a varying number of groups.
### Outcome

Participants will come away with an understanding of a number of different projects of which they might have been unaware, as well as an idea of how to participate in those projects and move them forward and use them in their own communities.

**Comment by hjbailey** [comment]
I think there is some overlap with offline localization tools.

**Comment by thornet** [comment]
@hjbailey thanks for modeling amazing Github commenting! <3

**Comment by cubicgarden** [comment]
I'd like to combine this session with another session, once I find it I'll combine it and shut this one down - as @thornet said on the call
