### ISSUE TITLE
#SharePrivacy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#457]
**[ Google Spreadsheet Row Number ]** 442
**[ Facilitator ]** Melissa Romaine
### Description

Participants learn how to teach why privacy is important, including topics like how data is shared, that privacy is optional in other browsers, and how Firefox has privacy options built-in. Participants will take these activities and contextualize them for teaching kids, adolescents, and adults about how to take control of their privacy online. We'll ask people to use a hashtag (#SharePrivacy > TBC) to share how they've taught others.
### Agenda

There will be a demonstration of the Tracking Protection feature in Firefox 42 using Lightbeam, and a hands-on experience about how privacy affects your online experience. Later, participants will be asked to build teaching kits for different demographic groups.
### Participants

It will not differ among 5, 15, or 50 people -- just that with more people, there will be more groups for people to work together.
### Outcome

Teaching kits about privacy! Ideally loads and loads of teaching kits that can be shared/localized, etc. After the festival we hope people will use the #SharePrivacy hashtag to share their teaching kits, blogs, and other documentation on how they've taught privacy.

**Comment by Melechuga** [comment]
Placeholder; covered by https://github.com/mozilla/mozfest-program/issues/242
