### ISSUE TITLE
Building Our #OpenWeb Community

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#459]
**[ Google Spreadsheet Row Number ]** 435
**[ Facilitator ]** Georgia Bullen
### Description

Most open___ work happens through people talking to each other -- whether from meeting on IRC, Twitter, in-person, or a connection through an intro. At it’s core, “open” is about working collectively to leverage networks to do, make, build, tell stories, protect, share, talk, meet, etc. In this session, let’s work on the human network, develop shared principles and brainstorm for the future #openweb community.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016

**Comment by Melechuga** [comment]
@Saallen Received an email from Georgia saying she hadn't received a rejection email. I'm going to put this into Digital Citizenship -- they are a partner org.
