### ISSUE TITLE
Fireside chat

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#46]
A hosted chat with a game expert, perhaps Eric Zimmerman or Ian Bogost (via Skype if needed), to talk about where the serious games movement began and what classrooms around the world are doing now to utilize games as a teaching tool. The audience will be able to ask their own questions, as well as ask for advice on projects.

**Comment by cubicgarden** [comment]
If you get Eric Zimmerman or Ian Bogost then we will certainly be interested @cubicgarden

**Comment by cubicgarden** [comment]
@Saallen I'm still interested...

**Comment by thornet** [comment]
@cubicgarden is this the session you wanted to catch up about?

**Comment by thornet** [comment]
@ryanpitts is this session actually happening? Are Eric Zimmerman or Ian Bogost coming? Think this was initially proposed with your games pathway and just catching up if it's happening or not.

**Comment by ryanpitts** [comment]
@thornet oh no, I apologize but I'm not actually sure where this proposal originally came from! It wasn't a session that any of our facilitators or pathway folks had proposed, and didn't come in via any outreach we did.

We figured it had been tagged with "Games & Understanding" to make us aware it might possibly exist, but there was no facilitator attached, so we assumed it didn't come through.

**Comment by thornet** [comment]
Thanks @ryanpitts for the clarification! Then I'll close and unlabel this since it's not actually proposed nor happening.

**Comment by cubicgarden** [comment]
Thats the one....
