### ISSUE TITLE
Privacy ≠ Porn

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#460]
**[ Google Spreadsheet Row Number ]** 443
**[ Facilitator ]** Melissa Romaine
### Description

This session will focus on use cases OTHER than porn to explain why and how privacy is important to the online experience. The goal is for participants to experience how online tracking can change their online life -- even when they don't watch porn.
### Agenda

At first, participants will be introduce to use cases on how privacy features can improve their online experiences -- like airline ticket purchasing. Participants will then be challenged with brainstorming other use cases where tracking can change their experience, and show how turning on privacy features can enhance their online experience.
### Participants

The format of the session will not change between 5, 15, or 50 participants -- just that more people means more groups for collaborative work.
### Outcome

Outcomes will include a list of possible use cases that the Firefox team can then build out and disseminate among a larger audience. The goal is to be able to share the positive effects of privacy features -- outside of porn.

**Comment by Melechuga** [comment]
Placeholder; covered by https://github.com/mozilla/mozfest-program/issues/169
