### ISSUE TITLE
Privacy Lab

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#461]
**[ Google Spreadsheet Row Number ]** 445
**[ Facilitator ]** Tennyson Holloway
### Description

Not so much a session as a resource: like in previous years when a team of volunteers helped people flash their FFOS devices, we want to set up a Privacy Bar (TBC) -- alà Apple's Genius Bar -- where people can get help with updating their Firefox to FF42, and learn more about the newest privacy features. And it's possible we'll have juice/snacks on hand.
### Agenda

We'll start with 3 volunteers who are well-versed in FF42 and like working with others. Hopefully, this is something that will be available Saturday + Sunday with rotating volunteers.
### Participants

Few people is fine; people will have to wait in line, work together, or come back at another time if the wait is long. Alternatively, we can recruit more volunteers if there is high demand.
### Outcome

More FF42 updates! A better understanding of the privacy features among users. (This is meant to be a help desk.)

**Comment by Melechuga** [comment]
OWF Tennyson proposed a session similar to this: https://github.com/mozilla/mozfest-program/issues/508 We could ask him to man the bar.
