### ISSUE TITLE
Innovating in the open for better lives (and better products)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#462]
**[ Google Spreadsheet Row Number ]** 436

**[ Facilitator ]** 
name: Michael Saunby
twitter: @msaunby
organization: Met Office
name: Shirley Chin
twitter: @shirleychin
organization: Pearson
### Description

Innovation is too often seen as a business imperative rather than a means to improve lives.

The growing use of Open Innovation, co-creation and user centred design by businesses, and the public sector will enable more citizens than ever before to participate in shaping the future, not only of the web but all the products and services they experience.

In the session we shall take a few existing ideas and innovations and try to make them better using these approaches. We’re not looking for expertise, but passion to see and make a better future.

Better how? Well it could be a new audience, or solve an existing problem in a novel way. Our primary tool will be the ‘hacker ethic’ - access, freedom of information, and improvement to quality of life.  

You’ll get to help design better weather warnings, or bring a problem of your own and share it.
### Agenda

This session is jointly led by -

Michael Saunby, Open Innovation Manager, Met Office Informatics Lab
Shirley Chin, Global Product Lifecycle, Chief Product Office, Pearson

We'll share our recent experiences and initiatives to grow engagement in innovation.

Most of the session will be in the form of a workshop.
### Participants

The more diverse the participants in this session the more interesting it is likely to become.

We’ll devote a few minutes to critiquing the methods too.  For example with regard to Open Innovation -
Ideas are sought outside the originating organisation.
Implementation can occur outside the originating organisation.
However it is typically embodied in a managed process. (But is that because businesses already have managers and processes?) So how would hackers do it?

We will note that open source software is creating universal access to quality software and consider how we might add to that.  Not just software but other creative commons.  

N.B. Leaders joining this session will be able to experience innovation with users and evaluate their own strengths, perhaps in refining ideas, or encouraging participation from quieter contributors. We might also be able encourage letting go, allowing projects to find new form and new applications.
### Outcome

(Re)discover that solving problems is fun.  A shared enthusiasm for improving all sort of things.   We’ll certainly keep sharing ideas on social media, and blogging about this and other experiences.

**Comment by Saallen** [comment]
cc @secretrobotron

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by cubicgarden** [comment]
Adding myself @cubicgarden
