### ISSUE TITLE
Make your own choose your own adventure news game with twine

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#463]
**[ Google Spreadsheet Row Number ]** 437
**[ Facilitator ]** Linda Sandvik
### Description

After a brief introduction of games created using Twine, you'll be using this popular open-source tool to brainstorm and create your own Choose-Your-Own-Adventure newsgame during the workshop. No coding experience necessary, as Twine will do all of the programming work for you, and generate an HTML file that is ready to publish anywhere. Plus, those with HTML/CSS and Javascript experience can also build upon and customize their games. 
### Agenda

workshop, everyone brings their own laptops to work on
### Participants

up to 20 will be OK I think, any more I will need help (will try to find co-facilitators)
### Outcome

more people making newsgames!

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Linda will for sure be traveling to London and attending MozFest. (Also, she's based in London :) )

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Games & Understanding" pathway.

**Comment by Zebetus** [comment]
@EPIKhub Once again i feel that this would be an amazing way to get youths involved with the journalism space

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone, likely most appropriate for Bronze participants
