### ISSUE TITLE
Fixing Indifference and Corruption in the Public Service Delivery: Leveraging Data to Get to those Responsible 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#464]
**[ Google Spreadsheet Row Number ]** 444
**[ Facilitator ]** Paul Wafula
### Description

How to prove negligence and corruption using data. Linking the corruption to the impact on the citizen and make those responsible to start caring. Present the data in friendly formats online through news apps and interactive mobile platforms customised for the users. Then allow users the ability to query the data, compare and make their own independent conclusions. It will be interactive and rich in personal experiences. 
### Agenda

I propose a fireside like chat format to make the data session  friendlier. The group shall identify several issues in their communities or nations that need attention and then try walk through the steps of fixing it through a data investigation. Participants shall share personal experiences and I will share my own experiences. Then there will be a demonstration of how one of my projects influenced government policy in Kenya.
### Participants

For five we shall make it more like a round table, fifteen would be a fire chat while 50 would be more like an a small amphitheater presentation. Participants will critique one or two projects and in the process learn the elements of a good data expose. 
### Outcome

The internet as a platform for investigative journalism
Cross border collaboration
Humanising big data

**Comment by ryanpitts** [comment]
Hi @jvallera, we're planning to include this session in our "Data & Impact" pathway, and would like to send out an acceptance notice on behalf of the Journalism space. It seems like it will be nice part of "Voices of Diverse Leaders" as well, but from what I can tell, that's a standalone pathway, not a space at this year's MozFest. Will it cause any problems if I:
- change the milestone here to "Journalism"?
- send an acceptance notice to the facilitator and connect him with our pathway coordinator?

**Comment by jvallera** [comment]
@ryanpitts Yes. That is fine. Will remove it from MLN space

**Comment by ryanpitts** [comment]
Great, thanks! If you end up wanting to include it as part of the "Voices of Diverse Leaders" pathway as well, just let us know.
