### ISSUE TITLE
Use your skills to actually change the world!

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#467]
Google Spreadsheet Row Number

467

Facilitator

name: Sandra Gaudenzi
twitter: @sgaudenzi
organization: IF Lab
name: Philo Van Kemenade
twitter: @phivk
organization: Popathon.org

Description

This is a session where coders and storytellers will join forces to challenge the way interactive stories have been conceived so far. You will be working on real projects that have a chance to be developed in the future, so that our ideas can go beyond prototyping!  If you are serious about change, and of being part of it, if you are a developer, a designer or a content person, then this session is for you!

**Comment by digitalSG** [comment]
Facilitators: Sandra Gaudenzi & Philo van Kemenade

duration: 2 hrs

Description:
This session is about challenging existing factual web narrative structures and inventing whole new ways to bring the user inside the reality that we want to change with our stories. You will work on real stories that are looking to be produced soon!

Session's objectives:
- bring storytellers and creative technologists together
- get interested in interactive stories that can change the world
- learn about actual trends in interactive documentaries & web natives stories
- learn about ways to use digital interactivity to transform the user into an active person (that might then participate in changing the world)
- brainstorm new ideas on how this could be done differently, and better
- work together to propose new solutions
- rediscover the pleasure of co-designing in multi-disciplinary teams

STRUCTURE: 
1. Introduction of facilitators and participants 
2. Learn:
   explanation of what a web-doc / web native factual story is & examples
   types of interactivity used so far to ""involve the user""
   why does an active user might be more inclined in ""changing the world""
3. Do:
   divide participants in 5/6 groups by ""type of interactivity"" to be explored
   each group has a series of issues to discuss and challenge
   make sketches, or code sketches, of new ideas and get ready to present them
4. Share & feedback:
   each group shares key ideas to all
   possible time for discussion

**Comment by digitalSG** [comment]
SESSION'S DESCRIPTIVE TEXT:

This is a session where coders and storytellers will join forces to challenge the way interactive stories have been conceived so far. We want you to feel part of a similar revolution than editing has been for films, more than a century ago. Together we will look at the ways in which interactivity has been used in factual stories to engage users, and we will create new ones.  You will be working on real projects that have a chance to be developed in the future, so that our ideas can go beyond prototyping! 
If you are serious about change, and of being part of it, if you are a developer, or a content person, then  this session is for you!

**Comment by cubicgarden** [comment]
@emmairwin can you confirm this was accepted and you have been in touch? ccing @Saallen @marcwalsh just incase...

**Comment by emmairwin** [comment]
@cubicgarden yes and yes! but... emailed @Saallen looking for email contact

**Comment by digitalSG** [comment]
@emmairwin: hey! Happy to talk! use sgaudenzi@yahoo.com or @digitalSG to contact me!

**Comment by cubicgarden** [comment]
Ok great...
