### ISSUE TITLE
Change the world through code: how to meet the person you need in your team to do so

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#468]
Google Spreadsheet Row Number

468

Facilitator

name: Sandra Gaudenzi
twitter: @sgaudenzi
organization: IF Lab
name: Filip Fastenaekels
organization: VRT

Description

Code like you give a damn! Why not using your skills to co-design interactive stories that can change the world? Today, coders and storytellers rarely work together from day one. Join this session to be part of the solution and meet storytellers and coders you'll want to work with!

**Comment by digitalSG** [comment]
Facilitators : Sandra Gaudenzi & Filip Faste

Duration: 1 hr

Description:
1. Introduction of all participants (10 min)
2. Presentation of the issue: coders and storytellers rarely work together from day one. Why is this happening and how can we change this? (5 min)
3. Facilitated discussion in groups (30 min)
4. Share possible solutions & create a group of people that might want to act on this after MozFest (15 min)

Session's aims:
- bridge the gap between storytellers and creative technologists by proposing practical solutions to network and pitch ideas to each others
- learn to listen to "the other point of view": needs, challenges and frustrations of both storytellers and creative technologists
- map concrete ideas that could be put in action after MozFest
- create a group of people that might want to act together on this issue after MozFest

**Comment by digitalSG** [comment]
SESSION'S  DESCRIPTIVE TEXT:

Code like you give a damn! Change the world through code! Why not using your skills to codesign interactive stories to make a difference? That would be great, no? But even if you wanted to, it is difficult to choose the stories you want to commit to, and to be aware of the people that might need you in their teams... At the moment coders and storytellers rarely work together from day one. We need to solve this if we want to move on. Join this session to be part of the solution and meet storytellers and coders you'll might want to work with!

**Comment by emmairwin** [comment]
cc / @geroter @emmairwin there's something here about helping grow participation through storytelling / helping technical contributors connect with people who might want to get involved on other levels.  also story telling the mozilla mission is something we can all work on.

**Comment by emmairwin** [comment]
@geroter we could send facilitation & community leaders to story tell with code contributor leaders and have them work on this as a design challenge in New Technologies!

**Comment by digitalSG** [comment]
@geroter that would be great!

**Comment by emmairwin** [comment]
I see this:  Presentation of the issue: coders and storytellers rarely work together from day one. 

How can this pathway intersect the Participation pathway without participants needing to be on day one for example?

**Comment by digitalSG** [comment]
actually @geroter, in terms of design challenges you might want to add the other session in this pathway  https://github.com/mozilla/mozfest-program/issues/467 - since it is about collaborating in existing interactive storytelling challenges....

**Comment by emmairwin** [comment]
Thanks @digitalSG

**Comment by emmairwin** [comment]
With https://github.com/mozilla/mozfest-program/issues/468 on new technologies for particiation
