### ISSUE TITLE
Inspiration time: explore recent projects that will change the way you understand the world

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#469]
Google Spreadsheet Row Number

469

Facilitator

name: Sandra Gaudenzi
twitter: @sgaudenzi
organization: IF Lab
name: Mike Robbins
twitter: @mike_j_robbins
organization: Helios Design Labs

Description

Come and explore some of the best interactive factual narratives that have been recently released. This is an opportunity for you to experience factual interactive narratives, be inspired by them and maybe change the way you understand and perceive the world!
Projects on display will be: Pirate Fishing (Al Jazeera), Do not Track (Upian, Arte, NFB), the {} and (Deep focus), Digital Me (BBC, Helios Design Labs), The shirt on your back (the Guardian) and Neurotics Neurones (Nick Cage).

**Comment by digitalSG** [comment]
Facilitator - Sandra Gaudenzi & Mike Robbins

Type of experience: installation / websites on a computer

Duration: Could be always on. 

Description: 
One, or more computers, are showcasing 4 or 5 great interactive factual narratives that have been released recently. This is an opportunity for people to experience interactive narratives for change and make up their mind about them. 
Possible project titles would be: Pirate Fishing (Al Jazeera), Do not Track (Upian, Arte, NFB), the {} and (Deep focus), Digital Me (BBC, Helios Design Labs), The shirt on your back (the Guardian).
We could organise a 1 hr slot to "chat with the authors" of Digital Me, as they are both at Mozfest.

NOTE: should be possibly located in a quiet space (needs headphones) or in an area where other pathways are showing projects (I am thinking specially of the Journalism strand).

Sessions' objectives:
- show what an interactive factual narrative might look like 
- allow people to have a first person experience of current web native stories
- have fun
- be inspired
- come out of your comfort zone

**Comment by digitalSG** [comment]
SESSION'S DESCRIPTIVE TEXT:

Come and explore  some of the best interactive factual narratives that have been recently released. This is an opportunity for you to experience factual interactive narratives, be inspired by them and maybe change the way you understand and perceive the world!
Possible project titles on display would be: Pirate Fishing (Al Jazeera), Do not Track (Upian, Arte, NFB), the {} and (Deep focus), Digital Me (BBC, Helios Design Labs), The shirt on your back (the Guardian) and more.

**Comment by digitalSG** [comment]
@erikao - Hi Erika, I was wondering if Journalism was organising a space to view projects... if you are then we could join forces and think about a "display space for stories that can change the world"...
Let me know if this is of interest...
Sandra

**Comment by cubicgarden** [comment]
@Saallen if we wanted to have this in the library somewhere? Would this be possible? @marcwalsh

**Comment by digitalSG** [comment]
@cubicgarden: hey there! I just had a one to one with Sarah Allen and she gave me a little background on what you are trying to do with the Library: effectively a demo / chill out space for people to try out things. If this is the case, then I think this would be the perfect place to have our "Inspiration time" session - which effectively is just a computer with 5 or 6 cool webdoc/i-doc/serious games loaded in it for people to play with.
One of the projects loaded on the computer will be Digital Me - which I know you are aware of as you tweeted about it!!! thanks for that ;-) - and we thought we could organise a 1 hr slot of  "meet & discuss with the authors" as both myself and Mike Robbins (creative coder/director) will be at MozFest.
Let me know what you think of this idea!!

**Comment by cubicgarden** [comment]
Yes thats what I'm thinking but you would need to keep an eye on them, if possible. Consider this accepted but I do need your email ideally so we can talk privately about everything. @Saallen @digitalSG

**Comment by digitalSG** [comment]
My email: sgaudenzi@yahoo.com and my phone number: 07939279162

Speak soon!

Sandra

**Comment by digitalSG** [comment]
Hi Ian, 

we never managed to finish our conversation about putting some examples of interactive narratives in your library space @ MozFest…

what are your plans?

shall we chat about it?

either send me a mail, or call me on 07939278162.

best!

Sandra Gaudenzi

Head of Studies, !F Lab - http://www.iflab.net
Visiting Research Fellow, University of the West of England & i-Docs co-director - http://i-docs.org/
PhD, Goldsmiths, University of London - http://www.interactivedocumentary.net/
personal blog - http://www.interactivefactual.net

**Comment by cubicgarden** [comment]
Ok join call me on skype tomorrow?

**Comment by digitalSG** [comment]
OK! What is your Skype address?  I’m sgaudenzi_skype  Free tomorrow from 12.00 till 2 PM.

If not: good old phone will do the trick!

my number 07939278162

Sandra Gaudenzi

Head of Studies, !F Lab - http://www.iflab.net
Visiting Research Fellow, University of the West of England & i-Docs co-director - http://i-docs.org/
PhD, Goldsmiths, University of London - http://www.interactivedocumentary.net/
personal blog - http://www.interactivefactual.net

**Comment by Saallen** [comment]
Yes, you can set up a laptop that show these on loop but with head phones.
Sandra can you get them up so the experiences are looped so you hop from
one sit to another ?

**Comment by digitalSG** [comment]
hummm…. I do not think so, they all sit on separate URLs as websites so… the best we can do is to create some tabs on a browser and restrict users from going elsewhere?

Do you have a technical person that can arrange that if I provide the URLs?

Sandra Gaudenzi

Head of Studies, !F Lab - http://www.iflab.net
Visiting Research Fellow, University of the West of England & i-Docs co-director - http://i-docs.org/
PhD, Goldsmiths, University of London - http://www.interactivedocumentary.net/
personal blog - http://www.interactivefactual.net
