### ISSUE TITLE
Revolutionary games

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#47]
A room where gaming stations (probably laptops with headphones) are setup with a series of revolutionary games in either the serious games movement, journalism, or independent gaming that really blew open the concept of using games as a storytelling tool. Participants can come in and out as they wish to play the games throughout the conference. Each station will also include a description about why this game was selected for this installation and what was so monumental about it.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
