### ISSUE TITLE
[Pathway] Voices of Diverse Leaders

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#471]
Curated by: Julia Vallera (@jvallera) and Simona Ramkisson (@simonaramkisson)
## Learning Objectives
- New methods/examples of bringing diversity to their work
- Ways to support and advocate for diversity on the web
- Make new connections to other community members doing this work
- A basic understanding of how Mozilla supports Diversity and young people  among the growing community and how to contribute to it. 
- Equip participants with what they need to teach like Mozilla in diverse communities that are inclusive to race, ethnicity, gender, sexual orientation, gender expression or identity, socio-economic status, age, physical, mental and learning  abilities, religious beliefs and political beliefs.
- Youth will be empowered to lead in their communities
### Young Leaders under the age of 21: AMELIA

Amelia is a sophomore in college in Arizona, USA. She is working with her local library to develop a community program that is for youth by youth. She is uses this pathway to connect with other people that are passionate about young people having a voice in social issues and being leaders in their community. She leads a workshop on the work she started in her library. Motivations: Practice leadership, Advocate for youth voice, Mentor peers, possibly become a diverse Leaders Youth ambassadors.
### Activist representing a marginalized learning community: TIG

Tig represents an organization working to bring gender equality into technology via hackathons, maker spaces and educational programs. She uses this pathway as a way to initiate partnerhsips that foster equal opportunity across educational platforms and orgnizations. She participates in this pathway to learn what the challenges, successes and interests are for others working to diversify the tech industry. 
### Women technologists: Arooj

Arooj started an organization that teaches young women how to code. She presents the program she started at Mozfest and uses this pathway as way to develop a leadership pathway for the young women she works with to teach web literacy skills in local schools.
### Youth Zone participant: Zanab

Zanab is a local high school student in London. She was invited to participate in the youth zone. As a participant she meets other local youth and learns new perspectives and tools in technology. She moves between the youth zone and this pathway throughout the weekend. The workshops and sessions she visits in the Diverse Leaders pathway give her a new perspective on the topic of inclusion in technology. When she goes back to the youth zone she shares what she learned with her friends. She feels empowered to network with others and learns there is a lot of opportunity to bring her new skills into her own school and community. She decides to start a youth group at her school to bring tech skills to any young person who may want it. 
## Pathway Experiences
- Teach Like Mozilla in your diverse communities
- Leadership Development for Youth 
- Round table: Hive youth meet-up and how it is a model for youth voice and leadership
- Fireside chat: What does diversity on the web mean and what can we do to support it? possible panel, pulling youth
- Maker station: Free area to build and make stuff - youth, adults, educators, learners, etc. (have a thimble station, an activity kit station, a pledging station, etc.)"
## Pathway needs
- Space for educators to discuss with community leaders, builders and other educators  the significance of inclusion of diverse voices and how it is done/not done in their communities;
- Youth facilitators (actual young people, not people who facilitate youth) 
- Pathway Curators- Simona and Julia
- Mozilla Webmaker/Thimble facilitator

**Comment by Zebetus** [comment]
@EPIKhub @thornet @jvallera I feel we should include this pathway in the youth zone some how maybe getting the youth facilitators involved in some way???

**Comment by EPIKhub** [comment]
@thornet @Zebetus @jvallera +1 here, its really relevant we cross pollinate in both direction, us to other space and other spaces to us :)?

**Comment by jvallera** [comment]
@EPIKhub absolutely. @simonaramkisson and I sorting out our pathway details now, but would love to coordinate with you on where there is overlap.
