### ISSUE TITLE
Computational Sociology (and Online Communities)

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-program#473]
Facilitator: Tara Adiseshan

The field of computational sociology is growing in exciting ways. This session will introduce folks to some of the resources, tools, and ideas that computational sociologists are working with. We'll talk about the increased visibility and interest in conducting research on online communities and online harassment and what that might look like with a computational sociology lens. The session will also touch on similarities between computational sociology and data journalism.

The session will begin with a (brief) introductory talk, defining computational sociology, pointing towards resources and tools. We'll then dive into a workshop. 

"With a smaller group of folks, I could spend a lot more time on the workshop and set aside more time for discussion.

With a larger group, I would probably divide the participants into smaller groups for discussion and workshop time."

**Comment by EPIKhub** [comment]
I would be interested to see a youth pathway for this session, leading out of the youthZone to this session.
