### ISSUE TITLE
Getting to the roots of the Hacks/Hackers movement

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-program#474]
Facilitator: Annabel    Church

There are a large number of Hacks/Hackers and other Journalism and Technology related groups scattered around Europe. Each group tackles local issues when organising events to facilitate their community needs, as well as trying to address the wider issues faced with technology and access to information within Journalism. Allowing groups to suggest ideas most relevant to their community group, as well as trying to address broader questions associated with the Hacks/Hackers movement and related movements both in their geographic region and globally, my hope is to tease out common threads and solutions.

Essentially what do these communities need and how to address this?

"Open participatory discussion/Workshop/Listening session.

A session introduction and framing, break out groups and then regrouping at the end for a final wrap-up.

There would be a structured set of questions/issues framed, while allowing participants to suggest further issues relevant to their community. The breakout groups would help facilitate possible ways of tackling these issues."

Splitting into working groups of 5 or less participants, rounding up group feedback 20 minutes before the end of session. Allow groups to give feedback on all ideas generated by posting the feedback sheets within/after/outside of the session.

**Comment by cubicgarden** [comment]
I removed this from the The connected village @Saallen @marcwalsh

**Comment by ryanpitts** [comment]
Closing as duplicate of https://github.com/mozilla/mozfest-program/issues/528
