### ISSUE TITLE
Draw your own election adventure, beyond official boundaries

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-program#479]
Facilitator: Juan Elosua

"This session will be geared towards working with elections data. We will focus on creative ways to show election results. 

For example, sometimes the official divisions of a city needed for administrative tasks are not necessarily meaningful to the city’s population. In many cases, the city has living parts that do not fit in the limits of official administrative level divisions

We will show how we have solved this issue for the Elections in Buenos Aires and I hope that after the session the attendees will have some creative ideas on how to work with election data and apply them in the next elections they are interested in."

"Every newsroom has to deal with elections on a periodic basis.

First, we will discuss best practices and examples from media around the world.

Demo time: After we will see in more depth an example of election coverage for the Buenos Aires elections where we have used leaflet draw plugin to allow readers to select custom areas of interest.

After, we will break into groups to think of creative use cases of elections data with an example dataset.

Finally, we will go through a hands-on part where we will build a minimal example of the use of the draw plugin similar to the one created at La Nación with some other election data."

**Comment by evaconstantaras** [comment]
Better for Tools, Analysis, & Storytelling track.
