### ISSUE TITLE
how to make physical and digital games

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#48]
Hands on experiences for how to make physical and digital games. In one session, participants are asked to group up and pick an already existing board game to play for a few minutes. Then, they are asked to adjust the rules to the game, as well as come up with a new theme for the game itself in order to teach a concept. In another session, participants will be taught how to make their own games using an existing tool like Twine, or GameSalad. Participants will leave having created a simple game of their own, which combats the myth that games can only be created by specialists.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
