### ISSUE TITLE
Dup. [Pathway] Changing the World with Interactive Stories

### ISSUE THREAD

**Issue by marcwalsh-zz** [mozilla/mozfest-program#484]
Experience 1's objectives:
- bring storytellers and creative technologists interested in interactive stories to change the world together
- learn about actual trends in interactive documentaries
- learn about ways to use digital interactivity to transform the user into an active person (that might then help in changing the world)
- brainstorm new ideas on how this could be done differently
- work together to propose new solutions

Experience 2's objectives:
- learn to listen to "the other point of view": needs, challenges and frustrations of both storytellers and creative technologists
- bridge the gap between storytellers and creative technologists by proposing solutions
- map concrete ideas that could be put in action after MozFest
- create a group of people that might want to act together on this issue after MozFest

Experience 3's objectives:
- show what an interactive experience that aims at changing the world might be (in this case the aim of the project, Digital Me, is to make you question if your digital and physical persona are aligned)
- allow people to experience it by interacting directly with the website of Digital Me
- have fun
- be inspired
- come out of your comfort zone

**Comment by cubicgarden** [comment]
Like to have a aspect of this running through the library. I'm about to put a proposal down for the Perceptive Radio v2, with workshop which could fit this pathway perfectly. @cubicgarden
