### ISSUE TITLE
[Pathway] Let's Encrypt

### ISSUE THREAD

**Issue by marcwalsh-zz** [mozilla/mozfest-program#487]
Let’s Encrypt is a proposed pathway that focuses on encryption. In this pathway, sessions will teach people why they should encrypt, how to use certain tools, build on existing tools, and design creative ways to teach others about encryption.  There's also a lot of confusion about some basic web privacy technology, like HTTPS - the goal will be to help eliminate confusion and empower people to protect themselves.

**Comment by Melechuga** [comment]
We changed the name of this pathway to "Backdoors + Cryptowars" to honor the work the actual Let's Encrypt team does. Issue resolved: https://github.com/mozilla/mozfest-program/issues/29

**Comment by EPIKhub** [comment]
Encrytion is important but there are loads of tools out there to hack, and not all Encrytion solutions are good options. Having a lock on your door gives a sense of security but if the lock is not robust enough, it might give a false sense of security; considering the number of tools and hackers out there who's aim are to reverese engineer every encoder on the market that works

**Comment by EPIKhub** [comment]
You should include Tad in this conversation, he knows a thing or 3 about this topic :) and I would be interested to see a youth pathway for this session, leading out of the youthZone to this session.

**Comment by Melechuga** [comment]
This ticket is closed. The pathway is now called "Backdoors + Cryptowars" Thank you.
