### ISSUE TITLE
Breaking the barrier of the web: learning HTML, CSS and Javascript

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#492]
**[ Google Spreadsheet Row Number ]** 447
**[ Facilitator ]** Dayany Espindola
### Description

The goal of our workshop is teach people how to be a part of the web through breaking the barrier of their involvement learning about how to do the things with git/Github, HTML, CSS and Javascript from the start (initial setup) to the delivery (deploy) of an application.
### Agenda

The workshop is tailored to make all the participants have at least a basic knowledge of the topics. To reach this goal we believe that each topic must last at least 30 minutes. Our attention is in the practical side, but without losing the theoretical concepts behind, with this the participants can follow on their own legs after the workshop.
### Participants

Participants will be divided in groups with a maximum of 10 persons, these groups can be subdivided into minor groups  to get a better interaction and people could help each other.
### Outcome

Contact with participants always provides a great learning experience for instructors, the contribution of each person is extremely important to make a great experience for the whole group. The best result of our experience is to awake the curiosity and attention of the group to continue the project in his own reality with help of other members of the group creating a community of knowledge sharing. We truly expect them after the workshop may contribute to a better web and be instructors or facilitators in the near future.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
