### ISSUE TITLE
Be Torrific!: Promoting Freedom of Expression with Tor

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#494]
**[ Google Spreadsheet Row Number ]** 449
**[ Facilitators ]** Tim Sammut (@t1msammut), Tennyson Holloway (@barontennyson ), Arzhel Younsi
### Description

During this session we will experience the various methods of participating and contributing to the Tor network. Tor, an open source software package combined with a global network of developers and volunteers, provides censorship circumvention and anonymous access for Internet users looking to access content or express themselves online.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by Melechuga** [comment]
Conversation with Tim, Oct. 1:
Intended outcome: desire + knowledge to continue using Tor -- as a user, or run a relay.
Experience: 
Intro (participatory):
- Ask about Tor usage among participants (experience? knowledge? relays)
- How does Tor relate to the open Web?
- Ask people if they'd want to run relays

Break into three categories/groups
Workshop (hands-on):
- Install Tor browser/Orbot on devices
- Run Tor and non-Tor browser side by side
- Canned activities
- Analyze experiences
- Curriculum creation

Closing (participatory):
- Ask people if/how they want to help; how much they're willing to spend/invest.

Personal outcomes:
- why do people want to use Tor, but not relay?
- other people's ideas/understanding of Tor helps with the bigger picture, esp with global experiences.
