### ISSUE TITLE
So you're a techie and you want to teach the web?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#498]
**[ Google Spreadsheet Row Number ]** 452
**[ Facilitator ]** Simeon Oriko
### Description

This sessions aims to bring together edu-stars and tech-stars to collaborate on sharing knowledge about tools, development and curriculum's that can help in teaching the web.
### Agenda

The session will take place in two formats:
1. a speed-geeking format with hands on demos of tools that can be used to teach the web
2. a workshop to explore ways techies and educators can collaborate to further web literacy
### Participants

With 5 - 15 people, the session will spend more time showcasing and teaching tools that can be used for teaching the web using the speed-geeking format.

For more participants, more time will be spent in the workshop exploring synergies for collaboration.
### Outcome

A key outcome of the festival is more collaborative efforts by techies and educators in the form of events and new tools.

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
