### ISSUE TITLE
Data journalism in the interest of an offline public

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#499]
**[ Google Spreadsheet Row Number ]** 453
**[ Facilitator ]** Samar Halarnkar
### Description

It will allow people to explore how offline communities can benefit from online data journalism. The session will discuss how the expertise of academics and professionals can be merged with journalism focused on data and investigative reporting; how public data can be interpreted with professional expertise and investigative reporting and 
finally disseminated via social media. The ultimate aim is to find ways to cater to an elite policy audience as well as the average twitter user, with final benefits being delivered to larger public groups that do not have Internet access.
### Agenda

I think a workshop might work best. I could make a short presentation and then everyone could dive right in, offering ideas and existing models; we could brainstorm about new methods and new technologies that could be universally or partially adopted. I could make notes and draw up a cheat sheet that could be later distributed.
### Participants

Five participants would mean a detailed discussion on varying approaches to the topic: Universal themes, what we could adopt as specific lessons, adaptability of these themes and lessons to circumstances and regions. With 15 participants I would make the session far more freewheeling, while leading it in the direction and outcomes that I seek. I would not like to handle a session with 50 people; I do not think that will be meaningful--unless most are part of the audience.
### Outcome

First, a list of best practices that could inspire other data-journalism, academic and research outfits: how we all do what we do, and what can we learn from one another. Second, to set up an online network that can advise and collaborate.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Data & Impact" pathway.
