### ISSUE TITLE
Measuring + Documenting Information Controls

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#500]
**[ Google Spreadsheet Row Number ]** 454
**[ Facilitator ]** Fereidoon Bashar
### Description

In countries with growing Internet censorship policies, it is expected that heavier information controls will be imposed around political events such as elections. This workshop will look at current efforts by researchers and civil society actors to document and report on information controls, and to reduce disruption to online information and communications by proactively developing alternative modes of connectivity via circumvention technologies in response to various scenarios that could be induced by the authorities in Iran. 
### Agenda

Fereidoon (ASL19) will design shortly.
### Participants

Fereidoon (ASL19) will design shortly.
### Outcome

Fereidoon (ASL19) will design shortly.

**Comment by Melechuga** [comment]
ASL19's proposal about network measurement in Iran.

**Comment by Melechuga** [comment]
Combining with https://github.com/mozilla/mozfest-program/issues/453
