### ISSUE TITLE
Draw your own election adventure, beyond official boundaries

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#501]
**[ Google Spreadsheet Row Number ]** 455
**[ Facilitator ]** Juan Elosua
### Description

This session will be geared towards working with elections data. We will focus on creative ways to show election results. 

For example, sometimes the official divisions of a city needed for administrative tasks are not necessarily meaningful to the city’s population. In many cases, the city has living parts that do not fit in the limits of official administrative level divisions

We will show how we have solved this issue for the Elections in Buenos Aires and I hope that after the session the attendees will have some creative ideas on how to work with election data and apply them in the next elections they are interested in.
### Agenda

Every newsroom has to deal with elections on a periodic basis.

First, we will discuss best practices and examples from media around the world.

Demo time: After we will see in more depth an example of election coverage for the Buenos Aires elections where we have used leaflet draw plugin to allow readers to select custom areas of interest.

After, we will break into groups to think of creative use cases of elections data with an example dataset.

Finally, we will go through a hands-on part where we will build a minimal example of the use of the draw plugin similar to the one created at La Nación with some other election data.
### Participants

If we have a small and technical group we could go faster in the first half of the session and dig deeper in the hands-on part around the use of custom boundaries to aggregate election results.

If the group is bigger or more divergent technically speaking then we can focus more on the discussion and demo part of the session anyhow we will give all the optional resources for those who want to get their hands dirty on the bootstrap election project.
### Outcome

With the new mindset in place they will be able to reuse that way of thinking out of the box to other projects or datasets where the customization of content delivers added value to readers. 

Content customization could be one of the ways newsroom can find bussiness models that make sense and any tool that works in that direction is worthy to enter in your toolbox.

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Juan will for sure be traveling to London and attending MozFest.

**Comment by thornet** [comment]
@ryanpitts is this session taking place in the journalism space? It's listed in the schedule, but the milestone and labels were removed.

**Comment by ryanpitts** [comment]
Nope, this one is not taking place! Sorry, I thought we just needed to remove the labels and it was marked as not happening.

**Comment by thornet** [comment]
Thanks for the confirmation, @ryanpitts! Unfortunately, this session is not taking place, so closing it now.
