### ISSUE TITLE
Introduction to D3js

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#502]
**[ Google Spreadsheet Row Number ]** 456
**[ Facilitator ]** Juan Elosua
### Description

This workshop will start from sratch around the D3 visualization library. D3 is an awesome library but the learning curve can become steep if you do not learn some basic concepts. On this session we will try to get those concepts deep into your brain so that you can continue learning afterwards

Basic previous Javascript, HTML and CSS is needed to profit from the workshop
### Agenda
1. Start with the D3 core functionality. Binding data
   - enter, update and exit subselections
   - Binding data by key
2. Dig into other functionalities:
   - SVG drawing
   - Scales
   - Axis
   - Transitions
   - Layouts
3. Some resources to keep learning

The format of the session will be a workshop / hands-on training so bring your own laptop
### Participants

Being a workshop the number of attendees can very without a problem.

If the group is really big some help from other facilitators with technical difficulties from the attendees would be appreciated
### Outcome

D3js is one of the most used libraries for Frontend visualizations  but getting the correct mindset to learn it from scratch can become difficult. In this session we will cover the basics letting the attendees to have a good start and continue their personal learning afterwards

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Juan will for sure be traveling to London and attending MozFest.

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter unsure but could help with visualization of participation data, might be fun to explore on a pathway for technology leaders in participation

**Comment by ryanpitts** [comment]
Woo! Another one for the joint pathway between Science and Journalism called "Tools & Analysis."
