### ISSUE TITLE
Improve the accessibility of your interactive

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#503]
**[ Google Spreadsheet Row Number ]** 457
**[ Facilitator ]** Alison Benjamin
### Description

Whether produced on a quick turnaround for breaking news, or over a longer term for an in-depth investigation, news interactives such as immersive pieces, interactive maps and stories and visualizations are at the forefront of engaging storytelling opening up stories to new audiences. They also offer a huge potential for creative inclusive design for wide audiences, including older users, people with disabilities, assistive technology users and people accessing news on-the-go through their phones. This session will explain some common Web accessibility techniques and principles as they can be applied to the development of news interactives.
### Agenda

Introduction
We'll start by providing a brief overview of some technical accessibility and progressive enhancement concepts, ranging from keyboard and SVG accessibility to how to use sound and descriptions to convey information in different modalities. 

Concrete tips
Then, we'll provide practical tips on how news interactives can be developed based on some common news application scenarious. We'll provide code and pseudocode examples (JavaScript, D3, HTML) and a list of resources for further study. 

Dealing with tight deadlines
Finally, because news application development often has a quick turn around, we'll discuss strategies on how coder/journalists can incorporate accessibility techniques with deadlines in-mind.

Discussion and moving forward
We'll also do a brainstorm / Q&A session towards the end of the session. 
### Participants

We'd appreciate help from Mozilla sourcing a sign language interpreter for the session and for help ensuring our space is accessible.

Because it's more of a presentation, it shouldn't matter too much if 5 - 50 people come. However, if there are fewer people, we may elect to break up into groups to focus on specific problems. 

Should this session be accepted by the Open News / Mozfest selection committee, prior to Mozfest we'll do a call out on Twitter asking folks if there are specific questions or ideas they'd like us to cover in the "concrete examples" section. 
### Outcome

We're going to make a presentation and we will be sharing the presentation slides on GitHub so that it will become a resource for the OpenNews community.

Depending on how the session goes, it's possible that we'll want to come up with ideas for accessible news interactive authoring tools. We can share those ideas with the Mozilla community, and we hope those ideas will be taken up and developed on. 

Please note: We will try to seek out other speakers to contribute the session.

**Comment by ryanpitts** [comment]
Alison is based in London, so travel would not be an issue.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Mobile & Accessibility" pathway.
