### ISSUE TITLE
[Pathway] Online Learning Done Face To Face

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#505]
**[ Google Spreadsheet Row Number ]** 459
**[ Facilitators ]** 
Bekka Kahn @rebamex
### Description

The Pathway we’d like to run is a Mozfest-long Learning Circle that teaches people how to run Learning Circles. These are peer-supported, open learning interventions, where groups of people come together to work through online content face-to-face. Learning Circles are designed to foster “academic mindsets” - ie: helping people learn how to learn more effectively. Online learning offers great potential for reaching communities who cannot access traditional education, but without a social wrapper around this content, many learners battle with completing online courses. Learning Circles are designed to provide the scaffolding learners need to take charge of their own learning and successfully complete online learning experiences. 
### Agenda

We will take participants through the four components of starting a learning circle - finding a course, identifying a space, finding a group of co-learners, and stepping into the role of facilitator. Each of these component-sessions would be a stand-alone, and participants will be able to build their own blueprint in each session. We could have courses listed to choose from, suggestions for spaces, marketing ideas, and a discussion on facilitation open, online courses in person. As mentioned above, the conversations will themselves be structured as a Learning Circle.
### Participants

 Learning Circles need a minimum of 4 people to really work, but more is always better. If we do find ourselves with more than 10 people, it would be possible to break the Circles into smaller sub-circles, and run them concurrently in the space
### Outcome

Learning Circles everywhere! We’d like to provide participants with the mechanisms and materials they need to take Learning Circles into their communities - and run them in libraries, schools, community groups, prisons, coffee shops and anywhere else people might come together to share space and knowledge. This materials include a facilitation handbook, course selection guide, and weekly recipe cards.

**Comment by emmairwin** [comment]
cc / @geroter @emmairwin For community leaders interested in teaching and facilitation this might be an empowerment session
