### ISSUE TITLE
Design Thinking - Maximizing Resources in Your Community

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#506]
**[ Google Spreadsheet Row Number ]** 460
**[ Facilitator ]** Helen Lee
### Description

As volunteer community leaders with little to no resources, how do we maximize resources in our community in order to achieve our goals?  This workshop allows community leaders (from novice to expert) to identify challenges in their communities, and apply Design Thinking process to come up with innovative solutions to maximize existing resources in order to achieve radical participation.  Participants will get a crash course on the Design Thinking problem solving process in a hands-on participatory exercise.  
### Agenda

This hands-on participatory workshop will start off with a brainstorming ice breaker on identifying common community challenges.  Participants will then receive a crash course on Design Thinking, break out into smaller groups to apply the Design Thinking problem solving process, then regroup to share out innovative solutions.  
### Participants

If the total number of participants is small, we will not break out into smaller groups, instead we will carry out the entire workshop together.  If the total number of participants is large, the majority of the hands-on component will require smaller group breakouts, so it will be more intimate and manageable.  
### Outcome

Participants will be able to apply Design Thinking as a new problem solving process when faced with challenges in their communities.   They will feel empowered to resolve challenges by maximizing resources with innovative solutions.

**Comment by soapdog** [comment]
cc: @soapdog

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin Helen who helped at Participation Sessions in Whistler.  Perfect for Community Building.

**Comment by amirad** [comment]
@emmairwin just to confirm, this session is happening in the building participation space? I would love to show that it overlaps with Mozilla Clubs pathway and keep the label (or have it in our space if that makes sense)

**Comment by emmairwin** [comment]
@amirad yes!   We'll probably keep it if that's OK, but welcome the crossover :)    If you want I can also include you on my 1:1 with Helen and we can talk about framing.

**Comment by amirad** [comment]
That's okay! I was gong to invite her to our pathway meeting but I'll let her focus on in for your space instead!

**Comment by emmairwin** [comment]
@amirad I think she'll probably want to focus on both, as per whistler. I'm sure we can enable her in both, and will talk to her about that in our 1:1

**Comment by amirad** [comment]
Ok...I haven't invited her or looped her into any of our meetings for the people in our track/space.
