### ISSUE TITLE
Visual Programming: Play Time with Blockly

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#507]
**[ Google Spreadsheet Row Number ]** 461
**[ Facilitator ]** Tennyson Holloway
### Description

This session will introduce participants to the open source, web-based visual programming editor Blockly. A custom MozFest build (possibly a Thimble implementation) will let participants learn the basics of visual programming, make a shareable (and remixable) program, and collaborate with others. The session will encourage discussion about the applications of visual programming (e.g. education), as well as its merits and drawbacks.
### Agenda

The session will begin with a short talk and demo, followed by free time to explore and code. Participants will then visit a website hosting a custom MozFest build of Blockly, which will explain how to use the visual editor, and have prebuilt challenges for all skill levels (never have programmed to guru). If someone doesn’t have a laptop, they can pair up with a facilitator or another participant. Participants will be free to chat and collaborate among themselves, and facilitators will be available to answer questions or raise a discussion topic to the group at large.
### Participants

Since the main activity is web based, the session can scale to a large number of participants. Additionally, with more participants, there is a greater chance that experienced programmers attend, and are able to help if the facilitators are overwhelmed with questions. As the number of participants gets smaller, group discussion will become more prominent, and the session might shift towards a more speculative and critical analysis of visual programming. 
### Outcome

Participants will leave with experience and understanding of visual programming, its merits and drawbacks, and its current applications. The MozFest Blockly build will stay up, and participants will be free to share the link, as well as contribute to the site’s code and growth.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by mattdigitalme** [comment]
cc @mattdigitalme

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
