### ISSUE TITLE
Privacy/Security Browser Extensions and You

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#508]
**[ Google Spreadsheet Row Number ]** 462
**[ Facilitator ]** Tennyson Holloway
### Description

This session will provide a place for discussion around privacy/security browser extensions. The main topics of discussion will answer three questions: ‘What extensions do you use?’, ‘Why are you using them?’, ‘Do you understand how it works?’. These questions will help facilitate for all a better understanding of the extensions, and why they are important. 
### Agenda

There will be a short talk at the start consisting of an abridged history of privacy/security extensions, an explanation of the session and it’s goals, and some personal anecdotes. The session will be split into small groups, where participants will (optionally) share with others (and in a etherpad) their answers to the questions above. Participants will discuss their answers, and also raise questions of their own for the group at large. Near the end of session, we’ll do a recap of some of the interesting answers, and have a discussion about possible avenues for the future of privacy/security browser extensions. The session is not under a time restriction, save for a minimum time of 60 minutes. Any additional allotted time will be put towards group discussion and recap. 
### Participants

Since we’ll be splitting up into discussion groups, the number of participants can be managed by either creating more groups, or having more people per group. The strategy taken depends on the number of facilitators attending the session. The session will be made entertaining and accommodating to all, regardless of technical understanding.
### Outcome

First, all participants will leave with a better understanding of the privacy/security extension world. They will learn the basics of how the most popular extensions work, and what the future holds (e.g. Mozilla’s Tracking Protection). Additionally, the participants answers to the three questions will be open for extension developers to view. Developers can incorporate the feedback and suggestions into an existing extension or a new extension. By exploring privacy/security extension user’s understanding and motivations, we can create better systems that help keep the web open; free from trackers, popups, and malware.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by Melechuga** [comment]
Could be morphed into Privacy Bar (https://github.com/mozilla/mozfest-program/issues/461) We could ask Tennyson to train the volunteers and man the bar.

**Comment by Melechuga** [comment]
Melissa will contact.
