### ISSUE TITLE
Digital inclusion and web literacy in emerging countries

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#509]
**[ Google Spreadsheet Row Number ]** 463
**[ Facilitator ]** Mario Brandão
### Description

This session is a fireside chat about the challenges and opportunities of trying to enable digital inclusion and web literacy on emerging countries and poor neighborhoods.

Our goals are:
- Identify common challenges faced by everyone in this segment and ways to overcome it.
- Collect awesome stories that we can share with advocacy and fundraising teams.
- Understand the different reasons why people chose to devote their time to these efforts and how we can help them.
### Agenda

The session is a fireside chat with facilitators serving as translators for those whose primary language is not English. We'll begin by understanding what everyone in our group is doing and then proceed to chat and an almost free form way about our topics. Facilitators will try to steer the conversation towards our goals in case we drift too much into other topics.
### Participants

Since we're doing a chat session, the more people the merrier. If we reach a number that makes conversation difficult then we'll break out into smaller groups and elect someone from each group responsible for notes and conclusions which we'll be shared with our larger group at the end of the session and over digital means.
### Outcome

We aim to have a bigger and actual picture of the efforts, challenges and opportunities being experimented by people from poor regions and emerging countries. By identifying these common challenges we hope to have an action plan or at least a seed group to work on reproducible solutions to overcome them. We also want to collect awesome tales that could be used by the fundraising and communications team to convey the results of MoFo actions to larger audiences.

**Comment by amirad** [comment]
cc: @amirad

**Comment by soapdog** [comment]
cc: @soapdog

**Comment by simonaramkisson** [comment]
@simonaramkisson @jvallera

**Comment by amirad** [comment]
@simonaramkisson @jvallera -- you should definitely take this in your pathway! Is related to work @soapdog is doing but fits better in yours than the clubs one!

**Comment by simonaramkisson** [comment]
@amirad @soapdog @jvallera Awesome, I think it would be a great fit and we can definitely figure out ways to make it a cross-pathway experience.

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter there's something to this about community building, inclusion and Participation.

**Comment by cubicgarden** [comment]
Could be good in the global village/library space @cubicgarden

**Comment by simonaramkisson** [comment]
We are allocating one of our travel stipends this this session, doesn't anyone have any concerns or are they already being taken care of

**Comment by jvallera** [comment]
@emmairwin @cubicgarden @simonaramkisson we are placing into the Diverse Leaders pathway and providing a stipend. Happy to use it as an overlap with participation.

**Comment by anivar** [comment]
If there is a possibility,  i am Interested in sharing some of our experience with Indian Language computing efforts of Swathanthra Malayalam computing (smc.org.in)   and FUELproject.org in this session

**Comment by simonaramkisson** [comment]
@Saallen @marcwalsh  unable to come to Mozfest due to funding

**Comment by jvallera** [comment]
@Saallen @marcwalsh disregard previous note. @simonaramkisson and I just found out this session facilitator WILL be joining us and will be included in our pathway. He is a part of Rio's staff.
