### ISSUE TITLE
[Pathway] Producing in the Open

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#51]
### Learning Objectives
- Experiences of others who have developed products in the open
- Skill identification
- ""Scrappy"" teamwork
- challenge identification <== what are your challenges? what are your team's challenges?
- Tips for mentorship <= what are the 10 advice that are needed to know when you mentor a contributor 
- Working on a team remotely
### Personas

Motivations
- wants to create a product or run a program
- wants to learn
- wants to create
- wants to hone a professional skill set
- wants to be part of a team (of professionals?)
- wants to work in the open
- wants to share what they know
- wants recognition for their work
- wants to be able to use their experiences to fill out their résumé
- wants to be enthusiastic about a cause and have fun, make friends, etc.
- wants an overview of the product process

Challenges
- doesn't necessarily understand their place
- is curious about how products are created
- doesn't understand how working in the open is beneficial/possible
- struggles with leadership in the open
- struggles with producing and communicating results in the open
- main incentive is employment
- needs in-depth mentorship (from a professional)
- Open Product Dev is not very selling on a CV (questionable from an employer point of view)

Curated by: Bobby Richter

**Comment by secretrobotron** [comment]
Rough notes:
- Meet in the morning
- Teams
- Come up with product ideas
- Learn
- Research
- Product
- Launch and demo!

come up with something silly and fake initially, but research, build, and launch it with a "comms plan"

#### credentialing (written letter about how cool you are) at the end?

**Comment by secretrobotron** [comment]
New Organizing Institute bootcamp

**Comment by secretrobotron** [comment]
150 words of description:

What's it like to research, develop, market, and launch products in the open? How do you communicate to users and partners? How do you build a community and engage volunteers? We'll share experiences and ideas about working on product-focused, open-source teams, and engage in the Mozilla festival through that lens.

There will be 3 main meeting opportunities:

### Orientation & Identification

Gather over coffee or burritos and discuss working on products in the open. Refine personas and expectations within group.
- What does it mean to work in the open?
- What makes people excited/nervous/confused/enthusiastic/etc?
- Commit to taking part, disrupting, and documenting experience throughout festival for shareback at the end

### Research, Design, and Produce

Integrate with other pathways and spaces. Map skills and perspectives to other parts of festival; bring them together in a comical, or meaningful way (great mockumentary opportunity).

### Reflect

Reflect and demo. Share experiences

**Comment by secretrobotron** [comment]
Even more succinct:

150 words of description:

What's it like to research, develop, market, and launch products in the open? How do you communicate to users and partners? How do you build a community and engage volunteers? We'll share experiences and ideas about working on product-focused, open-source teams, and engage in the Mozilla festival through that lens.

Through several group meeting opportunities, participants will discuss working on products in the open and refine personas and expectations before heading out to integrate with other pathways and spaces in the festival. The ultimate goal is to find a way to research, prototype, build, and market a product within the timeframe of the festival and within the context of another team/space/pathway's work. Finally, participants will reflect and demonstrate their findings through as comical and illustrative means possible.

cc @Saallen

**Comment by benrito** [comment]
@secretrobotron you want a rapping component? or just problem definition in a fun setting?

**Comment by secretrobotron** [comment]
@benrito: both, obviously, but the latter is the real goal.

**Comment by secretrobotron** [comment]
For reference: #314, #462, #550

**Comment by benrito** [comment]
you're sure about the rapping part? it requires people to step pretty
far out of their comfort zone!

i can put you in touch with the people that facilitated it in SF...
