### ISSUE TITLE
Leadership Games! 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#510]
**[ Google Spreadsheet Row Number ]** 464
**[ Facilitator ]** Adriano Cupello
### Description

 Will be a kit of Leadership paper games that will test and improve the ability to make fast decisions, based on strong arguments and quick voting decisions. Will be quick fun games. A couple of paper games and one game based on the London's Tube! The session's goals are: to develop Leadership and improve the skills to make fast and fair decisions. 
### Agenda

Will be a workshop interactive and people will don't need any computers or other devices. Paper, post it and sharpies only.
### Participants

They are all 5 to 10 people games. So will be easy to handle different number of people. 
### Outcome

This kind of activity makes people think. The goals achieved in this session will make people think about leadership and how we can make the decision-making process not something that end up harming the execution time of a task or an event planning. Also if they can bring this games and play with their community, they will be able to teach how to make this challenge scenario a little bit easier to handle and others can replicate too.

**Comment by soapdog** [comment]
cc @soapdog

**Comment by soapdog** [comment]
cc @chadsansing this one might interest you ;-) games and LD.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin  might be fun thing for community leadership on topic of decision making

**Comment by shadowcrow** [comment]
Oh,it's interesting, May I join host?
