### ISSUE TITLE
Data in Motion: SVG Animation for Information Visualization

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#511]
**[ Google Spreadsheet Row Number ]** 465
**[ Facilitator ]** Julia Smith
### Description

This session will introduce people to the different ways animation can enhance data visualizations and then teach participants how to use with Snap.svg (a JavaScript library for creating, animating, and interacting with SVG in modern browsers) in their data-driven projects.
### Agenda

Workshop agenda:

1) Overview: Different ways animation can enhance data visualizations.
2) Introduction to Snap.svg: What it is and why it's a good choice for SVG animation.
3) Hands-on coding: I'll walk participants through how to get started with the Snap API using this repo: https://github.com/julia67/snap-basics (in progress)
4) Working with data: After the basics, we'll get into how to use Snap for data-driven projects. We'll cover animation synchronization, working with cartograms, and surfacing embedded information from custom SVG files. 
5) Bonus: If people are interested, we could also get into incorporating audio (data sonification) with animation.
6) Brainstorm: Break into groups to generate ideas for animated data visualizations and then work on those.
### Participants

For most of the session, the content (introduction and tutorial) will stay the same. For the brainstorming part, if there are a lot of participants, we'll break into groups and then regroup to share ideas; otherwise we can stay together.
### Outcome

By the end of the workshop, attendees will be able to interact with basic SVG elements using Snap.svg and have a greater understanding of how to utilize animation for data-driven visualizations.

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Julia will for sure be traveling to London and attending MozFest.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Mobile & Accessibility" pathway.
