### ISSUE TITLE
Storytelling with animated video

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#512]
**[ Google Spreadsheet Row Number ]** 466
**[ Facilitator ]** Kavya Sukumar
### Description

Often complex ideas in a story don't get the attention they deserve because, let’s face it, you are allowed only one lede. Short animated videos are a great way to remedy this. They can bubble up interesting content in an easily shareable form that works on most devices. In this session, learn to create and publish your own animated video from scratch. We will also explore Adobe Expressions, a javascript like language, for coding your animation behaviors in a video. 

This session is good for beginners new to making videos as well as for people with some experience in video production looking to add animation to your skill set.

_Prerequisites:_  A working installation of Adobe After Effects and Adobe Photoshop. You can get a free 30-day trial from Adobe Creative Cloud at http://www.adobe.com/creativecloud/desktop-app.html. Instructions for installing After Effects and Photoshop are here: https://helpx.adobe.com/creative-cloud/help/manage-apps-services-desktop.html. It would be great for participants to already have software installed when they come to this session!
### Participants

This will be a hands-on workshop. With 5 people, I would have more time for 1-on-1 questions, but it should scale up just fine with more participants.

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Kavya will for sure be traveling to London and attending MozFest.

**Comment by ryanpitts** [comment]
Woo! Another one for the joint pathway between Science and Journalism called "Tools & Analysis."

**Comment by ryanpitts** [comment]
Changed session description after talking with Kavya; she'd prefer to run this session at MozFest. Swapping https://github.com/mozilla/mozfest-program/issues/451 into the "Tools & Analysis" pathway in place of the old session here.

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone, likely most appropriate for Bronze participants
