### ISSUE TITLE
From Participation to Collaboration

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#513]
### Google Spreadsheet Row Number

467
### Facilitator

Name: Hélène Petry
Twitter: n/a
Org: UFF - Fluminense Federal University in Rio, Brasil
### Description

The session is a fireside chat about participatory and collaborative methods for mozilla clubs and community building. In this session we'll explore best practices, tips, tricks and ways that club captains and facilitators can improve their game and make the most of the community they are a part of.

We'll look into ways to move from participation into collaboration and why these methods work and are the right approach for a "Teach Like Mozilla" framework.

**Comment by soapdog** [comment]
cc: @soapdog

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter participation fire side chat, through focused on specific roles of webmaker clubs.  Regional theme.

**Comment by amirad** [comment]
@soapdog can you help me with Helene's twitter and org please?!?!

**Comment by soapdog** [comment]
@amirad Hélène doesn't use Twitter and I think the org should be MoFo.

**Comment by amirad** [comment]
thx @soapdog
