### ISSUE TITLE
A Feminist Internet in 140 Characters

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#514]
**[ Google Spreadsheet Row Number ]** 468
**[ Facilitator ]** 

name: Andrea Del Rio
twitter: @andredelrio 
organization: Association for Progressive Communications (Ford-Mozilla Open Web Fellow)
### Description:

In this session we will remix the Feminist Principles of the Internet. We will come up with a version of these Principles aimed at people that love the Internet and believe in gender equality. And added fun challenge will be to make sure these Principles are tweetable (having 140 characters or less).

No laptop is needed for this session. All you need is eagerness to discuss the relation between women and the Internet and its related components (freedom of expression, violence, access, representation, economy and more).

These Principles were published by the APC (Association for Progressive Communications).

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by cubicgarden** [comment]
Oh I like it, keeping an eye on this one @cubicgarden

**Comment by cubicgarden** [comment]
Are you opening this back up for 2016? @Melechuga

**Comment by Melechuga** [comment]
@cubicgarden Nope. I was closing out issues to clean up my github, but then was asked to stop lol. She's not joining us this year. Thanks for checking though!
