### ISSUE TITLE
Massive Multiplayer ... In Person Games!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#515]
**[ Google Spreadsheet Row Number ]** 469
**[ Facilitator ]** Clay Ewing
### Description

A collective game session in which all the participants in the session play Atlantis, a multiplayer game, together using their phones as a controller. The game itself is shown on the projector. Participants must work together against a system, in teams (though they might not know who their team members are), and individually to accomplish goals in real time. Afterward, they’ll be group discussions about their experience, what types of things they were able to learn, and what topics are particularly suited to being taught with mass participation. Participants will also get some resources to help them create games like this on their own.
### Participants

Since it's a game that can handle as many users as the wifi can handle, any number of people will be able to participate.
### Outcome

They'll have a better conceptual understanding of what games can do, how games build understanding, and how they affect participants in teamwork situations. Also, I imagine this might be the opening session for the Games & Understanding track, which will hopefully propel participants into the pathway.

**Comment by ryanpitts** [comment]
Sisi is our pathway coordinator for Games & Understanding, and will have travel support to attend MozFest.

**Comment by EPIKhub** [comment]
could we have 2 sessions on this? one on satureday and one on sunday, so more than one space can play with this session?

**Comment by sisiwei** [comment]
Updated the agenda now that we have a clearer picture of what the game will be, so there will be no laser pointers, just cell phones!

**Comment by ryanpitts** [comment]
Changing facilitator to Clay Ewing from University of Miami. Not sure if he'd be available to run the session twice, but @sisiwei or I can check into it.

**Comment by EPIKhub** [comment]
@sisiwei @ryanpitts Ok I have to much selected already so lets leave this one, although I think this would have been fun and a good reflection piece for the parents and kids, in how mobile phones are used beyond it function as the youth media it is vs. how adult perceive it. BBC recently did a survey asking kids which would they not give up as a device, all said they would keep their mobile phone over other devices :)

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter learning about participation/tendancies and working in teams together 'mass participation' all cool to explore here.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Games & Understanding" pathway.

@emmairwin if you end up wanting to include this session in your pathway as well, it should for sure be at MozFest :)

**Comment by Zebetus** [comment]
@EPIKhub @ryanpitts  If they cant do the two sessions would it be possible for us to sign post some youths who are interested in journalism or such to this session???

**Comment by ryanpitts** [comment]
oh absolutely. It seems like the pathways concept will really encourage cross-pollination between floors and audiences this year. I will also reach out to the facilitator to see if he's interested and available to run the session twice, though.

**Comment by sisiwei** [comment]
@EPIKhub @ryanpitts @emmairwin Hey everyone -- just spoke with Clay. He's down to do a separate session for the YouthZone, with the caveat that we expect all the participants to have their own cell phones. Thoughts? The game won't work without everyone having their own cell.
