### ISSUE TITLE
Image is Everything: Visual Thinking

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#516]
**[ Google Spreadsheet Row Number ]** 470
**[ Facilitator ]** Amy  Burvall
### Description

From cave walls to Facebook walls we have always embraced visual communication With the changing media landscape, our streams, memes, and zines have exploded with imagery, ushering in a need for visual literacy skills. We are quickly moving from images as decoration and augmentation to images as sole content and communication tool. Technology has affected knowledge in such a way as to diminish the value of “raw” information and increase the value of sense-making, as well as chip away at attention spans, sparking a need for distillation of complex ideas. Images can essentialize the cumbersome in beautiful ways. They have a “stickiness” for the viewer and challenge the critical thinking of the creator.
This hands-on session offer participants an opportunity to tinker and play with:

metaphorical thinking, iconography, pictograms, emoji, typography, sketchnotes and photography. 

We’ll experiment with ways to use visual language for critical thinking, social interaction and creative expression
### Agenda

This is more of a workshop with lots of hands-on activities from which participants can choose. (I liked the #artofweb format I was a part of last year). I will interact with participants and have displayed exemplars and design specs. Here is a video trailer: https://www.youtube.com/watch?v=BYNQ2hzbeQI
### Participants

While the best grouping would be 5-30, larger groups could go to "stations" (these can be digital and our larger "commons" online if needed). I'd set things up much like a hands-on museum-type exhibit. 
### Outcome

I think participants will have a better grasp at the importance of visual thinking (particularly in the digital sphere), and how one does not need to be an "artist" in order to leverage an image. I hope they'll pick up some of the visual thinking strategies shared and use them personally or in their classrooms / on the web.

**Comment by thornet** [comment]
cc @metodb as possibly relevant for the seeing pathway.

**Comment by metodb** [comment]
@thornet, excellent. Yes this space does go right up my street. Or do I go right their street? Either way... Thanks.

**Comment by metodb** [comment]
This session sounds great and also goes along my pathway. Here is some information: [Pathway] Seeing–Drawing–Producing Smilies https://github.com/mozilla/mozfest-program/issues/35

**Comment by thornet** [comment]
@metodb great! I applied your pathway label for you.

**Comment by metodb** [comment]
@thornet, fab. Thank you so much. So looking forward to this year's edition of MozFest.
