### ISSUE TITLE
Using open source tools to analyze police data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#517]
**[ Google Spreadsheet Row Number ]** 471
**[ Facilitator ]** Paola Villarreal
### Description

This session will allow people to experiment with tools used in mapping and analysis and visualization of datasets that I am using on the "Police by numbers" project with the ACLU of MA. Tools include: PostgreSQL + PostGIS, D3 and other JavaScript tools and PHPDataProcessor a tool written specifically for this, REST, Geo/TopoJSON, etc.
### Agenda

I would like to showcase what can be mapped and which conclusions we can reach using those maps and graphs and then explain how it was done and which datasets were used and how, which technologies were used to process and visualize data, etc. 
### Participants

I think it would be perfect to make groups of 5 to try and use those tools to apply this to other cities. So if it is 1 group of 5 or 10 it is cool. 
### Outcome

I would like to see more people involved in arguing about those important topics with data in their hands.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by Melechuga** [comment]
@kaythaney @acabunoc @erikao Does this fit within any of your spaces? Would you be interested?

**Comment by Melechuga** [comment]
Hi @arlissc @acabunoc. Paola says she hasn't heard anything about her session; please let her know when you can! Thanks.

**Comment by abbycabs** [comment]
She should have gotten an acceptance -- sorry about that, will look into this

**Comment by arlissc** [comment]
Hi  @Melechuga @acabunoc - I have sent Paola her acceptance email.  I'm not sure how this one fell through the cracks.  Thank so much for following up.
