### ISSUE TITLE
Make du Jour

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#518]
**[ Google Spreadsheet Row Number ]** 472
**[ Facilitator ]** Amy Burvall
### Description

Creativity is about connecting dots...and mixing and combining things that don’t obviously go together. This workshop will offer participants a variety of low-barrier entry points to creative practices that will help them cultivate creativity on a daily basis - both analogue and digital, personal and combinatorial (with crowdsourced projects).
### Agenda

This will ideally be set up like our #artoftheweb was last year - sort of a "science fair/ open house/ interactive museum" situation. I would facilitate and talk with participants as well as display exemplars and instructions for the creative tasks, but primarily the experience is self-directed - as chance to play.
### Participants

I think if the set up was museum/ science-fair like as mentioned above, it wouldn't matter how many people were involved , though the best number at one time would be around 10-15 so I could really interact with each participant.
### Outcome

I would hope that participants would see creativity not as "special" or daunting but as something we all have and something that can be cultivated, with daily habits. Educators can take strategies back to classrooms and others may wish to incorporate some of these activities into their daily lives. All can be shared on the web or done completely analogue- most are hybrid.

**Comment by thornet** [comment]
cc @jvallera as potentially a creative entry to diverse leaders pathways

**Comment by Saallen** [comment]
cc @samueledyson wanted to be sure this was definitely not being captured under your Space before I closed the issue

**Comment by samueledyson** [comment]
Ok to close.
