### ISSUE TITLE
Run the Gauntlet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#52]
**[ Google Spreadsheet Row Number ]** 2
**[ Facilitator ]** Su Adams
### Description

This session is aimed at creatively engaging children to use a variety of talents towards a common goal.  Children will add to an activity course for the Sphero or Arduino robot, to create a colourful, interactive end result by the end of the weekend.

Example:
A child (or adult) might decide to make a tunnel or see-saw bridge etc... to add to the course then attach a MakeyMakey or Arduino and program it using Scratch, S4A or Mind+ etc... to code a response to an input for example a noise of some sort or traffic lights to change at another section.  

The aim is to demonstrate how many skills come together to create a great end result and to realise how all skills are valuable.  i.e. a child may choose to create and decorate a tunnel without any coding.

Skills:
Art, design, craft, coding, electronics, collaboration etc...
### Agenda

Drop in and/or session based, individuals can turn up and use the resources (cardboard boxes, paper, plastic containers etc...), electronics and programmable boards, along with their imagination to expand on a small pre-existing course.  

There will be a starting point already created by the Digital Leaders and Code Clubbers of our school.  This will provide ideas and something interesting to begin with.

We will have some Arduino's and MakeyMakey's, possibly a couple of Pi's too, but any additions would be helpful is that is possible.  We will bring laptops for the programming aspects.

The session would run over the whole weekend and be manned by the Digital Leaders, Code Clubbers, Website Club and Weaving the Web (web literacy club) Members of our school supported by myself and enough Adults to appropriately support the children.
### Participants

The session can run as either drop-in and/or timed sessions and will be well supported by children who will lead lead the activities, encourage participants and make suggestions methods where needed. We could handle 1 - 50 by break up the activity into mini areas, assuming we had the space.  i.e. 
Area 1 - Research and Design
Explore the course.  Consider challenges to make the course more interesting. Draw a design for their idea incl. resources needed, programming elements and any help needed, if identified.
Area 2 - Modelling area 
Making of the physical aspects, i.e. tunnels, see-saws, bridges, portcullis etc...
Area 3 - Electronics & Coding area 
Using their creation, participants put together the electronics/programming aspects of their design.
Area 4 - Testing
Participants add their creation, then test it.
### Outcome

The aim is to demonstrate how many skills come together to create a great end result and to realise how all skills are valuable. 

Participants will feel that they have a stake in the project and want to see the end result.  It would be great if this could be made available through the MozFest Blog.  Otherwise, we will have a page on our website for people to blog on anyway.

Participants will experience a tangible end result using their imagination and skill set to make something interesting happen in the physical world.  

I would like to think that participants will challenge themselves by expanding on what they already know, learn from those around them and from the opportunities to try new technologies too.  I see scope for mentors to learn too!

Learnt skills can be practised & expanded on after MozFest.

In my opinion this task fits all themes!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
adding the youth zone here @chadsansing as possible cross pollintation
