### ISSUE TITLE
Using Digital Fabrication Techniques to Make DIY Activist Gear

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#520]
### Google Spreadsheet Row Number

474
### Facilitator

Name: Drew Wilson
Twitter: @drewSaysGoVeg
Org: Ford Foundation/ Mozilla Open Web Fellow
### Description

High tech manufacturing tools are becoming more accessible for do-it-yourselfers, makers and activists. The tools you can find at a local maker space can be used to make inexpensive activist gear. In this participatory session, you’ll learn learn creative ways to user maker tools for activism. We’ll cover making giant banners, laser cutting stencils for spray painting, making custom vinyl stickers to culture-jam billboards, using CNC machines to carve block of linoleum or wood for printing posters. 
In the first part of the session you’ll get a quick overview of these DIY production techniques, see some examples of how activists have used these techniques, we’ll talk about how you can access these machines at maker spaces, and we’ll spend some time brainstorming some new ideas. In the second part we’ll get our hands dirty and print some t-shirts, bandanas, patches and posters. Bring a blank t-shirt to print on (but don’t worry if you don’t have one with you, we'll also have fabric and paper available).

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by EPIKhub** [comment]
@amirad what about this session, I feel it has scope and they are based at the college, where should it go?

**Comment by amirad** [comment]
Would be good in either! Maybe better in the youthzone but I will still mark it as applicable in our pathway to show crossover.

**Comment by EPIKhub** [comment]
@amirad I think this will be located on the 9th floor where the 3D printing lab is, who will taking the 9th floor space?

**Comment by amirad** [comment]
hmm not sure @Saallen @thornet - is there way @EPIKhub can have it apart of her space but on the 9th floor instead?

**Comment by EPIKhub** [comment]
@Saallen @thornet @amirad I think it would be better if who ever has the 9th floor host this session from a logistics perspective, also it would be a really good fit  with cc @msaunby for the garden and home pathway, it has a lot of synergy there.

**Comment by amirad** [comment]
@Melechuga do you think it would make sense for Drew to make this session a little bit broader (ex. Make DIY event gear) and have him in our Mozilla Clubs pathway? I like the session but right now it doesn't fit within our top ten

**Comment by amirad** [comment]
If not, that's also cool. I can de-label this and the session will be not approved.

**Comment by Melechuga** [comment]
hey @amirad 
I think Drew would be happy to be flexible. I'll put you in touch via email and let you drive that conversation.

**Comment by drewrwilson** [comment]
@amirad @Melechuga 

Yes, I'm happy to be flexible. (And I think organizing clubs is activism! :smile: ) 

I'd like to have some time to show examples of DIY gear that people use in their organizing to get people thinking creatively, then do some group brainstorming about things people could make, and then get hands-on and have people use some laser-cut stencils to print some shirts/patches/posters. (I'll bring all supplies: pre-cut stencils, inks, paper and fabric).

To give you a better sense of what I'm thinking about, here are three recent projects of mine that I could use as examples of using digital fabrication to make activist gear:

## Tabletop displays for Code for America clubs to use when setting up tables at events (using CNC machines):

[![table-display-07-final-product](https://cloud.githubusercontent.com/assets/4324656/10518391/33156d52-732f-11e5-9f2e-d8cea41630eb.jpg)
![image](https://cloud.githubusercontent.com/assets/4324656/10518633/5929e2d8-7330-11e5-8f55-699efe365a73.png)](https://drewrwilson.com/cfa-display/)
![image](https://cloud.githubusercontent.com/assets/4324656/10518766/dc7ae1f0-7330-11e5-8640-7efa4a23210a.png)
![image](https://cloud.githubusercontent.com/assets/4324656/10518771/e2b12b06-7330-11e5-9193-46e33c94e786.png)
- [more photos and step-by-step instructions on my blog](https://drewrwilson.com/cfa-display/)

## Laser-cut stencils to make signs for BlackLivesMatter rallies & protests:

![image](https://cloud.githubusercontent.com/assets/4324656/10518312/c98160a8-732e-11e5-91c4-2e5f4647150b.png)
![black-lives-matter-stencil](https://cloud.githubusercontent.com/assets/4324656/10518290/b721b2e6-732e-11e5-81dd-cae86f640b75.jpg)
![blm01](https://cloud.githubusercontent.com/assets/4324656/10518286/aeff2e9a-732e-11e5-951c-00f7f6d1e659.jpg)

## Vinyl-cutting stickers to make giant car-decals (used by The Humane League):

[![image](https://cloud.githubusercontent.com/assets/4324656/10518660/72909fb4-7330-11e5-9f41-a7469d934c29.png)
![image](https://cloud.githubusercontent.com/assets/4324656/10518668/7c3ae420-7330-11e5-8d36-8c1f91ed0b97.png)
[![image](https://cloud.githubusercontent.com/assets/4324656/10518255/8fd9fe6e-732e-11e5-8816-118373201aa7.png)](https://drewrwilson.com/projects/diy-car-decal/)](https://drewrwilson.com/projects/diy-car-decal/)
- [more photos on imgur](https://imgur.com/a/Bkd9B)
- [step-by-step howto on instructables.com](http://www.instructables.com/id/Car-decal-sticker-made-with-a-vinyl-cutter/)
- [read more in my blog post about the car-decals...](https://drewrwilson.com/projects/diy-car-decal/)

Related: I've recently been working on a digital tool for stencil design, [Stencil Validator](https://drewrwilson.com/stencilvalidator/). It's not done yet, but I'll try to in a more ready-state for MozFest so I can point it out during this session (but I don't want it to be the focus of the session). 

Anyway, I think this would be a fun hands-on workshop.

**Comment by amirad** [comment]
Awesome - love all these examples @drewrwilson 

Most of the people in the clubs community (or Mozilla Learning community in general) do not have access to high end machinery like in the examples you use? Is there one of the ideas that can be done without the fancy tools to create them? I'm leaning more towards the stenciling. Can we do something around there?

**Comment by amirad** [comment]
Whatever the case, let's get you in our space! Added you to our pathway and we can figure out the rest from there.

**Comment by ArtsAward** [comment]
@EPIKhub Possible Arts Award pathway out from the Youth Zone
