### ISSUE TITLE
Computational Sociology (and Online Communities)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#521]
**[ Google Spreadsheet Row Number ]** 475
**[ Facilitator ]** Tara Adiseshan
### Description

The field of computational sociology is growing in exciting ways. This session will introduce folks to some of the resources, tools, and ideas that computational sociologists are working with. We'll talk about the increased visibility and interest in conducting research on online communities and online harassment and what that might look like with a computational sociology lens. The session will also touch on similarities between computational sociology and data journalism.
### Agenda

The session will begin with a (brief) introductory talk, defining computational sociology, pointing towards resources and tools. We'll then dive into a workshop. 
### Participants

With a smaller group of folks, I could spend a lot more time on the workshop and set aside more time for discussion.

With a larger group, I would probably divide the participants into smaller groups for discussion and workshop time.
### Outcome

Hopefully people will have a starting place to learn more about computational sociology and online communities!

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellow, Tara will for sure be traveling to London and attending MozFest.

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Building Online Communities" pathway.
