### ISSUE TITLE
Day of Action: A web app to facilitate decentralized collective action

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#522]
**[ Google Spreadsheet Row Number ]** 476
**[ Facilitator ]** Drew Wilson
### Description

A “Day of Action” is a common pattern in activism, join this session to learn about an open-source webapp that helps people & organizations coordinate large-scale collective actions.

The “Day of Action” app started in December 2014, on the heels police murdering Mike Brown in Ferguson, Missouri. High school students across the US began tweeting #HandsUpWalkOut--they were planning a national student walkout to protest police violence against people of color. This wasn’t organized by a formal organization, just high school kids on social media. That night I made the first version of “Day of Action” and put it on HandsUpWalkOut.com. Over the next two days,  student organizers used the app to coordinate 100+ walkouts & related actions. The tool provides a workflow for adding a local event and generates a map so others can find local actions. Thousands of people participated and the tool was used 100k times that weekend.
### Agenda

In this session I’ll share what I learned from making this Day of Action web app. Together we’ll brainstorm, design and start coding to creating a more full-fledged version of the app. Organizers, designer and coders welcome. No tech or organizing experience necessary. Let’s get people off the Internet and into the streets.
### Participants

The focus will be on Day of Action as a common pattern and a web tool that can support activists who are organizing a day of action. Depending who comes and how many people, it could end up being a hacking session on github, it could be a sketching and design session where we draw out interfaces, a discussion of activist tactics, or a brainstorming with organizers about what small tools would help them be more effective.
### Outcome

I'd like to build some momentum for another release of this application and identify some groups or people who could use it on the ground after MozFest and provide feedback and help improve it together.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin intersection for using new tech for participation

**Comment by drewrwilson** [comment]
More info & some background on this project: https://drewrwilson.com/projects/handsupwalkout/

[![image](https://cloud.githubusercontent.com/assets/4324656/10519647/945b88bc-7334-11e5-8d5f-41318e1cc38c.png)](https://drewrwilson.com/projects/featuredprojects/handsupwalkout/)

[![image](https://cloud.githubusercontent.com/assets/4324656/10519638/8c09352e-7334-11e5-81db-3a0c196ca0b5.png)](https://drewrwilson.com/projects/featuredprojects/handsupwalkout/)

**Comment by drewrwilson** [comment]
This was was from last year (MozFest 2015), but it went so well that I'd be down to do another similar workshop this year! I learned a lot from doing it last year and would do things a little differently this year--even more interactive, even more brainstorm-y. Last year went really well, we had 25ish people & the session helped with the [Digital Tools for Activism](https://github.com/drewrwilson/toolsforactivism) project, which Mozilla featured on https://advocacy.mozilla.org site and github featured on their frontpage in their [Social Impact Showcase](https://github.com/showcases/social-impact). Anyway, lmk if you are interested in it for 2016 MozFest! 😄 😄

**Comment by Melechuga** [comment]
Hey @drewrwilson That's a great idea! If you have insights to build on from last year, even better. I'll put in another place holder for this type of session in our 2016 MozFest planning repo and tag you, so we can work there. Does that sound ok?

**Comment by drewrwilson** [comment]
Sounds good to me, @melechuga!
