### ISSUE TITLE
In Praise of Microservices and other Small Single-Purpose Applications

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#523]
**[ Google Spreadsheet Row Number ]** 477
**[ Facilitator ]** Matt Dennewitz
### Description

Microservices are quickly being recognized as a viable pattern for splitting monolithic codebases and team responsibilities into smaller, more manageable responsibilities. But this concept is not new: you've probably been doing this for years with one-off data collection services, data transformation scripts, scrapers, and more.  

We'll look at how our organizations (Pitchfork, The New Yorker) and other major news and non-news orgs are adapting their practices to support the economies of scope, and outline the benefits and tradeoffs our teams have made. In that, cover the decision making processes for services we've created or migrated, too, from initially recognizing a need and a fit, through implementation, and to maintenance and ownership. And finally, we'll talk about what got us to this point in the first place.

Our goal is to clarify the benefits of strong organization through microservices, and more, through more thoughtful and economical software design.
### Agenda

This after-school special-cum-fireside chat will involve one to many participants sharing direct experiences, implementation details, and battlefield anecdotes on the topics at hand. We'll plan for a Q&A, and if the crowd wills it, collaborative planning through a hypothetical (or real) scenario or two. We'll start the session by identifying a handful of problems our organizations have had, and then work through our solutions in detail.
### Participants

For a smaller and focused group, a roundtable scenario works well - potentially with room for hands-on guidance and examples. As the crowd grows, we're looking at a moderated conversation with ample Q&A.
### Outcome

Participants should be able to leave the talk with a sense of what a microservice is (philosophically), and concrete ideas of how this design pattern looks, why it looks this way, and of when it works best.

**Comment by ryanpitts** [comment]
Matt (and Michael Donohoe) are already making travel plans, planning to be there for MozFest.

**Comment by Saallen** [comment]
```
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
```
