### ISSUE TITLE
Diving into Docker: Developing a Darn Fast, Repeatable Workflow

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#524]
**[ Google Spreadsheet Row Number ]** 478
**[ Facilitator ]** Daniel Craigmile
### Description

It will teach them about Docker and what it can do to help them iterate more quickly, easily and repeatably. 

For developers they'll have a tool that can guarantee parity between development and production environments -- leading to fewer bugs and runtime problems. 

For scientists they'll have an easier way to create, share, and guarantee the reproducibility of their results.  

If all goes as planned everyone (or small groups of people) will have created and executed a Docker container. 
### Agenda

Motivation:
- What are the benefits?
- How does this help?
- What kinds of problems does it help solve?

Concepts:
- Dockerfiles
- images vs. containers
- volumes
- linking containers

Hands-on workshop:
- a simple example to allow participants to walk through the process of creating and using a Docker container
- if there are participants that have some level of knowledge about Docker I'll try to group them with novices
- if someone has an example of a science-y problem I can customize the project
### Participants

For a smaller number of participants we could, of course, devote more time and attention to each. We may even be able to customize the workshop portion for each person. 

With more participants there will probably be more questions and less time for the workshop. With more attendees it may be better to have more time (1.5 hours vs. 1 hour.)
### Outcome

I'll provide a curated list of resources (online tutorials, videos, etc.) and encourage people to continue using the tools presented and learning about how the technology may best be able to help them. I'll be happy to answer questions via email or Twitter after the session.

**Comment by ryanpitts** [comment]
cc @acabunoc 

This would be a potential crossover Science/Journalism session
