### ISSUE TITLE
Romance is Dying: How Platforms are Killing the Open Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#525]
**[ Google Spreadsheet Row Number ]** 479
**[ Facilitator ]** Michael Donohoe, Matt Dennewitz, Trei Brundrett
### Description

We all have colleagues who are smart, talented, award winning perhaps, but with little understanding of the digital foundation of their livelihood. They have accepted that apps and platforms can deliver content faster than their own bloated invasive websites. They forget the core purpose of the Web was to efficiently deliver text and media to a networked readership.

And who could blame them?

Consider an article of 40KB in text takes 2.5MB to deliver with auto-play ads, and 15s to load on a broadband connection on a publisher website. Imagine Facebook Instant Articles, Pocket, Apple News, or Flipboard and the inverse experience.

To preserve the publisher web site as something of relevance and within the control of publishers we need to rethink everything from content, ads, paywalls, and experience.

The goal is to determine whether to relinquish control and syndicate our content and continue a meaningful relationship with our audience.
### Agenda

Identify the problems in the system: Often we are our own worst enemies as an organization. We're in still flux (10 years later), or crisis depending on who you ask. In this period we are observing a number of short-term decisions at the potential expense of our long-term future.

User experience: This is now something we must recognize as an area of competition.  This encompases everything from load-time to advertising.

The rise of apps, platforms, and walled gardens: Facebook Instant Articles is here. Apple News is coming. Flipboard is still out there. Ad blocking is coming to iOS9. A mobile web page on a news site still can take 10 to 30 seconds to load over 4G.
### Participants

We can scale to meet larger set of participants.

From past experience at MozFest we can easily accommodate a full blown discussion of 50 people or a more hands on and practical approach with 5.
### Outcome

Shine a spotlight on site user-experience as a competing factor. Business rules (ad inventory, invasive placement, 3rd party tracking) is easy to quantify in terms of revenue. It has always been difficult to argue the damage to user-experience and user trust.

This sounds the alarm that you're now competing with Facebook and not just relying on them for traffic.

You're either syndicating your content now, or you're providing an exceptional experience.

**Comment by cubicgarden** [comment]
Interested in this one @cubicgarden

**Comment by ryanpitts** [comment]
Hi @cubicgarden -- we definitely want to bring this session to MozFest. Is it OK with you if we accept and assign the milestone to Journalism?

**Comment by ryanpitts** [comment]
Repinging -- @cubicgarden we'd like to accept this into the Journalism track, but if you've already accepted it, we'd also be happy to send attendees that way.

**Comment by cubicgarden** [comment]
Yes @ryanpitts changed

**Comment by ryanpitts** [comment]
Great, thank you!

Also making a note here so I don't forget -- heard from the facilitators and this not needs to _not_ be scheduled for late Sunday afternoon. One of them has a flight out that might conflict.

**Comment by ryanpitts** [comment]
Sending out an acceptance notice from Journalism for this session.
