### ISSUE TITLE
Making with Mozilla: Learning and Teaching

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#526]
**[ Google Spreadsheet Row Number ]** 480
**[ Facilitator ]** Gem Barrett, Ford-Mozilla Open Web Fellow, @gembarrett,
& Carole Caple
### Description

Learn how to craft an engaging lesson plan about digital and Web literacies while leveling up your own tech skills. This workshop is aimed at people who see the value in increasing web literacy, but who are not highly technical web users. These people would like to both improve their web literacy skills and learn how to improve the skills of others, particularly focusing on their friends and members of their family. Participants will learn skills both in basic coding techniques and standard teaching practices, thus enabling them to "level-up" their tech skills and showing them how to teach others in varying age groups. They will learn how to prepare and implement a lesson plan, taking into account factors such as the age group and technical ability of the learners, common coding exercises (such as printing “Hello world” to the screen and error console) and techniques such as keeping learners engaged.

**Comment by amirad** [comment]
cc @amirad

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Melechuga** [comment]
Hi @chadsansing @amirad Gem hasn't heard about this session; can you please get in touch with her when you can? Thanks!

**Comment by amirad** [comment]
Looks like it's @chadsansing's pathway but he removed his label. Might want to ask @BekkaKahn if this session is approved for their space?

**Comment by chadsansing** [comment]
@Melechuga, @amirad, @BekkaKahn  - thought this went to Online Learning Done F2F - correct?

**Comment by BekkaKahn** [comment]
Sorry @amirad  and @chadsansing - I tagged it as an intersection with our pathway, as I thought it had already been accepted. I don't think we have space for her in our pathway - should I get in touch with her?

**Comment by chadsansing** [comment]
@BekkaKahn - hold off just a bit; I think we can host this and will check.

**Comment by chadsansing** [comment]
Got it - we'll host. Thanks, all. Emailing Gem now.

@BekkaKahn, @Melechuga

**Comment by BekkaKahn** [comment]
Fantastic, thanks, @chadsansing
