### ISSUE TITLE
Disassembling the world's worst data wrapper: PDFs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#527]
**[ Google Spreadsheet Row Number ]** 481
**[ Facilitator ]** Ted Han
### Description

Introduce and demonstrate pdf processing tools and toolkits, including Tabula, DocumentCloud's docsplit, and other common pdf processing tools.  Participants should depart the session with an understanding of how to extract basic components from PDFs.
### Agenda

In a workshop setting, provide participants with a variety of PDF processing tools, and demonstrate a variety of basic workflows which could at a later date be repurposed or extended for participants needs (extracting text, tables, images, and so on).
### Participants

Demonstration of these tools should be reasonably scalable, especially if with co-facilitators.  If the group ends up being smaller, going over specific document sets becomes viable.
### Outcome

As part of the prepwork going into putting the session together, cheatsheet of common PDF processing tools & workflows.

Our goal is to arm participants with the knowledge they need to build their own PDF processing pipelines (or to employ existing tools like Tabula, etc).

**Comment by ryanpitts** [comment]
cc @acabunoc 

This would be a potential crossover Science/Journalism session

**Comment by mtigas** [comment]
:wave: (just stopping in, I think I'm technically a co-facilitator on this)

**Comment by ryanpitts** [comment]
Woo! Another one for the joint pathway between Science and Journalism called "Tools & Analysis."

**Comment by ryanpitts** [comment]
Sounds like it's possible that Manuel Aristarán will join for this one as well!
