### ISSUE TITLE
What we learned at Vox Media about how we build community and why it's important

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#529]
**[ Google Spreadsheet Row Number ]** 483
**[ Facilitator ]** Trei Brundrett
### Description

We will share lessons learned in building Vox Media's large communities, specifically SB Nation and The Verge. Folks will learn technology, design and community strategies that worked and some that failed. 
### Agenda

This will be a fireside chat with two of the principal architects of Chorus, a platform for launching and building media brands with a major focus on community. We will talk about our platform, our communities, our lessons learned.
### Participants

With any number of folks we'll talk, then we'll take questions and hopefully spark a conversation where others can share similar lessons.
### Outcome

Our ideal outcome would be that more folks understand a new way of thinking about community (beyond just comments), that they are inspired to build community and that we all learn how it can be done on the open web.

**Comment by ryanpitts** [comment]
As a Knight-Mozilla fellowship partner, Trei will for sure be traveling to London and attending MozFest.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin lessons learned building community, on the open web.

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Building Online Communities" pathway.
