### ISSUE TITLE
Mozilla Brick 101

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#53]
**[ Google Spreadsheet Row Number ]** 5
**[ Facilitator ]** Yash Shah
### Description
- A quick introduction to Mozilla Brick Project.
- How to make Complex Web applications in matter of few days using Brick.
- A short Demo of the web application I've made from Ground up & design process.
- Live coding of a sample web app ( like mini whatsapp ! ) using Mozilla Brick.
### Agenda

Most of the time, making web application takes time span of months because developers usually start making it all on their on from scratch. Mozilla Brick is awesome library which makes for developers very easy to make web apps on matter of just few days rather than months. Most of the components are readily available to use. This session would be kind of workshop session, which would definitely help budding developers to make them feel learned something out of it, and more confident using Mozilla Brick to make web apps.
### Participants

~ It'll all be the same provided enough seats and room space. Though I'd need projector to make them learn. 
### Outcome

I'll publish my source code to public repository on github. I'll also have a recorded video in case someone is having doubts to refer in future. I'll share my profile in case anyone wants a help to understand or for anything in future.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
