### ISSUE TITLE
Online Activism AMA

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#530]
**[ Google Spreadsheet Row Number ]** 484
**[ Facilitator ]** Gem Barrett
### Description

This session will allow people to directly learn from people who use technology and the web for activism work. Participants will have the chance to ask about online activism methods and techniques in order to add their voices to the huge numbers of people getting involved in activism and social justice online. Suggested topics include methods for leveraging social media to promote your cause, building an engaged audience and handling legal and media requests. Participating activists will also have the opportunity to discuss with each other ways in which various social justice groups can work together, techniques for online promotion and security and common tooling/standards.
### Agenda

This session will require about 90 minutes and is dependent on around 5 activists agreeing to take part. This session will be set up in a one-to-one ask-me-anything format, whereby a selection of activists from across a range of causes will sit on one side of a row of tables. Some activists may take part via video-conferencing (equipment will be sourced for this). Participants will sit opposite the activist and have up to 5 minutes in which to discuss online activism and using technology for social justice. I aim to have activists involved from a variety of online activism areas and I anticipate that the ask-me-anything format would not be suitable for longer than 30 minutes. A further hour will be allowed for the activists to have a discussion in a “fireside chat” style around how they use the web to work in the social justice and activism arena.
### Participants

If there are 5 participants then the ask-me-anything format will be shortened to 15 minutes and the remaining time will be dedicated to the “fireside chat” session for the activists to discuss common tooling and methods of working together. 

If there are around 15 participants then 30 minutes will be given to this portion of the session and the remaining hour will be in the style of a “fireside chat”. If more than 25 participants are interested in the session then, depending on the agreement of the activists, the ask-me-anything portion can be extended to 45 minutes and participants will be encouraged to limit their chosen activists to allow others to also take part in this session. The remaining time will be a “fireside chat” and audience members who did not get an opportunity to ask their question earlier will be encouraged to pose questions in this part.
### Outcome

Participants will be encouraged to post about the session on social media and engage with the various movements. Activists from other growing movements may attend as participants and the primary outcome that I see for this session is that more people will have the knowledge and confidence to engage with and grow social justice movements online. A strategy should also evolve from this session on ways to encourage others to get involved with causes they care about, and spread the word. A secondary outcome is that the activists will learn from each other’s online work and find way in which they can work together to better coordinate grassroots campaigns online and build their collective knowledge of technology-based tools for promoting and growing their movements.

**Comment by Melechuga** [comment]
Open Web Fellow - travel covered by Fellowship.

**Comment by Melechuga** [comment]
Feels similar to "Communities at Scale" https://github.com/mozilla/mozfest-program/issues/210. We could see if Gem could facilitate with Sara...? @shaghdoosti

**Comment by Melechuga** [comment]
Melissa will contact.
