### ISSUE TITLE
Open Business Models - Non-Profits need one too

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#531]
**[ Google Spreadsheet Row Number ]** 485
**[ Facilitator ]** Kelsey Wiens
### Description

Design your Open Business Model Canvas. Creative Commons just raised enough money to build a book on Open Business Model Case Studies. Thinking through your 'business proposition' is essential for all organizations. Join us to help show off your best case study and to build your own. 
### Agenda

Using the CC Open Business Model Canvas as a framework to discuss the major components of each -  What are current global examples of successful open business models and working through case studies and finally working on your very own Open Business Model Canvas to take home and share with your organization. 
### Participants

The canvas is worked though in small teams so can be done with 5 people or with 150.  A larger group would mean breaking people up into manageable groups to work through the case studies. 
### Outcome

Working through questions including ￼Key Partners, Key Activities, Key Resources and social good is a essential exercise in business and is often overlooked in not-for-profit but essential. I think it's valuable to have an Open Business Model Canvas to take home on put on their wall and remember those key elements. The CC Open Business Model team can also work with anyone interested in pursuing further work. The canvas' would also be used to provide insight for  CC Open Business Model book being launched in 2016.

**Comment by thornet** [comment]
cc @BekkaKahn -- perhaps framing as open business models for local learning?

**Comment by Saallen** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015- Hope you will submit another session for 2016
