### ISSUE TITLE
Localization Sprint for Circumvention and Encryption Tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#534]
**[ Google Spreadsheet Row Number ]** 488
**[ Facilitator ]** Dragana Kaurin
### Description

Everyone deserves the right to privacy and freedom from censorship. We have a number of tools available to English speakers, and because they're only in English these circumvention and encryption tools are not available to most of the world. Most concerning is that they are not available in languages spoken in the corners of the world that exercise strict media censorship and surveillance of communications. Localization Lab runs sprints that allow everyone to participate to translate these tools and make them available for their own communities, in their own languages. Every year I've been to Mozfest the crowd seems to be getting bigger and more diverse, this year is the perfect opportunity to engage the community in localizing internet freedom tools   
### Agenda

When folks walk in we hand them a pamphlet on which tools we support so they can work on the tools that meet their needs, and also describes how to set up an account and pick languages. 

If they don't have a Transifex account, we'll spend a moment setting up an account and giving a short tour of the Localization Lab Transifex hub. 

If we only have 5 participants (which is unlikely, l10n is very popular in the community because people dont have to be developers to contribute) we'll sit at one table together to work on the translations and socialize-- This is usually a good time for people to open up about questions they may have about security and circumventing censorship. 

If we have 15 or 50 participants, we will separate into language groups as that usually helps groups support one another and create a shared dictionary. 
### Participants

If Mozfest is held at Ravensbourne again it would be amazing to have a room or a corner for half a day or preferably one whole day where we can work and do trainings. We would need tables and outlets. If possible we would like to host the sprint on the second day so that we have a chance to make announcements and put up posters about the localization sprint and asking to bring their laptop. We also have a few spare laptops for use. 

Like I stated about we have a system of how to work the sprints with different numbers of participants and also levels of digital security and literacy. We'll use one large table if it's a smaller group and split off by languages if we have groups larger than 15.
### Outcome

Our goals for this sprint are:
*To expand the knowledge and understanding of an array of privacy and circumvention tools
*To finish up a number of translations
*To bring new people into the localization community and spread our message. 

We have a very active community online that will support the work at Mozfest. We would love to work on Thunderbird and Firefox because of how important they are to privacy community, they are often requested. 

We want people to feel good leaving the session, feeling that they contributed to the internet freedom sphere, and leave wanting to continue engaging the online community.

**Comment by Melechuga** [comment]
cc @hjbailey

**Comment by Melechuga** [comment]
Hi @hjbailey! Just wondering if you've accepted this session; I see it fits in the Backdoors + Cryptowars pathway, and am wondering if we need to reach out to Dragana. Thanks!

**Comment by hjbailey** [comment]
HI I haven’t I was going to raise this in the 1:1 today - I want to understand this a bit more. Can we chat on Skype?

**Comment by Melechuga** [comment]
@hjbailey Sure. I'm melissamegumi. Ping whenever.

**Comment by hjbailey** [comment]
@Saallen @marcwalsh @Melechuga  This is not going to be in Localization - Melissa please pick it up if you feel this will fit with you.

**Comment by Melechuga** [comment]
Thanks for letting me know @hjbailey ! 
I don't think we'll pick it up this year.

**Comment by hjbailey** [comment]
@marcwalsh @Saallen  I am closing this issue
