### ISSUE TITLE
An Open IoT Stack for Schools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#535]
**[ Google Spreadsheet Row Number ]** 489
**[ Facilitator ]** Brian Fuchs
### Description

In our session, we will build an IoT stack for schools. 

The Internet of Things provides a fantastic opportunity for school children to acquire STEM skills while learning more about their immediate environment as well. 

But there are a lot of IoT tools out there—so many, in fact, that it’s hard to know where to start. 

In this workshop we will look at how to assemble an IoT stack for schools. This includes everything from hardware, and calibration, to data aggregation and coding tools. 

The idea of this workshop is to share our knowledge with one another about tools and especially about gaps in the tool chain, from the point of view of parents, teachers and students. Participants will get hands-on experience of an IoT stack, with hardware provided by us. The goal will be to come up with a wish-list and suggestions about how Mozilla Science can help. 
### Agenda

The workshop will be part brainstorming, part hack.

We'll start with a presentation of a simple IoT stack / tool chain that we have been using for some of our ScienceMakers projects and Hacks. We’ll be bringing some Arduino boards and sensors along with us for you to try out but you’re encouraged to bring your own. 

Then we’ll dive into a group brainstorm session where we share experiences and work on our list of IoT tools and resources. We'll encourage participants to team up on a hack of their own, or simply help us add to the wish list of missing tools, resources and platforms

We’ll be doing some posts on the workshop in the run up to Mozfest, so check here for updates: http://mobilecollective.co.uk
### Participants

The more the merrier, but if we're a small group, we'll work on one hack together, and together compile one wish list. If we’re larger, and we have participants with kit, we’ll focus on demoing and try to share as many IoT stacks as possible. 
### Outcome

First, there’s the Wish list. We’ll share this with the Mozilla Science community as Community Project in the Forums, as well as on a live Wiki for the workshop & the ScienceMakers and Mobile Collective websites. 

Secondly, there’s the summary of the Open IoT Stack for Schools, which we’ll also share, and propose further curriculum development around on the Mozilla Science community Etherpad.

And thirdly, where we identify gaps and nice-to-haves  in the stack, we’ll propose a Code Sprint on the Etherpad for the next Global Science and/or a Collaborative Software Project for the Science Lab community.

With any luck, we'll be able to start working on something together during the workshop itself.

**Comment by Zebetus** [comment]
@EPIKhub this could be a good one to get kids involved and could be a good introduction to some sciencey techy stuff

**Comment by marcwalsh-zz** [comment]
cc @cubicgarden
