### ISSUE TITLE
Craft - Bridging your digital divide

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#536]
**[ Google Spreadsheet Row Number ]** 490
**[ Facilitator ]** Marie Flies Pathway leader w/
### Description

This is a roiling session in the craft area of the youthZone, the aim is to help parents explore how crafting is aligned to making as a concept and thus extendable into the digital, from paper crafting to friendship bracelet making. 
### Agenda

Stage 1:The session will use off the shelf craft books to create lollipop figures, the materials used will be similar than what is asked for in the book but not identical, so parents and children can explore the "How and What" else you can do. Stage 2 will be to add some basic electronic LED's, resistor, voice recording board and power source.
Stage 3: Re-use the electronics components to create a holiday card at home
### Participants

Organised by the #YouthZone
### Outcome

The objective of the session is to help people find common ground by being reminded about the process of making with crafts and then modding it to include that which that might to them be uncommon media's - electronics

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
