### ISSUE TITLE
Music - 50% of software engineers are instrumentalist.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#537]
**[ Google Spreadsheet Row Number ]** 491
**[ Facilitator ]** Luke Mayell - Musician
### Description

This is a rolling session for youths that explores the link between youth instrumentalist (players of a musical instrument) as a pathway into engineering and tech support roles through developing a passion for all things music technology and as an instrumentalist.
### Agenda

Youths will be encouraged to bring their own musical instruments to play with at the festival within the YouthZone and the session area will be augmented with experiences with Sonic Pi, Bo the robot who can be taught to play the Xylophone with code as an experience aimed at our youth musicians. 
### Participants

Rolling drop in session at the #YouthZone
### Outcome

Each young person taking part will be given a short questionnaire pre and post session to measure impact and we hope will have gained a better understanding of how what they love is aligned to engineering through STEAM.

**Comment by EPIKhub** [comment]
youthZone

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
