### ISSUE TITLE
Arts Award - Individual Pathway creator in schools and youth centres

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#538]
**[ Google Spreadsheet Row Number ]** 492
**[ Facilitator ]** Julie neville
### Description

Arts Award is managed by Trinity College London in association with Arts Council England.  It is an evidenced based qualification which provides a framework for schools, arts, cultural and youth sector organisations.  It supports young people to gain creativity and leadership skills. The focus is on iteration as a process post project to help teach young people how to create a project independently from inception to creation in any media they may wish to express themselves in aged 0-25.  Arts Award is offered at five levels, four qualifications and an introductory award
### Agenda

For MozFest 2015, we would like to propose a functional role for Arts Award where we use the Discover and Bronze award frameworks to help young people in the #youthZone explore the wider festival and return to report back  and share their experience with others
### Participants

This is a task oriented session to go out, explore, report back and share
### Outcome

The main objective, having taken part in the Discover or Bronze award within the youthZone, is that those who have had this initial experience might well feel more comfortable at other festivals to independently, iterate the process to go out, explore, report back and share

**Comment by EPIKhub** [comment]
youthZone

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin - would like to create a youth experience 'teaching partcipation' intersection for this in Participation.

**Comment by EPIKhub** [comment]
@emmairwin @geroter we will definitely add participation to one of the Arts Award option they can go and take part in. Tad is going to look at this I understand, linking from us to you and back again?
