### ISSUE TITLE
FlyWeb

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#539]
**[ Google Spreadsheet Row Number ]** 493
**[ Facilitator ]** Nicole Yee
### Description

The goal of the FlyWeb session is to promote, intrigue, and encourage feedback from attendees. We want to be able to engage users by showcasing our Fennec addon prototype and let their imagination do the rest because at the end of the day, FlyWeb has unlimited possibilities. We will also have tutorial materials and a full demo to showcase some popular use cases. We want to walk our attendees through the concept of advertising and consuming nearby services
on their phone. Lastly, we want our attendees to have the opportunity to see what we have been working on first hand and play with our prototype.
### Agenda
1. Introduce web developers to Fly Web, an API and platform to let  webpages and smartphone apps expose discoverable HTTP-based services,  and to let nearby smartphones (or webpages loaded onto smartphones)  discover and connect to them. 
2. Walk audience members through an example of creating a basic Fly Web  "hello world" application which lets a webpage on one phone provide a  service to a webpage on a nearby phone. 
3. Solicit feedback from audience members on three topics: a) The  concept and whether it made sense and whether they see potential in it.   b) If the API easy to interact with and understand, and whether they  could think of how to build larger-scale applications using it.  c) Any  new and interesting use cases or ideas they could come up with. 
### Participants

If we had 5 participants, we would host a more intimate workshop. We will gauge the understanding of our audience and adjust accordingly. Same will go for 15 and 50 participants But instead of an intimate workshop, we will aim for a more structured workshop encouraging hand raising, suggestions, and open feedback.
### Outcome

Mozfest is a great outlet for us to showcase FlyWeb to the general public because of diverse attendees. After the showcase, we hope to gain feedback on how FlyWeb resonates with the attendees. From the general attendees, we hope to gain an understanding of how well the idea reasonates and how accessible it is, and whether people are in general comfortable with the notion of advertising and consuming nearby services on their phones.  We also hope to elicit use case ideas and potential applications we had not thought of. From software hacker attendees, we hope to gain an understanding of how easy the API is to use, whether it makes sense, and whether people are able to get up and going with it quickly.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin Scaling participatory experiences perhaps, or New technologies for participation -- challenge

**Comment by emmairwin** [comment]
cc/ @Saallen @marcwalsh

**Comment by thornet** [comment]
cc @ileddigital as well

**Comment by emmairwin** [comment]
Late addition to our technology track
