### ISSUE TITLE
Switched On(line) Lighting

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#54]
**[ Google Spreadsheet Row Number ]** 7
**[ Facilitator ]** Evan Raskob
### Description

A diverse group of artists/industry practitioners will come together to develop a web-based interactive lighting system.

A collaboration between Ravensbourne's Design & Coding and Product Design courses and Goldsmith's Creative Computing Department to develop a workshop on interactive lighting/gaming/web-based/physical computing, a hack session to show the tool-kit developed in order to invite students/industry to hack them. The project aims to develop 3D printed lights to install around the building which would be networked through the web.
### Agenda

We will provide a codebase (via gihub) and some 3D printing facilities and initial designs and use our student helpers and staff to teach people the basics of our open source system (and tech) and then facilitate building new and innovative lighting systems controlled through the web.
### Participants

We will have plenty of students and staff on hand and, as educators, are used to teaching different group sizes.  We would work more closely with smaller groups, but for larger sizes would split out different tasks (brainstorming, sketching, programming, 3D modeling) into different responsible groups.
### Outcome

Our results (code, diagrams, plans) would be placed online and made open source, and even find their way into the curriculum of our universities and into course blogs and other promotional outlets.

**Comment by EPIKhub** [comment]
@Saallen @thornet @amirad @msaunby think this would be good for the garden and home pathway, it has a lot of synergy there.

**Comment by Saallen** [comment]
cc @cubicgarden
