### ISSUE TITLE
IoT is too important for big IT

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#540]
**[ Google Spreadsheet Row Number ]** 494
**[ Facilitator ]** Julian Tait
### Description

Inspired by the Things Network in Amsterdam, this session looks at crowd sourcing a free, open and distributed Internet of Things infrastructure for the benefit of everyone. The session looks at how using off the shelf Long Range Wide Area Network (LoRaWAN) components we can build city-wide IoT infrastructure that is community owned.
### Agenda

This is a workshop for people interesting in implementing an IoT network for and with their communities. It maps out the reasoning and challenges to implementation, and understanding the technology. We want people to input their experience, ideas and expertise.
### Participants

The session will run as intros and context setting. Then will break into smaller groups looking at what could be done with a community network, strategies for creating a network in our communities, and implementation. The discussions will be brought together at the end. This format should accommodate varying participant numbers
### Outcome

1) It is hoped that people will be inspired to develop an IoT infrastructure in their own communities.2) People will realise that IoT isn't a corporate vendor driven solution but one in which communities can create for themselves3) Build a network of community IoT expertise

**Comment by thornet** [comment]
cc @cubicgarden for potential interest

**Comment by cubicgarden** [comment]
This isn't happening sorry due to travel
