### ISSUE TITLE
Jupyter notebooks and Python data analysis

### ISSUE THREAD

**Issue by abbycabs** [mozilla/mozfest-program#543]
**[ Facilitator ]** Thomas Kluyver
### Description

Participants should come away with the knowledge and software tools to load data, process and visualise it, using Python, pandas and matplotlib, and to share Jupyter notebook files online.
### Agenda

We'll help people install Anaconda, a Python distribution including all of these tools. Depending on the participants' experience, we'll familiarise people with the Python programming language, then do some demos and exercises using pandas and matplotlib to work with data. Finally, we'll look at the notebook files the participants have created, and how to use nbviewer and nbconvert to share them.
### Participants

With fewer people, this session could be more tailored to their specific situations, for instance to focus on the kind of data they work with, and more interactive. With a larger group, this could be more of a 'classroom' type activity, alternating demonstrations with exercises.
### Outcome

Participants should be comfortable writing code to analyse their data, and on board with the idea of sharing their analysis methods, not just the results. We will highlight resources for further learning and ways to get support with problems.

**Comment by abbycabs** [comment]
flagging @ryanpitts -- good crossover session

**Comment by ryanpitts** [comment]
Yes, thank you!

**Comment by kaythaney** [comment]
possible to add a "training" tag? or is that getting too far into the details? :smile:

**Comment by ryanpitts** [comment]
Woo! Another one for the joint pathway between Science and Journalism called "Tools & Analysis."
