### ISSUE TITLE
Juke Mozilla

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#55]
**[ Google Spreadsheet Row Number ]** 11
**[ Facilitator ]** Sandeep kapalawai
### Description

"Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.Where words fail, music speaks. " this quote impacts me to propose a session .Most of us like Music . Keeping the point of view and to attract participants for Mozfest i prepared a plan to MozJukebox- its a place where participants can dedicate their special songs to their beloved ones and this session makes different from others and as well as participant's will learn how open web and music related to each other and by the way the can perform their own activity . we are here to make them aware of this.
### Agenda

After a brief introduction on the topic (including a few demos), participants will split up into smaller groups to create mash ups or original compositions, using the concepts and code samples from the topic introduction. My agenda goes here :
1)Introduce them about Open web
2)How music Impacts you
3)Juke box round
4)Role by participants
### Participants

Session'd be prepared in a way that'd not make a difference whether it'd be attended by 5 or 50 people. 
First my session goes with brief intro if it counts with 50 we can go or else my team will divide and start their session.
Later on we present themes in which participant is interested get into that ,each team consist of 10 members.
### Outcome

Participants learning a new skill that may influence further creative exploration on a individual level or provide an instructional foundation to pass the skills on to other interested parties. Again, for those participants who work with people, especially youth that have interest in music (performance/recording/production) Ultimately, this session may produce or influence the next one hit wonder!.Hope this session brings something new ever happens.Lastly participants will be satisfied with this session

**Comment by thornet** [comment]
Unfortunately, this session was not selected for the Mozfest program this year.
