### ISSUE TITLE
Learning & Leading Digital Literacy Focus Group

### ISSUE THREAD

**Issue by chadsansing** [mozilla/mozfest-program#551]
**[ Google Spreadsheet Row Number ]** Added by @chadsansing to issues.
**[ Facilitator ]** An-Me Chung
### Description

The Mozilla web literacy map is being refactored to include 21st Century skills needed for leadership development, and written in a language more approachable and accessible to diverse audiences.  We invite anyone interested in teaching web literacy skills to provide us with your insights and creative input on a draft 2.0 content and design, and  help us determine what curriculum and tools are needed to make the digital-age skills more relevant to more people. Come spend a few minutes with us moving around pieces of the map, and sharing stories of how you would use the map.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin possible education session on a pathway to Designing Learning Experiences Through Participation for our community leaders, by providing greater insight into possible tie-ins with web literacy.  Also has Leadership element.

**Comment by anmechung** [comment]
[ Facilitator ] An-Me Chung, Iris Bond Gill, Ian O'Bryne

Description: This Learning & Leading Digital Literacy Focus Group invites in and out of school educators, mentor participants, and anyone else interested in teaching web literacy skills to share their needs and wants for Web Literacy materials, resources, and teaching tools.  Hearing from a diverse community, will inform our refactoring of the  Web Literacy Map 2.0 including 21st Century Skills for leadership development.

Agenda
Participants will have an opportunity to reflect on a draft 2.0 web literacy map, provide a Blue Sky version that includes thinking on 21st Century Skills, and create profiles of potential users and how to make the map more approachable and accessible for learning and teaching web literacy skills.

Participants
Anyone interested in teaching and learning web literacy skills

Placeholder
Outcome
Engage a more diverse group of people in informing a more approachable and accessible web literacy map.

**Comment by chadsansing** [comment]
@anmechung - thank you! Updated.

**Comment by LindseyFrost** [comment]
@chadsansing @anmechung Do we still want something separate in the Hub space? Ongoing Web Lit Feedback station? If so, I will add separate issue.

**Comment by anmechung** [comment]
yes to something separate in the Hub space @Saallen is aware.  @sabrinang has already created as a separate issue (#1305).  Should we add as a separate issue that is part of the Mozfest-program repo in the MLN space milestone?

**Comment by chadsansing** [comment]
@LindseyFrost, @anmechung - sounds right - thank you both!

**Comment by anmechung** [comment]
@chadsansing @LindseyFrost @sabrinang - to close the loop on this that we did via email, we will have one large space in the Hub space (big wall space or 3 white boards) as the ongoing web lit feedback station.  We will also use this same space for facilitated Web Lit focus group workshop that is part of the learning and leaders pathway.

**Comment by LindseyFrost** [comment]
@samueledyson this is the web lit focus group in the hub space
