### ISSUE TITLE
The reality of diversity: The working dead

### ISSUE THREAD

**Issue by cubicgarden** [mozilla/mozfest-program#554]
[ Facilitator ] Melanie Grant, Leena Haque; Samina Rafiq 
Length: 1hour
# Description

Let’s attract your inner Zombie (Yes, we are using the Z-word)…
Set in a world overrun by the undead, you get to choose which characters can best face the apocalypse and survive, using only what nature and circumstance has given them.
# Agenda

Be Vigilant.  The horde can strike at any time.  When your location is compromised find a new shelter and avoid dark or confined spaces. Discuss with your group which Characters you will choose in order to maximize the potential for survival. What skills and talents will your team have? Who are they and what makes them so special that they will succeed where the rest of humanity has failed…
# Participants

The workshop can work for a maximum of 25-30 people and will revolve around open and honest discussion and challenge, both in individual teams and wider group observation. Be prepared to make difficult decisions and work to understand other perspectives. Open your minds….
# Outcome

Consider your own and others preconceptions and may be think twice before judging someone.

**Comment by emmairwin** [comment]
@cubicgarden again, there might be an intersection here for Participation but need to know more. t hanks!

cc/ @emmairwin @geroter possible for Designing Learning Experiences Through Particpiation
