### ISSUE TITLE
The web through the eyes of a dyslexic  

### ISSUE THREAD

**Issue by cubicgarden** [mozilla/mozfest-program#555]
Facilitator: 
Roger Broadbent, Manchester and Salford Dyslexia Services.
# Aim:

To explore the challenges and opportunities in encouraging digital and web inclusion in the dyslexic population. This is to be done through collaborative learning and solution finding.
# Objectives:

To understand what is dyslexia and its causes. Then to discuss how education and specifically IT and web inclusion is problematic for dyslexics.
To highlight the benefits of greater IT and web inclusion for dyslexic individuals.
To discuss how greater IT and web inclusion can be brought about, by working together with Mozilla.
To make a plan as to how these ideas can be implemented.
# Agenda
- To introduce the sessions’ aims and objectives, showing the time frame for each section.
- The showing of a short film interview documentary of dyslexics explaining their own experiences.
- Q & A session to determine what dyslexia is, and what are its causes.
- Pair work or group work (PW/GW) depending on the number of participants (more or less than 10). Exploring why dyslexics sometimes struggle with education, specifically IT skills and web inclusion.
- PW/GW highlighting the benefits of greater web and IT accessibility and inclusion could impact on dyslexic people.
- PW/GW to discuss how greater IT and web inclusion can be brought about by working in collaboration with Mozilla.
- As a group, draw up a timetabled plan of action as to how these ideas can be brought to fruition and implemented. The session would hope to come up with at least one idea that would be then developed and implemented. This would then form a part of the Manchester and Salford Dyslexia Service’s targets to help the region become a centre of excellence for dyslexia: helping dyslexic individuals achieve their full potential.
# Participants

Depending on the number of participants the activities used will be flexible. Also the sessions will show flexibility to accommodate the participants’ opinions at the time. The participants will decide what actions will be taken following the collaboration.
# Outcomes

Aim being to enhance the IT/web inclusivity of the dyslexic community.

**Comment by EPIKhub** [comment]
@cubicgarden Id be personally interested in this one when there is more details :) do you also have links with any Autism group?

**Comment by emmairwin** [comment]
@cubicgarden can you say more on this workshop, would love to think about Participation and diversity intersection, especially around providing learning resources that enable all abilities.

**Comment by cubicgarden** [comment]
Sorry guys, once I get more information I will update the issue.

**Comment by cubicgarden** [comment]
@EPIKhub We have another workshop which we are hoping to have given by someone with Autism #554

**Comment by EPIKhub** [comment]
@cubicgarden IF this is a session you are accepting please don't close it, all sessions that are closed are considered as rejected by the team so it will be confusing if you do :)

**Comment by cubicgarden** [comment]
Oh whoops! Will change them all when out of the hospital
On 8 Oct 2015 12:07 pm, Dorine Flies notifications@github.com wrote:@cubicgarden IF this is a session you are accepting please don't close it, all sessions that are closed are considered as rejected by the team so it will be confusing if you do :)
