### ISSUE TITLE
Creating adaptive storytelling content for the future of radio

### ISSUE THREAD

**Issue by cubicgarden** [mozilla/mozfest-program#559]
Facilitator: Adrian Gradinar, Dan Burnett, and Paul Coulton.
Type of experience: Workshop
Duration: 2hrs
# Introduction

The workshop will introduce participants to the concept of perceptive media and the creation of adaptive storytelling content.
# Agenda

To allow for the varying skills of the participants we will have two strands of activity to the workshop. The first will explore the capabilities of the Perceptive Media API and how adaptive stories can be created using the new Perceptive Radio as a platform. The second strand will use paper based story creation tools to allow participants to develop adaptive storytelling ideas that could be developed for the Perceptive Radio - 
http://www.bbc.co.uk/news/technology-22637945
# Participants

Maximum of 15
# Outcome

We will use participant feedback to adapt the current perceptive media API and feed their experience into the forthcoming creation of an interface to make the API easy to use

**Comment by emmairwin** [comment]
@cubicgarden is there a technology/hacking element to this?  Wondering.

cc/ @geroter @emmairwin

**Comment by cubicgarden** [comment]
There certainly could be if you want there to be, as the radio design and
hardware will be on GitHub by then, along with the code

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone, likely most appropriate for Bronze participants
