### ISSUE TITLE
Intelligent Web Things

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#56]
**[ Google Spreadsheet Row Number ]** 8
**[ Facilitator ]** Patrick  McGee
### Description

The session is built upon the idea of turning ordinary objects into connected web aware devices. The participants of this workshop will learn how the Web of Things might be used to provide a standardised approach for connecting objects to the web.  

The participants will choose an object and then apply 'Web of Things' thinking to make the object become a Web Thing (WT).

A Web Thing (WT) is an intelligent sensor (or sensor array) that can recognise an event, understand its own state and take action depending on the input. 

Through active participation the people can learn about the Web of Things in new and fun ways.
### Agenda

The agenda starts before the session where posters will be placed around the building. The posters will have two questions. If you wanted to give an object intelligence what would it be and why? 
These posters will be left all weekend to capture peoples thoughts and ideas.
Helpers will direct people to the posters and introduce the idea of the session so that as many people are aware of the session.
Resources will be created and placed on the walls and staircases for people to jot down their ideas and thoughts before or after the actual session. 
The actual session consists of a quick introduction of how to use the resources then the facilitator will assist the people to get the most out of the session.  Addressing any issues that are raised.
### Participants

As the participants use a resource to work through their ideas to convert their objects into Web Things. The whole session can be scaled up quite easily, allowing people complete freedom to work as teams or as individuals. 

The resource has been designed  to be used collaboratively and is being tested at other workshops ahead of Mozfest to refine and test it's use.
### Outcome

The main outcome for the session is to make people aware of the Web of Things thread. To demonstrate how easy it is to get involved and to make Web Things. Finally to show how to create simple plans which can be given to 'makers' to build the Web Thing they designed.

The best three ideas will be created by 'makers' after the festival and will be used at shows and events after Mozfest.

The main outcome for the organiser is to provide vital information for building new Computer Science lessons and workshops for the Web of Things thread.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
Once cc youth too

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by thornet** [comment]
Unfortunately this session was not selected for the program this year.
