### ISSUE TITLE
Data is beautiful. What’s Wikidata and why does it matter to me?

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#560]
[ Facilitators ] Nicole Ebber, Wikimedia Germany

Wikidata is a free linked database that can be read and edited by both
humans and machines, in an attempt to store data about the sum of all
human knowledge in an accessible way.

Initially built to as a central storage for Wikimedia projects like
Wikipedia, it provides support beyond just Wikimedia projects.

Available under a free license, exported using standard formats, and
linkable to other open data sets on the Web of Data, Wikidata can serve
as building-block on the Open Web when it comes to Free Knowledge.

What will you build with a structured data repository of Free Knowledge?
Learn how to contribute to Wikidata and use it in your own projects in
our workshop.
- Tell the developer community about Wikidata and find new friends for
  the Wikimedia movement
- Give technical documentation pointers to build new and exciting
  tools for Wikidata
- Ideas for using Wikidata content for your own project
- Open Data, open everything! How to use data as a building-block for
  a brighter future

Workshop Idea I: The The Hitchhiker's Guide to the Wikidata API
A technical workshop on Wikidata: Learn the nitty-gritty of using
Wikidata for your own projects, learn how to search and extract data
from the Free Knowledge Base that anyone can edit. We will guide you
through the MediaWiki API and teach you how to do complex searches
with SPARQL.

Workshop Idea II: Wikidata editathon
A Wikidata editing session: Everyone from Wikidata beginners to
superheroes is welcome. If you have never edited on Wikidata before
we'll give you an intro to get you started editing in no time. If you
are already an editor you'll be able to meet other editors to edit
together and talk about all things Wikidata.

**Comment by emmairwin** [comment]
cc/ @geroter  @emmairwin 

This could hook into new technologies for participation .  Note: Wikimedia Germany

**Comment by thornet** [comment]
cc @kaythaney re: open data

**Comment by thornet** [comment]
@acabunoc @kaythaney I added this session manually so let me know if you need the info of the facilitator to contact them.
