### ISSUE TITLE
Design Thinking for Participation 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#565]
### Mozilla Participation Team Workshop

This workshop will increase participants awareness of the possible, probable and desirable futures for Participation, and help them emerge with an attitude of 'prototyping in all we do', an appreciation of key forces influencing change, and goals for measurement. Human Centered Design will facilitate conversations on Participation in a way that innovates for the success of people in the community on goals they care about.

With this in mind the objectives of this workshop are:
- Ensure 'empathy for people' is 'built in' into the core of Participation design.
- Improve the capacity of project leaders and volunteers to imagine, assess and put into practice ideas that push their intiaitive forward through Participation.
- Encourage ideation, rapid prototyping and ‘early sharing’ of ideas across roles, and into volunteer communities for feedback.
-  Identify possible resources, activities and events in the broader organization where collaboration can be ongoing. (silo busting).
- Identify skills, knowledge and perspectives crucial to achieving the envisioned future.
- Encourage self-reflection and accountability of individual goals for Participation success. “Own what you do”.
- Help participants gain an awareness of possible, probable and desirable outcome for the 'big picture' of Participation
## How do you see this?

We have variations of this workshop that can plug into the audience who turns up (primary project owners, primarily volunteers, mix of both)

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin our workshop from whistler can be remixed for any audience interested in using design thinking for participation,

**Comment by thornet** [comment]
Is this session taking place? cc @emmairwin to update the schedule spreadsheet if so.

**Comment by thornet** [comment]
this session is not taking place.
