### ISSUE TITLE
Supercharge your Community

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#567]
#### Participation Team Workshop

This workshop falls under 'Building for Action and Impact' one of our identified building blocks for a [Participation Leadership Framework (v.1)](http://tiptoes.ca/wp-content/uploads/2015/08/2015-08-28_1244.png)

This fast-paced workshop helps community leaders gain empathy for their community, whether they are just starting to grow a contributor base, or evaluating successes and struggles of the existing. A series of activities will help participants define and co-create the first successful steps of a contributor pathway.

Participants will learn best practices for designing personas and pathways in their communities.

Participants will design their own Personas and Participation Pathways for their project/community.

Participants will share their findings, and collaborate on ideas with others in their group.

**Comment by emmairwin** [comment]
cc/  @geroter @emmairwin workshop we ran at open science leadership summit

**Comment by cubicgarden** [comment]
Could work in the library? @cubicgarden

**Comment by emmairwin** [comment]
closing for now, we may decide to run this but not 100% at the moment.
