### ISSUE TITLE
Building 'Desire Pathways' for Participation

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#568]
#### Participation Team Workshop

This workshop falls under 'Empowering Teams and People' one of our identified building blocks for a [Participation Leadership Framework (v.1)](http://tiptoes.ca/wp-content/uploads/2015/08/2015-08-28_1244.png)

This workshop will help existing and emerging leaders in the Mozilla community explore, identify and personalize the unique opportunity of their participation at Mozilla. Opportunities reflect the virtuous circle of participation which positively impacts goals of the project and individual.

This workshop will help project and initiative leads of any background of focus think more broadly about how participation can plug into the destination and desires of participation.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin workshop designed for FSA, but has broader scope to help both projects and volunteers consider pathways built to the goals of participants and not just projects.

**Comment by cubicgarden** [comment]
Sounds good, keeping an eye on this one @cubicgarden

**Comment by emmairwin** [comment]
We'll be experimenting with this as part of our coaching process, helping people create desire pathways between the three we have for Particiaption, and using this session to build on that for Mozilla pathways
