### ISSUE TITLE
Appmaker in a Box

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#57]
**[ Google Spreadsheet Row Number ]** 10
**[ Facilitator ]** kapalawai kapalawai
### Description

Appmaker and Webmaker currently require an Internet connection to work. On this session I will present the "Appmaker in a box" that allows the facilitator to create a self contained Appmaker workshop without the need for an internet connection. This is needed to teach on more poor or remote locations where internet access is not ubiquitous.
### Agenda

After this session people will know how to build and work with Appmaker in a box and thus be empowered to teach Appmaking with just a LAN.
### Participants

If I have few participants then it will get cozy and we'll basically talk our way into all topics. If I have lots of participants then it will be more like a presentation showing how it is done and then experimenting with it.
### Outcome

This empowers people to use Appmaker, and possibly Webmaker if I ever finish that one, without an internet connection. This will enlarge the venues and locations where we can teach and thus reach whole new demographic.

In emergent countries internet coverage is very flaky. There are areas where it is pretty good but move two blocks into a slum or poor region and there is no internet anymore. This project will allow us to go into the venues where we're needed the most and where we can affect the most important changes.

**Comment by Saallen** [comment]
cc youth learning

**Comment by thornet** [comment]
Unfortunately this session was not selected.
