### ISSUE TITLE
Visualizing Community Networks

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#570]
#### Participation Team Workshop

This activity is based on the popularized version of 'Six Degrees' called [Six Degrees of Kevin Bacon](https://en.wikipedia.org/wiki/Six_degrees_of_separation#Kevin_Bacon_game) and is meant to be a fast-paced fun and reflective opportunity to evaluate what our influence in enabling the change we need through our existing networks, but also as owners of change ourselves.
## Learning Outcomes
- Networks and Connections
- Reaching Decision Makers
- Everyone has the potential to successfully own or escalate community challanges

**Comment by emmairwin** [comment]
cc @geroter @emmairwin workshop to help combat 'I can't do this on my own, or someone else needs to move this forward, or I"m not staff'

**Comment by cubicgarden** [comment]
This could be great for the library and global village...

**Comment by cubicgarden** [comment]
Sorry I need a email address and owner to send a accepted email... @emmairwin ?

**Comment by emmairwin** [comment]
@cubicgarden this is one of our own sessions -  I am the owner :)

**Comment by cubicgarden** [comment]
Cool then I'll close it and we can talk later :+1:

**Comment by cubicgarden** [comment]
Any reason for the closure? Shall I take this off our list now?

**Comment by emmairwin** [comment]
@cubicgarden I saw that you removed your label   - and just juggling time figured we would take this off our plate.  Is it still on a pathway then?   Happy to revive.

**Comment by cubicgarden** [comment]
If I understand, we were going to put this in our schedule for Saturday
afternoon - in the garden but if we are closing it I can remove it?

**Comment by thornet** [comment]
Just confirmed with @cubicgarden and @emmairwin that this session will not take place to give folks more bandwidth. Hence, it being closed and removed.

**Comment by emmairwin** [comment]
Lets remove it.  Sorry I didn't realize there was still a dependency (was just looking at tags).  Thanks for follow up.
