### ISSUE TITLE
Diversity in the new economy

### ISSUE THREAD

**Issue by cubicgarden** [mozilla/mozfest-program#571]
Facilitator: Vimla Appadoo
Type of experience: Workshop and a discussion. 
Duration: 3 hours
# Introduction

I'm a huge advocate for women in tech, but I know that diversity in businesses and startups doesn't end there. I'm highly motivated to make a change to the status quo, to push barriers and make a positive change in the society we live in. As such, I think diversity is key to making a difference. I want to help show people how easy it is to be prejudice, but equally, how easy it is to overcome this and empower people to realise that we can make a change.
# Agenda

I want to run a 3 hour workshop. Each hour will be themed around a topic surrounding diversity (my initial thoughts are home, work and society). There will be discussions on these topics lead by myself and including the attendees. We will then ideate a real life solutions to the problems discussed. The idea being that these outcomes can be put onto an online platform and turned into a manifesto for positive change and diversity in each subject area.
# Participants

Smaller groups means there's a more intense discussion where I will lead people to really question their beliefs and thoughts on the topics at hands. This will really challenge their bias and prejudice.

A large group will be split up so that there's more than one discussion happening at once. This will be more focussed on the solutions, creating a larger and more detailed manifesto, with each group coming together at the end of each hour to narrow down their thoughts on diversity.
# Outcomes

After Mozfest, I want the outcomes and solutions ideated in the workshop to be the basis for a shareable manifest on how we can change society around us. I'd ideally create a community based around this manifesto, where we can regularly checkin on the progression of the solutions.

**Comment by ThatGirlVim** [comment]
Thanks Ian!

On Thu, Oct 8, 2015 at 3:18 PM, Ian Forrester notifications@github.com
wrote:

> Reopened #571 https://github.com/mozilla/mozfest-program/issues/571.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/571#event-430359034.

## 

Vimla Appadoo
Program Manager - Dotforge Impact

@ThatGirlVim
@dotforgeimpact
#DFImpact
