### ISSUE TITLE
How do communities come together?

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-program#572]
Facilitator: Sydette Harry, Coral Project

How are groups formed? How can the group document, recognize and ultimately work productively through various dynamics. Using Tuckman's theory of group psychology  as a basis, The Coral Project will workshop stages of group development and documentation. Participants will perform activities, learn basic group formation theory, and devise best practices for keeping records of projects, stories, and processes according to open standards.

**Comment by ryanpitts** [comment]
Journalism space is accepting this session, and adding to the "Building Online Communities" pathway.

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin  so this is focused on comments & journalism, but in all likelyood there are lessons here for managing forums, commenting communication in our communities generally as well.

**Comment by ryanpitts** [comment]
Journalism is accepting this session, and adding it to the "Building Online Communities" pathway.
