### ISSUE TITLE
Hacking Television

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-program#576]
Facilitators: Dan Schultz, Mark Boas, Tracy Jaquith

Goals:  Over 1,600,000 minutes of video are aired every hour on broadcast networks around the world.  This session is about learning to hack with video.  Come to get down and dirty with audio fingerprinting, transcription, closed captions, analysis techniques to bring this massive video corpus into the age of the app.

Agenda:  Over the course of two hours we will experiment with tools to ingest, analyze, and present video.  Come armed with a laptop and a good way to take notes, we’ll provide the software and video samples from the 2016 US elections.

We will start by working with tools for accessing TV and closed captions.  Then we will learn how to manipulate, clean, categorize, and extract information from the collected content.  Finally we will explore how to use this information.

The format will be workshop-style (small groups of 3-5 people in each group), with the tools and recommended experiments provided by the facilitators for each of the three pipeline phases we will be targeting.

To show you a working larger system using most all the tools in this toolkit, we'll go over the TV News Political Ads project at Internet Archive.

Scale (5 / 15 / 50):
We will break folks into 3-5 person groups (targeting groups of 5) which will make it easy to replicate across any number of participants.

Outcomes:
- Participants will walk away understanding how to use cutting edge tools and techniques for collecting, manipulating, presenting, and working with video.

**Comment by ryanpitts** [comment]
@benrito Just got this session description from Dan Schultz, and I think you had maybe been talking to him and Mark about accepting it? If so, that's awesome! If you weren't going to be able to, let me know and we'll make space for it.

**Comment by benrito** [comment]
Hey Ryan, definitely intend on making sure that the session finds a place in the program. If your program is the best place for it, that would be great! What do you think?

**Comment by ryanpitts** [comment]
We're fans of making sure this one is on the program too :) And also fans of spreading out news folks into other MozFest spaces! How about this -- Journalism will send an acceptance, and if you end up having room for this session in your space, let's switch it there?

**Comment by benrito** [comment]
Perfect, thank you sir!

I think this is likely to be the final solution because I'm not
representing any particular track, just the sanctity of the Mozilla /
Internet Archive partnership :)

Cheers!
Ben

**Comment by ryanpitts** [comment]
@benrito sounds great. Unless we hear otherwise, then, we'll plan on hosting this session in the Journalism space.

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone, likely most appropriate for Bronze participants
