### ISSUE TITLE
Giant Robot Turtles

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#58]
**[ Google Spreadsheet Row Number ]** 4
**[ Facilitator ]** Su Adams
### Description

Introduction to Programming for ages 4 and above.

In this 'doing' session we propose making a giant version of the board game Robot Turtles http://www.thinkfun.com/robotturtles-buy.

We have delivered this activity at our October '14 U Can Too Maker Party and had participants ranging from 3 all the way to 11.  Both the participants and DLs thoroughly enjoyed!
### Agenda

We will create a huge Robot Turtles board on the floor, get hold of some 'Turtle' shaped helium balloons and big cardboard boxes.  (I'm looking into getting boxes printed for our October Maker Party, that I hope to be able to flat-pack and reuse). Children will play the game using the command cards from the game itself.

Digital Leaders will run the activity explaining the task to participants. They will be responsible for moving the Turtle balloons (they know to be pedantic - in order to get across the importance of debugging code).
### Participants

5 or 15 participants are manageable as we can involve players as turtles too.  50 would not be a practical quantity of participants to support, however, I think the activity isn't likely to appeal to as many as that.  It is also a drop-in/ short session activity, so we would be able to cycle through participants quickly if needed or spend longer for those with a particular interest on higher challenges.
### Outcome

Young participants will have an understanding of algorithms, bugs, debugging, the importance of precise instructions etc... they will have a good grounding for further explanding into something device based, such as Scratch Jr, Scratch, Hopscotch, Tynker all sorts of other activities.  I am happy to provide a sheet with an idea of what children could go on to do after the events... "Ideas for exploration".  If that is of interest, just say :)

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
agai cc youth too here
