### ISSUE TITLE
Digital Identities: the landscape, the future, and legal hacking

### ISSUE THREAD

**Issue by mollycaitlin** [mozilla/mozfest-program#581]
As governments work to create increasingly integrated smart services, it is necessary to establish unique identification systems that correlate services around individual people. But how governments create, store, and provide access to unique identities and the sensitive personal data linked to them varies greatly around the globe. Do centralized systems threaten our rights to privacy? Should unique identification systems be linked to biometric data? How much authorization should individuals have to access and tinker with their data that is stored by the government? Should governments be cooperating with privately owned platforms that store networks of personal data, and if so how? 

This session will be an exploration of how governments around the world are currently creating a storing personal identifying information and a brainstorming session for how it should be designed in the future. The second half of the session will be a hackathon in the "legal hackers" model where we hack current technologies and try to create new systems that would address some of these problems, such as identity authorization systems and personal data consent receipts.

**Comment by cubicgarden** [comment]
Looks good but were pretty full in the global village ironically

**Comment by thornet** [comment]
Close this session as it's not been labeled or milestoned.
