### ISSUE TITLE
Garbage Disposal Room

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#582]
Series of three sessions about e-waste under the Global Innovation Network cc @Geralbine

**Comment by cubicgarden** [comment]
cc @Saallen and @marcwalsh not sure if @Geralbine has contacted them or not?

**Comment by Saallen** [comment]
Potential sessions experiences within this area
- [ ] Hardware show and tell - 
- [ ] Workshop - taking apart of old machines- what can be recycled? Do you know what this is? 
    2 hour sessions- but with rolling
