### ISSUE TITLE
MLN Friday Opening Meetup

### ISSUE THREAD

**Issue by LindseyFrost** [mozilla/mozfest-program#585]
Friday opening meetup for all MLN pathways.  Timing and details TBD.

**Comment by LindseyFrost** [comment]
@samueledyson @omnignorant

**Comment by LindseyFrost** [comment]
Tentative Friday Timing:

1pm facilitator training
3pm community leader cheer
4:00pm meet ups
6pm science fair

**Comment by omnignorant** [comment]
Nice. We have a time and a duration. One step at a time: crawl, walk, run, fly.
