### ISSUE TITLE
Feedback on Icons from SW

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#586]
Hey showed the icons to the SW and got the following feedback
**Digital Citizenship: Are these still flexible? Would love to have something more like this: http://images.clipartpanda.com/citizenship-clipart-world-peace-earth-clip-art-largethumb2292313.jpg

**Love it. Localization very clever and much improved on a speech bubble again.

waiting on dorine to get back to me about the youth zone 
cc @cassiemc @hannahkane

**Comment by cassiemc** [comment]
First thought is that the globe with people would be too close to Global Village...

**Comment by EPIKhub** [comment]
Its YOMO's official logo, could we keep the sheild? Ive ended up with
the entire youth Mozilla group, its as much their space as anyones :)

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by EPIKhub** [comment]
No its not the globe with people, its a blue shield with a light bulb in it


[image: --]
EPIK
[image: http://]about.me/dorine_flies
<http://about.me/dorine_flies>

**Comment by Saallen** [comment]
Dorines suggestion:as an alternative just a smilely face then but with a 3 sides of a box smile rather than a U?

**Comment by cassiemc** [comment]
@adiladil ^^

**Comment by EPIKhub** [comment]
I'm consulting with our youths, this is as much their space as anyone's, they would love the shield with the Lightbulb as its their creation, I explained it was felt their design was not appropriate

**Comment by EPIKhub** [comment]
As an alternative the suggestion was a modern as seen through the eyes of youth, smilely face with 3 sides of a box smile i.e  : ] not : )

**Comment by adiladiladil** [comment]
would something like this work for everyone? @Saallen @cassiemc @EPIKhub 
![youthj](https://cloud.githubusercontent.com/assets/11046943/10377632/7c0d24e4-6dd2-11e5-864e-60c9649ff023.jpg)

**Comment by EPIKhub** [comment]
middle part is perfect, just needs a circle around it rather than this shape

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies

**Comment by adiladiladil** [comment]
how's this?
![untitled-2](https://cloud.githubusercontent.com/assets/11046943/10382931/33aa4982-6df7-11e5-814b-560e7015b8d5.jpg)

**Comment by EPIKhub** [comment]
works for me :]

**Comment by EPIKhub** [comment]
@marcwalsh @adiladiladil @Saallen I like the circle better than the latest design of a 3D box with a smiley face.

As an alternative Ive been thinking about how to show "Common ground" in a simple pictorial fashion = Venn diagrams: abstract but an accurate representation of what we are trying to do at the youthZone of 2 circles intersecting as the world of the youth and the world of the adult finding common ground at the point of intersection

https://www.google.co.uk/search?q=venn+diagram&tbm=isch&imgil=X4kVMUq9rDitPM%253A%253BD6-zAFZquRFS1M%253Bhttp%25253A%25252F%25252Fndstudies.gov%25252Fcontent%25252F2-venn-diagram&source=iu&pf=m&fir=X4kVMUq9rDitPM%253A%252CD6-zAFZquRFS1M%252C_&biw=1303&bih=697&usg=__zUJXJ-3i3GhGS2U_vuxdG7zgVIc%3D&ved=0CDwQyjdqFQoTCLLM4Yrvt8gCFYZxFAodi48NQg&ei=jP8YVrLWCYbjUYuftpAE#imgrc=X4kVMUq9rDitPM%3A&usg=__zUJXJ-3i3GhGS2U_vuxdG7zgVIc%3D

**Comment by mwalsh-mozilla** [comment]
.
