### ISSUE TITLE
Innovative Disaster Relief – Examples from Haiti and Nepal 

### ISSUE THREAD

**Issue by Geralbine** [mozilla/mozfest-program#588]
Disaster aid takes time to reach the people who need it. Stockpiled and flown in, even getting it through customs, the aid can be hugely expensive. The aim of Communitere is to create shared space for relief organizations and locals, with the aim of sharing resources and fostering communication and collaboration. Lessons learned from the spaces in Haiti and the Philippines, as well as the new Resource Center in Nepal will be presented and ways to innovate disaster relief through small scale manufacturing, space sharing and other simple means to disrupt traditional aid supply chains will be discussed.

**Comment by EPIKhub** [comment]
@Geralbine you should add HOT hotosm.org amazing organization working to map disaster zones so people can saves lives quicker; they have a strong network in London

**Comment by Geralbine** [comment]
Great, would love to - do you have any direct contact?

**Comment by thornet** [comment]
cc @geroter as something to have on your personal radar, with great ties to Engineers without Borders!

**Comment by SpikeUK** [comment]
@Geralbine @EPIKhub HOT in London is mail@harrywood.co.uk . Also Standby Task Force - Justine Mackinnon - justine@standbytaskforce.com 

Sorry - I have just spotted this thread :(

**Comment by Geralbine** [comment]
Thanks! Will reach out to both!

**Comment by SpikeUK** [comment]
There is also Joseph Reeves from HOT at iknowjoseph@gmail.com if Harry is not about and Heather Leson heatherleson@gmail.com who has been to more MozFests than I have :)
