### ISSUE TITLE
HTML Puzzle Box Challenge

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#59]
**[ Google Spreadsheet Row Number ]** 26
**[ Facilitator ]** Yofie Setiawan
### Description

I created this HTML Puzzle Box which people can easily create because it's basically a papertoy, that you can print and craft by yourself. This boxes means to teach people, which has no knowledge about HTML basic languages, in a more fun way. Beside of teaching how to craft, we can play a HTML Puzzle Box Challenge which challenging how fast you can stack the boxes in right orders. 
### Agenda

30 minutes presentation and introduction about HTML Puzzle Box, and how it already used in many events.
30 minutes for crafting boxes, using scissors and glue or doubletape.
30 minutes to play challenge.
30 minutes for free session, QA, etc.
### Participants

With 5, we can teach them to craft the boxes, than we can play challenge. With 15 or 50 we can also do the same thing. Craft the boxes then play the challenge. We can separate in groups, so each group can play their challenge.
### Outcome

This is also interesting for adults to learn, so they can share and teach childrens about HTML basic language in a fun way and without need any internet connection at all. More information about HTML Puzzle Box please visit bit.ly/htmlpuzzlebox

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by amirad** [comment]
cc: @amirad

**Comment by EPIKhub** [comment]
Pathway "News to me!"

**Comment by yofiesetiawan** [comment]
Hi, I'm looking forward to share this at MozFest this year :)

**Comment by stretchyboy** [comment]
I've used this in school 4 times this month. Its cool. Where would be the place to give feedback / make suggestions on the project its self?

**Comment by yofiesetiawan** [comment]
hi @stretchyboy thanks for using html puzzle box to be part of your teaching activity. There's no specific place now to put feedback or suggestions, but maybe you can share your feedback here. And maybe i'll create a thread on discourse? Is everyone here also have access to discourse forum?

Anyway, i'm also still prototyping this to have a dedicated site, so people can visit and find all useful sources http://mozilla.or.id/htmlpuzzlebox/
