### ISSUE TITLE
Risks of Internet mob justice

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#6]
- Facilitators name
- We will look at how Cecil the lion has drawn attention to the rise of Internet mob justice; weakeness in platforms that contribute; tools and resources that can help; how platforms such as Yelp, Twitter etc. have reacted, what their policies look like now and how they can be strengthened.
- Agenda

**Comment by Melechuga** [comment]
cc @mixedpuppy @MozStacy @shaghdoosti

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for RESPECT

**Comment by Melechuga** [comment]
Placeholder.
