### ISSUE TITLE
Minecraft for local community

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#60]
**[ Google Spreadsheet Row Number ]** 19
**[ Facilitator ]** Sylwia Korsak prev. Presley
### Description

Learn about the value of Minecraft (and other games & tech) for small local communities engaging children, youth and grown ups. We would like to discuss civic engagement, learning through play and the inter-generational role of tech and specific games like Minecraft. 
### Agenda

Very short into to the learnings from our Pixel Club followed by moderated discussion. We will bring designed questions but depending on our participants we might adjust them to ensure more practical outcomes for the session. 
### Participants

Small group can follow moderated discussion (barcamp session style). Larger group can work in smaller teams and present learnings (on post-its & final updates)
### Outcome

Notes will be shared online, new networks as Twitter list, we hope that the topic will generate audiences working with Minecraft or willing to learn about its impact - some will share their learnings to inspire others, others will find solutions and inspiration for their current work. We will blog the learnings too.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by EPIKhub** [comment]
@Saallen unfortunately this Minecraft community team is not ready to attend MozFest this year, they have withdrawn as a result, I suggested they re-apply next year once they are more organised.
