### ISSUE TITLE
MLN Web Literacy Feedback

### ISSUE THREAD

**Issue by LindseyFrost** [mozilla/mozfest-program#605]
Feedback session on the Web Lit 2.0 in the Mozilla Learning Network Hub Space

**Comment by LindseyFrost** [comment]
@samueledyson

**Comment by LindseyFrost** [comment]
Emailed An-Me.  Don't know her GitHub handle.

**Comment by anmechung** [comment]
@LindseyFrost - description for getting ongoing feedback throughout 2 days at MozFest

Web Literacy 2.0: Digital-Skills Feedback Hub

The Mozilla web literacy map is being refactored to include 21st Century skills needed for leadership development, and written in a language more approachable and accessible to diverse audiences.  We invite anyone interested in teaching web literacy skills to provide us with your insights and creative input on a draft 2.0 content and design, and  help us determine what curriculum and tools are needed to make the digital-age skills more relevant to more people. Come spend a few minutes with us moving around pieces of the map, and sharing stories of how you would use the map.
