### ISSUE TITLE
Mozilla Participation - Tech Challange!

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#608]
**[ Google Spreadsheet Row Number ]** 466
**[ Facilitator ]** Emma Irwin
### Description

This is the kick-off session for the Pathway 'New Technologies for Participation - Challenge!' which asks you techie, story teller, maker, inventor to go out into Mozfest  - to learn,  hack and ultimately bring back new ideas for Participation at Mozilla.  If you can get away with it, bring the technology back with you as well.  This session will layout the challenge for Demo on Sunday!

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone

**Comment by EPIKhub** [comment]
@emmairwin good to send you people here?
