### ISSUE TITLE
Democracy Street - Gamifying and Learning from Open Data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#61]
**[ Google Spreadsheet Row Number ]** 24
**[ Facilitator ]** Joseph Cavalla
### Description

Democracy Street is an interactive digital arts and learning project, developed and curated by the artist Jon Adams. Commissioned by the Houses of Parliament and Arts Council England, and created in collaboration with Mozilla and Si digital, Democracy Street aims to raise awareness of the power of democracy and the importance of free and open information. 
We do this by engaging the public in the generation of a Digital Interactive Map that gives insight into the people and events that shaped our political landscape since the sealing of Magna Carta. 
We have created a mobile web app and website for users to discover the history of the people behind the names of their local streets - and how they contributed to democracy.
During the session participants can engage with the project directly via smartphones and mobile devices, seeing their discoveries adding data to the Interactive Map in real-time. 
### Agenda

The mobile web app and website have been live since March 2015. So far users have discovered over 4,000 streets, creating pockets of data for every street.
The data forms patterns of discovery, from which Jon Adams creates final artwork that will be exhibited around the country from November 2015. 
The agenda will start by introducing and describing the goals of the project.  Jon will then demonstrate the artwork he has already generated.
Participants will then be invited to go on their own journey's of discovery, with their contributions being displayed on the Interactive Map in real time.
Jon will also be creating artwork from the live data generated during the session.
The mobile web app is 'gamified' through the collection of Open Badges that reward users for each discovery or contribution they make. Completing the game awards users with a Digital Open Badge.
Please check www.democracystreet.com via a smartphone.
### Participants

After the initial introduction the session can be very fluid. 
The project appeals to a broad range of people across all age groups. We have found around 25% of users quickly become engaged, and stay in the app for roughly 20 minutes at a time.
We can accommodate any number of participants coming and going throughout the session. I have already successfully presented to audiences of over 100 at other conferences - with large numbers of people dropping in and out of the app throughout. 
Since everything is already developed all we need is a large projection to show people's discoveries on the web site as they happen - along with Jon's artwork as it gets generated during the session.
Participants will need to have a good quality smartphone or tablet device with an up to date OS, running a decent browser to contribute (it works great in Firefox).
### Outcome

This is a multi-faceted project with numerous stakeholders. Open Street Data is used to cross reference against a database of over 30,000 key people and events. We have embedded 450 rich content discoveries, with data provided by our other partners that include the National Portrait Gallery, National Archives, and History of Parliament Trust. This means the quality of the learning experience is very high - and each rich content discovery has direct links to our partner websites, encouraging users to go on deeper learning experiences.
We also have 'Easter Eggs' embedded in the app that point people to the Mozilla Manifesto and the Book of Mozilla. We will highlight how users can discover these links during the session - and why a free and open web is critical to us all.
Finally, Jon will be creating artwork during the session - which will be displayed nationally from November 2015.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @cubicgarden
