### ISSUE TITLE
sevensecondsago 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#614]
Join the Seven Seconds Ago team as we delve into a world of 360 virtual reality experiences, connected to the wild! We'll explore the concept of near-realtime virtual presence, the technologies needed, our progress so far and a demo of our Google Cardboard meerkat experiment.

**Comment by ileddigital** [comment]
Thanks @Saallen  - this fits into the garage - as I've a plan for people to adapt and make their own google cardboard experiences with it.

**Comment by Saallen** [comment]
Hey @ileddigital I added it here for a cross ref purposes and to give it a Github number- All new sessions must also be added to the schedule data app doc as shared by michelle. As all github issues were exported last Friday- so any new additions should be added in both places :palm_tree:
