### ISSUE TITLE
Let's make Firefox OS Add-ons!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#62]
**[ Google Spreadsheet Row Number ]** 12
**[ Facilitator ]** Michael Henretty
### Description

At Whistler, we saw a lot of excitement around creating and sharing add-ons for Firefox OS. I want to build on that excitement by hosting a session where people learn the process for building and submitting add-ons to the Marketplace. At the end of the session I also want people to demo what they created or perhaps pitch ideas for future add-ons. The goal is to get people excited by how quick and easy it is to customize the whole phone experience on Firefox OS.
### Agenda

I'll start with a brief live coding session on how to create a simple add-on for Firefox OS using a Flame and Firefox Nightly. Then I will pitch some ideas about what add-ons can do, just to get the creative juices flowing. Then we will break off into groups of one or two people, each having the goal of creating their own add-on. At the end of the session, people will be encouraged to come up and talk about what they built or would like to build given enough time. In the past people have been able to create add-ons extremely quickly, so we might even get a few submissions to the Marketplace.
### Participants

I will have a list of add-on ideas that people can choose to work on, but I think people will mostly work on their own no matter how many people attend. Regardless, my hope is to bring enough Flames (I'm thinking around 20) for everyone. If we have more than 20, groups can use the simulator to build and debug, and then we can share the Flames we have. I've done this with a group of about 100 university students all sharing about 10 devices, so I don't think this will be a problem. I also hope to have a few other mentors to help me depending on their availability (maybe :gmarty, :francisco, or :wilsonpage).
### Outcome

Well, I'm hoping we one or two submissions to the Marketplace. But more generally, add-ons have created a lot of buzz from within the Firefox OS project, so I would like to spread that buzz outside the project. My hope is that the people who come to my session will continue creating add-ons after they leave, and maybe (just maybe) even get excited about using Firefox OS given it's level of customizability.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
