### ISSUE TITLE
Ravensbourne 3D printing

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#620]
In this session, we will be showcasing how 3D printing works through the use of Desktop 3D printers such as Makerbots and the ultimakers. and talking about the benefits of 3D printing and how as designers, we can take advantage of this technology"

**Comment by EPIKhub** [comment]
@Saallen could the session leader signpost people taking part in this session down to the youthZone? we have Makercart and other sessions who could then take them in small groups or 1:1 to use the tech they just heard about
