### ISSUE TITLE
Mozilla Campus: What's Your Dream For Student Participation?

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#624]
Imagine a student starting their first day in college. Along the journey to graduation, they meet Mozilla for the first time. How will they become friends? How will they change the world, together? Come envision and build the next pathway for student participation at Mozilla with us!

**Comment by emmairwin** [comment]
@EPIKhub This session will be running for two hours in the Participation Space Saturday Block 3 & 4 and would love to connect with anyone in your space / network who might be interested in helping us dream this.

**Comment by EPIKhub** [comment]
We are doing a session sat block 1 about what are jobs in tech, shall we
signpost them to your session as a follow on? Maybe some from participation
could come to block 1?

On Friday, October 30, 2015, Emma notifications@github.com wrote:

> @EPIKhub https://github.com/EPIKhub This session will be running for
> two hours in the Participation Space Saturday Block 3 & 4 and would love to
> connect with anyone in your space / network who might be interested in
> helping us dream this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/624#issuecomment-152670961
> .

## 

[image: --]
EPIK
[image: http://]about.me/dorine_flies
http://about.me/dorine_flies
