### ISSUE TITLE
Crafting physical digital interactions through shared stories

### ISSUE THREAD

**Issue by ileddigital** [mozilla/mozfest-program#626]
Facilitated by: Babitha George and Neha Singh 

 We will work with participants in pairs to explore the broad theme of: MEETING PEOPLE | TELLING STORIES | CRAFTING EXPERIENCES. Beginning with a provocation around what each person personally wishes for around 'meaning' in a connected village, we will then pair them up to work out possible scenarios that explore these wishes. For example Neha’s automatic selfie generator that can help her stay in touch with her mother. 

We will use design research techniques in order to share stories, build collaborative ideas and hopefully enable completely new ways to see our relationship with digital through the physical world. 

All this over some Indian coffee and snacks under the Banyan Tree.

**Comment by ileddigital** [comment]
@cubicgarden @Saallen @thornet I've added this with Babitha this weekend. It's going to be under the Banyan Tree but I'm using the label garage to keep it managed.

**Comment by thornet** [comment]
Beautiful, thanks! Also confirming you added it to the schedule spreadsheet?

On Sun, Nov 1, 2015 at 1:14 PM, ileddigital notifications@github.com
wrote:

> @cubicgarden https://github.com/cubicgarden @Saallen
> https://github.com/Saallen @thornet https://github.com/thornet I've
> added this with Babitha this weekend. It's going to be under the Banyan
> Tree but I'm using the label garage to keep it managed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/mozfest-program/issues/626#issuecomment-152824760
> .

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org
