### ISSUE TITLE
Firefox OS Smart TV Exhibit

### ISSUE THREAD

**Issue by autonome** [mozilla/mozfest-program#629]
Details incoming.

**Comment by joechengla** [comment]
Facilitators: Joe Cheng, Evelyn Hung, Jack Lin

Come and check out what Firefox OS is like on a bigger screen Smart TV and get hands-on!
The Firefox OS Smart TV team is here and wants you to have fun with the TVs, such as tweeting your selfies on the TV (@fxos_tv) and playing a web game with a Firefox OS phone. Additionally, we will be happy to show you a quick product demonstration, future prototypes and how hacking can be done on the TV via WebIDE!
