### ISSUE TITLE
We're living in the future of work

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#63]
**[ Google Spreadsheet Row Number ]** 16
**[ Facilitator ]** Duncan Gough
### Description

During our sessions we'll talk about the importance of work in our lives, how to discover what you're good at, where to find the people who are like you, and how to find your way in an increasingly fragmented and entrepreneurial culture of work where strict job titles and roles are becoming increasingly irrelevant.
### Agenda

We'll talk a little about Somewhere - our platform for discovering how you work and people like you, but we'll also encourage people to share stories from their careers and, depending on numbers, try to encourage a discussion around what work means to different people.

We can also bring in some people from the Somewhere community who can talk about what they do and how they work.
### Participants

5 participants would be a time for us to build trust between people before asking to share their work, interests and aspirations.

With 15 we could still do the same but starting with a wider discussion around the future of work

With 150 we would introduce people from the Somewhere community, either via pre-recorded video interviews or in person, whilst sticking to the topic of work.
### Outcome

We would love to give people a way to connect with each other after the event, as we did for the Service Experience Camp and Disrupt Berlin:

https://www.somewhere.com/collections/service-experience-camp

https://www.somewhere.com/collections/disruptberlin

**Comment by thornet** [comment]
Unfortunately this session was not selected.
