### ISSUE TITLE
MozOpenHard Exhibit

### ISSUE THREAD

**Issue by autonome** [mozilla/mozfest-program#631]
Details incoming.

**Comment by kudodo** [comment]
MozOpenHard Project's CHIRIMEN is a full open source hardware with Firefox OS(B2G) with software to control I2C and GPIO devices from the Web. It is designed for Web designers to extend their creativity to outside the screen (to real world). Last year, the team had an ideathon at the Mozilla festival to discuss specification and architecture. This year, we would like to show several manufacturing sample boards at the session. Those are functional and participants can touch and try the WoT world at the booth. 
At the Exhibit, we will show digital signage demo using CHIRIMEN. Also, we will provide CHIRIMEN development environment touch and try session at the exhibit.
