### ISSUE TITLE
WoT Maker, Browser J5, Beacon Scanner

### ISSUE THREAD

**Issue by autonome** [mozilla/mozfest-program#634]
Details incoming.

**Comment by elin-moco** [comment]
## Description

A set of tools and libraries that makes Web of Things development easier. The goal is to lower entry barrier, enable cross-platform support and empower Makers/WebDevs to do more and do better.
Get inspired, imagine the future.

Exhibition includes: 

### Web of Things Maker

A jsfiddle-like online editor that makes prototyping your WoT projects faster and easier, you can write simple JavaScript code to control Arduino board, and see it in action instantly in your browser.
http://wotmaker.io/

### Browser Johnny Five

A browser porting of the node.js robotics library johnny five. Browser j5 enabled possibilities to integrate **things** directly with WebAPIs, WebServices, WebApps, and browser add-ons. Currently supports Firefox OS, Android, iOS via Cordova (PhoneGap).
https://wiki.mozilla.org/Browser_Johnny_Five

### Firefox OS Beacon Scanner

A Firefox OS add-on that demonstrates physical web integration, with this add-on installed, you can enable beacons scanner anytime by swiping up, and explore URLs or other information broadcast from nearby beacons right away.
https://wiki.mozilla.org/FxOS_Beacon_Demos
