### ISSUE TITLE
Hack on Firefox OS Smart TV

### ISSUE THREAD

**Issue by emmairwin** [mozilla/mozfest-program#636]

**Comment by joechengla** [comment]
Facilitators: Evelyn Hung, Jack Lin, Joe Cheng

Come and check out what it is like to hack on a bigger screen Smart TV!

In this session, participants will learn about the Firefox OS Smart TV with a quick product demonstration.
To unleash the hacker in all of you, we will demonstrate how to hack on the TV via WebIDE and share how to build TV optimized apps. 

Bring your laptop for some hands-on experience!
