### ISSUE TITLE
Hack a Bot! 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#64]
**[ Google Spreadsheet Row Number ]** 13
**[ Facilitator ]** Syed Omar Faruk Towaha
### Description

My session will allow people to inspire the developers to do something awesome with the combination of open source and robotics;
As the main audience of my session is developers I hope they will have a better understanding of what the world needs now; We need to play with hardware along with the software. And for playing with hardware robotics is the best starting; 

I hope the people who will join my session will be empowered to hack robots with Firefox OS and open source hardware; 

I will show people ways how the world will be more awesome if we can connect with hardware along with software; 

And I wish a great response from the session; 
### Agenda

This will work ; 
As we, the developers , are playing with codes for a long time, we feel the need that coding should bond with something that we can not only see on the monitors but also see on something else, say an artificial spider!
Isn't it more awesome than seeing your code giving life to something?

The agendas are:
1. Inspire developers about robotics;
2. Show people ways how they can combine the two things;
3. Do something different;
4. Make general people get pleasure in seeing how cool coding can be with the support of robotics; 
5. Do a new starting; 
### Participants

If I get more than 30 participants I'll be the luckiest one; 
Will give then chairs to sit; 
We will discuss about our ideas and planning sitting on the floor;
If I get 5 participants, we will make a group and discuss how the thing should go and make the session awesome; We will work together after the session ; 
### Outcome

The outcomes will be:
1. Create a new path for the hardware engineers to contribute;
2. The contributors around the world will be more encouraged to help Mozilla with this project[s].
3. The Common people will get interest in the new side of Mozilla;
4. My participants and I will have a very good communication after the event and will do what we decide on hte session;

**Comment by Saallen** [comment]
cc @kaythaney

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
