### ISSUE TITLE
HEBOCON

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#65]
**[ Google Spreadsheet Row Number ]** 25
**[ Facilitator ]** Julian Burgess
### Description

Make crappy robots and set them to battle each other in a sumo-wrestling tournament 
### Agenda

I saw the HEBOCON video https://www.youtube.com/watch?v=46ivFpsmEVQ and got in touch with Ishikawa Daiju. He would be happy to have a HEBOCON at MozFest. The idea is to make robots from various parts, without putting too much technology in to the design. The fun and surprises come when they battle as you cannot be sure which will win.
### Participants

I suggest we stick with 32 entrants (which can be small teams), but have as many people as possible to watch.
### Outcome

Understand that "good" design doesn't always triumph, there are many unknowns which can only be found through action

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
