### ISSUE TITLE
Participatory Mapping With Open-Source Tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#66]
**[ Google Spreadsheet Row Number ]** 14
**[ Facilitator ]** Oliver Roick
### Description

Participatory mapping provides citizens with tools to collect, visualise and analyse geographic data in order to understand processes happening in their neighbourhood and to support work towards change. In this hands-on session you will learn about software available for participatory mapping and how you can use them for your advantage. We will show you how to setup your own mapping projects, how to collect data using mobile phones and how to make a map from your data. 
### Agenda

We will start by introducing the concept of community mapping and the range of tools that are available to create maps on the Web. In a brief collaborative discussion, we will collect potential topics for new maps. We will then split the audience into breakout groups of up to five participants. Each group will work on one topic, setting up projects, collecting data and start creating maps. 
### Participants

The essential part of the session are the break-out groups where participants work on their mapping projects. We consider groups of five participants the optimal group size; the number of groups will vary accordingly. If the number of participants exceeds 50 we can also increase the number of participants per group. 
### Outcome

Participants will be able to take what they have learned to their communities and implement their own community mapping projects. The software we introduce is mostly open-source or is available free of charge. We will document everything online for reference.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by evaconstantaras** [comment]
Better for Tools, Analysis, & Storytelling track.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
