### ISSUE TITLE
Exploring Digital Humanities

### ISSUE THREAD

**Issue by ileddigital** [mozilla/mozfest-program#661]
The digital humanities is a movement that creates digital resources to study history, literature, art and many other subjects. It explores how mapping, quantification, visualization and other digital techniques can be used in those subjects, and brings a humanities perspective on current issues in the digital world such as identity, intellectual property and globalization. 

How does the digital humanities work with the artists, makers, performers, coders and wranglers at events like Mozilla Festival? How do we build better connections between the world of digital makers and that of historians and literary critics? These issues will be discussed by Jon Rogers of Dundee University with two leading commentators on the digital humanities, Tobias Blanke of King’s College London and Andrew Prescott of Glasgow University, AHRC Fellow for the ‘Digital Transformations’ theme.

**Comment by arantxaserantes** [comment]
I would like to join in this discussion. Is it open or may I contribute in anything? I am digital humanist in Spain.
