### ISSUE TITLE
Secret game of Werewolves

### ISSUE THREAD

**Issue by cubicgarden** [mozilla/mozfest-program#664]
Werewolf is played by two teams: the werewolf and the villagers. At the start of the game every player is given the identities, while the villagers at first know only the number of werewolf in the game.

There are two phases: "night" and "day." At night certain players secretly perform special actions; during day players discuss and vote to "lynch," or eliminate, one player. These phases alternate with each other until all werewolves have been eliminated or until the werewolves outnumbers the villagers.

Some players have special abilities.

Follow @cubicgarden and @ileddigital for information of where and when this weekend

**Comment by cubicgarden** [comment]
Look out @ileddigital @thornet @Saallen sometime this weekend!

**Comment by jgmac1106** [comment]
Is this a f2f game or a Twitter game like TvsZ? Maye a little both?
