### ISSUE TITLE
Localize The Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#67]
**[ Google Spreadsheet Row Number ]** 22
**[ Facilitator ]** Meghraj Suthar
### Description

The Session is about to teaching and localizing stuff. The web is growing day by day with awesome learners and we need to make it possible to provide in all possible languages, The Webmaker is available in many languages possible but its also requiring to localize the web into different modes where participation or people can reach out to the web. This session is all about the teach and do the productivity content localization with purity of content localization. Its a session to make the things with locale languages and localizing the things. So the engagement of people or participation can reach more with their locale languages. 
### Agenda

The Transifex is the tool or platform which allows us to how to localize the things and how to localize the projects & products. Agenda will flow like:
- Introduction
- Transifex Live Demonstration
- Webmaker Localization On Transifex
- Hands On Localization with Participation
- Webmaker Makes with Locale Languages
- How to localize their own organization or projects on Transifex
- How to localize Firefox Apps
- Prize Distribution To Awesome Localizers
- Demonstration By Localizers what they Learnt
### Participants

I believe in quality not in quantity so i would be happy with 5-15-20-25 but they should have to make sure they are interested in localizing the stuff in their languages, and they are ready to build the localized web because localization helps organization to engage more people.
### Outcome

Community Engagement With more members, because if someone doesn't knows the English language then its hard for them to connect with the web using existing resources but if localizers are ready to localize then its great for them to learn, make, engage, teach to others and spread the web across the world. I have being a Coordinator of Webmaker Localization project in India for National Language that is Hindi.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by amirad** [comment]
cc: @amirad

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
