### ISSUE TITLE
This is Not a Map: Building Interactive Maps with Creative Themes and Geometries

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#68]
**[ Google Spreadsheet Row Number ]** 23
**[ Facilitator ]** Aurelia Moser
### Description

What is a map and how can we play with that definition at MozFest? The meaning of "map" across disciplines is remarkably varied. It's effectively a spatial representation of geo-topography, a linking between tables by foreign key, a datatype in C++... At CartoDB, users make creative use of our custom basemaps feature, building remarkable maps of multivariate information off-the-(beaten) geographic projection. Many have designed and published interactive maps of cemetery burial plots, galactic drawings of the Star Wars Universe, heatmaps of court traffic during the NBA finals. Let's explore other maps, and investigate topic and themes not yet covered in interactives. Let’s .talk about how to map them and discuss why mapping might be the perfect expression of their meaning.

**Comment by chadsansing** [comment]
cc @chadsansing
