### ISSUE TITLE
Growing an Community: From zero to hero!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#69]
**[ Google Spreadsheet Row Number ]** 21
**[ Facilitator ]** Hossain Al Ikram
### Description

My session will help people to learn about a community(an functional area) which didn't existed few months back and now what have it become with many core contributors! My session will be an brainstorm session to share and learn from each and everyone! I guess, everyone has some potentiality and we will try to think, what we can do from those!
### Agenda

*Brainstorming the reason of a successful community!
*What needs to make community active!
*How to empower community by empowering community members
*Learning by hearing experience
### Participants

My session will be best for 5 or 15 people! As I would like to share my experience about growing an community as well as learning from them their experiences. How to implement this things in small group of people or when the number is big! I think, sharing is the best way of learning! So, sharing and learning from it will be sessions main goal!
### Outcome

This session will help me and everyone from the session to improve their community behavior. Help the community to nourish and make more impact on the web as well as Mozilla projects!

**Comment by Melechuga** [comment]
Could be a part of a "community" panel; not necessarily a part of the Digital Citizenship space, however. cc @shaghdoosti

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
