### ISSUE TITLE
Tools for Travelers on the Dark Side of the Internet

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#7]
- Facilitators name
- Format: Round Robin & break-outs. 
  - Round Robin (50min): Speakers will have stations. Participants will divide into 4 groups, and move around from station to station at 10-min intervals. Speakers will describe the issue of social exclusion they are working with, and answer brief questions.
  - Break-outs (60min): Participants will choose a speaker to work with to create educational materials (teaching kit style).
- Speakers include:
  - Emrys Schoemaker, Digital Purdah (https://github.com/mozilla/mozfest-program/issues/436)
  - Sarah Jeong, Architecting Against Online Harassment (https://github.com/mozilla/mozfest-program/issues/343)
  - Kelley Misata, The Open Information Security Foundation, Cyberstalking Expert
  - Violet Blue, Smart Girl's Guide to Privacy

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for RESPECT

**Comment by Melechuga** [comment]
Could include: https://github.com/mozilla/mozfest-program/issues/153

**Comment by Melechuga** [comment]
Could change to just Online Harassment: Panel + Content Creation

**Comment by Melechuga** [comment]
Could include https://github.com/mozilla/mozfest-program/issues/235 (Tackling the "nothing to hide" argument).
