### ISSUE TITLE
Mozilla Location Services

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#70]
**[ Google Spreadsheet Row Number ]** 29
**[ Facilitator ]** Harsha  Bandaru
### Description

Introducing MLS project to volunteers
The Mozilla Location Service (MLS) is an open service which lets devices determine their location based on network infrastructure like WiFi access points and cell towers. 
### Agenda

This open service relies on a community of contributors who are contributing in many different ways like.

```
Individuals collecting data

Currently more than 5 thousand individuals are helping us collect data for MLS.

Find all individuals at https://location.services.mozilla.com/leaders

Developers using and innovating on top of the service 

We have MozStumblr app for android

Aurora versions of Firefox for Android includes a way to contribute data and enhance this service.

Developers are working hard to integrate this service in Firefox OS.

We have FxStumbler app for Firefox OS operating system.

Recent versions of Firefox Desktop allow you to use this service instead of the default location provider.

Find complete info at https://location.services.mozilla.com/apps

MDN Link : https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation



Recently it was announced that Fedora project is going to use the Mozilla Location Service (MLS) as  the default geolocation provider for their Firefox Desktop packages. 

Stumling in a Box

https://wiki.mozilla.org/ReMo/SOPs/StumblingInABox
```
### Participants

if the number of participants is around 5 members i would like to discuss individually and let them know in contributing to MLS 
if the number is around 15 then i would divide them into group of 3 or 4 then engage them in group way and make sure that every individual get to know about the project .

if the number of participants are more than 50 then i directly take session for them and will have hands on session on how to create the basic application using the MLS then divide them into 4 to 5 teams and make team leads and then make the team leads responsible for the agenda and i will mentor the hands-on session 

Finally what ever might be the number of participants i will make sure that each and every individual would learn about the  Mozilla Location Services 
### Outcome

```
1. Call for regional mentors :

Initially we will invite few volunteers to lead their regional community.

Later we will ask volunteers to nominate themselves for region leads if they are interested. And based on the selection criteria we will select regional leads.

Depending on demand, we may need to cycle in new members to give everyone a chance to participate.
```

will train the regional leader as well

```
2. Community call for discussion about future plans.

3. Conducting activities
```

We can start with conducting location pilots on regional level

**Comment by EPIKhub** [comment]
Might it be possible to do a DIY find your lost kid, the school bag or keys hack :)?

**Comment by EPIKhub** [comment]
I'm working with Harsha on this session
