### ISSUE TITLE
WebVR - Make virtual reality games in your browser!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#71]
**[ Google Spreadsheet Row Number ]** 27
**[ Facilitator ]** Rabimba Karanjai
### Description

The purpose of the session is to show the capability of WebVR and how MozVR can help them make interactive immersive content!
The goals include
- Showing them the capability of VR, then make them realize the potential about WebVR/MozVR
- Tech them to actually create immersive content. So the goal would be after the session they should not how to shoot 360/180 degree videos with commercial camera and make it work with MozVR
- Teach them to hack on demos we already have. Goal is they should be able to hack into the building blocks of our presently available code
### Agenda

We will talk about WebVR, show a few demo's of the session and then will have a short interactive session on how they can get their own content out and get them in VR!(using webvr).
- We will go through a short demo of shooting a 360 degree (or 180 if we don't get that camera) video of the workshop and will then experience it in MozVR right within the demo!
- How we can build more demos (or games if anyone is ambitious!) using the building blocks of our present demos!
### Participants
- With 5. Real time hacking with the code! Change it. Test it. Hack it again. With everyone! So at the end of session everyone will have their own demo up and running
- With 15. Make teams and make them hack on that! End goal. Still we should have a few unique demos!
- With 50. Emphasize mostly on creating immersive content and the 360/180 degree video. How to make it. How to make it compatible with WebVR/MozVR
- With 100. Mostly do demos to the group of people. Demo them how to make content for it and make it compatible with webvr. And if have time then ask for volunteers to do it themselves to show others!
### Outcome

The ideal outcome should be the participants being knowledgeable about  MozVR. They should be walking out of the festival with the knowledge and interest about it so that they can talk/demo it to the further community members and expand the know how!
Make others know about it build a great ahcker community who contributes more into MozVR content including demo and videos.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Moonlapse** [comment]
@EPIKhub 
Would be a cool addition to the proposed "Bringing VR to the masses with your story".

**Comment by end3r** [comment]
Would love to help with that session if possible, have experience with Games and VR.

**Comment by EPIKhub** [comment]
@end3r why don't you come volunteer at Mozfest? Volunteers this year will have the choice of which space they would like to be in, so you can always choose the youthZone and I can then assign you to help in that session :)

**Comment by rabimba** [comment]
@end3r It'll be awesome if we can team up :D

**Comment by EPIKhub** [comment]
@end3r Register here to be a MozFest volunteer https://ti.to/Mozilla/mozfest-volunteers/

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone

**Comment by EPIKhub** [comment]
@end3r did you sign up as a volunteer?
