### ISSUE TITLE
Know the open web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#72]
**[ Google Spreadsheet Row Number ]** 30
**[ Facilitator ]** Sashoto Seeam
### Description

We the online activists often understand many thing but can't explain it to others. This session will help them to clear their view about open web and to express themselves while talking with common people.  
### Agenda

There will be few but important topics related to Mozilla's mission; like Open web, Web making, Net neutrality, Online privacy. And participants will first form a 3 peoples group. Each group will be given a topic, they will first discuss the topic among them. Then from each group 1 person will be allowed to say 5 key points from what they discussed about the given topic.
### Participants

I think we can take 30 people on the session. There will be 3 person in each group, which will make 10 groups. It will be best They can sit in a open place or in chair to talk. Also some sticky notes will be good so that they can write their views. 
### Outcome

After the festival participants' view about main core components of open web will be cleared. They will also find themselves easy while discussing or talking with people about this topics. Which will make impact in web advocacy and to aware common users. It will also help the participants to improve their leadership quality.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
