### ISSUE TITLE
Boot with web in early days !!

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#73]
**[ Google Spreadsheet Row Number ]** 31
**[ Facilitator ]** Rahul  Talreja
### Description

The session proposed is mainly focusing on School Students as a targeted crowd, as i feel if the seed is sown well the harvest can always be expected a good one. Thus through this session the fellow Mozillians and other attendees will learn about how can we include open source and web privacy content in school academic curriculum so that all the students taking their primary and secondary education should already know the importance of Web literacy , Privacy on web and Power of Open Source. 
Also if they are booted at this stage of schooling with the benefits of  contributing into open source projects and participating on web, we can surely expect our next generation to be infinitely awesome !!
We will try to make a generic academic friendly curriculum, which can be proposed later to the educational boards to include in curriculum.  
### Agenda

Since Moz Fest will have attendees from all round the globe, this will help us to know better that how can we implement this ideas in their countries, every attendees inputs will help us to know better and once every thing is set and finalized we can ask attendees to forward this proposal to the educational boards in their region. Also later we can take and make resources on Mozilla's Learning Network and can make best use of that for implementing this idea in school. 
If every thing works according to the plan we are very sure that the outcomes of this step would be a revolution to the entire digital world !!
Even the stats says how important it is to implement digital literacy in individuals lifestyle. (http://2010-2014.commerce.gov/news/fact-sheets/2011/05/13/fact-sheet-digital-literacy) 
### Participants

Their is no problem to us with the number of participants, in-case we have as less as 5 participant's our agenda would be as same as before , because this is not a group activity but an  idea on which we can work collectively to make our web better. And incase we get crowd of as many as 50 participants , it would be a cherry to pie as its very sure that out of 50 participants every 10th participant would represent another country and hence we would get better to know the condition in rest 5 countries (if we have 50 participation).
### Outcome

Once the proposal is discussed in festival we will take the proposal to our local educational boards and will try to implement in it the day to day curriculum in primary and secondary school. 
Also we would ask fellow attendees to join us in our project and help us in same by doing exactly same thing in their areas. Once all the regions would join us we can have digital literacy all round the globe and the better web for next generation !!

**Comment by Zebetus** [comment]
@EPIKhub Something we have talked about a lot

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
