### ISSUE TITLE
Story to Build Community

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#74]
**[ Google Spreadsheet Row Number ]** 15
**[ Facilitator ]** Rob Grundel
### Description

Teach the use of story as a tool to build community. If a story is well told, the idea contained within it can take in every listener that hears it. If we see something that can change for the better then, irrespective of our position, we can be a leader - but we need the tools to inspire and motivate.
### Agenda

Get people into groups of about 7. 

Teach the basics of story and get the groups interacting with that.

Then teach the specifics of leading with story and get the groups constructing narratives around a change they would like to see in the world.

Then teach the specifics of presenting a story and get the groups giving feedback on each other's presentation of their stories.

At the end, get one person from each group to present their case for change in a narrative and get feedback from the room.
### Participants

Because it's all group work and groups will contain no more than 7 people, individuals will still feel like they've been heard because the feedback from their co-participants.
### Outcome

It would be interesting to see how participants could continue to support each other in their goals and continue the feedback cycle on leadership and story. Some people may be using the tools of story face to face whereas others may be using it online. It would be interesting to see how they could learn from each other in the very real situations that they find themselves in where there is a genuine need for change and their leadership.

**Comment by chadsansing** [comment]
cc @chadsansing
