### ISSUE TITLE
HackUp Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#75]
**[ Google Spreadsheet Row Number ]** 28
**[ Facilitator ]** Tharun Rajendran
### Description

My session will be for young childrens from age of 6-12.In this basic remix of webpages will be implemented in this session.so,that even the youngs can know about open web.
### Agenda

My session agenda is 10 mins intro to web and moztools and a 20 mins remixing and a last 10 about their experience in this hackathon.
### Participants

Its a simple thing. In this its for childrens, so if a children of age 6 can be grouped with a age 15. So, a group consists of diffrent age.So,one can teach others in a different style.
### Outcome

Team work.creativity in young minds.how to lead a team.entrepurner skills.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016
