### ISSUE TITLE
Webmaker App

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#76]
**[ Google Spreadsheet Row Number ]** 18
**[ Facilitator ]** Brian Ssekalegga L
### Description

The session will teach participants on how to use the newly developed webmaker app . 
Using this app the participants will be able to  Make personal scrapbooks, photo galleries, comic strips 
and more by a simple method of WYSIWYG (What You See Is What You Get ).There is no need of any programming skills.

Main objective

To  Introduce new users to the new webmaker app and get feedback about how effective the app is. Also use the this session to explore what people want to use the app for. 
To collect Feedback from participants about how effective the app is and the kind of apps they they would like to come up with
To create a community for contributors towards webmaker app
To increase content on webmaker app by coming up with at-least 20-30 apps being developed using webmaker app
To have many installments of webmaker App by people
### Agenda

This session will increase creativity in participants. They will be able to share their work, stories, fun stuff, pictures, in a much more convenient but also funny way because Webmaker app was developed to be easy and fun.

10 mins - introduction & demo
30 mins - quiz (8-10 questions)
Posing a question in line with either webmaker or open web.
Introducing  is Webmaker app to the people.
Have people write down ideas or apps that they think can be developed using webmaker.
Divide the people into manageable groups
Downloading of webmaker App to mobile devices
Spend 10 minutes teaching a group all the basics of webmaker app 
Share the makes with others
Registering and creating a community /communities
20 mins - discussion & feedback
### Participants

With 5-10 participants I will be able to handle them all alone.
But if all is well and i get 20 interested people in my session , i will divide them into groups of 5 (4 groups) because this will enable each and every one to understand well how to use the app.
Also small groups are manageable.

i will teach one group of people then in that very group i will have each person to go and teach a group.
### Outcome

At the end of the festival i hope to increase content on webmaker app by coming up with a global community of active contributors to webmaker. This community will be composed of all communities in the world.

Since Webmaker is a good interactive app and people can Make personal scrapbooks, photo galleries, comic strips 
and more and share them with friends and family. 

After which we shall be able to launch Webmaker App in East Africa.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
