### ISSUE TITLE
Localization of Firefox Marketplace Apps / WebApps

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#77]
**[ Google Spreadsheet Row Number ]** 20
**[ Facilitator ]** Biraj  Karmakar
### Description

The idea is to make marketplace apps available in other languages. The session can show how to make open web apps easy to localize and how to contribute by localizing apps from Marketplace.
### Agenda

There are two important parts in the demonstration: first one is for developers where we present how they can make their web apps translatable,what are the main componets here, how those work also , how to handle those components  and will demonstrate live examples,
and making request to make their apps translatable. The second part is for contributors, we show a presentation on how they can translate existing apps in the Marketplace using the Transifex platform and we will provide some guideline before start translation. We'll give a web
link with compiled information for the both kind of audience. Here I will add basics of localization and translations. 
### Participants

Due to the nature of the session, I think I can handle 20-25 audience at once. This will help us to be more interactive with the audience and answer their questions/address their issues more sincerely.Though
our first session can handle more than 50 audience because there we will teach how we can translate in transifex platform.
### Outcome

After the event, Mozilla will get lot of translatable apps which will solved biggest challenge for App localization now.   Also developers will be informed what to keep in mind when designing their apps. Ideally, we can expect a boost in the number of globally accessible apps in the marketplace. Developer will  learn that how to make it translatable and they would engage localizer to directly to the project.

**Comment by hjbailey** [comment]
cc@hjbailey

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin

**Comment by hjbailey** [comment]
I am leaving this in the hands of participation group. We will happily find a place for Biraj to be apart of the localisation space.

**Comment by emmairwin** [comment]
@hjbailey we did not accept this session, but will coach this participant towards goals at Mozfest,  will reach out to better understand participation in the localization space.  

Did you notify of acceptance?  cc/ @Saallen @marcwalsh
