### ISSUE TITLE
Hackadons : small agile events for boosting donations to free software/culture

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#78]
**[ Google Spreadsheet Row Number ]** 40
**[ Facilitator ]** Bastien Guerru
### Description

People will learn about what is a hackadon and how to organize one.
### Agenda

I'll present what we did in 2013 and 2014, then everyone will (1) suggest a role he or she could play in a local hackadon : find sponsors, reach local floss organizations, contact projects in needs of donations, etc. ; then (2) suggest improvements and/or variations about this simple idea.  Finally we will draft the TODO lists for new hackadons, and connect the attendees with the existing hackadon community.
### Participants

5 participants : present the core "hackadon" idea ; have a lengthy discussion on how to boost donations for free softwares / free culture : why and how? is is a sensible goal? what are the best tools to achieve it? are hackadons worthwhile? then finally we'll engage participants in organizing their own if they want.

15 participants : same, with less discussion on why and how.

50 : a lengthier presentation on the why and how, and a small discussion about it at the end.

150 : a lengthier presentation on the why and how, no global discussion on it.
### Outcome

The outcome is easily assessed by the number of people engaging in the hackadon movement, and the number of hackadons organized all over the world.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
