### ISSUE TITLE
Boosting Productivity, Hacking Webpages, and Learning with Firefox Developers Tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#79]
**[ Google Spreadsheet Row Number ]** 35
**[ Facilitator ]** Nootan Ghimire
### Description

This session is supposed to cover all kinds of audience (well, expect Pros). Based upon them, the Goals are

Goals for:
1. Beginner / Learner
   Assuming the audience is just taking baby steps in web development, our goal for them would be to allow them to make basic webpages, and using 
   the tools to do it the easy way.
2. Intermediate
   The session is most appropriate for audiences who know _some_ web development, but aren't utilizing the tools. The goal will be to allow them 
   to learn using the Firefox tools (not only Console and Inspectors, but also other Firefox Developers Tools
3. Others
   For audiences with enough knowledge, I'll try to dive them into some apparently complex stuffs like Networks and Performance, but they will basically be involved in reviewing others' work.
### Agenda

I'll start the session with Introduction to the inbuilt Developer Tools. After that I'll guide them through a basic webpage which is as much vivid as possible (including CSS, JS). That will help Beginner. Then, I'll use Developer Tools to modify/debug the website. This is the main part - we'll use console to check logged message, track errors, change CSS, learn to use tools like 3D view, Computed CSS rules,  Box Model, Scratchpad, etc.
### Participants

Well with less participants (i.e., ~5 ppl), It would be easier for us to teach them individually. This will make the event more fruitful to the individual participants.

For medium sized people (around 15 people), we can make small groups of similar people and then teach them differently - as described above in Goals section.

For large sized audience, i.e., about 50 people, we will first make groups, categorize groups with similarities, will encourage Advanced Audience to teach Intermediate, Intermediate Audiences to teach to Beginners. We'll take rounds and guide them through what should be taught!
### Outcome

I see that after the festival, Participants will be able to use the inbuilt Firefox Developer Tools to boost their website designing and user experience developing experience. 

It will be a lot easier for them to grasp other Mozilla tools like X-Ray goggles (which is available as "Pick Elements" in Developer Tools), Thimble (which is available as "Inspector").

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
