### ISSUE TITLE
 Experiences of race, ethnicity and authoritarian governments

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#8]
- Facilitators name
- Description
- Will include a hacking session with an Open Web Fellow who is analyzing data around police discrimination practices in racially segregated neighborhoods. Other experiences are still under development.

**Comment by thornet** [comment]
cc @thornet

**Comment by Melechuga** [comment]
cc @mixedpuppy @MozStacy @shaghdoosti

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for RESPECT

**Comment by Melechuga** [comment]
Placeholder
