### ISSUE TITLE
How to make real books on the Open Web

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#80]
**[ Google Spreadsheet Row Number ]** 46
**[ Facilitator ]** Daniel James
### Description

From documentation to storytelling, the Open Web offers both the content and tools required to make beautiful books. Groups of authors can be together in one room at Mozfest or spread across the globe.

There are now a variety of closed-cloud platforms which can be used to create books and ebooks. Booktype is the fully open source alternative, which can be installed on your own web server for complete independence.

This will be a hands-on session introducing authors to collaborative, browser-based book authoring, taking them from first draft to print PDF, EPUB and more.
### Agenda

We will demonstrate open source workflows which supersede the proprietary office and design tools used in the contemporary book industry, while delivering faster proofing and production cycles.

Real, printed book design with CSS will be covered, with examples from Booktype users including Amnesty International and University College London.
### Participants

We will create accounts on a Booktype server for any number of participants to use during the session. Accounts could be created in advance of the session if a list of email addresses was available.

A laptop or other device, preferably with a keyboard, will enable participants to get the most out of the session.
### Outcome

Authors will be able to use the tools described in the session to continue to collaborate on open book production and CSS-based book design.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by hjbailey** [comment]
cc@hjbailey

**Comment by hjbailey** [comment]
I would love to see some cross over with different language books.

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by danielhjames** [comment]
Hi @hjbailey, we can definitely cover books in different languages during this workshop. Booktype has UTF-8 support throughout, we have experience of right-to-left Arabic publishing and are working on improving Chinese/Japanese/Korean support. The user interface is also localised, please see https://www.transifex.com/sourcefabric/booktype/ for the current status.
