### ISSUE TITLE
Social Learning Programme for the Web Literacy Map

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#81]
**[ Google Spreadsheet Row Number ]** 37
**[ Facilitator ]** Alvaro Caballero
### Description

Build a collection of lessons to run a social learning programme, to teach the Web Literacy Map.
This will connect the theory (the map) the resources (trigger questions, examples, videos, etc) and the pedagogy (social and online learning) on a tangible and ready-to-run series of sessions for everyone to use.
### Agenda

Split the groups into as many groups as topics of the map to be covered.
Then each group will assign a role for every group member in order to be responsible for capturing either Questions, Anecdotes or Resources.
The goal is to capture as much material, experience and perspectives as possible for each of the components of the map.
Then each group shares with the rest and everyone gets to enrich it.
Ideally participants will have their own laptop/tablet/mobile to allow for some searching and capturing.
### Participants

The number of participants will define how much of the Web Literacy Map we would be able to cover.
### Outcome

The end result will be a ready-to-run programme for educators and activitst so they can host their own online learning sessions about the web literacy map.

Ideally, we could even host a series of MOOC's!!!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by amirad** [comment]
cc: @amirad
