### ISSUE TITLE
Make all your Fun

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#82]
**[ Google Spreadsheet Row Number ]** 38
**[ Facilitator ]** Sandeep kapalawai
### Description

We always attracts for fun , and Joy etc,. so this idea makes me to propose a session for Mozfest'15.My Session will show how a group of people will perform activities by having fun .By Using Appmaker we will be making  teens or kids to learn about Appmaker,we will show you the demonstration.
### Agenda

Initially we will gather and discuss about the themes we need to make an APP  *Note : As its a fun , we will decide only on Fun Themes
 Participant will be choose their best themes
 Best among the Themes will  be choose and picked up
### Participants

Say if we have a 50-100 participants, we will make up to in to 10 participants for each group and 10 themes will be given .

They will be given time 
Suppose if the number is 5,10,15 ..30 will make odd number of groups varying not more than 4 groups and follow the same procedue
### Outcome

I Hope this Session Bring a great Response Especially from Teens and Kids, as it a fun filled event participant will be choose his desired theme and will be worked out , As a result there will be involvement with team work .This Session will bring a Good output.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
