### ISSUE TITLE
Explore the next Generation Web Culture 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#83]
**[ Google Spreadsheet Row Number ]** 33
**[ Facilitator ]** Sukanta Pal
### Description

This session focuses on extract ideas and innovative new things which reflect their lifestyle and beliefs. It will be surely brainstorm and motivate folks to draw their Arts,Cultures and Language on web canvas and share it with the whole world. There will also be opportunities for those people who have always wanted to learn a little bit 
code like HTML,CSS or JavaScript to try that out.
### Agenda

I will do a quick tutorial on the basics of Webmaker tools,Webmaker for Android and paper craft, then launch into a freeform workshop where folks work on their idea with coolest weapons and share with each other. Every culture has their own language, beliefs, traditions and codes which act as a foundation for learning, sharing and exploring.
### Participants

I can do one group brainstorming, or break into teams of 3-5 if necessary.If turnout is large, I’d encourage folks to form small groups to help each other and also provide some tips and tricks that help each other.
### Outcome

After the session, participants will surely know the power of open web and how they can share and teach others to use the power of open web.They will learn how Webmaker tools, Webmaker apps enable them to plot their ideas over the Open web and know how to create regional and localized teaching stuffs.They will be motivated to come forward for doing Contribution Or Get Involved some open source projects like Mozilla.It will be great to teaching, learning, hacking, sharing and collaborating together and make the web better place.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
