### ISSUE TITLE
Don't let HTML stop you

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#84]
**[ Google Spreadsheet Row Number ]** 32
**[ Facilitator ]** Marko Kazhich
### Description

think outside the box. HTML was made ages ago, and we need to provide modern experiences to users. I want to show people how to do that with the new web and give them ideas on how we might be able to do that in the future.
### Agenda

I intend to should people the hacks they know and replacements for the future. They will see custom elements working, they will see expanding accessibility and openness. A nice demo to show how we can use voice in the web of tomorrow, even in languages other than English (I'm a native Serbian speaker so I feel this deeply).
### Participants

I've spoken to various sized groups. My main goal is to engage people, I like to see them work together and actively participate to turn my talk into a discussion. 
### Outcome

Hipefully, they will see that the language of the web needs to expand. We've passed the age of hyperlinked books and we need to work on real life experiences on the web.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
