### ISSUE TITLE
Mini Minecraft HackJam on Raspberry Pi

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#85]
**[ Google Spreadsheet Row Number ]** 53
**[ Facilitator ]** Alan O'Donohoe
### Description

Minecraft offers digital makers a 3D virtual world which can be used to design and create interactive objects. On the $20 Raspberry Pi computer, users can use programming to control how these objects interact.

Through taking part in this Mini Minecraft HackJam, participants will understand the creative and educational potential of controlling Minecraft with code on a Raspberry Pi computer. 

After an introduction to programming Minecraft on the Raspberry Pi, participants will work in teams to create a Minecraft challenge assault course.

This session would suit learners who wish to explore the opportunities offered by controlling Minecraft and educators who wish to explore the potential of Raspberry Pi and Minecraft as teaching tools. 

This session will be led by Alan O'Donohoe an experienced educator in Computing & Raspberry Pi and David Whale an experienced software developer, author and STEM ambassador.
### Agenda
1. EXPLORE - Participants will first use Minecraft on the Raspberry Pi in creative mode to create a building - this will enable participants who have no prior experience of Minecraft to understand the Minecraft environment.
2. UNDERSTAND - Participants will be introduced to the potential that the Raspberry Pi offers that enables Minecraft to interact with other software and hardware. 
3. CREATE - Participants will work in small groups to create mini Minecraft challenges for other particpants to solve. 
4. EVALUATE - Participants will visit other groups to try their Minecraft challenges as part of an assault course. 
### Participants

Participants will be organised into teams of up to 5, if we have 5 participants we'll organise them into two groups. 15 participants would be organised into 5 groups of 3. If we have 50 participants, there will be 10 groups of 5. We anticipate that this session would realise it's full potential if 2 hours were allocated, but it would be possible to compress it into 1 hour if required. We are happy to repeat this on more than one day as we expect that it will prove to be very popular. 
### Outcome

If our proposal is accepted, we will write and publish a post before MozFest describing how we are planning to organise the session and then follow it up with a post about how we changed it to suit the audience. We expect that this may then be published as a MagPi article or other print media. 
All the code solutions for the Minecraft challenges will be published on GitHub for others to share and collaborate with. 
We will encourage participants to write and publish a blog post about their experience of the session and how they intend to use it themselves.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by EPIKhub** [comment]
News to me! Pathway Local club -> Civic engagement -> Pi

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
