### ISSUE TITLE
Build an IoT and chat-platform using Matrix

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#86]
**[ Google Spreadsheet Row Number ]** 41
**[ Facilitator ]** Matthew Hodgson
### Description

In this tutorial we will focus on gathering, processing & visualising data from various IoT and human sources, reviewing the various technologies available to unify the data whilst providing a deep dive into Matrix (matrix.org).

After an introduction to the problem space and available solutions, we will focus on introducing Matrix's architecture and its open source, Apache-licensed reference client and server implementations.

Attendees will then setup and demonstrate a 100% opensource and federated equivalent to Google Hangouts. As a next step they will gather IoT-data from various sensor arrays into the network, and aggregate, process and visualise this data via Matrix's Application Service API. Finally they will tie together both human and device communications and defragment ALL THE THINGS as the grand finale.
### Agenda

The agenda is to show how easy it is to make use of existing, opensource software to create an app in the Matrix ecosystem. Together we will start from scratch, checkout the code and first get a webclient running. We will use this webclient for human chat to demonstrate how it works, and then extend it by set up some IoT data sources (like a temperature sensor) and extend the client to display this data.

This is an incremental tutorial that can be extended, depending on time and the pace of the session. We can add more sources, display the data in different ways, and implement a reader that will make decisions based on the data. 

Hopefully this will make a lot more people aware of the Matrix ecosystem and encourage them to make use of it in their own apps in the future!
### Participants

The number of participants is less important, as everyone can follow the tutorial on their own laptops. More people might mean a slower session, but as described above, that's fine (it just means we won't have time to implement all the extensions).
### Outcome

We already have an active ecosystem where people discuss problems and solutions - and implement new apps on a regular basis. The room is hosted on the Matrix protocol (obviously!) at https://matrix.org/beta/#/room/%23matrix:matrix.org - and we will strongly encourage participants to join this room so they can get help and tell us about any future projects they undertake!

**Comment by Saallen** [comment]
cc @cubicgarden

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
