### ISSUE TITLE
Leading the awareness of openness

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#87]
**[ Google Spreadsheet Row Number ]** 34
**[ Facilitator ]** Aditya Putra
### Description

We are Mozillians, and we believe that the web must remain open. What we see today is that most of our family members, friends, and colleagues do not know anything about this. They don't know that every second, companies and governments are spying, stealing, and mining information from their gadgets. We can't just say to those people "I support the open web, period", but we have to encourage people to be aware of the openness. What I am going to do is to empower our fellow Mozillians to be the leaders in promoting openness.
### Agenda

First, I would like to explain the facts about how companies, governments, and people interacts in the internet. Then, I'd like to discuss how people around us aware that they are being spied by governments and companies, then I'd like to show related survey results. After that, I'd like to discuss what can we do as a Mozillian to make people aware and encourage them to support the openness. I think there will be some discussion and some games to make the session more alive.
### Participants

I think it won't be any problem.
If my session has 5 participants, It will be great as we can create a group discussion and make great plans, too. If I have 15, there won't be any difference. I will make a one group discussion. But if I have 50, I think I am going to divide the participants into 5-7 groups to make it more focus, then each group can explain what they get from the discussion.
### Outcome

The outcome is that the participants are able to lead the promotion of openness, at least for colleagues around them. I would like to remain in contact with the participants after the session. Probably we can hangout on Slack after the session.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
