### ISSUE TITLE
To build and protect yourselves online

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#89]
**[ Google Spreadsheet Row Number ]** 36
**[ Facilitator ]** Dyvik Chenna Thirunahari
### Description

The internet is a staple in many people's everyday lives. It is a great resource of wonderful information, but it is also a dangerous platform ever. In this session i am going to teach how build internet using Webmaker tools and also how to be safe on Internet using Mozilla . Come join us to build internet and also learn to be safe on internet.
### Agenda

As the graph of internet users is increasing vertically by hour it is very important to learn to build internet as well as keep themselves safe on the same. We mozillians have come up with Webmaker tools (Thimble, Popcorn and X-ray goggles) to make it easy for you to hack internet and also safeguard yourselves by using our tools like Lightbeam and Firefox interest dashboard.  

Agenda
- introduction to webmaker tools 
- Explain how all the tools work and how there are used.
- explain in detail about each and every tool
- Save the first project and also share with others online.
  -Teaching them to be safe on internet
- Exercise for participants
### Participants

1) If there are 5 to 15 participants, hands-on for this session can be possible.
2) Above can also be the case if there are 50 participants if each of them have their own laptops with them.
### Outcome

The final outcome will allow every individual having the concept of how the web works and they will have the clear idea of creating the web, which is in their own hand. 

Creating awareness about being safe on the internet.

Collect the makes made by participants and decide winners.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
