### ISSUE TITLE
Apps and Mobile

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#9]
- Facilitators name
-  The potential impact of anonymous apps; mean tweets, etc. Finding the right balance - protection from bullying but also allows youth to be expressive and open online without fear of judgment.
- Agenda

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Saallen** [comment]
@Melechuga Submitted as part of a pathway for Dont feed the trolls

**Comment by Melechuga** [comment]
Placeholder
