### ISSUE TITLE
This is paradise - co-creating our future cities. 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#90]
**[ Google Spreadsheet Row Number ]** 56
**[ Facilitator ]** Michelle Gay
### Description

This multi-day collaborative experiment focuses participants’ thinking on our future cities, utilizing participatory design methods to co-create a lo-fi ‘3D’ model of a future city using user-friendly materials.
Great ideas for sustainable, smart, beautiful, connected cities can originate from anyone.  This session looks to engage and inspire people to consider topics such as - what a resilient city looks like, what amenities and features it boasts, what apps and technologies make life more interesting, how we reflect upon and design public spaces, what new built forms can we imagine, what are smarter infrastructures, how can we creatively manage environmental factors such as light, sound, smell, and weather?
We will investigate the designs and facets of a livable city through collaborative model making. We’ll collectively construct a 3D material ‘sketch’ of our ‘Moz-city’ while simultaneously reflecting, brainstorming and conversing with fellow collaborators on various aspects of future cities.
### Agenda

A twitter campaign will tweet question-prompts to stimulate ideas and dreams of the features of resilient, friendly, livable cities.  What does an urban paradise look like to different communities?
The tweetlist of generated ideas projected like an LED ticker stream will allow participants and to see what people envision for future cities.  Printed tweets (like fortunes found in cookies) are strewn about a large model-making table. Available for all participants to consider at any time throughout MozFest, these ideas and materials offer easy points of inspiration and are meant to be mulled over, considered and responded to as part of the “collective future city building” project.  Emerging through the making process – a dynamically generated co-created lo-fi collaged city.   Everyone is encouraged to contribute their own ideas to either aspect of this process – through tweets or by participating in the physical making of our model of a future city.
### Participants

A large table is the gathering place for model-making over the entire MozFest –abundant with lofi accessible construction materials. For inspiration and insight into the collective discussion, the tweetlist will be projected nearby, the printed tweets spread about the table. The ‘in-the-round’ nature allows many to approach and work on aspects of the model city, and side-tables encourage people to create additional elements that can be contributed later.
Collaborating with new MozFest friends will be a salient and positive aspect.  A large open table with an easily graspable project focus is an excellent way of welcoming participation, encouraging contributions and opening long-form discussions around complex issues – in this case, the expansive and ultimately social, shared goal of considering how we can ‘make better cities together’.  The constantly accumulating new concepts arriving through twitter foster thinking, riffing on and further inspiration around these issues and ideas - while model making.
### Outcome

Imagining: our future cities through in-depth conversations, reflections and model making. Think creatively about public & private space, form, function, technologies, communities and the inter-relations between these layers of city design.  Kids and adults need opportunities to be engaged with city building and to see how our individual experiences of ‘city’ can be included in this process.
Experiencing: how we can collectively work toward a complex goal of designing an amazing city together.
Making: the fun yet thought-provoking session may elicit some potential applied ideas. The pleasure of co-creation can spur people into making the leap from sketch to innovation.  Perhaps the seeds of future apps will be imagined during this exercise or a young radical city planner will emerge through this session.
Sharing: model-making process will be documented, animated and shared at citizensinplanning.com - a site publishing teaching-kits and open-access collaborative projects to help communities think creatively about cities.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by chadsansing** [comment]
Facilitator cannot attend.
