### ISSUE TITLE
Mapping the Matrix: Open Cartography with Scientific and Spatial Data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#91]
**[ Google Spreadsheet Row Number ]** 54
**[ Facilitator ]** Aurelia Moser
### Description

Maps are popular visualizations applied to all scientific disciplines. Likewise, learning how to best apply cartographic tools to spatial problems is an important component to making sense of our world visually and physicially. At all scales, this skill can provide complex information with spatial clarity: where orbital maps drive an understanding subatomic dynamics at one zoom, and help us understand interactions in our cosmos at another. Still, sometimes the tools to build maps can be as obscure and proprietary as the data we are trying to parse.

This session will be a brief intro to open source mapping tools, a tutorial in map-making for science, and a drop in clinic to play with, manage, and map geospatial data. Participants will make maps with sample science data, or test /troubleshoot their own with open source software. 
### Agenda

We've implemented a few working group sessions, called "CartoCamps," around mapping education in New York City, and we'd love to expand beyond that hyperlocal group. With contacts at Mapzen and tutorial material using QGIS, MapBox, CartoDB and other open libraries and APIs, this would be a great opportunity to introduce mapping tools to scientists and test out usecases, and the corresponding performance of these tools against scientific datasets.
### Participants

A few of us will hopefully be at Mozfest, so we'd like to give a quick presentation and introduction followed by small group clinic sessions with our facilitiators (Dave Riordan from Mapzen, Stuart Lynn from CartoDB/Zooniverse, Andy Eschbacher + Aurelia Moser from CartoDB). I've found the small group split to be really productive, time economical, and intimate. It accommodates all attendance counts and can be easily done based on general proficiency or attending topic-level interest. We'll aim for a relaxed but thoughtful vibe best facilitated by close interaction with, but not reliance on, attending participants.
### Outcome

We'd like to get a maximum of attendees comforatable mapping with open source software. Likewise, we'd love to follow up with participants and support their projects beyond the festival. Mostly, we'd like to see people making better maps with science data, and we want to make that as painless as possible.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by abbycabs** [comment]
ping @ryanpitts

**Comment by ryanpitts** [comment]
Woo! This one will slot into a joint pathway between Science and Journalism called "Tools & Analysis."
