### ISSUE TITLE
Hacking Flexagons

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#92]
**[ Google Spreadsheet Row Number ]** 39
**[ Facilitator ]** Sara Mansouri
### Description

Flexagons are fun paper toys or according to Wikipedia "Flat models, constructed by folding strips of paper that can be flexed or folded in certain ways to reveal faces besides the two that were originally on the back and front.": https://www.youtube.com/watch?v=VIVIegSt81k
In our maker party in Canada we decided to make flexagons with our own photos! I started this project from scratch and used customized flexagons as a fun tool to teach the web to students and the result was amazing! http://smansoury.github.io/Flexigon/
The main goal of this session is to enjoy making creative flexagons while teaching simple HTML, CSS to participants. The participants will be encouraged to come up with interesting ideas for designing flexagons and use the web tools to create their design while practicing team work. Here is how a potential result may look like: http://tinyurl.com/flexigon. 
Finally, we will talk about ways to participate in this project: https://github.com/smansoury/Flexigon
### Agenda

(5 min) Showing some flexagons and briefly telling the interesting story behind flexagons. 
(5 min) Asking about participants familiarity with HTML. Making the groups of 2 to 5, depending on the number of participants
(10 min) Customizing and making our own flexagons, taking some photos with each other to use them in flexagon.
(10 min) Uploading the photos and copying their URLs in the internet (instructions will be provided for those who need).
(15 min) Teaching how to use X-Ray Goggles to change the source of images.
(15 min) Printing the flexagon patterns with our own photos, cut them out, stick and fold them.
(10 min) Playing with our own flexagon. I will give some more information about other patterns and other changes that they can make using X-Ray goggles (and on git repository for advanced participants.)
(10 min) Question and answer + exploring different patterns with their personal photos.
### Participants

The number of participants basically determines the group sizes. The groups will be combined of two to five persons. In case of small number of participants facilitators would be able to provide more time with each group and do brain storming to come up with more interesting ideas and provide guidance. 
In case of larger groups, we will try to distribute more experienced participants to different groups so the participants can help each other. In addition, to give them instructions I should get the attention of all groups and provide the directions for all groups at once. Moreover, we will hand out an instruction to each group so they can use. We may also use some published images from MozFest instead of taking and uploading photos in order to save some time for Q&A time.
### Outcome

Outcomes:
-Great taste of making and participating.
-Stimulating the participants creativity.
-Getting familiar with with some simple tools for developing web while having fun.
-practicing efficient teamwork. 

To take activities forward I will prepare a printed package for participants to take home, including:
-Some patterns 
-Instruction of changing the pattern. 
-Website URL that they can download many patterns and build in future.
-It’s open-source and available on Git so I will encourage interested participant to fork the project and improve the patterns by their commits 
- If they have any new ideas for other Flexagons, origami or modifiable paper crafts, they can add the patterns there.
  My big goal is providing a fun open-source resource for teaching web to youth. Something that they love and they want to share and teach their friends. They enjoy making crafts, It would be great to use its taste for teaching web!

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by amirad** [comment]
cc: @amirad

**Comment by chadsansing** [comment]
@amirad, maybe this session, like a flexagon, could appear simultaneously in different spaces.

**Comment by amirad** [comment]
It can @chadsansing - was just wanting to make sure it got included somewhere (sara is a Maker Party star turned Mozilla Club Captain!) and she created this fun, interactive activity to teach in event/club settings.

**Comment by chadsansing** [comment]
@amirad: Would clubs take this one as an intersecting session, and L&L can host the Thimble session as an intersection?

**Comment by emmairwin** [comment]
cc/ @emmairwin @geroter

**Comment by EPIKhub** [comment]
@chadsansing @emmairwin @geroter @amirad Ive Milestoned it but feel free to re Milestone it, just wanted to make it was Milestoned.

**Comment by sara-mansouri** [comment]
Thanks for accepting my proposal! I have changed my GitHub account username  to match my full name and the new URL of the worksheet is:
http://sara-mansouri.github.io/Flexigon/

looking forward to meet you all in London! :) 
@EPIKhub @chadsansing @emmairwin @geroter @amirad
