### ISSUE TITLE
How to run the perfect crowdfunding campaign

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#93]
**[ Google Spreadsheet Row Number ]** 45
**[ Facilitator ]** Natalie Jonk
### Description

We would run a workshop on running a crowdfunding campaign.  Walacea is a crowdfunding platform for science, since going live we have launched 8 projects, we have been very involved in each project launch and also seen what goes on behind the scenes i.e. google analytics for both successful and unsuccessful campaigns.  We have a range of theories on what makes a great campaign and would love to share ideas and hear the ideas of the group.
### Agenda

We would separate the session into five sections, if there is limited time we may only focus on the two most popular sessions with the group based on what people vote for at the beginning of the session.
Section 1 : How to create the perfect video 
Section 2 : How to map out your target audience of backer Section 3: How to map out your target media promoters Section 4:  How to choose the perfect perks and shape your content
Section 5: How to manage your time during the campaign

We would run these sessions as open discussions where we would first explain what we think is an good tactic then ask members in the group to pitch their ideas and describe there experiences (if they have crowdfunded).
### Participants

5 participants - The session would be run as a round table discussion giving each person the opportunity to share their ideas

15 partipants - as above, however there may not be time for everyone to share their ideas so if people wish to share their ideas they can choose to and others can sit and listen.

50 participants - We could separate people into groups of 10.  At the beginning of each section we will talk about what we think works then ask members of each group to discuss what they think is best and appoint a speaker to share their ideas with the rest of the groups.
### Outcome

For Walacea it would be helpful to learn from other peoples ideas on the best way to crowdfund and for other people it is a useful way for them to learn about how crowdfunding works, particularly the planning and promotion involved in running a successful campaign.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
