### ISSUE TITLE
 WOMOZ - Women in Mozilla. 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#94]
**[ Google Spreadsheet Row Number ]** 55
**[ Facilitator ]** Joyce Nalwadda
### Description

Womoz is Mozilla program that encourages women to contribute to the open web under Mozilla's mission of openness, innovation & opportunity. Women can also feel encouraged to participate in a number of Mozilla projects such as Firefox OS, webmaker among others.
Therefore this session will introduce women to a functional area called WOMOZ, that sensitises women on how to easily make good use of their skiils on the web depending on what they frequently use the it for.
### Agenda

Proper planning according to time given for the session. 
Ice brakers inform of jokes, games & success stories is nomally one of the fist activities on agenda, to disable fear & to enable us run a completely interactive session.
WOMOZ is already a running in East Africa where am based therefore we have well designed power point presentions of what the program is about, with a number of achievements & guidelines on how this program can be run.
### Participants

Together with other facilitators as mentioned above we want to ensure team work & division of labour to ensure that most of the audience's expectations are met.
Such as answering questions, dividing the session into small groups to enable sharing, reports & interaction. 
### Outcome

Comming up with sort & long term plans to run WOMOZ,
Encouraging new sign ups to the program,
drafting reports,
sharing communication links & contacts for follow up, 
tacking groups photos, 
forming WOMOZ clubs for further contribution.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy

**Comment by Melechuga** [comment]
Could be interesting for Inclusive Communities...?

**Comment by emmairwin** [comment]
is this accepted? @Melechuga

**Comment by Melechuga** [comment]
@emmairwin Not from Digital Citizenship.

**Comment by emmairwin** [comment]
cc/ @Saallen @marcwalsh

**Comment by thornet** [comment]
Unfortunately this session is not taking place.
