### ISSUE TITLE
How to Fight an Internet Shutdown

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#95]
**[ Google Spreadsheet Row Number ]** 42
**[ Facilitator ]** Deji Olukotun
### Description

Internet shutdowns represent a terrifying and real trend worldwide. Shutdowns and blocking often precede egregious human rights violations and impact our ability to seek, receive, and impart information. In 2015 alone, we've witnessed nearly a dozen shutdowns in a variety of contexts and situations, from the Pacific Rim to the Democratic Republic of the Congo. In the first short section, I'll share key strategic lessons for activists about how to fight internet shutdowns, including: working with telcos to resist government orders, how to speak about shutdowns in human rights language, engaging the UN, pressuring government figures, capturing data about shutdowns, and storytelling for change. I'll also share key indicators that we have tracked over time. 

The second, main part of the session will be wholly interactive and focus on a shutdown simulation that invites participants to respond to the shutdown.
### Agenda

The session will begin with a very short overview of internet shutdown trends and data, as well as Access' new campaign, and key lessons from what we've learned. 

During the longer interactive section, we'll run a simulation of a real internet shutdown. One group will operate inside the country where the shutdown occurs and the second will be outside the country. We'll show what tools each group can do to push back and turn the internet back on so that information can keep flowing. Importantly, we'll show how they can coordinate their efforts and record them to prevent future human rights abuses. 
### Participants

The first part of the session -- key lessons from our campaign -- can be shared with any number of people. The interactive part of the session will work by dividing participants into groups. These can be as small as groups of 3 people. In a small group, each participant in the simulation would have access to multiple tools. With larger groups, each participant would have access to a smaller tool. We can also simulate 1 shutdown per group of 10 people so as to identify different people's responses. In other words, we could game multiple shutdown scenarios.
### Outcome

We'll have built a core group of people who can take action against internet shutdowns around the world. They'll have access to the latest tools, strategies, and research to end internet shutdowns. We'll also ask people to opt-in to a mailing list if they'd like to join the fight against shutdowns to encourage grassroots collaboration and activism across borders. We would also create a cohort of skilled first responders to push back against shutdowns.

**Comment by Melechuga** [comment]
cc @mixedpuppy @shaghdoosti @MozStacy
