### ISSUE TITLE
Web Literacy: CSS is Fun!  

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#96]
**[ Google Spreadsheet Row Number ]** 44
**[ Facilitator ]** Salman Rahman Desh
### Description

Our topic "CSS is Fun" is all about making colorful animation,  shapes in HTML pages by CSS3. In this session participants will learn,  create and share their project done by CSS.  They will present their makes after creation. Whole thing will be colorful with sign-pen, sticky notes etc.  We will also use puzzle games to introduce audience properly cause visualization is the best way to learn which strongly believe.  
### Agenda

I think it will awesome and very much attractive to audience.  As our main audience is kids and school students, so such kind of colorful will let them feel free to explore their colorful thoughts of their deam worlds.
### Participants

This session is not like others session and wont be that much formal.  It will be a friendly session which help audience to talk and share.  Moreover we start by playing games and also would like to know their creativities such as dance,  singing,  art works etc which will also help to think what will they are going to make.  
### Outcome

After MozFest we will be a team and will continue as a team.  We will help them by providing resources, communicate through mail, skype or facebook.  Can do online traning sessions and also will help them so that they can organize small kitchen party and make them to keep in touch with "teach the web" project of Mozilla.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by chadsansing** [comment]
Facilitator cannot attend.
