### ISSUE TITLE
Personal Data – a change in ownership

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#97]
**[ Google Spreadsheet Row Number ]** 52
**[ Facilitator ]** Julian Ranger
### Description

Many commentators are talking about personal data being owned by the individual.  What implications does this have for privacy, for sharing, for innovation?  How radical is such a change?  Does it solve the problems perceived with unpermissioned use of data today? Does it introduce new issues? 
### Agenda

We would spend five-ten minutes framing the problem, showing potential solutions with perceived benefits and then stimulate an open discussion to address the questions identified above in session goals.
### Participants

With up to 20 participants a single group discussion on the topics can be handled.  Greater than 20 would involve participants being split into smaller groups with a list of questions to address and then time reserved at the end for each group to report their conclusions with a period set aside for final thoughts.
### Outcome

As facilitators for the session we would write a summary of the outcome of the session and, for all those who noted a willingness to participate subsequently, would invite further comments/editing of that summary before posting on a blog site inviting further discussions via a #futurepersonaldata tag.

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
