### ISSUE TITLE
Hack a Design Challenge to Use With Your Students

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#98]
**[ Google Spreadsheet Row Number ]** 64
**[ Facilitator ]** Devin  Dillon
### Description

This session will empower people to lead hands on, open ended STEM projects for students of all ages using Iridescent's CuriosityMachine.org platform. First, participants will tackle an open-ended design challenge from CuriosityMachine.org. Each design challenge presents a problem that participants will solve through building a solution with materials like straws, cardboard and tape. Then, attendees will discover the educator resources that the platform has and hack the materials for use at in your learning space. Educators can customize these learning experiences in many ways -- they can change (but are not limited to) the design challenge materials, lesson plans and unit structures that are already posted on Curiosity Machine.

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by emmairwin** [comment]
cc/ @geroter @emmairwin  familiar with curiosity machine, would be good learning opportunity for edu community leadership
