### ISSUE TITLE
Build your custom Sumobot

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#99]
**[ Google Spreadsheet Row Number ]** 43
**[ Facilitator ]** Giovanny Andres Gongra Granada
### Description

We are going to build custom sumobots (http://sumobotkit.com/) and learn how to control them with Javascript.
### Agenda
- What is a sumobot
- Start building bots
- Introduction to Javascript
- Learn how to control the sumobot with Javascript
- Show your final custom sumobot
- Join the final sumobot battle
### Participants

The idea is organize groups up to three people. Every team will get a kit with all the tools and materials to build a custom sumobot. The can personalize with colors and stikers, it's all about imagination. Would be great to have around a max of 25 participants in the session.
### Outcome

Kids or people who assist to the session will get interested after the event to create more custom sumobots, experiment with external pieces to add features, change boards to increment possibilities and show their friends how is easy is control them with Javascript.

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
